### ISSUE TITLE
Add new feature: aproximate entropy

### ISSUE THREAD

**Issue by jneuff** [blue-yonder/tsfresh#1]
For a description of the feature see https://en.wikipedia.org/wiki/Approximate_entropy
A tutorial on how to add new features to tsfresh can be found in our documentation: http://tsfresh.readthedocs.io/en/latest/text/how_to_add_custom_feature.html

**Comment by CYHSM** [comment]
I implemented it based on the Wikipedia Article but changed the list comprehension to a vectorized method, which seemed a lot faster with my limited testing. Should i just add the feature calculator as shown in the docs and create a pull request?

**Comment by MaxBenChrist** [comment]
@CYHSM A pull request would be helpful, I am looking forward to it.
