### ISSUE TITLE
Error when importing tsfresh

### ISSUE THREAD

**Issue by VadimKanarsky** [blue-yonder/tsfresh#1001]
Hello! Successfully installed tsfresh using pip. However, an error occurs when importing tsfresh(
-->
![image](https://user-images.githubusercontent.com/126089304/220664559-fb2cff8f-5e01-4159-87f4-e3de5cbd1b3f.png)

- Python version: 3.9.12
- Operating System: Windows 11 home single language 
- tsfresh version:  0.20.0
- Install method: pip

**Comment by nils-braun** [comment]
Hi @VadimKanarsky !
This looks like an issue with CUDA (which I guess was installed by you) and numba (one of the package we depend on), as e.g. stated [here](https://stackoverflow.com/questions/74768750/numba-cuda-possible-mix-of-compiler-ir-from-different-releases).
My suggestion would either to follow the advise in the stackoverflow post (downgrade to an older CUDA) or if you do not need CUDA at all, uninstall it.

**Comment by VadimKanarsky** [comment]
> @nils-braun, thanks for your valuable advice! I removed CUDA and tsfresh imported without problems. However, if I need cuda (e.g. for deep learning), which version of CUDA do I need to install to make tsfresh work correctly?

**Comment by nils-braun** [comment]
Quoting from the link I included above:

> use CUDA 11.x or earlier
