### ISSUE TITLE
Memory problem, how to fix it?

### ISSUE THREAD

**Issue by b-y-f** [blue-yonder/tsfresh#1005]
**The problem**:
With this code, on a 16GB memory laptop, failed. Is there any way to fix it?

```python
X = extract_features(
    df, column_id="meter_id", column_sort="iso_datetime",chunksize=1000
)

result = X.compute()
```

**Anything else we need to know?**:

### Performance issue

My data is only 3 IOT data merged, each IOT have 20,000 + rows, after mereged, I got 3 distinct ids and 100,000 rows in total, how to use less memory when extract features?

And most of the time, it won't use full cpu and only use 2/8GB of RAM. And very extremem time, it usees full memory, any ways to improve it?

```
023-02-28 12:48:42,708 - distributed.worker_memory - WARNING - Worker tcp://127.0.0.1:51430 (pid=1768) exceeded 95% memory budget. Restarting...
2023-02-28 12:48:42,741 - distributed.nanny - WARNING - Restarting worker
```

Performance: 
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/13849223/221726656-1581e3de-17f6-4d09-8c6a-4299976fd0f0.png">

![image](https://user-images.githubusercontent.com/13849223/221738934-d7343703-14e5-47b3-9399-b0f8824fd3f0.png)

**Environment**:

- Python version: 3.9
- Operating System: MAC
- tsfresh version:           0.20.0
- Install method (conda, pip, source):

**Comment by b-y-f** [comment]
when i use 8 core cpu, and chunk_size=10000. Worker dead. 
When I use 1 core cpu, ...........................10000. Job finished, but extrememly slow. 3 ids, takes 1 hours. But we have 100,000 ids.

**Comment by b-y-f** [comment]
Just realized that my 16GB will be split into 2GB if I create 8 workers in LocalCluster. 
So I changed the core to 4 so it have 4GB? But the CPU usage is still low.

**Comment by b-y-f** [comment]
I have used 2 cores and set chunk_size=1, which has resulted in successful execution. However, this implies that for each time series related to an id, a minimum of 8GB of RAM is required. Therefore, for my current test data consisting of 20,000 rows, 8GB of RAM will be used. If I were to use more than 20,000 rows, say 40,000 rows, each chunk will require 16GB of RAM.

**Comment by b-y-f** [comment]
And it still slow, tested with 3ids, 80,000 rows, 4 columns, it takes 40min to finish.

**Comment by nils-braun** [comment]
Every parallelization in `tsfresh` is on the ids and kinds/column (what we call a timeseries), never on the rows. Most feature calculators can not be parallelized, so all we can do is split the work among different time series (not on rows). 

There are a few things you an try out:
* do not use all feature extractors, but only use a subset, for example https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html#tsfresh.feature_extraction.settings.EfficientFCParameters
* extract features on windows of your data. Depending on your use case, it might make sense to chunk the series into smaller windows and extract features on them.
* if this is not a real-time use case, write a batch execution script which extracts features on each timeseries (and each column) one after the other and store the results. It might take long (but might be much faster with different settings, see above) but if you e.g. let it run for a night you have all the results.

**Comment by b-y-f** [comment]
> if this is not a real-time use case, write a batch execution script that extracts features on each time-series (and each column) one after the other and stores the results. It might take a long (but might be much faster with different settings, see above) but if you e.g. let it run for a night you have all the results.

For this, if the length of data are different, like one series is 1000 rows, another 20000 rows, would they outcome different features? e.g. 1000row gives me 500 feature and 20000rows data gives me 2000 features. If I concat all data together this won't happen.

**Comment by nils-braun** [comment]
>  If I concat all data together this won't happen.

That is correct! As I said, this depends on your use your use-case (sometimes it makes sense, sometimes it does not). Depending on what you want to do afterwards with the features, it might be ok to have the features only for windows of the data. Example: if you want to forecast, it might not make sense to have features from too long ago anyways. Or another example: if you want to classify timeseries on anomalies, it might be fine for your use case if one of the windows per time series has an anomaly. But again, if it makes sense depends on your use-case.

**Comment by b-y-f** [comment]
Solved
