### ISSUE TITLE
support of python 3.10

### ISSUE THREAD

**Issue by Yasslight90** [blue-yonder/tsfresh#1019]
Hi,

I tested the library on a python 3.10.6 and got the following bug:

`ModuleNotFoundError: TSFreshFeatureExtractor requires python version to be <3.10, but system python version is 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0].`

Is it planned to support python 3.10? or is there a workaround to fix this issue ?

Thank you :-)

**Comment by nils-braun** [comment]
Hi @Yasslight90! 
tsfresh itself is compatible with python 3.10.
However, it looks like you are using tsfresh via another framework (maybe sktime?) which seems to have a hardcoded constraint for tsfresh. Are you using such a framework? In this case: would you like to open an issue there?
Thank you!

**Comment by nils-braun** [comment]
Closing this issue as tsfresh seems not to be the limiting package :) 
If you need help finding the actual limit (I guess it is sktime's wrapper around tsfresh), please tell me!
