### ISSUE TITLE
Add functional end to end tests for the feature calculators

### ISSUE THREAD

**Issue by earthgecko** [blue-yonder/tsfresh#105]
As per https://github.com/blue-yonder/tsfresh/issues/102#issuecomment-266214963

During tests, test to ensure that the tsfresh version is calculating the exact
same values and feature names by calculating the features of a known static
timeseries. Each version then has a baseline in the tests too.

The tests take a sample of the first 60 data points, calculate the features so
it is very fast and then the feature name strings and values are compare to the
baseline.

On detecting changes the tests fail and outputs the differences and all the info
required to update the test with the new features and the new baseline csv which
are generated by the tests themselves, if new features are being added.

**Comment by nils-braun** [comment]
#105 was merged.
