### ISSUE TITLE
05 Timeseries Forecasting (multiple ids).ipynb doesn't work as written

### ISSUE THREAD

**Issue by jcoffi** [blue-yonder/tsfresh#1057]
**The problem**:

05 Timeseries Forecasting (multiple ids).ipynb doesn't work as written. 

>     ---------------------------------------------------------------------------
>     AssertionError                            Traceback (most recent call last)
>     Cell In[17], line 1
>     ----> 1 X_train_selected = select_features(X_train, y_train)
> 
>     File ~/anaconda3/lib/python3.10/site-packages/tsfresh/feature_selection/selection.py:153, in select_features(X, y, 
>     test_for_binary_target_binary_feature, test_for_binary_target_real_feature, test_for_real_target_binary_feature, 
>     test_for_real_target_real_feature, fdr_level, hypotheses_independent, n_jobs, show_warnings, chunksize, ml_task, multiclass, 
>     n_significant)
>
>     149 check_for_nans_in_columns(X)
>     150 assert isinstance(y, (pd.Series, np.ndarray)), (
>     151     "The type of target vector y must be one of: " "pandas.Series, numpy.ndarray"
>     152 )
>
>     --> 153 assert len(y) > 1, "y must contain at least two samples."
>     154 assert len(X) == len(y), "X and y must contain the same number of samples."
>     155 assert (
>     156     len(set(y)) > 1
>     157 ), "Feature selection is only possible if more than 1 label/class is provided"
> 
>     AssertionError: y must contain at least two samples.

**Anything else we need to know?**:
I've attached the notebook that shows the error along with the versions of all modules installed.

**Environment**:
- Python version: 3.10.12
- Operating System: ubuntu 20.04
- Pandas version: 2.1.4
- tsfresh version:  0.20.1
- Install method (conda, pip, source): pip

[05 Timeseries Forecasting (multiple ids) (1).zip](https://github.com/blue-yonder/tsfresh/files/13773269/05.Timeseries.Forecasting.multiple.ids.1.zip)

**Comment by nils-braun** [comment]
Hi @jcoffi!
I think what happened here is that the years specified in the code are too old and the downloaded data does not contain them anymore. Could you check if this is the case? If yes, would you like to do a small PR to fix this? Thank you!

**Comment by nils-braun** [comment]
Hi @jcoffi - I fixed it in the newest release :)
