### ISSUE TITLE
Feature calculator return type documentation

### ISSUE THREAD

**Issue by dilwong** [blue-yonder/tsfresh#1062]
This isn't a bug, but more of a documentation issue.  According to the [docs](https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html), as well as in the docstrings for the functions in `tsfresh.feature_extraction.feature_calculators`, the documented return type for feature calculators of `fctype=combiner` appears  to be incorrect.  For example, see `agg_linear_trend` that claims to return a pandas Series, or `augmented_dickey_fuller` that claims to return a `float`.

**Comment by nils-braun** [comment]
Very good observation @dilwong (and sorry for the late response). Would you like to do a PR to fix this (or at least some of them)?

**Comment by dilwong** [comment]
Ok sure, I submitted PR #1070 for this.
