### ISSUE TITLE
IOError: bad message length

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#107]
While working with a larger data set, I got a `IOError: bad message length` from the multiprocessing pool. I will try to reproduce the bug with random data.

I was trying to extract the MinimalProperties.

Maybe this will be solved by the new parallelizing by samples.

**Comment by nils-braun** [comment]
Yes, this could maybe be solved but still we need to find out, why this is happening. 

This is a quite well known problem, and there are plenty of solutions out there (e.g. http://stackoverflow.com/questions/10721915/shared-memory-objects-in-python-multiprocessing). We just have to find one that suits our needs best :-)

**Comment by nils-braun** [comment]
@MaxBenChrist Any news on that? Still problems?

**Comment by MaxBenChrist** [comment]
I did not occur again and I did not had the time to reproduce it

**Comment by MaxBenChrist** [comment]
Should be fine with our parallel extraction
