### ISSUE TITLE
__version__ incorrect in 0.3.0

### ISSUE THREAD

**Issue by earthgecko** [blue-yonder/tsfresh#109]
It appears that tsfresh-0.3.0 is reporting the incorrect version in __version__.  I have compared 0.1.1 and 0.1.2 and ```pkg_resources.get_distribution('tsfresh').version``` reports the correct version in both of those, tsfresh-0.3.0 reports __version__ as:

0.1.1.post0.dev62+ng0f1b4c7

**Comment by MaxBenChrist** [comment]
have you installed tsfresh from github or from pypi?

**Comment by earthgecko** [comment]
pypi via pip

**Comment by MaxBenChrist** [comment]
should be fine now with version tsfresh-0.3.1. We will use twine in the future to deploy

**Comment by earthgecko** [comment]
Hi @MaxBenChrist 

Travis just did I build on my pr and the pypi install of 0.3.1 is fine on my local with the version and the tests.

```
(tsfresh-py352) gary@mc11:/opt/python_virtualenv/projects/tsfresh-py352/apps/tsfresh_test_tsfresh/tsfresh$ python
Python 3.5.2 (default, Jul 11 2016, 13:20:59)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tsfresh
>>> tsfresh.__version__
'0.3.1'
>>>
```

However on Travis the build is reporting both py2 and py3 version as:
tsfresh-0.3.1.post0.dev8+ng8c69469.dirty

py2 build - https://travis-ci.org/blue-yonder/tsfresh/jobs/183918566#L644
py3 build - https://travis-ci.org/blue-yonder/tsfresh/jobs/183918567#L643

And that is from generated from:

```python
from tsfresh import __version__ as tsfresh_version
TSFRESH_BASELINE_VERSION = str(tsfresh_version)
if TSFRESH_BASELINE_VERSION == '0.1.1.post0.dev62+ng0f1b4c7':
    # #109 was fixed in 0.3.1, just here for local testing purposes, for the
    # various local version.
    TSFRESH_BASELINE_VERSION = '0.3.0'
```

Sorry for finding weirdness.

**Comment by MaxBenChrist** [comment]
When you are building a non tagged version of tsfresh (such as in your pr branch), you will end up with a `tsfresh-0.3.1.post0.dev8+ng8c69469.dirty` version. 

Does this affect you?

**Comment by earthgecko** [comment]
Noted, that can be handled easily enough, thanks @MaxBenChrist

**Comment by MaxBenChrist** [comment]
:)
