### ISSUE TITLE
Travis is not deploying to pypi

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#110]
Travis is not deploying the tagged version 0.3.1, the log says

```
build succeeded, 7 warnings.
Submitting documentation to https://pypi.python.org/pypi
Upload failed (503): first byte timeout
```

possibly related to #109

**Comment by earthgecko** [comment]
This could just be a valid timeout?  It has the look of a varnish cache or nginx timeout - first byte timeout is often the varnish/nginx response to a backend failure.  I see you have submitted again and the job log says it is working, anyway just FYI on ```first byte timeout```

**Comment by MaxBenChrist** [comment]
I used twine to upload to pypi, was quite straightforward:

```bash
python setup.py sdist
python setup.py bdist_wheel --universal
twine upload dist/*
```

**Comment by MaxBenChrist** [comment]
Also `pkg_resources.get_distribution('tsfresh').version` reports version '0.3.1'

**Comment by nils-braun** [comment]
Is this still an issue?

**Comment by MaxBenChrist** [comment]
Yes. I was uploading the latest releases by hand. 

Von meinem iPhone gesendet

**Comment by nils-braun** [comment]
Ok, do you have non alpha-numeric characters in your password? 
It seems, there are problems with this
https://docs.travis-ci.com/user/deployment/pypi/

**Comment by MaxBenChrist** [comment]
> Ok, do you have non alpha-numeric characters in your password?
It seems, there are problems with this
https://docs.travis-ci.com/user/deployment/pypi/

No. just numbers + letters

**Comment by MaxBenChrist** [comment]
This works now, the 0.11.2 release was uploaded to pypi automatically.
