### ISSUE TITLE
Development roadmap

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#119]
We should have a discussion about the development roadmap for tsfresh:

I would propose that we focus on the speed in the near future. 

1. Getting the parallelization right (chunk size?)
2. maybe caching some feature calculators
3. doing some performance testing with the different feature calculators (see issue #74), maybe speed up some
4. increase number of unit tests (issue #11)
5. get the impute function faster (issue #123)

Then we should have some discussions about the data flow internally. For example @jneuff raised some issues with the current state of the extraction settings object and I agree with him. We should improve on that.

After we cleaned our internal data flow, we should improve the documentation (issues #92, #102, #61, #51 and so on)

Then, when we have finished that we can tackle topics like statefull feature calculators, new feature calculators, rolling time window functionality and so on.

**Comment by nils-braun** [comment]
:+1:

**Comment by earthgecko** [comment]
:+1:  and stateless for this iteration at least, seeing as this stateless iteration seems quite popular at the moment.  It may be interesting to see what all those stars and forks can do with stateless for this iteration of tsfresh at least.  After all, timeseries need a bit of time ;)

**Comment by MaxBenChrist** [comment]
Updated the plan @nils-braun and @jneuff.

**Comment by MaxBenChrist** [comment]
We had a maintainer meeting today and restructured a lot of stuff internaly, see https://github.com/blue-yonder/tsfresh/pull/133

for example we ditched both the featureextraction as well as the featureselection settings objects

**Comment by MaxBenChrist** [comment]
Wow. I think we tackled most of those issues already. I think we can close this one.
