### ISSUE TITLE
Time series data stream

### ISSUE THREAD

**Issue by sfragosorodrig** [blue-yonder/tsfresh#120]
Hey guys!

Thanks for this amazing tool!

I have a dataframe like this:

Index            Feature_1    ....   Feature_n        Y
2015-01-01          2.4             2.7               3
2015-01-02         2.2             2.2               4
2015-01-03         2.3             2.5               2

How can I extract features for each of the rows while only using info that is know at each row, i.e. only using that row and the previous ones?

**Comment by earthgecko** [comment]
Hi @sfragosorodrig 

Manipulate your data to match a format a described in the docs.  URL inbound.

**Comment by earthgecko** [comment]
@sfragosorodrig http://tsfresh.readthedocs.io/en/latest/text/data_formats.html just manipulate your data to one of those formats and feed it to tsfresh.

**Comment by nils-braun** [comment]
Hello! Thank you for your question :-)
Do you only want to know how to extract features from the timeseries at all (then see earthgeckos answer) or how  to do this in your special problem with the "rolling" timeseries?

For the rolling timeseries, the easiest solution is to feed for each row the pruned dataframe into the `extract_features` function and do this in a loop until you are through your dataset, like (this is not correct python, but the special implementation depends on your requirements. If you want, you can upload a notebook?)

`for row in dataframe:
   pruned_df = dataframe[0 .. row]
   extracted_features = extract_features(pruned_df, ...)`

Please keep in mind, that in the moment we do not have any caching implemented in tsfresh for this special case (and will probably not have in the near future). (see also #86)

**Comment by sfragosorodrig** [comment]
Hey @earthgecko and @nils-braun,

thanks for your replies. Currently, I am doing exactly what @nils-braun said. But this demonstrated to be very slow...so I though there had to exist a smarter way..apparently not, that's a shame. You don't see this as a major drawback?

I also didn't manage to get the parallel implementation to work (but that's for another issue I guess)..

Thanks for your time!

**Comment by nils-braun** [comment]
Well, the problem is that most of our features can not be cached easily and can change quite a bit when a new row is added (there are "easy" things like the sum or the mean, more complex things like peak finding, and things where it may get hard like features calculated using different FFTs etc). We do know that this is a major feature - but in the moment I personally o not see how this will end up in tsfresh very quickly.
