### ISSUE TITLE
Add reasonable feature extraction settings

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#122]
The current build is failing because earthgeckko's snapshot can not find the entropy features whose calculation was removed in 8a586ee1d11ffa7524f3b0d223552dbf197c0e74

to mitigate this we could offer three extraction objects

1.    FeatureExtractionSettings => all features
2.   ReasonableFeatureExtractionSettings => faster, calculates all but highly complex features. all features without attribute "high_comp_cost"
3.   MinimalFeatureExtractionSettings => fastest, only the basic features

**Comment by nils-braun** [comment]
This was implemented and will be refined in the next major version.
