### ISSUE TITLE
Structure and clean up our tests

### ISSUE THREAD

**Issue by jneuff** [blue-yonder/tsfresh#125]
Currently our tests are not very well structured and often it is not at all clear, what we are testing with which function. We can improve on that!

**Comment by MaxBenChrist** [comment]
We will have a Hackaton in January where we tackle this issue

**Comment by MaxBenChrist** [comment]
Is that still a problem? where could we improve?

I am suffering a little bit from tunnel vision here, for me the structure is quite logic.

**Comment by nils-braun** [comment]
I can double what @MaxBenChrist said, at least people know where to find them (otherwise there would be no working PRs ;-) )
Lets leave it as it is.
