### ISSUE TITLE
Explain the interpretation of the DriftBif time series 

### ISSUE THREAD

**Issue by kempa-liehr** [blue-yonder/tsfresh#129]
See discussion in https://github.com/blue-yonder/tsfresh/pull/127

**Comment by MaxBenChrist** [comment]
while we are on it, we could rename the varibles `n, l, m` to `n_ids, length_ts, n_kind` to make them more clear. Also the file could be made PEP 8 compatible (e.g. 2 blank lines between methods). Last thing can be achieved by pycharms reformat code.

**Comment by kempa-liehr** [comment]
Copy that. :-)

**Comment by MaxBenChrist** [comment]
:+1:

**Comment by nils-braun** [comment]
This will probably not happen in the near future, so I am closing it ;-)
