### ISSUE TITLE
'MinimalFeatureExtractionSettings' has no attribute 'n_processes'

### ISSUE THREAD

**Issue by marta-em** [blue-yonder/tsfresh#130]
I'm trying to extract features using tsfresh package and extract_features() function. I'm trying to set `MinimalFeatureExtractionSettings` . 

tsfresh Version: 0.4.0.post0.dev1+ng19fa136

However, I get the following error:

`AttributeError:` type object 'MinimalFeatureExtractionSettings' has no attribute 'n_processes'`

Code:
```
import numpy as np
import pandas as pd

column_names = ['time_series1', 'time_series2','time_series3']
ts = np.random.rand(6,3)


df_to_extract = pd.DataFrame(data=ts, columns = column_names)

df_to_extract['id'] = 1
df_to_extract['time'] = np.arange(1,7)

#print(df_to_extract)

import tsfresh
from tsfresh import extract_features
from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute

from tsfresh.feature_extraction import FeatureExtractionSettings
from tsfresh.feature_extraction import extract_features
from tsfresh.feature_extraction import extract_features, MinimalFeatureExtractionSettings


extracted_features = extract_features(df_to_extract, 
                                      column_id="id", 
                                      column_sort="time", 
                                      parallelization= 'per_kind', 
                                      feature_extraction_settings= MinimalFeatureExtractionSettings)
```

I'm using Python 3.5 (Anaconda) on Win10.

Any ideas how to solve that issue?

**Comment by earthgecko** [comment]
Hi @marta-em 

This may not be what you desire but it works, remove the parallelization and define settings from ```MinimalFeatureExtractionSettings()```

```python

settings = MinimalFeatureExtractionSettings()
extracted_features = extract_features(df_to_extract, 
                                      column_id="id", 
                                      column_sort="time", 
                                      feature_extraction_settings=settings)
```

**Comment by MaxBenChrist** [comment]
Merry xmas! 

You have to initialize the MinimalFeatureExtractionSettings object. In your example the parentheses are missing.

**Comment by marta-em** [comment]
That solved the issue. Thanks. 

Also, it should be mentioned in the documentation because the current example given on the website doesn't work. It's confusing. 
http://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html

**Comment by MaxBenChrist** [comment]
Which one?

**Comment by marta-em** [comment]
Description of this: 
`class tsfresh.feature_extraction.settings.ReasonableFeatureExtractionSettings`

```
>>> from tsfresh.feature_extraction import extract_features, MinimalFeatureExtractionSettings
>>> extract_features(df, feature_extraction_settings=MinimalFeatureExtractionSettings)
```

Overall, great package :)

**Comment by MaxBenChrist** [comment]
If you want you can correct this and submit a pr. 

Thanks :)

**Comment by MaxBenChrist** [comment]
@earthgecko you were on the right track ;)

**Comment by earthgecko** [comment]
@MaxBenChrist oh that is good, Merry xmas :)
