### ISSUE TITLE
add mean_change_quantiles

### ISSUE THREAD

**Issue by kempa-liehr** [blue-yonder/tsfresh#134]
The idea of mean_abs_change_quantiles had been derived from discussion on the `driftbif_simulation` example and modelling the time series as Langevin equation as explained by [Siegert el al. (1998): _Analysis of data sets of stochastic systems_](http://dx.doi.org/10.1016/S0375-9601(98)00283-7). 

Therefore, not the mean absolute change per quantile, but its mean change per quantile is relevant.

**Comment by MaxBenChrist** [comment]
Also, we could investigate if it makes sense to make an "apply" feature out of this to only calculate     `div = np.abs(np.diff(x))` once

**Comment by MaxBenChrist** [comment]
At the moment we are completely restructuring tsfresh internally, afterwards we can implement this issue easily :)

**Comment by MaxBenChrist** [comment]
as the upcoming release will be breaking, we should include the renaming in it as well

**Comment by MaxBenChrist** [comment]
The current naming is correct. 

see, https://github.com/blue-yonder/tsfresh/blob/6dbdaef6d0dc0296c96a29db5ef757193051f649/tsfresh/feature_extraction/feature_calculators.py#L1023

But, we can add mean_change_quantiles, with out the abs

**Comment by MaxBenChrist** [comment]
merged with pr #248
