### ISSUE TITLE
Thanks for all the improvements! 

### ISSUE THREAD

**Issue by ClimbsRocks** [blue-yonder/tsfresh#141]
I submitted a few tickets after trying to use this my first time or two. Coming back to it now after a month or so away from the project, the user experience as a new user is MUCH better. Just wanted to say thanks for all the work you've done so far, and the work I see you're continuing to do in different branches.

**Comment by MaxBenChrist** [comment]
Thanks for the kind words. :)

**Comment by earthgecko** [comment]
Seconded ;)
