### ISSUE TITLE
Warning while feature selection

### ISSUE THREAD

**Issue by bobchennan** [blue-yonder/tsfresh#147]
No handlers could be found for logger "tsfresh.feature_selection.feature_selector"

Does it matters?

**Comment by MaxBenChrist** [comment]
It is fine, you have to [configure a logger](http://excid3.com/blog/no-handlers-could-be-found-for-logger)

**Comment by MaxBenChrist** [comment]
Maybe we can consider to call

```
import logging
logging.basicConfig()
```

somewhere in our scripts if the user does not specify a logging handler.

**Comment by bobchennan** [comment]
Yes, since it is not mentioned in the document.

**Comment by MaxBenChrist** [comment]
It is in the master, thanks for reporting it @bobchennan
