### ISSUE TITLE
Improving the speed of some feature calculators

### ISSUE THREAD

**Issue by tdeboissiere** [blue-yonder/tsfresh#148]
I have identified 4 feature calculators for which I could rewrite a faster implementation (cf. gif)

https://gist.github.com/tdeboissiere/def451b1e5e56c1fd8c8c133d7ffa8dc

I got speedups greater than 2 in most cases and as high as 20 for some dataframe configuration.
I don't know if my implementation is compatible with tsfresh' internals but if it is, I'll create a PR for that.

**Comment by MaxBenChrist** [comment]
Looks good! Looking forward to the pr
