### ISSUE TITLE
ipython notebook error 

### ISSUE THREAD

**Issue by deter3** [blue-yonder/tsfresh#15]
in notebook , robot_failure_example.ipynb , 

X_filtered = extract_relevant_features(df, y, column_id='id', column_sort='time') 

had error of 

"ValueError: Column a__autocorrelation__lag_8 of dataframe must not contain NaN values "

**Comment by jneuff** [comment]
Yeah, we recently changed the standard setting for feature extraction to not impute the results. Some features might produce NaNs under certain conditions. To have the results imputed you need to instantiate the FeatureExtractionSettings class manually and set IMPUTE to the desired impute function.

This should do the trick:
```python
from tsfresh.feature_extraction import FeatureExtractionSettings
from tsfresh.utilities.dataframe_functions import impute_dataframe_range

extraction_settings = FeatureExtractionSettings()
extraction_settings.IMPUTE = impute_dataframe_range
X_filtered = extract_relevant_features(df, y, column_id='id', column_sort='time', feature_extraction_settings=extraction_settings)
```
Thanks for bringing this up!
