### ISSUE TITLE
fit_transform / transform methods

### ISSUE THREAD

**Issue by vgoklani** [blue-yonder/tsfresh#157]
Is there a fit_transform / transform method? I would like to fit a model on a particular dataset, and then use those parameters to transform other datasets.

**Comment by jneuff** [comment]
Yes, we offer sklearn compatible transformers in the tsfresh.transformers module.

**Comment by nils-braun** [comment]
If you want, you can find some more information on their usage here:
http://tsfresh.readthedocs.io/en/latest/text/sklearn_transformers.html
