### ISSUE TITLE
Permission denied for robot_execution_failures data download 

### ISSUE THREAD

**Issue by deter3** [blue-yonder/tsfresh#16]
tsfresh.examples.robot_execution_failures.download_robot_execution_failures() 

got error 

"Permission denied: '/usr/local/lib/python2.7/site-packages/tsfresh/examples/data'"

i have to manually sudo mkdir folder and sudo wget http://archive.ics.uci.edu/ml/machine-learning-databases/robotfailure-mld/lp1.data to folder '/usr/local/lib/python2.7/site-packages/tsfresh/examples/data/robotfailure-mld/ " to make` df, y = load_robot_execution_failures()` working .

**Comment by jneuff** [comment]
We expected users install the package inside a virtualenv for which the user has full access rights. That is our normal workflow. Thanks for bringing this up, we will try to come up with a fix for the next release!

**Comment by jneuff** [comment]
The permissions are now checked before file creation is attempted.
