### ISSUE TITLE
using TSfresh feature expansion

### ISSUE THREAD

**Issue by RylandCapital** [blue-yonder/tsfresh#164]
I have a financial time series matrix with Open High Low Close columns. 
I was under the impression, for example, that you could use TSFresh to take the given features (aka Open High Low Close) and have it automatically create many more feature columns based on the original 4. 

From my experience it looks like TSFresh is taking each feature column and returning 1 value per 'id' per period. With a financial time series such as stock there is no 'id' aspect unlike the robot example.' Is there a way to create an entire new column with the characteristics of the applied formula (whether it be sums or abs energy, whatever)?

My goal is to have a new matrix that instead of 1000x4 for instance is 1000x100 with the feature column being derived from the original 4. 

Thanks!
Ryland

**Comment by MaxBenChrist** [comment]
Hi ryland,

There is actually an id in those financial time series, it is the day/asset combination.

The use case that you describe can be tackled by  Tsfresh. You will have to stack your dataframe to make it fit tsfreshs API.

However, even though you can calculate the features for the open high low close, i think does not make much sense from a machine learning point of view: normally time series or other signals are kind of uniformly sampled, in your case the high and low values can be spread all over the day. It would make more sense to take the price over the day and create features out of that. ( actually high and low are already features of the original time series)
