### ISSUE TITLE
Paralleling Feature Extraction

### ISSUE THREAD

**Issue by zwu52** [blue-yonder/tsfresh#166]
Thanks for developing such a nice library. I could see many fields can be benefited. So I notice the extraction takes fowever when I have hundreds of objects with thousands of channels of time seires. I was wondering if you guys were thinking about parallizing the feature extraction processes or are the algrorithms not paralleizbale? It would be nice to extract large scale features using people's on board GPUs.

**Comment by nils-braun** [comment]
Thank you!
Actually the extraction of features is already parallel in the IDs and kinds. As we are relying on different libraries (e.g. numpy, scipy etc) for calculating the extracted features, it is not that easy to ship all this to a GPU. Or do you know an easy possibility to port that code to a GPU?

**Comment by MaxBenChrist** [comment]
Even if we had the means to port tsfresh to the GPU, this will not speed up all features. (e.g. feature that involves sorting such as the median should stay on the CPU)

**Comment by MaxBenChrist** [comment]
I closed the issue as we already have a comprehensive parallelization in place
