### ISSUE TITLE
tsfresh for stock data

### ISSUE THREAD

**Issue by speculati0n** [blue-yonder/tsfresh#167]
I just recently converted AAPL stock features such as RSI and some Moving averages over a 10 year daily period into a stacked DataFrame using the date as the column_id, and the feature name (i.e. RSI, Moving Averages) as the column_kind.  I turned into a stacked dataframe so it would work within TSFresh. (my goal was to create many more features off of the given features (i.e. RSI, Moving Averages). While TSfresh executed perfectly, I don’t think the output features is what I was looking for. For example I am trying to have TSfresh take the RSI feature that I gave it and have it return for example some new feature columns like 1. Sum over a rolling period 2. Moving average of RSI of whatever length 3.Variance over a rolling period  . I thought TSfresh took a time series and created a new feature based on that series. Am I mistaken exactly what TS Fresh Does?

**Comment by nils-braun** [comment]
You are perfectly right in what TSFresh is doing, so this should be no problem.
What kind of output do you have afterwards? Or can you maybe give us a kind of example (e.g. a Jupyter notebook, can also be fake data, just for the format) so we can play around a bit?

**Comment by MaxBenChrist** [comment]
I am not sure if you use tsfresh correctly. I think you use it to calculate features (e.g. variance) of another feature (e.g. oving Averages), that is not the intended use.

tsfresh is for the translation (aggregated) time series to features. Try using the asset prices instead of the moving average.

Please have look at the documentation & notebooks and then come back if you have specific questions. When coming back please provide a data sample

**Comment by speculati0n** [comment]
Here is an image of an example of my original AAPL data: Contains Date, Asset's Close, and 10 Period Moving Average

Original:
![image](https://cloud.githubusercontent.com/assets/26420672/23966662/9619317c-0992-11e7-9e87-5d4639c69005.png)

I then stack the data so it looks like this (to work is TSFresh)

Stacked:
![image](https://cloud.githubusercontent.com/assets/26420672/23966806/22af3f96-0993-11e7-88ed-c0cf32fa69f8.png)

This is what I get

Output:
![image](https://cloud.githubusercontent.com/assets/26420672/23967072/f69075f0-0993-11e7-9f5d-20606453963c.png)

As you can see, TSFresh creates more columns/adds new features to my dataframe. However, I believe it is just returning that calculation PER DATE where I thought it would create a new column/new feature that is a rolling calculation of the original series involving multiple dates (aka IDs). Without a rolling factor or number involved, I can only imagine it is taking the abs energy calculation for instance and applying it to one timeseries/feature value per date and returning that. 

Thank you very much for taking the time to help me understand. I have been learning TSFresh for a while now and have really enjoyed it.

Speculati0n

**Comment by speculati0n** [comment]
I was not able to get it to work as I don't think the package was designed
for continuous time series.

**Comment by MaxBenChrist** [comment]
This is a scenario for which tsfresh works. I have personally used it on similar problems in the past (e.g. calculate a moving trend over technical indicators such as RSI). 

To use tsfresh you have to create a data frame that contains all the sliding windows on which you want to extract the features of. 

If you have a time series of length 10 and want to use a sliding window of exactly size 5, you will have to extract the 5 sliding window time series and create a new dataframe. We have some functionality to create those sliding windows, please see https://tsfresh.readthedocs.io/en/latest/text/forecasting.html or https://github.com/blue-yonder/tsfresh/blob/master/notebooks/timeseries_forecasting_basic_example.ipynb or https://github.com/blue-yonder/tsfresh/blob/master/notebooks/timeseries_forecasting_google_stock.ipynb

**Comment by nils-braun** [comment]
We do have functionality to roll and forecast. If this is not enough for your examples, please feel free to reopen. I am just cleaning up issues.
