### ISSUE TITLE
AAPL stock data

### ISSUE THREAD

**Issue by speculati0n** [blue-yonder/tsfresh#168]
Here is an image of an example of my original AAPL data: Contains Date, Asset's Close, and 10 Period Moving Average

Original:
![9619317c-0992-11e7-9e87-5d4639c69005](https://cloud.githubusercontent.com/assets/26420672/23979473/1c4a586a-09d0-11e7-9c6f-dd8c24e33dbe.png)

I then stack the data so it looks like this (to work is TSFresh)

Stacked:
![22af3f96-0993-11e7-88ed-c0cf32fa69f8](https://cloud.githubusercontent.com/assets/26420672/23979479/2576a114-09d0-11e7-9baa-72d5e6019f43.png)

This is what I get

Output:
![e](https://cloud.githubusercontent.com/assets/26420672/23979499/425916d6-09d0-11e7-9fff-34bc9ca5af2e.png)

As you can see, TSFresh creates more columns/adds new features to my dataframe. However, I believe it is just returning that calculation PER DATE where I thought it would create a new column/new feature that is a rolling calculation of the original series involving multiple dates (aka IDs). Without a rolling factor or number involved, I can only imagine it is taking the abs energy calculation for instance and applying it to one timeseries/feature value per date and returning that.

Thank you very much for taking the time to help me understand. I have been learning TSFresh for a while now and have really enjoyed it.

Speculati0n

**Comment by MaxBenChrist** [comment]
what is your column_id when you call tsfresh? the date column?

I am afraid that this does not look like a proper application of tsfresh :-/

**Comment by MaxBenChrist** [comment]
>  I can only imagine it is taking the abs energy calculation for instance and applying it to one timeseries/feature value per date and returning that.

Most features are boring for a one value time-series, e.g. the abs energy will just be the absolute value of the singular value

**Comment by nils-braun** [comment]
Reading through your issue and the images, I think what you want to have is the following:

A data frame with the following columns: ID, Date, AAPL Close, MovingAerage. From your starting data frame you would build as many time series, as you have dates, each of them one row longer that the one before. You would give each of these time series a unique ID and stack them together. Then you feed this into tsfresh.
Tsfresh will calculate its features on the data for each ID, this means in your example from above only on one row per ID - but you want it to calculate on several rows - so you have to fill in several rows with the same ID.

Example:
You start data frame is like:
Date  AAPL MovingAverage
1        x         y
2        z         a

Then you would feed into tsfresh:
ID    Date     AAPL     MovingAverage
0      1          x             y
1      1          x             y
1      2          z             a

with column_id = ID, column_time = Date.

tsfresh does not do the rolling by itself, you have to supply this to tsfresh.

**Comment by nils-braun** [comment]
Please also refer to #86, which is currently open.
