### ISSUE TITLE
Intel MKL ERROR

### ISSUE THREAD

**Issue by t2396156** [blue-yonder/tsfresh#169]
hi~,
      today i update my tsfresh to the lastest version and also other  fundamental package such as numpy, scipy. Then when i run my feature extrect code, it raise error:
Intel MKL ERROR: Parameter 4 was incorrect on entry to DGELSD.
and the program never goes foward until i shut it down manually.
my code ran successful yesterday, and I dont know which part goes wrong.
and here is part of my code.

```
def feature_extract(series):
    extracted_features = extract_features(series, column_id="id", column_value='value')
    return extracted_features
    
def feature_select(extracted_features, y):
    impute(extracted_features)
    features_filtered = select_features(extracted_features, y)
    return features_filtered

if __name__ == "__main__":
    series, y, emotion_idx = get_series()
    extracted_features = feature_extract(series)
    features_filtered = feature_select(extracted_features, y)
```

**Comment by MaxBenChrist** [comment]
I think this orignates from _estimate_friedrich_coefficients (the np.polyfit call in line 1317 in tsfresh/tsfresh/feature_extraction/feature_calculators.py)

Can you provide a minimal example? The data that caused these errors would be of great interest.

**Comment by MaxBenChrist** [comment]
It seams to follow from NaN or Inf values

(see http://stackoverflow.com/questions/24173301/numpy-polyfit-suppress-printing-of-intel-mkl-error-message)

In the friedrich oefficients

``` Python
        try:
            coeff = np.polyfit(result.x_mean, result.y_mean, deg=m)
        except (np.linalg.LinAlgError, ValueError):
            coeff = [np.NaN] * (m+1)

```
we maybe add a check if `result.x_mean` and `result.y_mean` are finite

**Comment by t2396156** [comment]
@MaxBenChrist 
ok, can you give me your email, then i can send my dataset and code.

**Comment by MaxBenChrist** [comment]
I wont have time until 26 of march, maybe you upload it? 

we only need that time series that caused this error, not all.

**Comment by MaxBenChrist** [comment]
Uploading to a repository is perfect, but you will have to boil the issue down to a subset of your data.
(Just start with 10 time series, run your script, check if error occurs, if not take the next 10 time series, so time series 11-20 untile you find it)

Thanks.

**Comment by t2396156** [comment]
@MaxBenChrist 
i'v upload my data in my repo, u can get my data here:
[https://github.com/t2396156/tsfresh_data](url)

**Comment by t2396156** [comment]
@MaxBenChrist  
and i run the code on my another dataset, it program raise no error
but it seems going to run forever if i dont shut it down.

**Comment by MaxBenChrist** [comment]
How big is the data set (length time series, number of ids)?

Do you see movements of the status bar?

**Comment by t2396156** [comment]
i have nearly 9000 series whith total length of 1.6million point, the status bar stays zero all the time.

**Comment by t2396156** [comment]
i meet another problem, i run the same code in different environments and the result are very different.
This three environments are all in my windows PC.
the code runs well in ipython and i get my feature.
![image](https://cloud.githubusercontent.com/assets/12410347/24045371/d51743fa-0b59-11e7-91b4-ae5a50fbb3f1.png)

it stop here when run in python shell
![image](https://cloud.githubusercontent.com/assets/12410347/24045104/e98383ea-0b58-11e7-99e4-154a28e62147.png)
and it raise this error repeatedly in pycharm
![image](https://cloud.githubusercontent.com/assets/12410347/24045305/9050a2d4-0b59-11e7-97f1-f8482ad141bb.png)

here is the code:
```
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures
from tsfresh.examples import load_robot_execution_failures
from tsfresh.transformers import RelevantFeatureAugmenter


download_robot_execution_failures()
df, y = load_robot_execution_failures()
# leave only a single column, namely a
df = df.drop(['b', 'c','d','e','f'],axis=1)
print df

y_train, y_test = train_test_split(y)
df_train = df.loc[df.id.isin(y_train.index)]
df_test = df.loc[df.id.isin(y_test.index)]
X_train = pd.DataFrame(index=y_train.index)
X_test = pd.DataFrame(index=y_test.index)
df_train.shape, df_test.shape

  
#X_train["pre_extracted_feature"] = 0 # add a feature
from tsfresh import extract_features
extracted_features = extract_features(df_train, column_id="id", column_sort='time')
from tsfresh.utilities.dataframe_functions import impute
from tsfresh import select_features
impute(extracted_features)
features_filtered = select_features(extracted_features, y_train)
print features_filtered
```

**Comment by MaxBenChrist** [comment]
I do not have access to any windows machine...

**Comment by MaxBenChrist** [comment]
This issue is reproduced by time series of type a and id 86 of the robot actitivity dataset.

I will submit a pr in a bit

**Comment by MaxBenChrist** [comment]
see pr 171

**Comment by MaxBenChrist** [comment]
Please check if your problems also occur with version 0.7.0, if they do reopen this issue.
