### ISSUE TITLE
Discuss/refactor baseline tests

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#179]
I am not sure if this unit test is that beneficial to us anymore as we check the values of the feature calculators individually.

**Comment by MaxBenChrist** [comment]
I would be in favor of removing them completely

**Comment by nils-braun** [comment]
Well, I wasn't in favor of the test from the beginning, but I thought the idea would be to have some sort of "real world" test with a full dataset?

**Comment by MaxBenChrist** [comment]
Are you citing me? ;) Okay, then lets ditch it

**Comment by MaxBenChrist** [comment]
I just merged pr #180 and removed the baseline tests
