### ISSUE TITLE
settings_new.from_columns not sticking strictly to given feature names

### ISSUE THREAD

**Issue by devautor** [blue-yonder/tsfresh#183]
I am trying to extract _strictly the same features for test data which tsfresh has selected from extracted ones for training data_. I have this as code: ``` settings_new.from_columns(trained_features)``` [learnt from [here]](https://github.com/blue-yonder/tsfresh/issues/22)
Code snippet:
```python
X = extract_features(train_df, column_id='unit', column_sort='cycles', feature_extraction_settings=extraction_settings, parallelization='per_sample')
X_filtered = select_features(X, y)
trained_features = list(X_filtered.columns.values)[1:]
settings_new.from_columns(trained_features)
X_new = extract_features(test_df, column_id='unit', column_sort='cycles', feature_extraction_settings=settings_new, parallelization='per_sample')
```
**Problem:** My test features count to 5328, same for X, and not X_filtered which is 1045.
Perhaps, all parameters are being tweaked again, or I am doing it the wrong way. So, how should I get only those features from test data which have been selected finally from test data feature extraction & selection process.
OS: Ubuntu 16.04 LTS
tsfresh 0.7.0

P.S.: Sorry for the long post, I just wanted to be clear. I have asked this on gitter too, I hope that is not arrogant. Thanks a lot for this real-needed library!

**Comment by MaxBenChrist** [comment]
Hi @devautor,

You have to replace

`settings_new.from_columns(trained_features)` 

with

`settings_new = settings_new.from_columns(trained_features)`

**Comment by MaxBenChrist** [comment]
I corrected the other snippet as well, thanks for reporting that. 

If your problems persist, please reopen this issue
