### ISSUE TITLE
The impute method does not work properly on np.float64 or np.int64

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#187]
It returns the same DataFrame. Casting it as `np.float32` seem to resolve this

**Comment by MaxBenChrist** [comment]
Can be reproduced by

``` Python
from tsfresh.utilities.dataframe_functions import impute
import pandas as pd
import numpy as np
X = pd.DataFrame({"a":range(10), "b":range(10)})
impute(X)
impute(X.astype(np.float32))

```

**Comment by MaxBenChrist** [comment]
Well, the bug occurs in 

https://github.com/blue-yonder/tsfresh/blob/master/tsfresh/utilities/dataframe_functions.py#L153

``` python

    indices = np.nonzero(np.isnan(df_impute.values))
    if len(indices[0]) > 0:
        replacement = [col_to_median[columns[i]] for i in indices[1]]
        df_impute.values[indices] = replacement

```

**Comment by MaxBenChrist** [comment]
so, I boiled this down to 

```Python

import pandas as pd
import numpy as np
X = pd.DataFrame({"a":range(2), "b":range(2), "c": range(2)})
X.iloc[0,0] = np.NaN
X.iloc[1,1] = np.NaN

print(X)

X64 = X.copy()
X64  = X64.astype(np.float64)
print(X.info())
print(X64.info())


indices = np.nonzero(np.isnan(X.values))
indices64 = np.nonzero(np.isnan(X64.values))

X.values[indices] = [5, 5]
X64.values[indices64] = [5, 5]

print(indices)
print(X)
print(indices64)
print(X64)

print(X._data)
print(X64._data)

X.iloc[indices] = [5, 5]
X64.iloc[indices64] = [5, 5]

print(indices)
print(X)
print(indices64)
print(X64)
```

which gives me 

```
     a    b  c
0  NaN  0.0  0
1  1.0  NaN  1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
a    1 non-null float64
b    1 non-null float64
c    2 non-null int64
dtypes: float64(2), int64(1)
memory usage: 120.0 bytes
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
a    1 non-null float64
b    1 non-null float64
c    2 non-null float64
dtypes: float64(3)
memory usage: 120.0 bytes
None
(array([0, 1]), array([0, 1]))
     a    b  c
0  NaN  0.0  0
1  1.0  NaN  1
(array([0, 1]), array([0, 1]))
     a    b    c
0  5.0  0.0  0.0
1  1.0  5.0  1.0
BlockManager
Items: Index([u'a', u'b', u'c'], dtype='object')
Axis 1: RangeIndex(start=0, stop=2, step=1)
FloatBlock: slice(0, 2, 1), 2 x 2, dtype: float64
IntBlock: slice(2, 3, 1), 1 x 2, dtype: int64
BlockManager
Items: Index([u'a', u'b', u'c'], dtype='object')
Axis 1: RangeIndex(start=0, stop=2, step=1)
FloatBlock: slice(0, 3, 1), 3 x 2, dtype: float64
(array([0, 1]), array([0, 1]))
     a    b  c
0  5.0  5.0  0
1  5.0  5.0  1
(array([0, 1]), array([0, 1]))
     a    b    c
0  5.0  5.0  0.0
1  5.0  5.0  1.0
```

**Comment by MaxBenChrist** [comment]
So, `iloc` seem to do the job.

**Comment by nils-braun** [comment]
Just to clarify for later reference: the problem is the `.values` function, which (according to the documentation):
> The dtype will be a lower-common-denominator dtype (implicit upcasting); that is to say if the dtypes (even of numeric types) are mixed, the one that accommodates all will be chosen. Use this with care if you are not dealing with the blocks.
So in case of mixed dtypes (which you have created, as you start with int64 and add np.NaN (which is float64) to two columns only, converting them to float64 but not the third column), you only get a *copy* of the numpy values. Changing them does not change the underlying data set.

**Comment by MaxBenChrist** [comment]
> So in case of mixed dtypes (which you have created, as you start with int64 and add np.NaN (which is float64) to two columns only, converting them to float64 but not the third column), you only get a copy of the numpy values. Changing them does not change the underlying data set.

Yes, I came to the same conclusion. The underlying problem is that the `.astype` is not operating inplace.

**Comment by MaxBenChrist** [comment]
solved by pr #189

**Comment by xhochy** [comment]
The problem here seems to be related to mixed-dtype DataFrames not having a single backing NumPy array. In this case `.values` returns a copy of the DataFrame with the most common dtype. If the DataFrame is of a single dtype, then all columns are backed by a single Matrix. This matrix is then returned as the result of `.values`. Only in the latter case, modifications to the matrix returned by `.values` will be back-propagated to the original DataFrame.

**Comment by MaxBenChrist** [comment]
Thanks for the explanation, uwe.
