### ISSUE TITLE
do_not_calculate() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by devautor** [blue-yonder/tsfresh#192]
do_not_calculate() doesn't work like mentioned in the doc [here](http://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html#tsfresh.feature_extraction.settings.FeatureExtractionSettings):
Code:
```
extraction_settings = FeatureExtractionSettings()
extraction_settings = extraction_settings.do_not_calculate("length")
```

> TypeError: do_not_calculate() takes exactly 3 arguments (2 given)

Also, from the source-code:
> Delete all features of type identifier for time series of type kind.
>         :param kind: the type of the time series
>         :type kind: basestring
>         :param identifier: the name of the feature
>         :type identifier: basestring

**What are these two parameters? What does type of time series mean?**
Version: tsfresh(0.7.0)

**Comment by MaxBenChrist** [comment]
Kind is the type of the time series and identifier is the name of the feature, in this case length

**Comment by MaxBenChrist** [comment]
http://tsfresh.readthedocs.io/en/latest/text/data_formats.html

**Comment by MaxBenChrist** [comment]
The Linke contains a detailed description of the data formats and the kind column
