### ISSUE TITLE
Feature Extraction:   0%|  | 0/6 [00:00<?, ?it/s] Takes Forever and it never ends

### ISSUE THREAD

**Issue by LoganCarvalho** [blue-yonder/tsfresh#193]
Hello everyone,
I'm facing what a believe is an issue.

1. I'm using OS X El Capitan 10.11.6
2. I'm on the latest version of TFRESH since I just (April, 13, 2017) installed it via pip
3. It happened with me yesterday (April, 14, 2017). The dataset I'm using looks like this:
Date,Close
27.03.2017 00:00:00,1.08452
...
4. The entire code I'm trying to run is the following one:
`import pandas as pd`
`from tsfresh import extract_features `
`from tsfresh.feature_extraction import MinimalFeatureExtractionSettings`

`DataFrame = pd.read_csv('seriesForex.csv', engine='python')`
`featu = extract_features(DataFrame, column_id='Date', column_value='Close', feature_extraction_settings = MinimalFeatureExtractionSettings()) `

I also tried:

`featu = extract_features(DataFrame, column_id='Date', column_value='Close')`

5. I've tried running the example on the link below with no results as well:
[https://github.com/blue-yonder/tsfresh/blob/master/tests/examples/test_robot_execution_failures.py]()

What am I missing? Thanks in advance.

**Comment by moritzgelb** [comment]
Hi, 

it seems to me that you didn't use the ```column_id``` argument correctly. 
Please take a look at the [documentation]( http://tsfresh.readthedocs.io/en/latest/text/data_formats.html).

Cheers, 
Moritz

**Comment by nils-braun** [comment]
The Date column is probably the sort column in your case. The ID should be a number, that distinguishes different time series.

**Comment by ddofer** [comment]
Same issue, stuck at 0% , 
"[00:00<?, ?it/s]"

df_fresh_tr = extract_relevant_features(tr_data.drop(["class","timestamp"],axis=1), y,
                                                     column_id='targetName', column_sort='Time')


Data:  (Time is in seconds , I drop the timestamp. targetName is the ID)

Time | class | posX | posY | posZ | targetName | velX | velY | velZ | timestamp
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0.0 | 3 | 0.000000 | 0.000000 | 476.575673 | YantakNg3 | 486.926974 | 3.057090 | 305.119216 | 2017-01-01 00:00:00.000
0.5 | 3 | 241.974495 | -3.247714 | 629.299199 | YantakNg3 | 483.225599 | -0.534244 | 305.483552 | 2017-01-01 00:00:00.500

**Comment by wxhdf** [comment]
me too

**Comment by nils-braun** [comment]
@wxhdf - do you have a reproducible example? How large is the dataset you are using and have you tried with the minimal settings?
