### ISSUE TITLE
roll_time_series creates same values

### ISSUE THREAD

**Issue by TKlerx** [blue-yonder/tsfresh#197]
Hi all,

thanks for the great library and the new feature of rolling time series.
Unfortunately, there seems to be a bug in the new feature:
Instead of using the values of the previous timestamps, always the same values are used for a point in time t.
I attached a notebook where I implemented the rolling time series on my own and compared it with the tsfresh version.
[bug-tsfresh-rolling.zip](https://github.com/blue-yonder/tsfresh/files/958964/bug-tsfresh-rolling.zip)
I could supply a test case with and create a pull request if you wish.

Versions:
Win10 x64
tsfresh 0.7.1
python = 3.5 and 3.6

The expected output of the example given at https://tsfresh.readthedocs.io/en/v0.7.1/text/rolling.html should should be

id | t | variable | value
------------ | ------------- | ------------ | ------------- 
1  |2 	|x_shift0 	|2.0 
1 |2 	|x_shift1 	|1.0 	
1 |2 	|y_shift0 	|6.0 	
1 |2 	|y_shift1 	|5.0 	

but the output is

id | t | variable | value
------------ | ------------- | ------------ | ------------- 
1 |2 	|x _shift0|2.0 
1|2 	|x_shift1 |2.0 	
1 |2 	|y_shift0 |6.0 	
1|2 	|y_shift1 |6.0

**Comment by nils-braun** [comment]
Hi @TKlerx!
Thank you for your question. And you even included a notebook - this is how we like our bug reports :+1: 

However, I think I do not understand your question fully. The time column is also shifted, so the time of `t = 2` has always the same `x` and `y` values - we just "delete" the "later" rows (or the earlier ones, depending on the direction). 
If you look into `df_tsf_rolling[(df_tsf_rolling.id == "id=1, shift=1") & (df_tsf_rolling.variable == "x")].sort_values(by=['t','id'])` and `df_tsf_rolling[(df_tsf_rolling.id == "id=1, shift=0") & (df_tsf_rolling.variable == "x")].sort_values(by=['t','id'])` in your notebook, you may see how it works.

Please ask, if you still have a question.

**Comment by TKlerx** [comment]
Hi @nils-braun,

thank you for your quick answer. You are correct, I misunderstood the API. I thought that I would get the values of id=1 from t=1 added to id=2 and t=2.

As you mentioned, one has to group by the new id.

Is there any possibility to define the maximum length of the resulting time series?
I would like to use it in the following scenario:
For time t=i, I want to include the previous k measurements and extract features for in these k+1 measurements. 

Is there any possibility to do this right away?

Thank you,
Timo

**Comment by MaxBenChrist** [comment]
Hey Timo, Have you looked at the `maximum_number_of_timeshifts` parameter? You can use it to shift up to maximum of k values.

I dont think we have a functionality to shift exactly k values.

**Comment by nils-braun** [comment]
Well, you could of course just filter by the created if (the shift is encoded in it), but you probably want to limit to only one shift value to save computation time, do you? If this is the case, you would probably have to reimplement the shift function on your own... If time consumption is not a problem here (which I think it should not be), you can just extract until k and filter out the values you want to have.

**Comment by TKlerx** [comment]
Ok, thanks @MaxBenChrist and @nils-braun for your answers. 

You are right @nils-braun, I am trying to save computation time, so I will implement it on my own.

**Comment by MaxBenChrist** [comment]
I don't think you will save much time @TKlerx because you will have to calculate the same auxiliary results. We are just not throwing them away. 

However, if you manage to speed up the calculation I would be very happy to see a pr! :) 

Also, do you have any feedback about the documentation of our method? Apparently it confused you, maybe you have same ideas to improve it?

**Comment by TKlerx** [comment]
I already implemented the shift by k on my own. It's in the notebook. I did not try to optimize it for runtime, but I guess it could be more efficient than computing all shifts.

I will try to make a PR, but probably not before 15th May :(

Same for the documentation. I have some ideas and will create another PR then.

**Comment by MaxBenChrist** [comment]
Perfect, looking forward to them
