### ISSUE TITLE
Time reversal discrepancies

### ISSUE THREAD

**Issue by kipkeston** [blue-yonder/tsfresh#198]
I was looking at the time reversal function description from the docs and the source code for it. There is a discrepancy between the docs and the code.

The code is as follows:

`(np.roll(x, 2 * -lag) * np.roll(x, 2 * -lag) * x - np.roll(x, -lag) * x * x)`

however based on reading the documentation, I expected:

`(np.roll(x, 2 * -lag) * np.roll(x, 2 * -lag) * np.roll(x, -lag) - np.roll(x, -lag) * x * x)`

Furthermore, can the documentation better explain the differences between the tsfresh implementation and the Fulcher or Schreiber & Schmitz versions?

**Comment by MaxBenChrist** [comment]
There is indeed a difference between documented and implemented version, in the implemented version the x before the minus is not lagged.

**Comment by MaxBenChrist** [comment]
Disclaimer: I don't had the time to read the papers in detail. 

But, the Schreiber and Schmitz paper (https://www.macalester.edu/~kaplan/knoxville/PRE05443.pdf) contains 5 measures of non-linearity. Interesting for us. We could implement all of them.

Regarding the time reversal function, Further, Schreiber and Schmitz use 
![bildschirmfoto 2017-05-08 um 10 51 33](https://cloud.githubusercontent.com/assets/13162426/25797135/4f521532-33dc-11e7-94a9-0658e7e67bd2.png)
to detect deviations from time-reversibility.

Meanwhile, Fulcher propose to use
![bildschirmfoto 2017-05-08 um 10 53 25](https://cloud.githubusercontent.com/assets/13162426/25797224/92df452c-33dc-11e7-846a-1a4ccc5b0fe3.png)

I am not sure about the implications of the different measures, maybe somebody with a background in physics can elaborate a little bit. Both sources use other measures, so we should update our calculation and/or documentation.

**Comment by kipkeston** [comment]
tREV from the literature is equivalent to differencing the sequence by some lag and then calculating the skewness coefficient. I think the correct implementation should follow naturally from there.

**Comment by MaxBenChrist** [comment]
sorry for the delay. as always, time is limited :-/

I am still planning to tackle this issue. Would be interesting to have all 5 measures of non linearity.

> tREV from the literature is equivalent to differencing the sequence by some lag and then calculating the skewness coefficient. I think the correct implementation should follow naturally from there.

So you say that time reversal asymmetry statistic is equal to skewness coefficient of the lagged diffed signal. But in the Fulcher equation from above, the mean term is missing in the skewness coefficient, isn't it?

**Comment by benfulcher** [comment]
The definition used in [hctsa](https://github.com/benfulcher/hctsa) rescales relative to the second order moment, as is implemented in (the now long abandoned package) [TSTOOL](http://www.physik3.gwdg.de/tstool/).
But it also computes the raw version from Schreiber and Schmitz, Eq. (6), i.e., the numerator of the normalized statistic.
I'm not fully on top of the theory to provide much nuance as to which implementation makes more sense, but the nonlinear time-series analysis literature is a large one, and there have been lots of methods developed for detecting nonlinearity. hctsa also implements a range of higher order autocorrelations etc., and some surrogate data methods, all of which have been used in the literature to detect nonlinear time-series structure.

**Comment by MaxBenChrist** [comment]
@benfulcher Thanks for the feedback :) 

I will add an issue that we scan TSTOOL for other features to implement.

Further, I fixed the missing lag. thanks for reporting @kipkeston.

I  will also add some other measure of non linearity from the Schmitz paper.
