### ISSUE TITLE
robot_failure_example: "IndexingError: Unalignable boolean Series key provided"

### ISSUE THREAD

**Issue by Heavy02011** [blue-yonder/tsfresh#199]
I'm encountering an error using the  [(robot_failure_example)](https://github.com/blue-yonder/tsfresh/blob/master/notebooks/robot_failure_example.ipynb) using code to generate own sample data like

    df = pd.DataFrame(
          {"id"  : [ 1, 1, 1, 1, 2, 2, 2, 2],
           "time": [10,11,12,13,14,15,16,17],
           "a"   : [ 2, 2, 3, 2, 2, 3, 2, 2],
           "b"   : [ 0,11, 0, 0, 0, 0, 0, 0]},
           index = [ 1, 2, 3, 4, 5, 6, 7, 8])
    y = pd.Series([])

    for i in range(8):
       y[i] = 0
    y[1]=1

after the execution of 

    %time X_filtered = extract_relevant_features(df, y, column_id='id', column_sort='time', feature_extraction_settings=extraction_settings)

This is the error message:

<img width="486" alt="bildschirmfoto 2017-05-07 um 16 12 19" src="https://cloud.githubusercontent.com/assets/1910508/25781902/102179da-3340-11e7-9223-8eca8c8e6e14.png">

1. Your operating system: macOS Sierra 10.12.4 using conda 4.3.11 with  [carnd-term1 environment](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md)
2. The version of *tsfresh* that you are using: tsfresh (0.7.1)
3. The data on which the problem occurred: see above
4. A minimal code snippet which reproduces the problem/bug: just copy code lines into "robot_failure_example" notebook

<img width="1144" alt="bildschirmfoto 2017-05-07 um 16 05 15" src="https://cloud.githubusercontent.com/assets/1910508/25781834/08b3a408-333f-11e7-8c38-252039eccf02.png">

What obvious point do I overlook?

**Comment by MaxBenChrist** [comment]
Your target vector should only contain two values as you only have two samples

**Comment by MaxBenChrist** [comment]
Was something in the documentation that confused you? Maybe you have an idea to improve it? :)

**Comment by kr1stjans** [comment]
I disagree that target vector should only contain two values for two samples.

Target vector is independent of the number of samples. Target vector in the documentation is 0 and 1 only because there are two states (robot reports a failure or not). If we have one, two or n robots, the target vector would still have only two values.

In the different scenario, the target vector could be robot's electricity consumption. Target vector values would therefore be any real number or integer number (electricity consumption can be 1 Wh, 2Wh, 100Wh, 1000Wh, independently of the number of robots). One, two or n robots could have all those values.

I just recently discovered tsfresh, so correct me if I'm wrong, but this is how I understand it.

**Comment by MaxBenChrist** [comment]
sorry, but a feature selection for just one sample does not make sense. Lets assume you have a feature matrix with one sample and three features

f1 | f2 | f3 | y
1 | 0 | 4 | 1

How do you want to select features???

If you have two or more samples, like

f1 | f2 | f3 | y
1 | 0 | 4 | 1
11| -4 | 1 | 0
...

you can e.g. start looking at the correlation of target f1 to the target y and select features based on the correlation.

**Comment by MaxBenChrist** [comment]
If you have just one sample, you have no variation in the features which means that you can not address how the feature is connected to the target

In the same way, you can not train a regression or classification model on just one sample

**Comment by kr1stjans** [comment]
I agree with your last comments, but the word "sample" in your first post in this issue confused me.
> Your target vector should only contain two values as you only have two samples
```
df = pd.DataFrame(
      {"id"  : [ 1, 1, 1, 1, 2, 2, 2, 2],
       "time": [10,11,12,13,14,15,16,17],
       "a"   : [ 2, 2, 3, 2, 2, 3, 2, 2],
       "b"   : [ 0,11, 0, 0, 0, 0, 0, 0]},
       index = [ 1, 2, 3, 4, 5, 6, 7, 8])
y = pd.Series([])

for i in range(8):
   y[i] = 0
y[1]=1
```
But there are 8 samples and 8 target values in OP's example. If there are 8 samples, I though my definition of sample was wrong. So I search for somethins else. I though you mean two distinct ids (ie two different robots with ids 1 and 2 with the word sample). Sorry, my bad. However, this doesn't explain OP's error. He has 8 samples and his target variable has 8 values. Why does he get error?

**Comment by MaxBenChrist** [comment]
He has two samples (one with id 1 and one with id 2)
