### ISSUE TITLE
Several feature calculators lack unit tests

### ISSUE THREAD

**Issue by jneuff** [blue-yonder/tsfresh#2]
The feature calculators augmented_dickey_fuller, fft_coefficient, number_cwt_peaks, spkt_welch_density, cwt_coefficients lack unit tests. See [feature_calculators.py](https://github.com/blue-yonder/tsfresh/blob/master/tsfresh/feature_extraction/feature_calculators.py) for their implementations. Stubs for the corresponding tests can be found in [test_feature_calculations.py](https://github.com/blue-yonder/tsfresh/blob/master/tests/feature_extraction/test_feature_calculations.py)

**Comment by MaxBenChrist** [comment]
Now all features are tested :)
