### ISSUE TITLE
Can anyone provide a example of a regression problem?

### ISSUE THREAD

**Issue by NickYi1990** [blue-yonder/tsfresh#200]
I really do not know how to use this package to solve a regression problem, like predict a company in which day earned how many money.

But i think this package must can be used to solve this kind of problem, is there any example?

**Comment by mynameisvinn** [comment]
this package "contains many feature extraction methods" that characterize time series data. it wont, however, fit regression models (or any other statistical models) for prediction.

**Comment by MaxBenChrist** [comment]
Vinn is right, tsfresh is just used to do the preprocessing. It will map the time series into the feature space, on this feature space you can use regression models from other libraries, e.g. Tensorflow or sklearn.

I will let this issue open, We need some notebooks showing how to use tsfresh for time series forecasting g

**Comment by NickYi1990** [comment]
thanks!

**Comment by yenicelik** [comment]
Has there been any progress on this ever since the last comment?
