### ISSUE TITLE
Function FeatureExtractionSettings.do_not_calculate() cannot deduct features

### ISSUE THREAD

**Issue by smueller18** [blue-yonder/tsfresh#203]
Version: latest

I tried to exclude some features from the extraction process but an error occured.
The error also occurs on running the example from http://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html#tsfresh.feature_extraction.settings.FeatureExtractionSettings:

```python
from tsfresh.feature_extraction import FeatureExtractionSettings
settings = FeatureExtractionSettings()
# Calculate all features except length
settings.do_not_calculate("length")
from tsfresh.feature_extraction import extract_features
extract_features(df, feature_extraction_settings=settings)
```
Follwoing exception is thrown:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-19-39faeea46945> in <module>()
      2 settings = FeatureExtractionSettings()
      3 # Calculate all features except length
----> 4 settings.do_not_calculate("length")
      5 from tsfresh.feature_extraction import extract_features
      6 extract_features(df, feature_extraction_settings=settings)

TypeError: do_not_calculate() missing 1 required positional argument: 'identifier'
```

Anyway, the function `FeatureExtractionSettings.do_not_calculate()` cannot remove any features in that form, because at the position where the exception is thrown, the dictionary `settings.kind_to_calculation_settings_mapping`, which the functions tries to deduct items from, is empty.

For me, it make only sense, that the function `do_not_calculate()` is replaced by the following one:

```python
def do_not_calculate(self, kind):
        """
        Delete all features of type kind.

        :param kind: the type of the time series
        :type kind: basestring
        :return: The setting object itself
        :rtype: FeatureExtractionSettings
        """

        if not isinstance(kind, basestring):
            raise TypeError("Time series {} should be a string".format(kind))

        del self.name_to_param[kind]
        return self
```

I did not open a pull request, because the existing `FeatureExtractionSettings.do_not_calculate()` function has its eligibility to filter features after creating a settings object by calling `FeatureExtractionSettings.from_columns()`.

Can you check that please?

**Comment by smueller18** [comment]
Just saw that #133 updates the settings module and handling would be a lot easier. If that pull request makes it to the master branch, this issue can be closed automatically.

**Comment by MaxBenChrist** [comment]
Hi @smueller18, Thanks for reporting this issue. 

I would prefer to not invest in the old API and switch to the new one as fast as possible. I already started to solve the merge conflicts on the #133 PR. 

If you wait a few days, this problem will be obsolete.

**Comment by MaxBenChrist** [comment]
The pr is finally in master. ;)

**Comment by MaxBenChrist** [comment]
So you can just do

```
 from tsfresh.feature_extraction import ComprehensiveFCParameters
settings = ComprehensiveFCParameters()

del settings["length"] # removes the length feature from group of extracted features
from tsfresh.feature_extraction import extract_features
extract_features(df, default_fc_parameters=settings)
```
