### ISSUE TITLE
Feature extraction support for time series with different sampling rates

### ISSUE THREAD

**Issue by smueller18** [blue-yonder/tsfresh#204]
In a scenario with time series with different sampling rates, a dataset could look like:
```
	id	time	a	b
0	1	0	4	9.0
1	1	1	3	NaN
2	1	2	5	7.0
3	1	3	7	NaN
4	2	0	8	13.0
5	2	1	11	NaN
6	2	2	4	11.0
7	2	3	2	NaN
```
The sampling frequency of `a` is 1 and of `b` is 0.5.

tsfresh does not allow this timeseries, because the column `b` contains `NaN` values.
```python
import pandas as pd
import numpy as np
from tsfresh import extract_features

data = {
    "id": [1,1,1,1,2,2,2,2],
    "time": [0,1,2,3,0,1,2,3],
    "a": [4,3,5,7,8,11,4,2],
    "b": [9,np.nan,7,np.nan,13,np.nan,11,np.nan],
}
columns = ["id", "time", "a", "b"]
timeseries = pd.DataFrame(data=data, columns=columns)

extract_features(timeseries, column_id='id', column_sort='time')
```
Output:
```
/opt/conda/lib/python3.6/site-packages/tsfresh/utilities/dataframe_functions.py in normalize_input_to_internal_representation(df_or_dict, column_id, column_sort, column_kind, column_value)
    324     for kind in kind_to_df_map:
    325         if kind_to_df_map[kind][column_value].isnull().any():
--> 326             raise ValueError("You have NaN values in your value column.")
    327 
    328     return kind_to_df_map, column_id, column_value

ValueError: You have NaN values in your value column.
```
At the moment, in that case, the dataset must be split into two seperate sets:
```python
import pandas as pd
import numpy as np
from tsfresh import extract_features
from tsfresh.feature_extraction import MinimalFeatureExtractionSettings

settings = MinimalFeatureExtractionSettings()

data_a = {
    "id": [1,1,1,1,2,2,2,2],
    "time": [0,1,2,3,0,1,2,3],
    "a": [4,3,5,7,8,11,4,2],
}
data_b = {
    "id": [1,1,2,2],
    "time": [0,2,0,2],
    "b": [9,7,13,11],
}
columns_a = ["id", "time", "a"]
columns_b = ["id", "time", "b"]

timeseries_a = pd.DataFrame(data=data_a, columns=columns_a)
timeseries_b = pd.DataFrame(data=data_b, columns=columns_b)

features_a = extract_features(timeseries_a, column_id='id', column_sort='time', feature_extraction_settings=settings)
features_b = extract_features(timeseries_b, column_id='id', column_sort='time', feature_extraction_settings=settings)

pd.concat([features_a, features_b], axis=1)
```

It would be nice to implement support for timeseries with different sampling rates, which in my case are generated by SQL queries including multiple tables.
What I can imagine is the introduction of a new parameter (`has_different_sampling_rates`) to the function `extract_features()` and if it is set to `True` then allow `NaN` values. To extract features with only valid values, each column could be filtered with `column.loc[~column.isnull()]` before feeding them to the calculators.

This modification would also allow different timeseries with equal sampling rates but shifted timestamps:
```
	id	time	a	b
0	1	0	NaN	9.0
1	1	0.1	3	NaN
2	1	1	NaN	7.0
3	1	1.1	7	NaN
```

**Comment by MaxBenChrist** [comment]
This is the reason why we have the stacked dataframe format, see option 2 on http://tsfresh.readthedocs.io/en/latest/text/data_formats.html

You can melt (https://pandas.pydata.org/pandas-docs/stable/generated/pandas.melt.html) your dataframe and then drop the nans.

**Comment by MaxBenChrist** [comment]
```
timeseries = pd.melt(timeseries, id_vars="id", value_vars=["a", "b"])
timeseries.rename(columns={"variable":"kind"}, inplace=True)
timeseries.dropna(inplace=True)
```

this should do the job

**Comment by MaxBenChrist** [comment]
Regarding the `has_different_sampling_rate` parameter, I do not think it is a good idea to add a parameter for this. I think it is a preprocessing and not a calculation issue

**Comment by smueller18** [comment]
Thanks for the quick reply, I did not know `pd.melt()` so far. With that it's easy to implement for me.

**Comment by MaxBenChrist** [comment]
No problem ;) bytheway we are always looking for nice examples as  ipython notebook, feel free to submit a Pr if you have one
