### ISSUE TITLE
Add MinimalFeatureExtractionSettings

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#21]
Right now our FeatureExtractionSettings contains many features.

It would be nice to have a smaller FeatureExtractionSettings object that only calculates basic properties such as mean, median, min, max. This would allow to fastly  tinker with data and then later calculate the big list of features

**Comment by nils-braun** [comment]
Do you think it would be better to delete the other calculations from the beginning in the name_to_param array or just do not add them to the kind_to_calculation_settings_mapping in the set_default_parameters function?

And how to deal with it in the from_columns method? I think here the functions should still be added if the user requests them - this is why I would not delete them from name_to_param but from kind_to_calculation_settings_mapping.

**Comment by MaxBenChrist** [comment]
@jneuff looked into that. Maybe he can add some remarks as well. We moved the setup of `name_to_param` from the `set_default_parameters` to the constructor. See 8048ef4.

The current logic is *"extract all the features from `name_to_param` for all types of time series"*. 

If we follow that for a minimal MinimalFeatureExtractionSettings Object, then it just have a smaller  `name_to_param` object.

**Comment by jneuff** [comment]
I'd offer methods to instantiate a minimal and a full Settings object. A simple solution would be to initialize `name_to_param` as empty dict in the __init__ and provide two class methods that will instantiate and configure a minimal and a full Settings object respectively. Similar to what we're doing right now with from_columns.

**Comment by nils-braun** [comment]
I am actually against doing this with another member function - because it would be something everyone has to call everytime and it would be easily forgotten. I would rather create a child class MinimalFeatureExtractionSettings and overload the constructor.
