### ISSUE TITLE
SystemExit: 2 when running from tsfresh import extract_relevant_features

### ISSUE THREAD

**Issue by pbamotra** [blue-yonder/tsfresh#214]
-MacOS X
-installed using pip install tsfresh 
-import error
<img width="985" alt="screen shot 2017-06-15 at 2 38 31 pm" src="https://user-images.githubusercontent.com/6505165/27202947-79414a88-51d8-11e7-889b-6924f4093a59.png">

**Comment by MaxBenChrist** [comment]
We are all using Mac OS, without the problem that you described. 

You can try to install tsfresh into a virtual environment:

``` bash

virtualenv venv
. venv/bin/activate
pip install tsfresh
```

**Comment by nils-braun** [comment]
This looks more as something may be wrong with your python installation in total (because we do not have such a `__main__.py` in our project).

**Comment by MaxBenChrist** [comment]
Like @nils-braun, I do not see that your problem is related to tsfresh. Please reopen this issue if the problem persists and you have more indications that the error originates from tsfresh
