### ISSUE TITLE
Introduce scientific results of feature selection

### ISSUE THREAD

**Issue by smueller18** [blue-yonder/tsfresh#216]
Writing my thesis, I need a scientific result of how the features are being selected. Therefore, it is very helpful to plot the Benjamini-Yekutieli procedure like in the paper [Distributed and parallel time series feature extraction for industrial big data applications](https://arxiv.org/abs/1610.07717), Figure 2.

For this feature, the rejection line and the significance test DataFrame must be passed somehow to the user. I created the branch [feature/scientific-report](https://github.com/smueller18/tsfresh/tree/feature/scientific-report) and implemented the feature on a fast way, because I need the results soon. But this version is NOT backwords compatible, because some functions will return more parameters than in the older versions.

Do you have any suggestions how this feature could be implemented without loosing backwords compatibility?

At https://github.com/smueller18/tsfresh/blob/feature/scientific-report/notebooks/benjamini_yekutieli_plot.ipynb you can find a notebook with the plots I need for my thesis.

**Comment by MaxBenChrist** [comment]
Our feature selector return the p-values. You can take them, reimplement the benjamini hochberg procedure and plot it.

I do not see an opportunity to plot it without breaking other things.

**Comment by MaxBenChrist** [comment]
Also I do not see a need to create those plots inside tsfresh.

**Comment by MaxBenChrist** [comment]
If you need some help, please reopen this issue. 

Also, your plots seem finished (I could have provided my plotting routines)
