### ISSUE TITLE
How to deal with rolling window

### ISSUE THREAD

**Issue by mahnunchik** [blue-yonder/tsfresh#219]
How to deal with rolling window on data from exactly one source (`column_id` in term of `extract_features`)?

For example I have the data:

```
                       amount 
2017-01-01 00:01:00    100
2017-01-01 00:01:30    200
2017-01-01 00:02:00    300
2017-01-01 00:02:30    100
2017-01-01 00:03:00    100
```

I'd like to extract features by 1 hour period, so windows should be like:

```
2017-01-01 00:01:00    100
2017-01-01 00:01:30    200
```
```
2017-01-01 00:01:30    200
2017-01-01 00:02:00    300
```
```
2017-01-01 00:02:00    300
2017-01-01 00:02:30    100
```
```
2017-01-01 00:02:30    100
2017-01-01 00:03:00    100
```

Is `roll_time_series` designed for this task or not?

**Comment by nils-braun** [comment]
No, not really. I mean, you can start with the function and add some filtering afterwards - but probably it is easier to create your own small method doing this.

**Comment by mahnunchik** [comment]
Hi @nils-braun 
Do you plan to implement something for this task in future?

**Comment by nils-braun** [comment]
No, not really. The problem is, that more or less everyone has a slightly different requirement on how he wants to roll the data - so it is easier to just give the basic functionality in the library and let the user to the rest.
But iff you want to do a pull request, feel free about it :-)
