### ISSUE TITLE
Bug in `mean_autocorrelation`?

### ISSUE THREAD

**Issue by nikhaas** [blue-yonder/tsfresh#222]
OS: Ubuntu 16.04, Python 3.5, tsfresh 0.8.1

There might be a bug in the method `mean_autocorrelation` ([Link to line of code](https://github.com/blue-yonder/tsfresh/blob/master/tsfresh/feature_extraction/feature_calculators.py#L288))

The calculation of the autocorrelation for all lags 0...k simultaneously following the equation for [autocorrelation estimation](https://en.wikipedia.org/wiki/Autocorrelation#Estimation) (as mentioned in the documentation) can be achieved by using `np.correlate`.

But the results of the `tsfresh` code do not match the result when averaging the results of [`statsmodels.tsa.stattools.acf`](http://www.statsmodels.org/dev/generated/statsmodels.tsa.stattools.acf.html), see this example with the time series `x = [1, 2, -3]` from the [tsfresh test for mean autocorrelation](https://github.com/blue-yonder/tsfresh/blob/master/tests/feature_extraction/test_feature_calculations.py#L140):

```python
# Implementation of tsfresh
x = [1, 2, -3]
var = np.var(x)
n = len(x)
r = np.correlate(x - np.mean(x), x - np.mean(x), mode='full')
r = r[0: (n - 1)] / np.arange(n - 1, 0, -1)
print(np.nanmean(r / var))
# out: -0.589285714286

# Using statsmodels acf function, lag 0 is omitted by indexing!
print(np.nanmean(acf(x, unbiased=True)[1:]))
# out: -0.535714285714
```
Be aware that lag 0 (which is trivially 1) is omitted during averaging, but is an output of the `acf` function.

Reversing the order of the divisors provided by `np.arange` from

```python
r = r[0: (n - 1)] / np.arange(n - 1, 0, -1)
```

to

```python
r = r[0: (n - 1)] / np.arange(1, n, 1)
```
achieves the expected result `-0.535714285714`. This is because the application of `np.correlate` to a timeseries itself yields as a result a symmetric output, for example

```python
x = [1, 2, -3]
np.correlate(x - np.mean(x),x - np.mean(x), mode='full')
# out: array([ -3.,  -4.,  14.,  -4.,  -3.])
# accroding to lag: [2, 1, 0, 1, 2]
```
where, by slicing, lag 0 is omitted and one can choose the right or left hand side to the centered lag 0 (in this case: 14). Now apply averaging (ascending np.arange on the left side or descending on the right side) and divide by the variance of the time series to get all autocorrelation values for all lags.

This was also discussed in this [issue about np.correlate to calculate autocorrelation on SO](https://stackoverflow.com/questions/643699/how-can-i-use-numpy-correlate-to-do-autocorrelation).

**It seems that the tsfresh test suite does not catch this error.** To my mind, this is because there is an error in the by-hand-calculated result of the autocorrelation of the time series `x = [1, 2, -3]` (biased variance estimate of the series: `4.66666666667`).

Strictly following the aforementioned equation for autocorrelation estimation in Wikipedia, instead of

```python
expected_res = 1 / np.var(x) * (1 * 2 + 2 * (-3) - 3 / 2) / 2  # -0.5892857142857143
```

imho, it should be

```python
expected_res = 1 / np.var(x) * (((1 * 2 + 2 * (-3)) / 2 + (1 * -3)) / 2)  # -0.535714285714
```

Suggestion: Why not rely on the `statsmodels.tsa.stattools.acf` function? What led to the decision of doing this calculation by hand with `np.correlate` instead of using `statsmodels`? It was very hard for me to track and reproduce the `np.correlate` behaviour. From my perspective, using `acf` would ease the understanding, and seems to be a wrapper around `np.correlate` as it can be seen in the [source code](http://www.statsmodels.org/dev/_modules/statsmodels/tsa/stattools.html#acf), where `acf` invoces `acovf`. For speed improvement, the statsmodels implementation provides a FFT flag to do calculations with fast fourier transform which yields a great time saving.

If speed is an argument: A quick comparison yields the following results for the time series `x = np.random.randn(int(2*10e4))` on my machine (using IPythons `%%time` magic):

- tsfresh implementation with `np.correlate`: CPU times: user 11.1 s, sys: 0 ns, total: 11.1 s
- use statsmodels `acf` w/o FFT: CPU times: user 10.7 s, sys: 0 ns, total: 10.7 s
- use statsmodels `acf` w/ FFT: CPU times: user 52 ms, sys: 16 ms, total: 68 ms

I recommend (and could deliver a PR):

- fix the `np.arange` OR
- use `statsmodels.tsa.stattools.acf` with or without FFT
- correct the calculated result int the tsfresh test suite

#### One last remark

- What is the discriminative power of `mean_autocorrelation`? I haven't seen this feature so far. What about `var_autocorrelation` or some quantiles of the autocorrelation function? This would yield more insight in the structure of the ACF.

**Comment by MaxBenChrist** [comment]
Hi @nikhaas, welcome to tsfresh. Awesome investigation & explanations ! 

It is important that the docstring of the function calculator aligns with the calculated value. The name can be ambiguous, as long as the docstring is congruent. 

The docstring that is contained in mean_autocorrelation contains the following definition of the mean autocorrelation:
![bildschirmfoto 2017-07-05 um 16 22 29](https://user-images.githubusercontent.com/13162426/27868796-27949fe8-619e-11e7-91cf-e2c1e8f3939d.png)

if I calculate that by hand for the example `x=[1, 2, 3]`,  I get

``` python
expected_res = 1 / 3 * 1 / np.var(x) * ( 1/(3-1) * ((1-0)*(2-0)+(2-0)*(-3-0) + 1/(3-2) * ((1-0)*(-3-0)))
expected_res = 1 / 3 * 1 / np.var(x) * ( 1/2 * (2-6) + -3)
expected_res =  -5/ 3 * 1 / np.var(x) # is -0.35714285714285715

# but
np.nanmean(acf(x, unbiased=True)[1:]) # is  -0.5357142857142857
np.nanmean(acf(x)[1:]) # is -0.25
# tsfresh is -0.589285714286
```
So, none of the presented ways to calculate the mean autocorrelation is as described in the docstring.

I think the problem here is that it is not clear over what are we averaging the autocorrelation? lags or summands in the most inner sum?

actually, if we replace the outer correction factor `1/n` by `1/(n-1)`, then `np.nanmean(acf(x, unbiased=True)[1:])`and docstring are equal.

Next steps:

- From the look of it, I would be in favor to use `statsmodels.tsa.stattools.acf` with FFT due to its speed. Can you create a small plot where you inspect the different ways for different time series lengths?
- I would be in favor to change the docstring (1/n to 1/n-1) and use `np.nanmean(acf(x, unbiased=True)[1:])`

**Comment by MaxBenChrist** [comment]
```Python 

import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import time
from statsmodels.tsa.stattools import acf

lengths = [10, 50, 100, 200, 300, 400, 500, 600, 700, 1000, 2000, 3000, 4000, 5000]
t = [0]*len(lengths)
t_fft = [0]*len(lengths)

n_iter = 100

for _ in range(n_iter):
    i=0
    for l in lengths:
        x = np.random.normal(size=l)
        start_time = time.time()
        np.nanmean(acf(x, unbiased=True, fft=False)[1:])
        t[i] += (time.time() - start_time)
    
        start_time = time.time()
        np.nanmean(acf(x, unbiased=True, fft=True)[1:])
        t_fft[i] += (time.time() - start_time)
        i+=1

plt.plot(lengths, t, label="normal")
plt.plot(lengths, t_fft, label="by fft")
plt.legend()
plt.show()
```

gives the following image
![Uploading Unknown.png…]()

so it seems for random time series, after 1000 ticks we have the break even point with regard to the fft calculation. I will ad a switch that uses the fft if the length is bigger than 1250.

**Comment by MaxBenChrist** [comment]
![unknown](https://user-images.githubusercontent.com/13162426/28028277-50f44314-659c-11e7-9455-2e452eb9a49d.png)

**Comment by nikhaas** [comment]
Sorry for the late response. 
> actually, if we replace the outer correction factor 1/n by 1/(n-1), then np.nanmean(acf(x, unbiased=True)[1:])and docstring are equal, see

I can confirm your thoughts.  The usage of statsmodels' `acf`, rejecting lag 0 and averaging solves the issue. The docstring corresponds to the calculation. Nice normal vs fft plot! The speed advantage for large timeseries is remarkable.
Seems that I was to slow to supply the fix ;-).
