### ISSUE TITLE
How is time in DataFrame used in feature extraction?

### ISSUE THREAD

**Issue by wsjzha** [blue-yonder/tsfresh#225]
Hello, I am new to time series feature extraction. I have two questions here:

1. why we need to have time in the DataFrame? I think it could be useful when the sampling frequency varies over time. However, if we have a time series data which is sampled at a fixed frequency, how does time help for feature extraction?

2. in some cases, how should I define time? Say I want to classify multiple events and I have multiple recording segments for each event.  Here, I know the interval between two adjacent samples are the same but don't know the starting time for each segment. Also, the sequence of the samples has some useful information, but the starting time for each segment is not so useful. 

Thanks for any help!

**Comment by nils-braun** [comment]
As stated in our documentation, the time column is only used for sorting and then dismissed, before any feature is calculated.

**Comment by pfornia** [comment]
Hi @nils-braun thanks to you and the team for this wonderful library! If I could recommend making this fact a little more prominent in the documentation, I think that would be beneficial. I spent some time looking for this exact question in the docs and never really found anything that stated this clearly until I found this thread. Maybe it could be mentioned in the FAQs, or even in the Intro "What not to do with tsfresh?" section.

Another useful feature would be flags on the individual features (similar to Minimal/EfficientFCParameters) indicating when the feat is assuming even spacing. This would make it possible to quickly grab only the appropriate feats when dealing with un-evenly spaced TS.

**Comment by nils-braun** [comment]
Thanks @pfornia for your hints.

I like both of your proposals. Do you think you could do a first suggestion PR for your first idea: mentioning this in the documentation prominently? 

Regarding your second idea, that would of course be a bit more work. I could imagine combining this with a better feature calculator table which shows those information additional to the description.

**Comment by pfornia** [comment]
Awesome, yep happy to contribute! Give me a day or two.
