### ISSUE TITLE
Native support for multi classification in feature selection

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#226]
Would be great to have native support for multi classification during feature selection as done in 

https://github.com/blue-yonder/tsfresh/blob/master/notebooks/human_activity_recognition_multi_class_example.ipynb

We probably need a new parameter for that to divide multi classification from regression.

This should be quite straightforward to implement. Just perform feature selection on binary one-versus all for each class and combine all relevant features.

**Comment by jneuff** [comment]
See #232

**Comment by MaxBenChrist** [comment]
Merged!
