### ISSUE TITLE
Add to FAQ: different length of time series possible

### ISSUE THREAD

**Issue by bobchennan** [blue-yonder/tsfresh#24]
Does it support different length of time series?

I am interested to use it on audio tasks.

Thanks!

**Comment by MaxBenChrist** [comment]
Yes, it supports different time series lenghts.

**Comment by mynameisvinn** [comment]
@bobchennan @MaxBenChrist different lengths dont matter - as long as the sampling frequency is the same (eg constant sampling audio at 20hz). constant sampling frequency is required for certain calculations, eg fourier transforms
