### ISSUE TITLE
Add feature "number of zero crossings"

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#241]
https://en.wikipedia.org/wiki/Zero_crossing

could be an interesting, easy to add feature

**Comment by MaxBenChrist** [comment]
We can have a general feature counting the crossing around a value m

**Comment by kempa-liehr** [comment]
I've got an implementations together with unit tests from a different project, which could be easily adapted for refresh.

**Comment by MaxBenChrist** [comment]
> I've got an implementations together with unit tests from a different project, which could be easily adapted for tsfresh.

it is really easy to implement.

`
x = np.sign(x-m)
x = np.diff(x)
f = sum(np.abs(x))
`

**Comment by MaxBenChrist** [comment]
Done!

**Comment by MaxBenChrist** [comment]
See pr #260
