### ISSUE TITLE
Calculate Absolute Values and Normalize Fourier Coefficients

### ISSUE THREAD

**Issue by nikhaas** [blue-yonder/tsfresh#244]
I've created a pull request #243 with a rewritten notebook / tutorial / explanatory material for the discrete fourier transformation.
I gained some detailed knowledge and propose 
1) to report the absolute values (Pythagoras on real and imaginary part of the complex number) of the fourier coefficients, which can be calculated via `np.abs`
2) to normalize the DFT coefficients somehow related to the time series length. In detail, I ask to set the parameter `norm="ortho"` in the `np.fft.rfft` function.

I think my motivation gets clear in detail if you scroll through the notebook. One major learning point is the following: **The k-th Fourier Coefficients does correlate the series (with n data points) to a sinusoidal signal with k cycles, sampled with n data points.** For example, if the series is only one period of a sinus, it can be described perfectly by the 1st Fourier coefficient, all others are zero.

In summary, one needs to decide what one is interested in:

- If all series of an investigated dataset are of the same length, normalization is not an issue. If you want to compare time series of different length, raw fourier coefficients cannot be used for comparison of the time series
- Also, if the length of the series is a recorded feature by *tsfresh*, the classifier could (in principle) be capable of learning the "normalized" fourier coefficients, which allow conclusions about the amplitude / absolute value. But this is a nonlinear relationship (it is hyperbolic) which cannot be learned by linear classifiers
- This is a design decision: With the current setup, 
    - it seems that [it is set in the settings](https://github.com/blue-yonder/tsfresh/blob/master/tsfresh/feature_extraction/settings.py#L123) to record both the real and imaginary part of the coefficients and to choose the first 100 coefficients
    - in an earlier version of tsfresh, only the first 10 coefficients were taken into account.  This corresponds to establishing some kind of "lowpass" filter.
- White noise (in theory) is present in all frequencies. So, this kind of noise is not restricted to higher frequency bands. However, of one regards higher frequency bands as uninformative (i.e. in some sense as "noise"), it is perfectly fine to reject them and somehow implement a "lowpass" filter by selecting only lower-order coefficients
- If you invoke the FFT calculation in numpy, you get all fourier coefficients. It is up to the feature engineer (tsfresh default-settings engineer) which coefficients shall be reported. Maybe the first 10 (corresponding to the 10 lowest "frequencies", somehow a lowpass) and last 10 coefficients (corresponding to the 10 highest "frequencies", somehow a highpass) are interesting contrary to the first 100 DFT coefficients? I leave this open to discussion.

**Comment by MaxBenChrist** [comment]
I do not see any compelling reason why we have to use the absolute value of the instead of real and imaginary part.

the normalization is a valid point if we have different sized time series.

**Comment by nikhaas** [comment]
Well, you could consider to change the "encoding" of the DFT coefficients from complex numbers to polar coordinates with amplitude (by `np.abs`) and phase (by `np.angle`). This info might be more interpretable to the reader. It might be a matter of taste. Do not have compex numbers elsewhere in *tsfresh*?

I do not get what you mean by 
>we would need some instrument to setup the maximal time series length for all function calculators

I pointed out in #243 that normalization with `norm="ortho"` does not yield true amplitudes, because it divides the fourier coefficients by `sqrt(n)`, where division by `n` yields "true" amplitude information

**Comment by MaxBenChrist** [comment]
I think the normalization is off the table, as it does not really do anything right? 

Regarding the absolute value or angle. We could add those as further features, so the fft can return, real, im, angle and amplitude. the feature selection will then decide which are relevant.

**Comment by MaxBenChrist** [comment]
you wanna submit a pr for that?

**Comment by nikhaas** [comment]
I'll have a look at it soon.

**Comment by MaxBenChrist** [comment]
implemented this in pr #264
