### ISSUE TITLE
Adapt doctoring of normalize_input_to_internal_representation

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#254]
Currently our internal format is 

``` Python
{kind: pandas DataFrame with exactly two columns (the value and the id)}

```

So one example is 

```Python

{'a':      id  val
 57  500   74
 47  500   64
 8    10   56
 0    10   11
 46  500   70
 4    10   30
 45  500   65
 13   10   43
 51  500   77, 

'b':      id  val
 36   10   78
 67  500   60
 27   10   37
 69  500   12
 25   10   23
 34   10   44
 76  500   20
 68  500   79
 60  500    4
 23   10    7
 66  500   54}

```

The problem is the id column, this information is duplicated. Maybe we can have more nested dictionaries? Like

```
{kind: { id: values} }
```

Here, we could have the values as a plain numpy array

**Comment by nils-braun** [comment]
Ähm - this is not our internal format :-D
Our internal format is a melted pandas Dataframe, so
```
id kind sort value
```
We still support the old respresentation, but this is translated to this dataframe

**Comment by MaxBenChrist** [comment]
> Ähm - this is not our internal format :-D

Well, I was not working on the master but on the `0.8.1`, my bad.

**Comment by MaxBenChrist** [comment]
However, we should adapt the docstring of the `normalize_input_to_internal_representation` to reflect the new format.

**Comment by MaxBenChrist** [comment]
see pr #263
