### ISSUE TITLE
Include Principal Component Analysis in tsfresh

### ISSUE THREAD

**Issue by smueller18** [blue-yonder/tsfresh#259]
I did a PCA analysis after the feature selection process of tsfresh and I think it is a good idea to implement this code also in the tsfresh project.
I created a notebook file for that purpose. Because I cannot upload .ipynb files here, have a look at https://github.com/smueller18/tsfresh/blob/pca/notebooks/pca.ipynb. My suggestion is to implement the class PCAForPandas from cell [1] somewhere in the tsfresh project and to include the notebook without cell [1] for the notebook collection.
I can also include the class if you say me where to place. Documentation and testing is not included so far and has to be done before merging.

The notebook explains how to implement #42 .

**Comment by MaxBenChrist** [comment]
That is the PCAforPandas class that I wrote and send to you, right?

I do not think that the PCA should be included in this project. I feel that refresh should stay a feature extraction package, even though we also include a feature selection.

However, with the latest updates, the number of (highly correlated) features increased. It could be beneficial to provide the user with some easy measure for feature selection and dimension reduction.

Lets discuss this. @nils-braun , @jneuff , what do you think?

**Comment by smueller18** [comment]
@MaxBenChrist Yes PCAforPandas is based on the code you provided but also extended with automatic normalization and reduced to work with pandas DataFrame only.

**Comment by jneuff** [comment]
> However, with the latest updates, the number of (highly correlated) features increased. It could be beneficial to provide the user with some easy measure for feature selection and dimension reduction.

I wouldn't add it as functionality to tfsresh. There are already libraries for this purpose out there. What we could do, is add some notebooks with examples doing some feature/dimensionality reduction.
