### ISSUE TITLE
Potential new features: relative power by chunk or length fraction

### ISSUE THREAD

**Issue by Ezekiel-Kruglick** [blue-yonder/tsfresh#266]
Just a feature I have had work in the past.

For N fractional lengths L of an overall series length L' , generate N different features where each one is the sum of squares over the chunk with length L divided by the overall sum of squares. This give the ratio of power in each of the N bins.

If you think this is something you'd want in tsfresh, I can generate the code and a pull request. I just didn't want to go do that without checking first.

**Comment by MaxBenChrist** [comment]
Hi @Ezekiel-Kruglick. Welcome to tsfresh. 

The potential feature that you describe sounds interesting. Have you used it before in some application?

**Comment by Ezekiel-Kruglick** [comment]
Yes, I've used it in a couple projects. It's a feature that is easy for humans to see as well ("hey, there's a big bump in this area"), which can be nice.

**Comment by MaxBenChrist** [comment]
Alright let's do it. I updated the documentation on how to add custom feature calculators. If you face any challenges or have questions let me know

**Comment by Ezekiel-Kruglick** [comment]
I see the new documentation, you anticipated many potential questions, thanks!

I have forked and cloned to my dev machine. I look forward to working on it.

**Comment by MaxBenChrist** [comment]
See pr #268
