### ISSUE TITLE
impute function is replacing whole column by mean

### ISSUE THREAD

**Issue by nikhaas** [blue-yonder/tsfresh#272]
`tsfresh version: 0.8.1.post0.dev32+ng76b27dd.dirty`

I played around with the `Robot Execution Failure Dataset` and found the following issue after feature extraction via 

```python
X_impute = extract_features(df, 
                            column_id='id', column_sort='time',
                            default_fc_parameters=extraction_settings,
                            impute_function=impute)  # line of interest
```

This is how it looks like when using `impute`:

 F_x__autocorrelation__lag_0 | F_x__autocorrelation__lag_1 | F_x__autocorrelation__lag_2 | F_x__autocorrelation__lag_3 | F_x__autocorrelation__lag_4 | F_x__autocorrelation__lag_5 | F_x__autocorrelation__lag_6 | F_x__autocorrelation__lag_7 | F_x__autocorrelation__lag_8 | F_x__autocorrelation__lag_9 | ... | T_z__autocorrelation__lag_0 | T_z__autocorrelation__lag_1 | T_z__autocorrelation__lag_2 | T_z__autocorrelation__lag_3 | T_z__autocorrelation__lag_4 | T_z__autocorrelation__lag_5 | T_z__autocorrelation__lag_6 | T_z__autocorrelation__lag_7 | T_z__autocorrelation__lag_8 | T_z__autocorrelation__lag_9
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- 
1.0 | -0.076923 | 0.180843 | 0.204837 | 0.17553 | 0.063926 | 0.022942 | 0.080526 | 0.20315 | 0.258199 | ... | 1.0 | 0.392026 | 0.206194 | 0.080582 | 0.177171 | 0.0 | 0.0 | 0.070913 | 0.023415 | 0.162102
1.0 | -0.093750 | 0.180843 | 0.204837 | 0.17553 | 0.063926 | 0.022942 | 0.080526 | 0.20315 | 0.258199 | ... | 1.0 | 0.392026 | 0.206194 | 0.080582 | 0.177171 | 0.0 | 0.0 | 0.070913 | 0.023415 | 0.162102
1.0 | -0.342466 | 0.180843 | 0.204837 | 0.17553 | 0.063926 | 0.022942 | 0.080526 | 0.20315 | 0.258199 | ... | 1.0 | 0.392026 | 0.206194 | 0.080582 | 0.177171 | 0.0 | 0.0 | 0.070913 | 0.023415 | 0.162102
1.0 | -0.311002 | 0.180843 | 0.204837 | 0.17553 | 0.063926 | 0.022942 | 0.080526 | 0.20315 | 0.258199 | ... | 1.0 | 0.392026 | 0.206194 | 0.080582 | 0.177171 | 0.0 | 0.0 | 0.070913 | 0.023415 | 0.162102
1.0 | 0.075713 | 0.180843 | 0.204837 | 0.17553 | 0.063926 | 0.022942 | 0.080526 | 0.20315 | 0.258199 | ... | 1.0 | 0.392026 | 0.206194 | 0.080582 | 0.177171 | 0.0 | 0.0 | 0.070913 | 0.023415 | 0.162102

The values for `autocorrelation` are the same across all timeseries / id for the higher lags, e.g. `F_x__autocorrelation__lag_2`.

This is how it looks like when using `impute_dataframe_zero`:

F_x__autocorrelation__lag_0 | F_x__autocorrelation__lag_1 | F_x__autocorrelation__lag_2 | F_x__autocorrelation__lag_3 | F_x__autocorrelation__lag_4 | F_x__autocorrelation__lag_5 | F_x__autocorrelation__lag_6 | F_x__autocorrelation__lag_7 | F_x__autocorrelation__lag_8 | F_x__autocorrelation__lag_9 | ... | T_z__autocorrelation__lag_0 | T_z__autocorrelation__lag_1 | T_z__autocorrelation__lag_2 | T_z__autocorrelation__lag_3 | T_z__autocorrelation__lag_4 | T_z__autocorrelation__lag_5 | T_z__autocorrelation__lag_6 | T_z__autocorrelation__lag_7 | T_z__autocorrelation__lag_8 | T_z__autocorrelation__lag_9
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- 
1.0 | -0.076923 | 0.000000 | 0.000000 | 0.000000 | 0.000000 | 0.000000e+00 | 0.000000 | 0.000000 | 0.000000 | ... | 0.0 | 0.000000 | 0.000000 | 0.000000 | 0.000000 | 0.000000 | 0.000000 | 0.000000 | 0.000000 | 0.000000
1.0 | -0.093750 | -0.387445 | -0.388870 | 0.070423 | 0.710011 | -5.882353e-02 | -0.313340 | -0.311805 | 0.166667 | ... | 1.0 | 0.300000 | 0.030429 | -0.408248 | -0.462910 | -0.428571 | -0.377964 | 0.487950 | 0.471405 | 0.632456
1.0 | -0.342466 | 0.297020 | -0.347945 | 0.254951 | -0.449467 | 4.034265e-17 | -0.417365 | 0.645497 | -0.316228 | ... | 1.0 | -0.400000 | 0.030429 | -0.333333 | 0.240563 | 0.218218 | -0.377964 | 0.333333 | -0.400000 | 0.632456
1.0 | -0.311002 | -0.403516 | 0.369175 | -0.078193 | -0.450721 | 5.103104e-01 | 0.205557 | -0.679366 | 0.522233 | ... | 1.0 | 0.312253 | -0.312653 | -0.714286 | -0.250217 | 0.104116 | 0.437500 | 0.142857 | -0.166667 | -1.000000
1.0 | 0.075713 | -0.117244 | -0.184637 | -0.393177 | 0.052926 | -3.029914e-01 | 0.056344 | 0.848528 | -0.108465 | ... | 1.0 | 0.538382 | 0.209568 | -0.204980 | -0.449013 | -0.504030 | -0.502616 | -0.320256 | 0.416667 | 0.447214

The latter one corresponds to the results when calculating `pd.Series.autocorr()` by hand.

You can find a [more comprehensive documentation of the bug in this notebook](https://github.com/nikhaas/tsfresh/blob/acf_pacf_autocorr_notebook/notebooks/autocorr_acf_pacf_comparison.ipynb), cells 1-13 with a plot in cell 13.

Can you reproduce it?

**Comment by MaxBenChrist** [comment]
Great analysis @nikhaas 

This is heavy. It looks like the impute function is setting the whole column to the mean value instead of just the NaN cells. Will investigate further

**Comment by MaxBenChrist** [comment]
This bug only occurs if there are NaNs in multiple columns, which is why it got undetected by our unit tests. @nils-braun or me will fix it

**Comment by nils-braun** [comment]
Thank you very much for reporting this @nikhaas. I have fixed the bug (I hope) and also made the `impute` function much faster.

**Comment by nikhaas** [comment]
You're welcome :smiley: Man, you fixed that quickly!
