### ISSUE TITLE
Parallelization performance v0.7.1 and commit ...1c99e8

### ISSUE THREAD

**Issue by NoamGit** [blue-yonder/tsfresh#277]
Hi,

Two topics that I wanted to discuss:

##  Runtime increase in latest commit
We compared the extraction time of [version 0.7.1](https://github.com/blue-yonder/tsfresh/releases/tag/v0.7.1) to code version [1c99e8](https://github.com/blue-yonder/tsfresh/commit/76b27dd95b7702c1c0222d55aca755ab5b1c99e8). We varied the number of ids ,where every chunk/time-series had length = 91 and the dataframe had 4 kinds of ts columns. As you may see in the figure and table below, we didn't see any significant improvement when using 4 processes in parallel and `CHUNCKSIZE = None` (fastest settings). How does this fit your [benchmark results](https://github.com/blue-yonder/tsfresh/pull/217) ?

![image](https://user-images.githubusercontent.com/13464827/28775204-6f5ab9c4-75f9-11e7-8e6f-7010994b596e.png)

Results table:

#ids | 0.7.1 w parallel [sec] | 1c99e8 w parallel [sec]
-- | -- | --
940 | 8.95 ±1.2 | 14.6 ±2.47
4500 | 46.98 ±14.21 | 61.96 ±1.66
7612 | 74.37 ±9.18 | 69.07 ±6.3
30523 | 295.98 ±49.15 | 317.16 ±16.52

BTW, I actually saw a nice improvement with no-parallelization (`N_PROCESSES = 0`). See table below:

#ids | 0.7.1 w/o parallel [sec] | 1c99e8 w/o parallel [sec]
-- | -- | --
940 | 12.42 ±0.51 | 10.34±0.69
4500 | 58.04 ±1.04 | 45.79±0.09

*mean and std taken from 5 trials*

##  50% CPU usage with no-parallelization
Recently I've noticed that while using the package for feature extraction, the CPU usage with no-parallelization settings stays mostly near 50±2%. This means that functions that are located deeper in `_do_extraction_on_chunk` are opening many processes/threads that are not configurable by the tsfresh API. Accordingly, what is the meaning of working with more than 2-3 processes, which use 100% CPU?
I've also noticed, that when working with  `N_PROCESSES > 4` run time tends to raise drastically

![image](https://user-images.githubusercontent.com/13464827/28779156-d7ade5e4-760a-11e7-9666-c9fabd278798.png)

### Disclaimer: 
I've modified the parallelization backend in `feature_extraction/extraction.py` from `multiprocess` to` concurrent.futures (ProcessPoolExecuter)` in order to allow an hierarchical parallelization scheme. This scheme allows to run in parallel 2 modules - one module for DB extraction, preprocessing and feature extraction (tsfresh) and second child module for the internal tsfresh parallelization . The change can be seen in the image bellow

![image](https://user-images.githubusercontent.com/13464827/28774962-626a7228-75f8-11e7-8162-63a680852c51.png)![image](https://user-image

s.githubusercontent.com/13464827/28779134-c5264a92-760a-11e7-91b0-009e9aa8123b.png)

**Benchmark settings**
OS: win7, 
Resources: Xeon 48-cores, 32 RAM GB
Python interpreter: python 3.6
tsfresh package version: [0.7.1](https://github.com/blue-yonder/tsfresh/releases/tag/v0.7.1) and [1c99e8](https://github.com/blue-yonder/tsfresh/commit/76b27dd95b7702c1c0222d55aca755ab5b1c99e8)
feature extraction settings: mean,std,var,median,max,min, sum_values, length ,augmented_dickey_fuller, ar_5_params

Thanks

**Comment by MaxBenChrist** [comment]
>  mean,std,median,max,min,augmented_dickey_fuller, ar_5_params

those are the only features that you extract?

how long are your time series?

**Comment by NoamGit** [comment]
I've updated the list. I only used - 
`mean,std,var,median,max,min, sum_values, length ,augmented_dickey_fuller, ar_5_params
`
Every time-series is a 91 values array. 
For example, 7612 ids define a data frame with shape [2,770,768 , 1] (91 ts-array length X 7612 ids X 4 kind/var)

**Comment by MaxBenChrist** [comment]
> For example, 7612 ids define a data frame with shape [2,770,768 , 1] (91 ts-array length X 7612 ids X 4 kind/var)

This sounds wrong. it should be at least two columns value and id, which gives a dataframe of shape [2770768, 2]

**Comment by NoamGit** [comment]
You are right, I meant that there is 2,770,768 rows.

**Comment by MaxBenChrist** [comment]
Can you provide your benchmark code plus data?

**Comment by NoamGit** [comment]
Unfortunately I can't provide no code nor data (both are under protection). 
Yet, the code is very simple and straight forward. It includes the `extract_features` with the aforementioned settings in a 5 repetition for loop timer.
The actual data isn't important ,since it is the same for every comparison. Only its size and number of columns matter, which can be inferred from my previous posts.

**Comment by MaxBenChrist** [comment]
Do you observe the same behavior for random time series?

**Comment by nils-braun** [comment]
You are writing something about DB extraction. Does this mean you are not reading the data from RAM but feeding it in from the DB?

**Comment by nils-braun** [comment]
So, thank yo very much for this nice report - I will definitely have a look into this and see, where the bug is.

**Comment by NoamGit** [comment]
@MaxBenChrist  - Haven't tried it yet. 

@nils-braun  - We read our data for DB and not from RAM, *however* the feature extraction is performed only on RAM stored data (after the DB extraction it becomes part of the workspace). The experiment is a very simple and straightforward input-output measurement.

**Comment by nils-braun** [comment]
Ok, then I will try to reproduce this.

**Comment by nils-braun** [comment]
Ok, I have tried to reproduce what you are seeing, but unfortunately, I could not see the same issues here.

Let me first discuss what I have done and that what the results are.

My testing machine is an SLC6 machine (linux) with python 3.6.2. It has 28 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz and 252 GB RAM (I tried to be as closely as possible to your machine, but I do not have a windows machine at hand).

I am doing my benchmarking studies with the following script:

```
#!/usr/bin/env python
from __future__ import print_function

from tsfresh import extract_features
import pandas as pd
from time import time

def benchmark(X, processes):

    print("Number of rows:", len(X))
    print("Number of ids:", len(set(X["id"])))
    print("Number of kinds:", len(set(X["dimension"])))
    print("Mean length of chunks", X.groupby(["id", "dimension"])["time"].count().mean())
        
    params = {"mean": None, 
              "standard_deviation": None, 
              "variance": None,
              "median": None,
              "maximum": None,
              "minimum": None,
              "sum_values": None,
              "length": None,
              "augmented_dickey_fuller": [{'attr': 'teststat'}, {'attr': 'pvalue'}, {'attr': 'usedlag'}],
              "ar_coefficient": [{'coeff': 5, 'k': 10}]}
    
    try:
        from tsfresh.feature_extraction.settings import FeatureExtractionSettings
        h = FeatureExtractionSettings()
        h.n_processes = processes
        h.name_to_param = params
    except ImportError:
        h = params
        
    start = time()
    try:
        f = extract_features(X, column_id="id", column_sort="time", column_kind="dimension", column_value="value", 
                         parallelization="per_sample", feature_extraction_settings=h)
    except TypeError:
        f = extract_features(X, column_id="id", column_sort="time", column_kind="dimension", column_value="value", 
                         n_jobs=processes, default_fc_parameters=h)
    end = time()

    print("Time:", end - start)
    
    return dict(
        rows=len(X),
        ids=len(set(X["id"])),
        kinds=len(set(X["dimension"])),
        length_of_chunk=X.groupby(["id", "dimension"])["time"].count().mean(),
        time=end-start,
        number_of_features=len(f.columns),
        number_of_results=len(f),
        processes=processes,
    )

if __name__ == "__main__":
    import sys
    import os

    X = pd.read_pickle("test.pkl")
    revision = sys.argv[1]

    output_file = "result_{}.pkl".format(revision)
    if os.path.exists(output_file):
        print(output_file, "already present")
        exit()

    result = pd.DataFrame([
        benchmark(X[X["id"] < 10], 1),
        benchmark(X[X["id"] < 50], 1),
        benchmark(X[X["id"] < 100], 1),
        benchmark(X[X["id"] < 500], 1),
        benchmark(X[X["id"] < 1000], 1),
        benchmark(X[X["id"] < 5000], 1),
        benchmark(X, 1),

        benchmark(X[X["id"] < 10], 2),
        benchmark(X[X["id"] < 50], 2),
        benchmark(X[X["id"] < 100], 2),
        benchmark(X[X["id"] < 500], 2),
        benchmark(X[X["id"] < 1000], 2),
        benchmark(X[X["id"] < 5000], 2),
        benchmark(X, 1),

        benchmark(X[X["id"] < 10], 4),
        benchmark(X[X["id"] < 50], 4),
        benchmark(X[X["id"] < 100], 4),
        benchmark(X[X["id"] < 500], 4),
        benchmark(X[X["id"] < 1000], 4),
        benchmark(X[X["id"] < 5000], 4),
        benchmark(X, 4),

        benchmark(X[X["id"] < 10], 10),
        benchmark(X[X["id"] < 50], 10),
        benchmark(X[X["id"] < 100], 10),
        benchmark(X[X["id"] < 500], 10),
        benchmark(X[X["id"] < 1000], 10),
        benchmark(X[X["id"] < 5000], 10),
        benchmark(X, 10),
    ])

    result.to_pickle(output_file)
```
which is executed for v0.7.1 (which is commit 2d408a41738e0442f0547eefe5c264a142ba89f6) and the current master version (which is commit 77b714c63c68db43ffc027b9988414c5ca621575). My dataframe is constructed using the shipped driftbif_simulation script and uses:
* up to 7000 ids
* two kinds
* time series length of 91 

For feature extraction (as you see), I am using the same parameters as you are doing - but of course without the changes you did to the threading etc.

For the results, see the next post ( tension! :-D )

**Comment by nils-braun** [comment]
Ok, here are the results. The first plot shows a comparison with 1, 4 or 10 processes between v7 and master, with different number of ids. As you see, we are faster on master than with v7 - the difference is larger with larger time series (as then parallel processing is more important) and smaller with larger number of processes (as the execution time is then so fast, that streaming becomes more important, which is more or less the same in both cases, as we do have to transport the data to the processes anyhow).

![parallel](https://user-images.githubusercontent.com/6116188/28872380-36e2cc62-7789-11e7-93e0-6cf613aafd8e.png)

The next plot shows the speedup plot - so the time with the same number of ids over the number of processes. As you see, we are getting faster with more processes (expected) and with very large number of ids (100) on many cores (10), the speedup is actually worse - the reason is again the streaming, because here the master process can not feed the data as fast as the child processes can work on it (but 100 ids is a corner case with 10 processes...)
![speedup](https://user-images.githubusercontent.com/6116188/28872448-88ba350c-7789-11e7-9809-25ab14fcea87.png)

I have also looked onto the cpu utilization and in my cases, 4 processes meant 4 cpus have 100% workload etc...
Actually we are not opening any threads on our own - so I do not see any reason why this should happen.

Next post is then some summary....

**Comment by nils-braun** [comment]
So as you see, unfortunately I could not reproduce your bug.
I would suggest, you try your setup without your own implementation of the multiprocessing - maybe this helps. As we are relying on the multiprocessing implementation of python itself, I do not see that many things we can do here (or we doing wrong here), sorry. It could be that you are running in some sort of locking mechanism, some sort of RAM issues, some sort of limits, that only apply on Windows.

PS: I have not tested the n_jobs=0 mode, but will do so soon.

**Comment by MaxBenChrist** [comment]
Awesome analysis @nils-braun!

**Comment by NoamGit** [comment]
Thanks, great work @nils-braun 
I will try this out on a linux machine and see if results are similar.
If not, I will continue to report.

BTW, I think that the most interesting question is - why is the CPU usage so high without parallelization?

**Comment by nils-braun** [comment]
You have seen this with v0.7.1 or with the master or with both?

**Comment by NoamGit** [comment]
With both..
I believe the reason is because of using 50% with 1 process. This means that the feature_calculators module is doing some heavy parallel processing by itself

**Comment by nils-braun** [comment]
Well no, I am quite sure it does not - so let me check this in the evening today

**Comment by nils-braun** [comment]
At least we are not expecting this to happen :-D

**Comment by nils-braun** [comment]
Ok, I have checked with `n_jobs` set to 0 in the master version I was describing above - and the CPU utilization looks as expected: 100 % of one core, nothing on other cores.

So, I think here is something going on - but it is quite hard to reproduce this without your code... But I can understand if you can not give this to us.
For me, everything looks quite fine and understood. What I do not understand, is why your CPU utilization is 100 % for 4 processes and 50 % for 0 processes, which seems not have something to do with the parallelization tsfresh is doing....

One last question concerning the processes=0 case: as you have reimplemented the parallelization on your own: `n_jobs=0` does still mean no parallelization at all, as in the code sample you have shown?

**Comment by nils-braun** [comment]
Feel free to reopen, if this problem is still there and not understood :-)

**Comment by SirJohnFranklin** [comment]
I set n_jobs to 0, but still each process uses more than 1cpu equivalent in percentage.
