### ISSUE TITLE
RelevantFeatureAugmenter does not impute with default settings

### ISSUE THREAD

**Issue by jneuff** [blue-yonder/tsfresh#278]
.. and worse, our current tests do not catch this problem. `NaN` values are actually fed into the significance tests that fail to detect that either.

I propose:

Removing the impute_function parameter from the `RelevantFeatureAugmenter` altogether. If someone wants the flexibility, they can use the other transformers.

**Comment by MaxBenChrist** [comment]
Ok. lets remove the impute parameter and always impute.

**Comment by MaxBenChrist** [comment]
solved by pr #281
