### ISSUE TITLE
link issue with repo description

### ISSUE THREAD

**Issue by xgdgsc** [blue-yonder/tsfresh#28]
The repo description "Automatic extraction of relevant features from time series: http://tsfresh.readthedocs.io. " , there should be a space before the last dot or the url won' t open correctly.

**Comment by jneuff** [comment]
It works fine for me (Safari). Which browser are you running?
There seem to be different takes on this, see [1] for example.

github renders the relevant part of the README.md to:
```html
documentation at <a href="http://tsfresh.readthedocs.io">http://tsfresh.readthedocs.io</a>.</p>
```
I think this is OK.

[1] http://ux.stackexchange.com/a/15228

**Comment by MaxBenChrist** [comment]
Maybe he was referring to the description on the top. 

It had a dot which I removed

<img width="1003" alt="bildschirmfoto 2016-11-01 um 17 49 53" src="https://cloud.githubusercontent.com/assets/13162426/19898263/9e490b56-a05b-11e6-891c-ca6c5f53efa1.png">

**Comment by jneuff** [comment]
That seems about right.
