### ISSUE TITLE
Fix docstrings for feature calculators

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#286]
There are some docstrings in the `tsfresh.feature_extraction.feature_calculators` submodule that are malformated, we should fix them

**Comment by nikhaas** [comment]
I also noticed that. So I began to format the docstrings:
- make them at most 80 characters per line
- streamlined the "references": it seems like until now, everyone did is on his behalf. The problem with some references, the web and / or latex build fails, see this examples:

## 1) Some docstrings so far
- sample entropy web
![sample_entropy_reference_web](https://user-images.githubusercontent.com/18031651/28896154-958bad5e-77db-11e7-81b5-68ac392a2a98.png)
- c3 web (this is an example from my local sphinx build, somehow not rendering the equation)
![c3_reference_web](https://user-images.githubusercontent.com/18031651/28896153-958b2d34-77db-11e7-93a0-cdebc20740bf.png)
- empty references (latex)
![empty_references_pdf](https://user-images.githubusercontent.com/18031651/28896156-958cdada-77db-11e7-937f-ac40d4e6378e.png)
- references inline (latex)
![referenes_inline_pdf](https://user-images.githubusercontent.com/18031651/28896155-958c5bf0-77db-11e7-98dc-cfa5accaa467.png)

## 2) Modified Docstrings / References
I propose the following method, using `rubric` with indents by `|`:
```python
    .. rubric:: References

    |  [1] Friedrich et al. (2000): Physics Letters A 271, p. 217-222
    |  *Extracting model equations from experimental data*
```
That's how it looks in latex:

- example 1
![new_references_links_pdf](https://user-images.githubusercontent.com/18031651/28896152-95846864-77db-11e7-9ac5-85755ad7de54.png)
- example 2
![new_reference_pdf](https://user-images.githubusercontent.com/18031651/28896151-958236de-77db-11e7-989f-0f83852b8611.png)
- and in the web:
![new_sample_entropy_docstring](https://user-images.githubusercontent.com/18031651/28896623-7ac24e86-77dd-11e7-8464-111a64e7bf6d.png)


I don't think that we need to deal with a common bibliography.
Until now, I've fixed the docstrings in `feature_calculators`. There might be references in other docs / malformattings that can also be updated.

## 3) Error in `doctest`
Btw, when I run `python setup.py doctest`, I get some errors. This is the output: 

```
# Sphinx version: 1.6.3
# Python version: 2.7.13 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.8
# Last messages:
#   **********************************************************************
1 items had failures:
  11 of  22 in default
22 tests in 1 items.
11 passed and 11 failed.
***Test Failed*** 11 failures.
#   Document: text/feature_extraction_settings
------------------------------------------
#   **********************************************************************
File "text/feature_extraction_settings.rst", line 36, in default
Failed example:
    extract_features(df, default_fc_parameters=settings)
Exception raised:
    Traceback (most recent call last):
      File "/home/niklas/anaconda3/envs/py27tsfresh/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest default[3]>", line 1, in <module>
        extract_features(df, default_fc_parameters=settings)
    NameError: name 'df' is not defined
#   
#   **********************************************************************
1 items had failures:
   1 of   4 in default
4 tests in 1 items.
3 passed and 1 failed.
***Test Failed*** 1 failures.
#   Document: api/tsfresh.examples
------------------------------
#   
#   1 items passed all tests:
   7 tests in default
7 tests in 1 items.
7 passed and 0 failed.
Test passed.
#   Doctest summary
===============
   59 tests
   22 failures in tests
    0 failures in setup code
    0 failures in cleanup code
#   build finished with problems, 16 warnings.

```
Should one test for this regularly? Is it also possible to test whether the Web and Latex build looks good?

Referencing #287

**Comment by MaxBenChrist** [comment]
I have not really used `python setup.py doctest` so far.
