### ISSUE TITLE
extraction and filtering not equal to filtered extraction

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#29]
User @Huandao0812  reported in issue #22:

> Hi Max, I tried to do the same by your example, but my X_new has different number of features than my X_old, my code is here https://github.com/Huandao0812/lstm_exp/blob/master/test_tsfresh.py#L46 
can you have a quick look

> update: I check the diff of 2 set of columns and this is the difference:
the X_new has 2 more columns than the X_old
diff columns = set(['feature__cwt_coefficients__widths_(2, 5, 10, 20)__coeff_13__w_20', 'feature__cwt_coefficients__widths_(2, 5, 10, 20)__coeff_3__w_5'])

**Comment by MaxBenChrist** [comment]
Hi @Huandao0812, could you please provide some data for the code snippet?

**Comment by MaxBenChrist** [comment]
It is a wild guess, but It could be that the .fromcolumns() method does not play nicely with [apply features](http://tsfresh.readthedocs.io/en/latest/text/how_to_add_custom_feature.html) that have multiple parameters

**Comment by Huandao0812** [comment]
@MaxBenChrist the data is under the folder data/ in the repos https://github.com/Huandao0812/lstm_exp/tree/master/data

**Comment by MaxBenChrist** [comment]
Thanks @Huandao0812, I will look into that.

**Comment by MaxBenChrist** [comment]
I think I found the reason. Features that had multiple parameters could end up with different name even though their configuration was the same. (For example featureXY__a_1__b_2 and featureXY__b_2__a_1)

A simple sorted fixed this.
