### ISSUE TITLE
sklearn_transformers error

### ISSUE THREAD

**Issue by crawles** [blue-yonder/tsfresh#293]
Mac OSX 10.12.5
TSFRESH: version 0.8.1

This does not work. I get an error of `ValueError: Input contains NaN, infinity or a value too large for dtype('float32').` (also needs to add a line to load data: `load_robot_execution_failures()`)
https://github.com/blue-yonder/tsfresh/blame/master/docs/text/sklearn_transformers.rst#L32

Any ideas? Thank you!

**Comment by MaxBenChrist** [comment]
Please update to 0.9.0

**Comment by crawles** [comment]
Thank you!
