### ISSUE TITLE
Missing Quotes around Dickey Fuller attr parameter

### ISSUE THREAD

**Issue by solidua** [blue-yonder/tsfresh#301]
Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system
macOS 10.12.6
2. The version of *tsfresh* that you are using
0.10.0
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
UCI har data 
4. A minimal code snippet which reproduces the problem/bug
On _calculate_relevance_table_, it returns a dataframe containing a column of the feature calculators with parameters. Some features accept string parameters and _calculate_relevance_table_ returns them surrounded in double quotes: 
> z_earth_user__agg_linear_trend__f_agg_"var"__chunk_len_50__attr_"slope"

however for the _augmented_dickey_fuller_ calcuator, the string param is not surrounded by quotes

> z_earth_user__augmented_dickey_fuller__attr_pvalue

the quotes are necessary for _get_config_from_string_. If the string param doesn't have the double quotes it will raise a _ValueError: malformed string_ on _ast.iteral_eval(value)_

> File "/usr/local/lib/python2.7/dist-packages/tsfresh/feature_extraction/settings.py", line 65, in from_columns 
>    config = get_config_from_string(parts) 
>  File "/usr/local/lib/python2.7/dist-packages/tsfresh/utilities/string_manipulation.py", line 37, in get_config_from_string 
>    dict_if_configs[key] = ast.literal_eval(value) 
>  File "/usr/lib/python2.7/ast.py", line 80, in literal_eval 
>    return _convert(node_or_string) 
>  File "/usr/lib/python2.7/ast.py", line 79, in _convert 
>    raise ValueError('malformed string') 
> ValueError: malformed string
> 

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by MaxBenChrist** [comment]
I can reproduce the bug. Thanks for reporting it.

This is quite easy to fix. I will fix it and add a unit test that will catch such errors in the future.

**Comment by solidua** [comment]
sweet thanks

**Comment by MaxBenChrist** [comment]
Gosh. This was fixed in 0.10.0. 

You probably were still using 0.9.0, as me yesterday

**Comment by MaxBenChrist** [comment]
see https://github.com/blue-yonder/tsfresh/commit/017e93e8fdba7414b107ccf3f6777adf984e9721
