### ISSUE TITLE
Handling of nan and inf values

### ISSUE THREAD

**Issue by zzzmk** [blue-yonder/tsfresh#310]
I would like to know if a list of features that can result in `nan` or `inf` can be shared.

Alternatively, what would be the minimum length of each time series to guarantee no `inf` or `nan` values?

Thank you

**Comment by nils-braun** [comment]
I think I do not fully understand your question. 
The length is not the only factor that decided if there are nan values. This depends on the feature. Do you want a dataset that is finite for every feature? Or only for one?

Maybe it is easier for me if you describe, why you want such a thing. We have included imputing functions that get rid of nan values, so it should be no problem to have such values.

**Comment by MaxBenChrist** [comment]
To realize such a list, we would have to flag every feature calculator. Quite some work for a list that does not directly provide values.

If you need a clean feature matrix (e.g. because your classifier or regressor does not support non finite input), you should add some preprocessing steps to your pipeline.

**Comment by senjed** [comment]
Hi, 
My data does not contain any nan values. However, after extracting features with tsfresh,  I get a dataframe that has many nan values. Do you have any insight on how to fill in these nan values? There are so many types of features and I guess they have to be dealt with in a different manner based on the feature type.

**Comment by nils-braun** [comment]
As @MaxBenChrist said, it is a rather tedious work and actually will also heavily depend on the input data.
As no one volunteered for this issue for so long, I will close it.
