### ISSUE TITLE
update contribution page

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#315]
whats missing on http://tsfresh.readthedocs.io/en/latest/text/how_to_contribute.html?highlight=tests is 

- separation of unit and integrations tests
- two virtual envs for python 2.7 and 3.5.2

**Comment by nils-braun** [comment]
The separate venv is now not needed anymore and I actually think it is good to test both the unit and integration tests.

So I am closing this :-)
