### ISSUE TITLE
ImportError: cannot import name 'MinimalFeatureExtractionSettings'

### ISSUE THREAD

**Issue by ShivamPanchal** [blue-yonder/tsfresh#320]
I am using latest version of tsfresh.
tsfresh-0.10.1.post0.dev4+nge531b85

BUT, WHEN I TRY TO IMPORT THE MinimalFeatureExtractionSettings IMPORT ERROR SHOWS UP:
----> 2 from tsfresh.feature_extraction import MinimalFeatureExtractionSettings

ImportError: cannot import name 'MinimalFeatureExtractionSettings'

**Comment by MaxBenChrist** [comment]
There is no `MinimalFeatureExtractionSettings` object anymore, they are called MinimalFCParameters now:

https://github.com/blue-yonder/tsfresh/blob/1a7e9ac689ce449ac8ef322795455a6cc7a44ca3/tsfresh/feature_extraction/settings.py#L146

**Comment by ShivamPanchal** [comment]
I am using this : 
X_train = extract_features(df_shift_train, column_id="id", column_sort="time", column_value="value", impute_function=impute, 
                     show_warnings=False, feature_extraction_settings=MinimalFCParameters())



but, now the error is : 

TypeError: extract_features() got an unexpected keyword argument 'feature_extraction_settings'

How, should I use this?

**Comment by ShivamPanchal** [comment]
Thanks MaxBenChrist, I have read it from the documentation. Thanks for your help. And, I would also like to congratulate you and all tsfresh team for building such a good time series analysis package in python. Its amazing.

**Comment by MaxBenChrist** [comment]
We changed the API, where do you have this lines from?

""" Python
X_train = extract_features(df_shift_train, column_id="id", column_sort="time", column_value="value", impute_function=impute,
show_warnings=False, feature_extraction_settings=MinimalFCParameters())
"""
