### ISSUE TITLE
Combining Features of TSFRESH and PCA

### ISSUE THREAD

**Issue by ShivamPanchal** [blue-yonder/tsfresh#321]
Hi, I am having a time series data, I have the target predictive variable and around 100 independent variables. I was using PCA and a bunch of other algorithms to play around. THen, I used TSFRESH. Its performing good to my expectations. Now, I am going to start the another experiment. I want to merge the features extracted from MinimalFeatureExtraction Settings and PCA (number of components) together alongwith the normalization (or standard scaling). 

Need your Suggestions.
Will it be a good approach? Or I should do something else. I just want to use both the features PCA and TSFRESH , as I can't avoid the 100 independent variables.

Thanks in Advance.

**Comment by MaxBenChrist** [comment]
> Hi, I am having a time series data, I have the target predictive variable and around 100 independent variables. 

are you trying to do time series forecasting or classification?

**Comment by MaxBenChrist** [comment]
> Will it be a good approach? Or I should do something else. I just want to use both the features PCA and TSFRESH , as I can't avoid the 100 independent variables.

I would just construct three different feature matrices and then `pandas.concat` them together.

However, I feel that your question is not really related to tsfresh. It is more of a general modeling question. I will close this.
