### ISSUE TITLE
extract_features failed in debugging mode in pycharm 

### ISSUE THREAD

**Issue by tamzhiyang** [blue-yonder/tsfresh#336]
Oh no, you encountered a problem while using *tsfresh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system
Window 10, Anaconda 5 64 bit, python 3.6, Pycharm 2017.2.3

2. The version of *tsfresh* that you are using
tsfresh-0.10.1-py2.py3-none-any.whl

3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
This occurred on the quick start code documented in http://tsfresh.readthedocs.io/en/latest/text/quick_start.html

4. A minimal code snippet which reproduces the problem/bug
The code is from quick start http://tsfresh.readthedocs.io/en/latest/text/quick_start.html

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by MaxBenChrist** [comment]
That example executed fine on my machine
