### ISSUE TITLE
Provide function to produce list of features from FeatureExtractionSettings object

### ISSUE THREAD

**Issue by jneuff** [blue-yonder/tsfresh#34]
There should be an easy way to obtain a list of all features a FeatureExtractionSettings object is configured to calculate.

**Comment by nils-braun** [comment]
In form of human-readable output or do you just want a list? Or what was the intention behind it?

**Comment by jneuff** [comment]
The idea was to have a list, like the column names of the resulting feature matrix but without the `kind` prefix. It's not that important, just nice to have. As you can easily get an overview without calculating the features. Of course you could just look at the `name_to_param` member, but then it is not immediately clear for all features what the results will be.

**Comment by nils-braun** [comment]
In the moment, the result is dependent on which kind you are referring to, because you could have different settings for different kinds - so the answer without the kind column would be actually wrong...

**Comment by MaxBenChrist** [comment]
I think that we just need to apply `convert_to_output_format` to the `default_fc_parameter` object

**Comment by nils-braun** [comment]
The setting objects are basically a dictionary, so all the information is there.

Everything else needs a bit more thinking and I do not see any benefit, so I am closing this now.
