### ISSUE TITLE
Rolling Time Series

### ISSUE THREAD

**Issue by snowde** [blue-yonder/tsfresh#342]
Rolling Time Series: 
This did not produce a new id

``` Python

def roll_out_time_series(time_shift):
        # Shift out only the first "time_shift" rows
        df_temp = grouped_data.shift(time_shift)
        df_temp[column_id] = df[column_sort]
        if column_kind:
            df_temp[column_kind] = df[column_kind]
        return df_temp.dropna()
```

I changed it to this 

``` Python

def roll_out_time_series(time_shift):
        # Shift out only the first "time_shift" rows
        df_temp = grouped_data.shift(time_shift)
        df_temp[column_id] = df[column_id].map(str) + str(time_shift)
        if column_kind:
            df_temp[column_kind] = df[column_kind]
        return df_temp.dropna()
```

**Comment by MaxBenChrist** [comment]
Can you maybe elaborate your issue in a little bit more detail? 

Have you seen http://tsfresh.readthedocs.io/en/latest/text/forecasting.html ?

**Comment by nils-braun** [comment]
What do you mean by creating new IDs? The ID is in our case the name of the column, where the rolling stopped.

**Comment by snowde** [comment]
Hi Nils,

I didn't quite catch what your function did. Here was my situation.

Had a time series of multiple stock pricing data and had to recalculate tsfresh on all dates, rolling with size k for each consecutive date.

This is what I came up with:

https://paper.dropbox.com/doc/Rolling-x499qLMtLFBzthcrMwQlq?_tk=share_copylink
Rolling<https://paper.dropbox.com/doc/Rolling-x499qLMtLFBzthcrMwQlq?_tk=share_copylink>
paper.dropbox.com
def roll(good,length, sorter, id): # Check to ensure all id's are at least as long as one rolling time series bytag = good.groupby(id).aggregate(np.



________________________________

**Comment by nils-braun** [comment]
Hi @snowde,

well, you are of course free to use any other method, if you like :+1: 
If your method is faster or has a larger use case, you can make a pull request if you want (but I have not looked through it in detail).

As @MaxBenChrist already pointed out, the rolling mechanism is quite well described in our documentation. There, it is also described what happens to the IDs etc.
