### ISSUE TITLE
Query regarding parameter value setting

### ISSUE THREAD

**Issue by apangshu** [blue-yonder/tsfresh#344]
How can we determine the parameter values when setting the feature extraction parameters through kind_to_fc_parameters dictionary?

Ex)
m=5, r=0.5 in
approximate_entropy__m_5__r_0.5

**Comment by nils-braun** [comment]
The settings are described in our documentation http://tsfresh.readthedocs.io/en/latest/text/feature_extraction_settings.html.
They are a dictionary (or in this case a dictionary for every kind, so a dictionary of dictionary) where you set the parameter as the value.
