### ISSUE TITLE
Only depend on ipaddress on Python 2

### ISSUE THREAD

**Issue by xhochy** [blue-yonder/tsfresh#345]
`ipaddress` is a Python2-only package. Depending on it makes `tsfresh` Python 2-only. 

This blocks the update to 0.11.0 on conda-forge with the following error:

```
Can't build /…/tsfresh-feedstock/recipe due to unsatisfiable dependencies:
The following specifications were found to be in conflict:
  - ipaddress -> python 2.7*
  - python 3.5.*
Use "conda info <package>" to see the dependencies for each package.

Typically if a conflict is with the Python or R
packages, the other package needs to be rebuilt
(e.g., a conflict with 'python 3.5*' and 'x' means
'x' isn't build for Python 3.5 and needs to be rebuilt.
```

**Comment by MaxBenChrist** [comment]
I have no experience with conda.

How can we make tsfresh only depend on ipaddress on Python 2?

**Comment by nikhaas** [comment]
It looks like it's the other way round: `ipaddress`is Python 3.3+. [Link to Docs](https://docs.python.org/3.3/library/ipaddress.html)
There are [three backports for Python 2](https://github.com/phihag/ipaddress/blob/master/OTHER_BACKPORTS.md) out there. Looks like the most popular one is the one from [Philipp Hagemeister](https://docs.python.org/3.3/library/ipaddress.html)
The package is on conda-forge [Link](https://anaconda.org/conda-forge/ipaddress). So it should be possible in principle to integrate it in the conda ecosystem.

**Comment by xhochy** [comment]
This is independent of conda, this is general python packaging. You need to change the requirement to something similar of

```
ipaddress>=x; python_version <= '2.7'
```

The Python package `ipaddress` is a Python 2-only package. In Python 3 it is part of the standard library.

**Comment by MaxBenChrist** [comment]
Ah thanks @xhochy, I was not aware of the environment markers for pip requirement files. Will open a pr
