### ISSUE TITLE
SSL error while installing via pip

### ISSUE THREAD

**Issue by Tych0n** [blue-yonder/tsfresh#348]
### For future generations

1. Operating system - Windows 7 (Anaconda)
2. _
3. The data on which the problem occurred - pip install tsfresh
4. A minimal code snippet which reproduces the problem/bug:

conda create --name timeseries python=3.5
activate timeseries
conda install spyder
pip install tsfresh

5. Any reported errors or traceback

Collecting tsfresh
  Could not fetch URL https://pypi.python.org/simple/tsfresh/: There was a probl
em confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed (_ssl.c:719) - skipping
  Could not find a version that satisfies the requirement tsfresh (from versions
: )
No matching distribution found for tsfresh

### Solution
pip install --trusted-host pypi.python.org tsfresh

P.S. https://anaconda.org/conda-forge/tsfresh doesn't work

**Comment by xhochy** [comment]
@Tych0n What is the problem with the package from conda-forge? Why doesn't it work?

**Comment by Tych0n** [comment]
@xhochy python doesn't see tsfresh after installing despite the fact that i see it in "conda list"

**Comment by MaxBenChrist** [comment]
@Tych0n as you just closed it, how did you solve this issue?

**Comment by Tych0n** [comment]
@MaxBenChrist as i mentioned in "Solution" section.

**Comment by MaxBenChrist** [comment]
Ah, thanks. @Tych0n 👍
