### ISSUE TITLE
Example of custom feature calculation

### ISSUE THREAD

**Issue by Jwely** [blue-yonder/tsfresh#350]
Hey everyone, firstly thanks for the work on this, I think it'll be useful to me.

I'm recently diving into this package and wanted to extend the base settings with some domain specific feature calculators, specifically those used to describe and model the actions of many plants and insects using daily summary weather data. This is just one example, but this kind of calculation is actually fairly widespread within agriculture, ecology, etc since daily weather data summaries have been collected by humans for a long time.

The docs instruct adding to `feature_calculators.py` directly which might be appropriate later (as it may be useful to someone other than me) but not quite yet, so I extended it externally by:

```python 3
import tsfresh
from tsfresh.feature_extraction.settings import EfficientFCParameters
from tsfresh.feature_extraction import feature_calculators

# define some feature extractor
@feature_calculators.set_property("fctype", "simple")
@feature_calculators.set_property("special", "dailytemp")  # maybe useful? TODO
def total_gdd(x, base, maximum):
    """
    Summation of heating/growing degree days used commonly for
    plant and insect activity and growth modelling. Simple linear version.

    :param x: pandas time series with daily temperature data
    :param base: base temperature of the gdd
    :param maximum: maximum temperature for gdd accumulation
    :return:
    """
    gdd = x - base
    gdd[gdd < 0] = 0
    gdd[gdd > maximum] = maximum

    return gdd.sum()


# add it to the tsfresh feature calculators
feature_calculators.__dict__["total_gdd"] = total_gdd


# define a new settings class to use as 'default_fc_parameters'
class BioTempFCParameters(EfficientFCParameters):

    def __init__(self):
        super().__init__()
        self["total_gdd"] = [{"base": 20, "maximum": 32}]

# extract the features
extracted_features = tsfresh.extract_features(
    *my_other_args, 
    default_fc_parameters=BioTempFCParameters())
```

It works, but while creating it I encountered some troubles / room for improvement.

1) All the documentation seems to say that a general feature_calculator `x` input may be `pd.Series`, but in practice only `np.ndarray` seems to be accepted. Am I incorrect?

2) I'd like to use python3 type-hinting on these extensions to fit our style guide! But unfortunately `ComprehensiveFCParameters()` uses the deprecated `getargspec()` instead of `getsignature()`. If I get the time and motivation maybe I'll take a look at implementing this without breaking python 2.7 support.

3) I'm not convinced this is an ideal model for **extensible** feature extraction, but I'm unable to suggest a better way at this time. I haven't verified yet that this approach works with as intended if the `kind_to_fc_parameters` kwarg is used. If it does work, perhaps the docs could use updating to point users towards this method of extension?

**Comment by MaxBenChrist** [comment]
Hi @Jwely, 

> All the documentation seems to say that a general feature_calculator x input may be pd.Series, but in practice only np.ndarray seems to be accepted. Am I incorrect?

In the past, we used pd.Series. We internally switched to np.ndarray for performance reasons. We should edit the documentation in that respect

> I'd like to use python3 type-hinting on these extensions to fit our style guide! But unfortunately ComprehensiveFCParameters() uses the deprecated getargspec() instead of getsignature(). If I get the time and motivation maybe I'll take a look at implementing this without breaking python 2.7 support.

Which extensions? Are you rewriting tsfresh? I a not sure I understand what you are referring to here. You could just use `six.PY2` to use `getargspec()` for python 2.7 and `getsignature()` for python 3

> I'm not convinced this is an ideal model for extensible feature extraction, but I'm unable to suggest a better way at this time. I haven't verified yet that this approach works with as intended if the kind_to_fc_parameters kwarg is used. If it does work, perhaps the docs could use updating to point users towards this method of extension?

The way you add your feature calculator is a little bit hacky. We assume the feature calculators to be contained in the respective submodule, as described here http://tsfresh.readthedocs.io/en/latest/text/how_to_add_custom_feature.html

**Comment by nils-braun** [comment]
It seems there is no additional question, so I will close this.
