### ISSUE TITLE
Lots of warning during run-time

### ISSUE THREAD

**Issue by GSTev** [blue-yonder/tsfresh#353]
Hi,

I want to adopt tsfresh and currently i am working with the tutorial on the site.
And during run-time i keep getting the following warnings:
1. FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

2. UserWarning: nperseg = 256 is greater than input length  = 15, using nperseg = 15
  .format(nperseg, input_length))

And lots of warnings from statsmodels:
1. RuntimeWarning: divide by zero encountered in double_scalars
  return np.dot(wresid, wresid) / self.df_resid
2. RuntimeWarning: divide by zero encountered in log
  se = -1 * np.log(similarity_ratio)

And so on. i think it is a bit strange getting all those warnings when the only thing i did is to try 3 line of code from the tutorial:
`    download_robot_execution_failures()
    timeseries, y = load_robot_execution_failures()
    extracted_features = extract_features(timeseries, column_id="id", column_sort="time")`

Is something wrong with my env or this is the normal behavior of the package? 

1. Your operating system - Windows 7
2. The version of *tsfresh* that you are using - 0.10.1

Thanks a lot!

**Comment by nils-braun** [comment]
Thank you for your report!
Unfortunately, these warnings are normal.
As we do automatic extraction, it may happen that certain time series are not suited for all feature extractors, so they will output warnings in those cases.
We could probably turn them all off somehow (and are doing this for some things), but I think the user should get a feedback on what exactly is going on.
Concerning the `FutureWarning`: this is one of our included modules (not written by us), so the only thing we can do here is wait for the package conveners to do their job...
