### ISSUE TITLE
Predicting Future Values

### ISSUE THREAD

**Issue by shaakash** [blue-yonder/tsfresh#354]
I am using TSFresh for feature extraction for one of the time series problem.
I have to predict the daily closing balance for around 100 commercial accounts.

Now I train and fit my data till say 12/22 (available data) and have to predict 7 days in future. How do I do this efficiently? 

My Approach: 
a. Predict the target variable (amount) for 12/22. 
b. Append it to my original timeseries and feed it as input to feature extraction process to get relevant features.
c. Train and fit the new model
d. Predict for 12/23
e. Repeat a through d for 7 days

Not sure if this is the best way to approach this situation so reaching out to you to check if there is any function/method with TSFresh that would allow me to save all this computation and fitting over and over again.

Thanks,
Aakash

**Comment by MaxBenChrist** [comment]
hey @shaakash, please have a look at http://tsfresh.readthedocs.io/en/latest/text/forecasting.html

**Comment by juanmanuelrq** [comment]
> I am using TSFresh for feature extraction for one of the time series problem.
> I have to predict the daily closing balance for around 100 commercial accounts.
> 
> Now I train and fit my data till say 12/22 (available data) and have to predict 7 days in future. How do I do this efficiently?
> 
> My Approach:
> a. Predict the target variable (amount) for 12/22.
> b. Append it to my original timeseries and feed it as input to feature extraction process to get relevant features.
> c. Train and fit the new model
> d. Predict for 12/23
> e. Repeat a through d for 7 days
> 
> Not sure if this is the best way to approach this situation so reaching out to you to check if there is any function/method with TSFresh that would allow me to save all this computation and fitting over and over again.
> 
> Thanks,
> Aakash

Hi, How could you solve the problem?
