### ISSUE TITLE
Data formats can be much simpler for the user

### ISSUE THREAD

**Issue by srcolinas** [blue-yonder/tsfresh#356]
I think the package should work even if the time series is passed only as a sequence of any length or a numpy array of one dimension. From the documentation, I see that it uses pandas dataframes, which are of course widely used in data analysis, but are really unnecessary when it comes to machine learning models per se (see the way in which Sci-kit learn works). I really see nothing useful in using pandas if I just have an array of values already in numpy

**Comment by MaxBenChrist** [comment]
From our/my experience, pandas Data Frame are the standard carrier of relational information for data science. pandas is a great package to do analysis on your data. This is why we developed the package in the first place. (we used to heavily rely on pandas `.groupby` in the pas) 

Now, If you have your time series data in numpy arrays, you can just call the pandas Dataframe constructer and use tsfresh on that.  

I think it would be also possible to change our api to also accept plain numpy arrays, do you want to submit a PR for that?

**Comment by nils-braun** [comment]
I think @MaxBenChrist is right. We heavily depend on the pandas functions. This might not be the best decision, but it will be very hard to remove this dependency again. Feel free to reopen this issue if any one of you has the bandwidth to work on this.
