### ISSUE TITLE
ClusterDaskDistributor with sklearn transformers?

### ISSUE THREAD

**Issue by bmmalone** [blue-yonder/tsfresh#357]
This is not a problem per se, but is it possible to use the `ClusterDaskDistributor` with the sklearn transformers, such as `RelevantFeatureAugmenter`?

The distributor works fine when following the example in "tsfresh on a cluster", but I cannot find any seemingly-relevant parameters on the transformers. Please let me know if I am missing something in docs or otherwise. Thanks.

**Comment by MaxBenChrist** [comment]
Sorry for the late response.

At the moment, the RelevantFeatureAugmenter does not accept the `distributor` argument that is necessary to set the `ClusterDaskDistributor` for the transformer. Adding this should be pretty much straightforward.

I will try to add it once I have more time.

**Comment by bmmalone** [comment]
Thanks; I also found that directly submitting calls via the normal dask client (with some instances chunked together) works fine, so this is not pressing for me.

**Comment by nils-braun** [comment]
It seems this issue is stalled. I will close it.
