### ISSUE TITLE
how to use tsfresh on single-date-column  dataset

### ISSUE THREAD

**Issue by cristph** [blue-yonder/tsfresh#360]
Hi everyone，here is my dataset:

date      |     id  |   y
201701 |      1  |   0.1
201702 |      1  |   0.1
201701 |      2  |   0.2
201702 |      2  |   0.2
......

My problem is: How can I use tsfresh on this kind of train-dataset?
I want to generate features on lag values, window values, etc, while I only have date and idin this dataset and y is the value to predict. 

I read docs of tsfresh,  it seems that there must be other features for function extract_features()...

**Comment by MaxBenChrist** [comment]
Sorry, I do not understand what you want to achieve. Have you read

http://tsfresh.readthedocs.io/en/latest/text/data_formats.html

and 

http://tsfresh.readthedocs.io/en/latest/text/forecasting.html

**Comment by huangshizhi** [comment]
for example,for test data,we don't know the value  or the predict value is nan,how do we extract_features?

**Comment by huangshizhi** [comment]
en..,for example，in you example, https://github.com/blue-yonder/tsfresh/blob/master/notebooks/timeseries_forecasting_google_stock.ipynb,how do we predict the next some day's stock High value?for example ,the next 6 days value? 
2017-01-03 
2017-01-04 
2017-01-05 
2017-01-06 
2017-01-09 
2017-01-10
