### ISSUE TITLE
Lag for agg_autocorrelation, misleading documentation

### ISSUE THREAD

**Issue by helske** [blue-yonder/tsfresh#362]
In the documentation it is said that `agg_autocorrelation` computes the autocorrelations for all lags up to the length of the series. But looking at the codes, this is not the case: The `nlags` parameter of the `acf` function is not defined, and it defaults to 40. It would actually be nice if this lag could be defined as a parameter. Anyway, the docs are misleading, but I am not suggesting to change the lag to the length of the series as the long lags are estimated inefficiently and they dominate the aggregation.

**Comment by MaxBenChrist** [comment]
@helske, valid point, I will have a look at it.
