### ISSUE TITLE
Modeling the extracted features and sampling synthetic time series from the trained model?

### ISSUE THREAD

**Issue by HongminWu** [blue-yonder/tsfresh#365]
Hello there,
Thanks for your fantastic work on the features extraction of time series.
Recently, I want to address the problem of how to generating several synthetic time series from a given time series?
I think with the "tsfresh" can easily extract the features from the given time series, after that, do you think we can use some statistical models to model those features and sampling from it?  

Any suggestions or comments will be appreciated!
Best regards，

**Comment by MaxBenChrist** [comment]
Hi @HongminWu, 

sorry for the late answer. I understand your problem. 

You could use the features to generate synthetic time series, however you need to know how those features relate to the time series generating process. Also, you need to make assumptions about your time series.

For example, we have a feature (`ar_coefficient`) that fits an autoregressive model and extracts its coefficients. You could take those coefficients and sample new AR time series from that.

**Comment by nils-braun** [comment]
It seems this issue is stalled. Closing it.
