### ISSUE TITLE
docs breaking in Sphinx 1.7.2

### ISSUE THREAD

**Issue by earthgecko** [blue-yonder/tsfresh#373]
1. operating system
Ubuntu 14.04.5 LTS

2. The version of *tsfresh*
v0.11.0

3. Problem setup test fails

```
../bin/python2.7 setup.py docs
```

5. Any reported errors or traceback

With Python-2.7.14 and the latest Sphinx-1.7.2

```
$ ../bin/python2.7 setup.py docs
running build_sphinx
creating /opt/python_virtualenv/projects/tsfresh-test-py2714/tsfresh/docs/_build
creating /opt/python_virtualenv/projects/tsfresh-test-py2714/tsfresh/docs/_build/doctrees
creating /opt/python_virtualenv/projects/tsfresh-test-py2714/tsfresh/docs/_build/html
usage: setup.py [OPTIONS] -o <OUTPUT_PATH> <MODULE_PATH> [EXCLUDE_PATTERN, ...]
setup.py: error: argument -o/--output-dir is required
$
```

Updating the conf.py with a output_dir and module_dir and running  ```setup.py doctest``` seems to be a change in setuptools/sphinx now or since Sphinx-1.7.x maybe...
Even then with lots of output and fails.

Downgrading Sphinx to the last version specified in the rdocs-requirement.txt resloves the issue and works as expected for now.

```
Sphinx==1.6.4
```

Instead of 

```
Sphinx>=1.6.4
```

**Comment by nils-braun** [comment]
That is our requirement now, so it seems it works.
