### ISSUE TITLE
How to use API for a particular regression task: pedicting values for every moment in time?

### ISSUE THREAD

**Issue by ODemidenko** [blue-yonder/tsfresh#376]
Please, help me to understand how to use the lib for a particular problem.
I have sensor measurements on different units, at different moments and time (cycles). The task is a regression - predicting how many cycles left before the failure .
I struggle to understand how shall I cast feature extraction+selection task into tsfresh API.

Data example:
unit | cycle | sens2 | sens3 | cycles_to_failure
1 | 1 | 641.82 | 1589.70 | 100
1 | 2 | 642.15 | 1591.82 | 99
1 | 3 | 642.35 | 1587.99 | 98
1 | 4 | 642.35 | 1582.79 | 97
2 | 1 | 642.15 | 1591.82 | 100
2 | 2 | 642.35 | 1587.99 | 99
2 | 3 | 642.35 | 1582.79 | 98

I expect to get features correlated with the cycles_to_failure.
I tried it this way:
```
features=extract_relevant_features(df[['unit','cycle','sen1','sens2'],
                                   y=df['cycles_to_failure'],
                                   column_id='unit',
                                   column_sort='cycle',
                                   ml_task='regression')
```
And I get the following error:
All inputs to `kendalltau` must be of the same size, found x-size 100 and y-size 20631 (I have 100 units in the dataset, and 20631 data points on this units overall)

As far as I got it - it is expected that I provide final regression value for each of units (y vector must have same shape and sort order as column_id ?). 
But, for my task, I have some values to predict at every moment in time (so, prediction is another timeseries).  What is the best way to use an API in such a situation?

Probably the right option is to generate sub-timeseries here and feed them to extract_relevant_features? But how exactly shall I use `.make_forecasting_frame` method then? I couldn't understand its "kind" parameter from the docs and [existing notebook example](https://github.com/blue-yonder/tsfresh/blob/master/notebooks/timeseries_forecasting_basic_example.ipynb) there are different "kind" values in the example, which is absolutely misleading).  I actually failed to understand what exactly do the following parameters mean in any methods: `column_kind, column_value`, they remained unclear after I read functions docs, and I didn't find any clarifying examples.

**Comment by ODemidenko** [comment]
I found pandas .rolling functionality that allows calculating features on a rolling basis. So, I will probably use it instead, for a simple feature generation. For an automatic feature selection probably it's easier to adapt tsfresh calculators and selection methods, as I suspect.

**Comment by MaxBenChrist** [comment]
>  I actually failed to understand what exactly do the following parameters mean in any methods: column_kind, column_value, they remained unclear after I read functions docs, and I didn't find any clarifying examples

have you looked at the first page of the docs: http://tsfresh.readthedocs.io/en/latest/text/data_formats.html ?

**Comment by MaxBenChrist** [comment]
I do not understand what you are trying to achieve, your machine learning task is unclear to me. Do you estimate the remaining lifetime of a spare part?

You use the terms "moments", "cycles" and "time", what is the difference between them?

**Comment by ODemidenko** [comment]
> have you looked at the first page of the docs:р 
> http://tsfresh.readthedocs.io/en/latest/text/data_formats.html ?

Sorry, I didn't expect to find answers there previously. Now I understand everything regarding `column_ kind, column_value`

> Do you estimate the remaining lifetime of a spare part?

Yes. 
Sorry for the typo and excessive synonyms in my original question. So, I have predicted variable (remaining lifetime) for each point in time. And I want to construct new features on a rolling basis for every moment in time as well, and I need a fixed window size for this rolling window, like pandas df.rolling provides.

**Comment by MaxBenChrist** [comment]
okay, fully understand now

> Sorry for the typo and excessive synonyms in my original question. So, I have predicted variable (remaining lifetime) for each point in time. And I want to construct new features on a rolling basis for every moment in time as well, and I need a fixed window size for this rolling window, like pandas df.rolling provides.

did you see our rolling functionality? see http://tsfresh.readthedocs.io/en/latest/text/forecasting.html 
also, we have a few notebooks in the notebook folder that illustrate the rolling mechanism

the rolling mechanism its still not perfect but it should do the job for you. We also welcome help to improve it ;)
