### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by olutobi01** [blue-yonder/tsfresh#378]
Hi Guys,
Kudos for the great work on the package.

Can you please advise on the recommended preprocessing steps for a time series before the feature extraction step.

Thanks

**Comment by MaxBenChrist** [comment]
Hi @olutobi01,

this is highly dependent on the problem at hand. Common techniques are normalizing, standardization, removing of nans, resampling etc. 

What kind of problem do you want to tackle?

**Comment by olutobi01** [comment]
Hi @MaxBenChrist ,
Thanks for the response.

I am working on multivariate sensor data from a manufacturing process.

I have performed standardization for each sensor and I wonder if this may lead to information loss in the signal.

**Comment by MaxBenChrist** [comment]
It is hard to say without knowing your application, I close this as its not directly related to tsfresh
