### ISSUE TITLE
is feature selection for multi-label classification supported?

### ISSUE THREAD

**Issue by daanvdn** [blue-yonder/tsfresh#379]
Hi,

I have a question for which I couldn't  find an answer in the docs or examples: does tsfresh support feature selection for **multi-label classification** problems or will it only work for binary classification? 
If it is supported, should the DataFrame be formatted in a specific way?

Thanks a lot

**Comment by MaxBenChrist** [comment]
Just for the extraction of the features, it does not madder if you have a binary or multi-classification target vector. 

the feature selection was developed for binary classification but can be also applied to multi class settings, see here 

https://github.com/blue-yonder/tsfresh/blob/master/notebooks/human_activity_recognition_multi_class_example.ipynb

**Comment by MaxBenChrist** [comment]
Hi @daanvdn, 

this sound like a general task ("using a binary feature selection algorithm on a multi label classification problem"). I am not sure what is the best way to tackle this but I am pretty sure you can find a few summary papers on that problem.

>  I guess I could treat every combination of N labels as a label of itself, but I don't know if that would work within your framework?

I would extract the features without the selection, save the features matrix and then compare different feature selection approaches (remap the label combinations to multi class problem, inspect the labels individually etc.). Our toolbox is not able to do those transformations though, we expect a binary target vector and select features based on that. However, the re-maping should be easily achievable with pandas/numpy.

**Comment by MaxBenChrist** [comment]
If your data can be published, we can help you to setup an exemplary ipython notebook to merge into tsfresh

**Comment by MaxBenChrist** [comment]
@daanvdn, sorry for the late answer. Can you write me a message on gitter?

**Comment by smishra** [comment]
Hi @MaxBenChrist @daanvdn I am similar problem, having time series that has multiple targets. Can you please recommend a solution if you found one. Thanks

**Comment by nils-braun** [comment]
It seems this issue is stalled. Closing it.

**Comment by RickyKaku** [comment]
It seems the 
https://github.com/blue-yonder/tsfresh/blob/master/notebooks/human_activity_recognition_multi_class_example.ipynb
is no longer available, what's the new address for it? Thanks.

**Comment by nils-braun** [comment]
Thanks, it is now moved here: https://github.com/blue-yonder/tsfresh/blob/main/notebooks/examples/04%20Multiclass%20Selection%20Example.ipynb
