### ISSUE TITLE
improve documentation on chsnks and chunk size parameter

### ISSUE THREAD

**Issue by adrianloy** [blue-yonder/tsfresh#385]
Hi,

I am unsure what exactly the chunk parameter for the `extract_features` function is. Does it refer to rows? Percentage of the dataframe? in memory size of one chunk? And what happens if the default value of None is set? The docstring isn't very helpful here.

I currently have problems of getting out of memory exceptions, can this parameter help me there? 

Thanks in advance,
Adrian

**Comment by MaxBenChrist** [comment]
Hi @adrianloy,

the documentation could be improved here. 

Its quite easy, one chunk is a singular time series for one id and one kind. If you set the chunk size to 10, then it means that one task is to calculate all features for 10 time series. 

If you set it to None, we use, depending on distributor, heuristics to find the optimal chunk size. If you get out of memory exceptions, you can try it with the dask distributor and smaller chunk sizes. 

How big is your data? how big is your memory?

**Comment by adrianloy** [comment]
Thanks for the clarification! Would be nice to have in the docs indeed.
