### ISSUE TITLE
How to set the time step window for tsfresh?

### ISSUE THREAD

**Issue by gprasad19** [blue-yonder/tsfresh#386]
I need to calculate the features for a sensor data column with 100 observations. But the features need to be calculated for a window of every 10 observation. How do I do it using tsfresh?

**Comment by earthgecko** [comment]
Hi @gprasad19 

Please see http://tsfresh.readthedocs.io/en/latest/text/forecasting.html that may help you, but that is only a guess.

There are a number of other closed issues relating the rolling time series and windows, search the issues and reviewing some of them may help or have a look and scroll back through https://gitter.im/tsfresh/Lobby, there are a number of examples of things people are trying to do with tsfresh, you may find something similar to what you are trying to achieve.

**Comment by nils-braun** [comment]
The rolling mechanism described in the link @earthgecko gave does exactly this: it helps you create "chunks" of the timeseries, that you can then use for calculating the features.
I do not understand the downvote of @mohataher but I see the question as answered. I will close it.
