### ISSUE TITLE
tsfresh returns empty dataframe even when datapoints are adequate

### ISSUE THREAD

**Issue by loginofdeath** [blue-yonder/tsfresh#387]
My timeseries dataframe has about 6000 rows and 27 features. I feel that the dataset is adequate. Still tsfresh is returning empty dataframe when I try to extract relevant features.
1. My operating system: MacOS Sierra
2. *tsfresh* ==0.11.0
[timeseries.csv.zip](https://github.com/blue-yonder/tsfresh/files/2088197/timeseries.csv.zip)

**Comment by earthgecko** [comment]
Hi @loginofdeath

With your csv as is, features are generated, you need to pass the column_id and column_sort parameters.  See http://tsfresh.readthedocs.io/en/latest/text/data_formats.html

```python
import csv
import pandas as pd
from tsfresh import extract_features, extract_relevant_features, select_features
df = pd.read_csv('timeseries.csv', delimiter=',')
extract_features(df, column_id='index', column_sort='time')
```

Results

```
variable	Feature_0__abs_energy	Feature_0__absolute_sum_of_changes	Feature_0__agg_autocorrelation__f_agg_"mean"	Feature_0__agg_autocorrelation__f_agg_"median"	Feature_0__agg_autocorrelation__f_agg_"var"	Feature_0__agg_linear_trend__f_agg_"max"__chunk_len_10__attr_"intercept"	Feature_0__agg_linear_trend__f_agg_"max"__chunk_len_10__attr_"rvalue"	Feature_0__agg_linear_trend__f_agg_"max"__chunk_len_10__attr_"slope"	Feature_0__agg_linear_trend__f_agg_"max"__chunk_len_10__attr_"stderr"	Feature_0__agg_linear_trend__f_agg_"max"__chunk_len_50__attr_"intercept"	...	Unnamed: 0__time_reversal_asymmetry_statistic__lag_1	Unnamed: 0__time_reversal_asymmetry_statistic__lag_2	Unnamed: 0__time_reversal_asymmetry_statistic__lag_3	Unnamed: 0__value_count__value_-inf	Unnamed: 0__value_count__value_0	Unnamed: 0__value_count__value_1	Unnamed: 0__value_count__value_inf	Unnamed: 0__value_count__value_nan	Unnamed: 0__variance	Unnamed: 0__variance_larger_than_standard_deviation
id																					
487.0	1455.471033	2.200586	-0.458479	-0.327044	0.976090	5.050060	0.993894	0.449978	0.028843	NaN	...	2.552000e+03	4.992000e+03	7328.0	0.0	1.0	1.0	0.0	0.0	168.666667	1.0
488.0	2659.748858	2.249495	-0.415134	-0.289317	0.914572	6.939999	0.996220	0.460025	0.023158	NaN	...	1.887000e+04	3.762533e+04	56274.0	0.0	0.0	0.0	0.0	0.0	176.250000	1.0
...
...
131 rows × 22232 columns
```

**Comment by MaxBenChrist** [comment]
@loginofdeath does tsfresh return features? did you pass a target column when using to extract relevant features?

**Comment by loginofdeath** [comment]
Hi @MaxBenChrist , it was a false alarm. You have created an awesome module for handling time-series data. Please close this issue.

**Comment by MiracleLemon** [comment]
> Hi @MaxBenChrist , it was a false alarm. You have created an awesome module for handling time-series data. I am closing this issue.

Hi @loginofdeath 
I'm curious how you solved it! I've had the same problem.

**Comment by enesok** [comment]
> Hi @MaxBenChrist , it was a false alarm. You have created an awesome module for handling time-series data. I am closing this issue.



> > Hi @MaxBenChrist , it was a false alarm. You have created an awesome module for handling time-series data. I am closing this issue.
> 
> Hi @loginofdeath I'm curious how you solved it! I've had the same problem.

Me too.
