### ISSUE TITLE
Using tsfresh for Anomaly Detection problem

### ISSUE THREAD

**Issue by loginofdeath** [blue-yonder/tsfresh#389]
1. My operating system-Mac OS Sierra
2. tsfresh ==0.11.0
3. For security concerns, I cannot share the data

Hi,
I am using tsfresh in the field of Anomaly detection. First of all, I am only training on the positive values and testing it on a mixture of positive and negative values. After getting the relevant features from tsfresh, I want to scale it and then feed it to a One class classifier. I used RelevantFeatureAugmenter() in a pipeline but it gave me this error:
`ValueError: not enough values to unpack (expected 2, got 1)`. 

I know this is because I supplied only one y value(1). My first question: is there any way to bypass that?

To circumvent that,I then used this pipeline structure:
```
pipe=Pipeline(
[
   ('fresh',FeatureAugmenter(column_id='index', column_sort='tick',default_fc_parameters=MinimalFCParameters())),
    ('scaler',StandardScaler())
])

```
My question is : suppose I fit_transform this pipeline on some training data and then train it on some classifier. Will I get the same features if I pickled the pipeline and loaded it and used it to transform on  the testing data so that it can be given to a classifier?

My third question: I am handling different users and it takes a lot of time for tsfresh to calculate the relevant features( sometimes close to 30 mins). Is there any way such that for the first time it runs on a particular user and selects some features and we could save this preference. So that whenever a new user comes we only calculate those features.

Thank you again for creating this awesome package. 

Regards,
Souraj

**Comment by MaxBenChrist** [comment]
> My question is : suppose I fit_transform this pipeline on some training data and then train it on some classifier. Will I get the same features if I pickled the pipeline and loaded it and used it to transform on the testing data so that it can be given to a classifier?

have you seen this notebook https://github.com/blue-yonder/tsfresh/blob/master/notebooks/pipeline_with_two_datasets.ipynb ?

**Comment by loginofdeath** [comment]
Ah yes, saw the notebook. Can you please answer question one and two?

**Comment by MaxBenChrist** [comment]
> I know this is because I supplied only one y value(1). My first question: is there any way to bypass that?

no, you can never select features if your target vector only has one value

> My third question: I am handling different users and it takes a lot of time for tsfresh to calculate the relevant features( sometimes close to 30 mins). Is there any way such that for the first time it runs on a particular user and selects some features and we could save this preference. So that whenever a new user comes we only calculate those features.

you would have to implement something externally and wrap it around tsfresh, in tsfresh, feature extraction and selection are separated.

**Comment by loginofdeath** [comment]
Thanks for answering my questions.
