### ISSUE TITLE
conda environment and tsfresh

### ISSUE THREAD

**Issue by rpanai** [blue-yonder/tsfresh#390]
I'm experiencing a problem with your library and dask. I have a conda environmet with dask and if I install tsfresh via `pip install tsfresh` whenever I try to use ``dask.dataframe` I receive the following error

`File "<stdin>", line 1, in <module>
  File "~/.conda/envs/hybridDEV/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 3, in <module>
    from .core import (DataFrame, Series, Index, _Frame, map_partitions,
  File "~/.conda/envs/hybridDEV/lib/python3.6/site-packages/dask/dataframe/core.py", line 40, in <module>
    pd.core.computation.expressions.set_use_numexpr(False)
AttributeError: module 'pandas.core.computation' has no attribute 'expressions'`

**Comment by MaxBenChrist** [comment]
This looks like a dask not a tsfresh problem to me

Have you tried installing tsfresh via pip?

**Comment by rpanai** [comment]
I did install tsfresh via pip. I'm not sure if it's a `dask` problem as it was working fine before install `tsfresh`.

**Comment by MaxBenChrist** [comment]
this is the first result on google: https://github.com/pandas-dev/pandas/issues/18355

which version of dask are you running?
