### ISSUE TITLE
select_features keeps running

### ISSUE THREAD

**Issue by Devarsh-UTD** [blue-yonder/tsfresh#393]
1. Your operating system - MacBook Pro (Retina, 15-inch, Mid 2014)(8cores)

2. The version of *tsfresh* that you are using - latest

4. A minimal code snippet which reproduces the problem/bug
when I use 500 rows , the select_features works fine and gives me all the important features, but when I increase the number of rows to 17000, the select_features keeps on running plus it does not use all cores, because when I check my cpu utilization it is somewhere around 9-12%(User), the same thing also happens when I run select_features using 500 rows only, it doesn't use 8 cores or the default 4 cores in either of the cases. Kindly help me out.

5. Any reported errors or traceback

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by MaxBenChrist** [comment]
Please provide a minimal code example. 

Von meinem iPhone gesendet

**Comment by Devarsh-UTD** [comment]
![screenshots](https://user-images.githubusercontent.com/33138515/42282680-49acc5f6-7f75-11e8-9fb6-18870f10681b.jpg)
Case 1 - When 500 rows, the above code works completely fine and I am able to get important features from select_features.
Case 2 - When I keep everything same and increase the number of rows to 17000, I am able to extract features, but when I run select_features, it keeps running and does not start multiprocessing,

**Comment by Devarsh-UTD** [comment]
<img width="926" alt="screen shot 2018-07-04 at 10 37 02 am" src="https://user-images.githubusercontent.com/33138515/42283025-44c3e87a-7f76-11e8-888d-4dc2071b4a92.png">
I am using this code for select_features, it works for 500 rows but not 17000. Kinldy note In either  of the cases it does not take n_jobs=8 into account nor the default n_jobs = 4, because the cpu %(User) is around 9-12% in both the cases

**Comment by MaxBenChrist** [comment]
bty , the parameter is `n_processes` not `n_jobs`

**Comment by Devarsh-UTD** [comment]
I Put in all the 794 columns and memory usage is 9%-12%, which makes me think that the select_features has not started, because by default it uses 4 cores and with 4 cores the memory usage should be around 50-60%

**Comment by MaxBenChrist** [comment]
Without an example (code+data) its hard for me to debug this

**Comment by Devarsh-UTD** [comment]
I will try to get the data as soon as possible. 
In the meantime I have another question - 
lets say I have a time series dataset for 10 days.
For Example:-

      X   timestamp
      2   2018-01-20
      6   2018-01 - 21
 and so on....

All the tutorials that I have gone through show that we can extract features from the above dataset, divide it into train and test , built a model using machine learning algorithm on train dataset and test it on test data set. This works perfectly when we know the value of X at a particular tilmestep.

My question - If I want to predict for the 11th day, how shall I generate features for the 11th day, because I will not be having the value of X for the 11th day. But I do have value of X from 1 to 10. Is there a way to generate features for the 11th day, without having the value of X for 11th day.

**Comment by Devarsh-UTD** [comment]
I checked out the notebook - https://github.com/blue-yonder/tsfresh/blob/master/notebooks/timeseries_forecasting_basic_example.ipynb.

Over here the roll_time_series function is just imported and not used.

**Comment by Devarsh-UTD** [comment]
I read through - http://tsfresh.readthedocs.io/en/latest/text/forecasting.html.
As far as I understood we can extract features for either Full Dataset or subset of data based on the rolling mechanism. From the example dataset above, I can create features based on either the full 10 days or subset of 10 days using the rolling window. But how do I create features for 11th day?

Thanks
Devarsh

**Comment by MaxBenChrist** [comment]
you can't create features for the 11 day because you want to predict for that day.

This is a time series forecasting task. you will have to calculate your features on sliding windows. 

However that question is only partly related to tsfresh. Try to understand the transformations in the linked notebook. I don't have the time at the moment to answer questions about statical modeling.

**Comment by MaxBenChrist** [comment]
Hi @Devarsh-UTD, did you manage to solve your issues regarding the `select_features` method?
