### ISSUE TITLE
Problem in extracted_features function when used with ComprehensiveFCParameters

### ISSUE THREAD

**Issue by shujamughal** [blue-yonder/tsfresh#398]
Hi,
There is an issue in extracted_features function. it does not return those features which are returned in MinimalFCParameters configuration when used with ComprehensiveFCParameters settings. I have attached the sample input and output in both cases. and below is the sample code.

extracted_features = extract_features(temp, column_id="interval_Id", column_sort="timestamp", default_fc_parameters = ComprehensiveFCParameters(), disable_progressbar=True)
 
extracted_features_minimum = extract_features(temp, column_id="interval_Id", column_sort="timestamp", default_fc_parameters = MinimalFCParameters(),disable_progressbar=True)
        
Please let me know what is the solution,
Thanks
Shuja

[input_and_features.zip](https://github.com/blue-yonder/tsfresh/files/2227562/input_and_features.zip)

**Comment by nikhase** [comment]
All the features calculated with `MinimalFCParameters` are also calculated by `ComprehensiveFCParameters`. I checked in Linux the column names of your files
```
comm -12 <((head -1 all_features.csv) | tr ',' '\n' | sort)  <((head -1 basic_features.csv) | tr ',' '\n' | sort) 
```
and got the following list of features which is calculated by both:
```
cpu__length
cpu__maximum
cpu__mean
cpu__median
cpu__minimum
cpu__standard_deviation
cpu__sum_values
cpu__variance
id
```
tsfresh acts exactly like intended: In the first case it calculates all features listed in `MinimalFCParameters` (8 features in total), in the second case it calculates the 974 features defined by `ComprehensiveFCParameters`, which include the 8 features from the minimal setting.
Does this answer your question?

**Comment by shujamughal** [comment]
well... if you open both files then the values are blank in case of all_features file for the above-mentioned features. However in basic_feature file, it has values against the features.  Please let me know if there is any ambiguity
Thanks

**Comment by nikhase** [comment]
Looking with python, I cannot reproduce what you are saying.
```
import pandas as pd
basic_features = pd.read_csv("basic_features.csv", index_col=0)
all_features = pd.read_csv("all_features.csv", index_col=0)
all_features[basic_features.columns]
Out[4]: 
    cpu__length  cpu__maximum  cpu__mean  cpu__median  cpu__minimum  \
id                                                                    
0          18.0         44.92  35.977778         35.6         29.52   

    cpu__standard_deviation  cpu__sum_values  cpu__variance  
id                                                           
0                  4.618927       647.600005      21.334484  

In [5]: basic_features
Out[5]: 
    cpu__length  cpu__maximum  cpu__mean  cpu__median  cpu__minimum  \
id                                                                    
0          18.0         44.92  35.977778         35.6         29.52   

    cpu__standard_deviation  cpu__sum_values  cpu__variance  
id                                                           
0                  4.618927       647.600005      21.334484 
```

**Comment by nikhase** [comment]
If there are no further questions or the problem is resolved, we can close this issue.

**Comment by shujamughal** [comment]
problem solved.
