### ISSUE TITLE
Parallelize the calculation of features

### ISSUE THREAD

**Issue by jneuff** [blue-yonder/tsfresh#4]
Currently we calculate the features in a [list comprehension](https://github.com/blue-yonder/tsfresh/blob/master/tsfresh/feature_extraction/extraction.py#L84):

``` python
extracted_features = [_extract_features_for_one_time_series(relevant_time_series, str(kind),
                                                                column_id, column_value, feature_extraction_settings)
                                  for kind, relevant_time_series in kind_to_df_map.iteritems()]
```

A first step would be to parallelize this list comprehension with joblib or something similar.

Further, as can be seen [here](http://tsfresh.readthedocs.io/en/latest/_images/feature_extraction_process_20160815_mc_1.png) the calculation of features is fragmented both horizontally and vertically. So we can also parallelize on a per sample basis.

**Comment by nils-braun** [comment]
@jneuff Are there already plans on how to do this? I am glad to help in this issue :-)

**Comment by MaxBenChrist** [comment]
Done in 80803d688694e28b9a2739a7738f881d3da5b730 for different kind of time series
