### ISSUE TITLE
About the freezing of tsfresh even at built-in data set

### ISSUE THREAD

**Issue by HarryHaoLee** [blue-yonder/tsfresh#400]
1. Your operating system 
Windows 10 & Ubuntu 16.04 LTS
2. The version of *tsfresh* that you are using 
0.11
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
I used the robot_execution_failures(built-in data set) and one my own data set. The form is as follows:
index id time EMG BVP GSR RESP
0        1   0     5.02  24.83  5.42  46.41
4. A minimal code snippet which reproduces the problem/bug
``` python
extract_settings = ComprehensiveFCParameters()
X = extract_features(df, column_id='id', column_sort='time', default_fc_parameters=extract_settings, impute_function=impute)
X_filtered = extract_relevant_features(df, y,column_id='id', column_sort='time', default_fc_parameters=extract_settings)
```

I run this code with Python 3.6 on Windows 10 OS and it is always stuck whichever data set I use. After a long time like more than 10 hours, it displays 'MemoryErr'.
I run the code with Python 2.7 on Ubuntu 16.04 LTS and it can finish correctly on robot_execution_failures data set but it is stuck at 80% at my own data set.
5. Any reported errors or traceback 
It is just stuck.

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by HarryHaoLee** [comment]
My dataset contains 80 instances and every instance contains 2001 rows so it contains about 160000 rows. On Linux I tried thousands of rows and I can get correct result. But for 20, 40 and 80 instances I can't get any results. The RAM may be too small? Because I only allocate 2 GB RAM for it. On Windows I never get any results on any dataset of any size.

**Comment by MaxBenChrist** [comment]
None of the developers has access to a windows machine, so we can only give rudimentary support for tsfresh on windows. 

Do you have any logs or error messages that pop up?

As said, please try to run your feature extraction with MinimalFCParameters or EfficientFCParameters, not the ComprehensiveFCSettings

**Comment by nicholasg97** [comment]
I just wanted to say that I was having the same issue on a windows machine within an Anaconda environment, and what solved the issue for me was uninstalling tsfresh using pip and installing with 
`conda install -c conda-forge tsfresh`

**Comment by gammaci** [comment]
> I just wanted to say that I was having the same issue on a windows machine within an Anaconda environment, and what solved the issue for me was uninstalling tsfresh using pip and installing with
> `conda install -c conda-forge tsfresh`

Thanks, this worked for me too, side note no need to uninstall with pip, just overwritten previous installation.
