### ISSUE TITLE
extract_features not working, stuck at 0% complete.

### ISSUE THREAD

**Issue by ABillington96** [blue-yonder/tsfresh#402]
I have looked at the other issues saying the same thing but wasn't able to resolve the problem.

I am running Windows 10 and have tried using both Python 2.7 and Python 3.5.
I have made sure that tsfresh is up to date.

The problem is that when I use extract_features() the console gets stuck on:
    Feature Extraction:   0%|          | 0/1 [00:00<?, ?it/s]

The code I am trying to run is from your quick start guide, initially I tried it on a large data set, but thought that it may have been too large so used the one from the tutorial, but I still encountered the same problem. So I reduced the size of that data set further to see if that would help but I still encounter the same issue. 

The code I am trying to run is this:

    import pandas as pd
    from tsfresh import extract_features
    from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, \
        load_robot_execution_failures
    from tsfresh.feature_extraction import MinimalFCParameters

    # Download the dataset
    download_robot_execution_failures()
    
    # Load the dataset
    timeseries, y = load_robot_execution_failures()
    
    # Extract just the first time series from the dataset
    pattern = timeseries.loc[timeseries['id']==1]
    
    # Remove all variables other than the minimum
    pattern= pattern.filter(items=['id','time','F_z'])

    # Only use minimal features
    settings = MinimalFCParameters()
    # Extract the features from the single pattern
    extracted_features = extract_features(pattern,
                                          column_id="id", 
                                          column_sort="time",
                                          default_fc_parameters=settings)

Thanks

**Comment by howardlhw** [comment]
I experienced the same problem previously. Try restarting / upgrading your IDE and it should be fine. I restarted once and it was ok afterwards.

**Comment by ABillington96** [comment]
Thanks for the suggestion @howardlhw, I just tried that but still facing the same issue :(

**Comment by howardlhw** [comment]
Can you check if your settings are the same as mind? I'm using spyder 3.2.4 and I just run it, it seems ok. Can you also try pip install tfresh --upgrade, and restart the IDE to see if it works?

![image](https://user-images.githubusercontent.com/11436624/44091094-ec3a9236-9ffe-11e8-9399-4d5b67aeedcd.png)

**Comment by ABillington96** [comment]
@howardlhw I am using python 2.7.15 and spyder 3.3.0, however the problem resolved itself when I tried the pip upgrade! Thanks for your help!
