### ISSUE TITLE
increase-timeouts-notebook-tests

### ISSUE THREAD

**Issue by earthgecko** [blue-yonder/tsfresh#409]
Notebook test time out on Travis tests as per documented and tested in #372

Breaking down pr #372 to single prs so adding increased time outs to tests/integrations/test_notebooks.py

**Comment by MaxBenChrist** [comment]
I think we should take out the notebooks from travis, from time to time or before making a new release, we the developers make sure to run the tests also on the notebooks and examples

**Comment by earthgecko** [comment]
@MaxBenChrist this does stops them running on Travis - see my comment in the commit https://github.com/blue-yonder/tsfresh/commit/751d09dec0a5b306934d46861a5dc16e8983aedf#r30238766

**Comment by MaxBenChrist** [comment]
We excluded the notebooks from travis. the developer should run them before making a release
