### ISSUE TITLE
update-dependencies

### ISSUE THREAD

**Issue by earthgecko** [blue-yonder/tsfresh#412]
The dependencies are moving and requirements being specified with ```>=``` are now causing problems  for new users.  Seeing as the new deps versions are untested deprecation warnings are becoming errors, e.g. #405 

Attempting to update the dependencies and identify errors to debug and fix, this issue is to track all the tests in the associated pull request/s.

**Comment by earthgecko** [comment]
## Not pip cache - numpy 1.11.1 is bundled in the Travis python-2.7.11.tar.bz2

Same result without pip cache folder - https://travis-ci.org/blue-yonder/tsfresh/jobs/421458427#L461

```
9.44s$ pip install numpy scipy coveralls
Requirement already satisfied: numpy in /home/travis/virtualenv/python2.7.11/lib/python2.7/site-packages (1.11.1)
Collecting scipy
  Downloading https://files.pythonhosted.org/packages/2a/f3/de9c1bd16311982711209edaa8c6caa962db30ebb6a8cc6f1dcd2d3ef616/scipy-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl (30.8MB)
```

So checking https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-2.7.11.tar.bz2
as the only explanation is that it is bundled in the archive.

```
cd /tmp
wget https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-2.7.11.tar.bz2
mkdir -p /tmp/travis-python-2.7.11
tar xjf python-2.7.11.tar.bz2 --directory /tmp/travis-python-2.7.11/

..
..
$ mkdir -p /tmp/travis-python-2.7.11
$ tar xjf python-2.7.11.tar.bz2 --directory /tmp/travis-python-2.7.11/
$ ls -al /tmp/travis-python-2.7.11/home/travis/virtualenv/python2.7.11/lib/python2.7/site-packages/numpy-1.11.1.dist-info/metadata.json
-rw-rw-r-- 1 gary gary 1351 Aug 25  2016 /tmp/travis-python-2.7.11/home/travis/virtualenv/python2.7.11/lib/python2.7/site-packages/numpy-1.11.1.dist-info/metadata.json
$
```

**Comment by earthgecko** [comment]
## Review

Travis Python archives bundles have numpy bundled:

- Python 2.7.11 bundled with numpy==1.11.1
- Python 3.5.2 bundled with numpy==1.14.5

This means testing has never been with any higher versions of numpy.  pr #420
only specifically deals with working around this issue, it includes no other
changes and Travis builds and tests are passing at the latest version with
numpy 1.15.1

This does push the numpy requirement from the user point of view up from
numpy>=1.10.4 to numpy>=1.11.2 unfortunately this must be done to ensure that
Travis is testing at the latest versions.

Successful Travis run for PR #420 https://travis-ci.org/blue-yonder/tsfresh/builds/421486714

**Comment by MaxBenChrist** [comment]
> Python 2.7.11 bundled with numpy==1.11.1
Python 3.5.2 bundled with numpy==1.14.5

Did not know that. Do you have an overview over which python package versions are used in travis?

**Comment by MaxBenChrist** [comment]
Agree with you @earthgecko, we have to diverse the numpy versions that we test on travis. 

So far, we always run our unit tests against the two year old 1.11.1. 

Not sure what the best way is, maybe combination of build stages and grepping the requierement.txt?

**Comment by MaxBenChrist** [comment]
> This does push the numpy requirement from the user point of view up from
numpy>=1.10.4 to numpy>=1.11.2 unfortunately this must be done to ensure that
Travis is testing at the latest versions.

I don't like that. I don't see an immanent need to update the user requirements.txt just so we properly run our tests on travis . I am sure we can do some grep magic in the pipeline ;):

**Comment by earthgecko** [comment]
@MaxBenChrist pr #429 now provides the above via 4 stages

![](https://s3.amazonaws.com/uploads.hipchat.com/523785/3447727/6WDSnKGG7Zcld6q/upload.png)

See https://travis-ci.org/blue-yonder/tsfresh/builds/424327053

**Comment by MaxBenChrist** [comment]
Great work @earthgecko, I think the build matrices are great addition to our test suite
