### ISSUE TITLE
SampleTauTestCase.test_ratio failing inconsistently

### ISSUE THREAD

**Issue by earthgecko** [blue-yonder/tsfresh#413]
The SampleTauTestCase.test_ratio test is failing inconsistently.  The self.assertTrue
was set at the new value of 0.002 introduced at https://github.com/blue-yonder/tsfresh/commit/a57a09fe62a62fe0d2564a056f7fd99f58822312 and this fails between 14 and 24
times in 100 in my testing.

Testing this at the original 0.001 value pre the above commit results in failure
between 46 and 61 times in 100 in my testing.
Further testing at 0.003, 0.004 and 0.005 all generate a decreasing amount of
errors.

Using the value of 0.006 seems to generate 0 errors on repeated tests of 100
iterations.

This test can be easily tested and reproduced with the following code:

```python
import numpy as np
from tsfresh.examples.driftbif_simulation import sample_tau

less_than_value = 0.002
# less_than_value = 0.003
# less_than_value = 0.004
# less_than_value = 0.005
# less_than_value = 0.006

count = 0
errors = 0
for i in range(100):
    count += 1
    tau = sample_tau(100000, ratio=0.4)
    sample = np.array(tau)
    before = np.sum(sample <= 1/0.3)
    beyond = np.sum(sample > 1/0.3)
    abs_value = abs(0.4 - float(before)/(before+beyond))
    if abs_value < less_than_value:
        print('%s - before - %s, beyond - %s, abs_value - %s' % (str(count), str(before), str(beyond), str(abs_value)))
    else:
        print('ERROR :: %s - before - %s, beyond - %s, abs_value - %s' % (str(count), str(before), str(beyond), str(abs_value)))
        errors += 1

print('%s errors in %s tests' % (str(errors), str(count)))
```

@nils-braun any thoughts here, as it stands now this test is going to fail ~14-22% of the time it seems.

**Comment by MaxBenChrist** [comment]
Verified this, great catch @earthgecko

**Comment by MaxBenChrist** [comment]
I ran it for 0.0006 for quite some iterations and no failed test
