### ISSUE TITLE
Understanding the column_id and features being generated

### ISSUE THREAD

**Issue by joel-wilson** [blue-yonder/tsfresh#416]
Hi All,

Recently got introduced to this package. Was excited because am working in heavy industries where we get lot of sensor data. I had 2 observations to share :

Note :  **THIS ISSUE IS NOT ABOUT ANY TECHNICAL BUGS**

1. I fail to understand the parameter "column_id" despite the examples and docs on the pages. Let's say I need to predict whether its going to rain or not using temperature and precipitations etc data at 5 sec interval.
` Time    Temp    Wind    Rain_or_Not`
` 00:00                    32         12        0`
` 05:00                    29         13       1`
so on. In this I have equivalent to `1 robot` as in example of tsfresh docs. So what would my `column_id` argument be ?

2. I do not see features like lag_5min, lag_1hr OR temp_max_at_lag_1hr etc kind features which are also intuitive in nature like `pH` 2 hours ago affects the mineral being produced now etc. I feel alongwith the existing features like absolute_energy and coeff etc, such lagged variables should also be generated. Let me know if they already are.

Thank you

**Comment by joel-wilson** [comment]
@earthgecko Woww! This was useful. Therefore how i was leveraging the package was not correct. Hmm

I converted my existing data into input1 and got a resultant output data with 6 rows(original 6 timeseries) and ~1000 columns for the tsfresh features.

What i am confused is how would this data be used for modelling now ? Like I want to predict the target for each hour of my test data. How will I get the model trained to do this  ? 
I have lost m "time" factor from the data now right.

**Comment by earthgecko** [comment]
Hi @joel-wilson yes playing with an example of your data set converted to a dataframe of:

```
	time	id	kind	value
0	00:00	1	Temp	32
1	00:00	2	Wind	12
2	00:00	3	Rain_or_Not	0
3	00:05	1	Temp	29
4	00:05	2	Wind	13
```

With lots of random data added for 2 hours results in features similar to:

```
variable	Rain_or_Not__abs_energy	Rain_or_Not__agg_autocorrelation__f_agg_"mean"	...	Wind__time_reversal_asymmetry_statistic__lag_1 ...
id																					
1	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	...	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN
2	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	...	0.435327	1.42688	-0.917015	0.0	0.0	0.0	0.0	0.0	6.555439	1.0
3	731.0	756.0	0.006065	0.009016	0.000659	1.0	0.0	0.0	0.0	1.0	...	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN	NaN

3 rows × 2382 columns
```

And yes you are correct, there is no time element in the extracted features, this is expected and there is not meant to be one.

As to your question relating predicting, please see the docs page on forecasting
https://tsfresh.readthedocs.io/en/latest/text/forecasting.html

Personally have not played with this aspect of tsfresh, so unfortunately I cannot
give you any additional advice in this regard.
