### ISSUE TITLE
get rid of pivoting on results chunks

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#417]
In 
https://github.com/blue-yonder/tsfresh/blob/ba8e3db386257f3156352deb8e8ff2ae3b379400/tsfresh/feature_extraction/extraction.py#L240

we use a pivot command to aggregate chunk results.

I want to profile this command and see if its a performance bottleneck. Maybe we can parallelize it. I am not sure if its not bloating up memory for bigger datasets

**Comment by nils-braun** [comment]
Fixed in #705
