### ISSUE TITLE
IndexingError: Unalignable boolean Series provided as indexer

### ISSUE THREAD

**Issue by zhanghaocore** [blue-yonder/tsfresh#422]
I have encountered an error: 
```
IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match
```
- Operating system: CentOS release 6.6 (Final)
- TSFESH VERSION: 0.11.0
- PYTHON VERSION: 3.0

- Where the error occurred: 
Path: /tsfresh/feature_selection/relevance.py
Line: 72
```
    # Calculate contingency table
     n_y1_x0 = sum(y[x == x0] == y1)
     n_y0_x0 = len(y[x == x0]) - n_y1_x0
     n_y1_x1 = sum(y[x == x1] == y1)
     n_y0_x1 = len(y[x == x1]) - n_y1_x1
```

- My own corrected code:
```
    # Calculate contingency table
    n_y1_x0 = sum(y[y.index.isin(x[x == x0].index.values)] == y1)
    n_y0_x0 = len(y[y.index.isin(x[x == x0].index.values)]) - n_y1_x0
    n_y1_x1 = sum(y[y.index.isin(x[x == x1].index.values)] == y1)
    n_y0_x1 = len(y[y.index.isin(x[x == x1].index.values)]) - n_y1_x1
```

**Comment by MaxBenChrist** [comment]
Hi @zhanghaocore, sorry for late answer. 

Can you elaborate a little bit why your solution is preferable over the existing implementation?

**Comment by zhanghaocore** [comment]
Thank you very much for your reply to my question.
I modified the code. Just to deal with the problem that the IDs of LABEL DATASET is more than unique IDs of the FEATURE FATASET. Because my data is too large, when to transform the data, it is easy to ignore the inclusion relationship between the two data sets. When the situation I mentioned was happening, TSFRESH did not give a friendly hint to help solve the problem. So I modified the code myself to solve the problem. In other words, TSFRESH checks the data before processing the data to ensure that the data passed in itself does not have the data errors I mentioned.

**Comment by MaxBenChrist** [comment]
> I modified the code. Just to deal with the problem that the IDs of LABEL DATASET is more than unique IDs of the FEATURE FATASET.

we make the (justified) assumption that target and time series container have exactly same ids. If the sets of the ids do not match, the extraction should fail. 

I will see if we have a warning for that inplace
