### ISSUE TITLE
Help reduce warnings/errors

### ISSUE THREAD

**Issue by jheffez** [blue-yonder/tsfresh#425]
I'm about to start a new project and would like to use tsfresh. I tried to experiment with the robots example with my current environment. It spited too many errors and warnings to list here. To the point where the desired output was lost in the warnings/errors and thus unusable.

I'm perfectly fine setting up a new environment, optimized for tsfresh. Can you please recommend the best configuration for a python environment to minimize the errors/warnings? What I'm looking for is the right python environment/package combination most compatible with tsfresh (with the least warnings/errors).

Using Windows 10/python 3.5 with latest tfresh, 0.11.
robots example: https://github.com/blue-yonder/tsfresh/blob/master/notebooks/robot_failure_example.ipynb

**Comment by earthgecko** [comment]
Hi @jheffez could you add the output from ``pip list`` here in terms of you current environment.

In terms of getting rid of deprecation warnings at less you could try a setup a specific Python virtualenv for tsfresh and from ``requirements.txt`` change all the '>=' to '==' to fix to lower version of the dependencies packages.  That will get rid of a lot of the deprecation warnings.  As for the errors you are encountering, please add the traceback/s here.  However I would imagine == on all the requirements would fix those too.

**Comment by MaxBenChrist** [comment]
Just configure a logger in your application and filter the warnings out
```
import logging
logging.basicConfig(format='%(levelname)s:%(message)s', level=logging.DEBUG)
```

**Comment by MaxBenChrist** [comment]
User gets a lot of 

C:\Users\user\py\36env\lib\site-packages\scipy\signal\spectral.py:1773: UserWarning: nperseg = 256 is greater than input length = 15, using nperseg = 15 .format(nperseg, input_length))

errors

**Comment by MaxBenChrist** [comment]
@jheffez can you confirm that this problem was window specific?
