### ISSUE TITLE
I use tsfresh to run on a cluster, but it runs slower than native multithreading.

### ISSUE THREAD

**Issue by zhanghaocore** [blue-yonder/tsfresh#428]
I use tsfresh to run on a cluster, but it runs slower than native multithreading. Is my way of using it wrong?

- Operating system: CentOS release 6.6 (Final)
- TSFESH VERSION: 0.11.0
- PYTHON VERSION: 3.6

```
from tsfresh.examples.robot_execution_failures import \
    download_robot_execution_failures, \
    load_robot_execution_failures
from tsfresh.feature_extraction import extract_features
from tsfresh.utilities.distribution import ClusterDaskDistributor

...

    Distributor = ClusterDaskDistributor(address="sheduler-host:8786")
    X = extract_features(df[['id', 'value', 'kind', 'time']], column_id="id", column_sort="time", column_kind='kind', column_value='value', distributor=Distributor)
```

**Comment by MaxBenChrist** [comment]
Its not a easy task to get any algorithm performant on a cluster. the runtime depends on so many factors, e.g. chunksize, size of time series, used features, connection speed between workers, number of dask workers/threads etc. 

Without detailed information about your dask cluster/your data at hand its hard to give you advice

**Comment by MaxBenChrist** [comment]
I close this.

@zhanghaocore If you can provide a detailed benchmark, information about your dask cluster and a detailed description of the problem, you can reopen this issue
