### ISSUE TITLE
Improve FAQ

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#43]
Add the following points to FAQ:

- PCA, why is it useful and which implementation to use
- Extraction and filtering is equal to filtered extraction
- How to save time by pickling calculated features
- How can I apply tsfresh to huge time series datasets ?

**Comment by mynameisvinn** [comment]
ill take a stab either way, but in my experience singular spectrum analysis (ssa) is more relevant than pca since we're dealing w time series data

**Comment by MaxBenChrist** [comment]
The PCA is not done on the time series Data points but on the normalized values of the features. You are r getting to a ssa on the time series aren't you?

**Comment by nils-braun** [comment]
tsfresh and the documentation has evolved a lot since this issue was created. I am closing because of this now. Makes no sense to keep this very old issue open.
