### ISSUE TITLE
future extraction

### ISSUE THREAD

**Issue by stepanm** [blue-yonder/tsfresh#440]
Hi! I'm extract relevant futures from my data with tsfresh, and get names best 5 futures.
Now i want extract futures from other set of data with getting 5 names. I do something like this.

```
in: FutureToExtract=tsfresh.feature_extraction.settings.from_columns(feature_names[:5])
Out:
{'InpayPCS': {'agg_linear_trend': [{'attr': 'intercept',
    'chunk_len': 50,
    'f_agg': 'mean'}],
  'fft_coefficient': [{'attr': 'real', 'coeff': 0}],
  'mean': None,
  'sum_values': None},
 'OutpayPCS': {'cwt_coefficients': [{'coeff': 9,
    'w': 2,
    'widths': (2, 5, 10, 20)}]}}

In:X = extract_features(XScaled, column_id='regnum', column_sort='regdate', kind_to_fc_parameters=FutureToExtract)
```
As i understand, this function extracting all futures,but I need extract only "FutureToExtract"
**How I can limit set of kind futures?**
I guess, i can modify FutureToExtract to set default_fc_parameters.
OS Windows 7
tsfresh 0.11.0

**Comment by MaxBenChrist** [comment]
Please read the documentation on https://tsfresh.readthedocs.io/en/latest/ its all explained there 

Or look at our collection of ipython notebooks
