### ISSUE TITLE
ar_coefficient feature: difference between calculated numer of coefficients and parameter k

### ISSUE THREAD

**Issue by dstum01** [blue-yonder/tsfresh#445]
Hi, 
probably there is some misunderstanding on my side:

When I extract the features by default settings I get

`ratio__ar_coefficient__k_10__coeff_0`
`ratio__ar_coefficient__k_10__coeff_1`
`ratio__ar_coefficient__k_10__coeff_2`
`ratio__ar_coefficient__k_10__coeff_3`
`ratio__ar_coefficient__k_10__coeff_4`

where k = 10 and `varphi_0`,..,`varphi_4` as parameters for the autoregressive AR(k) process given in the documentation where the feature `tsfresh.feature_extraction.feature_calculators.ar_coefficient(x,param)` was introduced.

To my mind, the calculation from the docs need to calculate the coefficients `varphi_0`,..,`varphi_10` to be consistent with `k = 10`. 

Is there any reason to skip these calculations?

Thank you for your work and support and best regards!

**Comment by nils-braun** [comment]
Oh damn it - this question got never answered :-(
Sorry! I guess it just slipped through... 2 years :-/

So no, there is no good reason to do this. Other than it was set like this.
I will change it to 10.
Thanks and again very sorry!
