### ISSUE TITLE
Feature Augamenter Pipeline "Transforming" on X and time_series_container inconvenient problem 

### ISSUE THREAD

**Issue by zhangruinan** [blue-yonder/tsfresh#446]
### Background: 
1. Your operating system: Ubuntu
2. The version of *tsfresh* that you are using: 0.11.0

My problem: 
I understand using timeseries_container as a custome for tsfresh in sklearn-style pipeline, but it has been causing some unnecessary problems:

### Problem 1
``` python
 def transform(self, X):
        """
        Add the features calculated using the timeseries_container and add them to the corresponding rows in the input
        pandas.DataFrame X.
        To save some computing time, you should only include those time serieses in the container, that you
        need. You can set the timeseries container with the method :func:`set_timeseries_container`.
        :param X: the DataFrame to which the calculated timeseries features will be added. This is *not* the
               dataframe with the timeseries itself.
        :type X: pandas.DataFrame
        :return: The input DataFrame, but with added features.
        :rtype: pandas.DataFrame
        """
        if self.timeseries_container is None:
            raise RuntimeError("You have to provide a time series using the set_timeseries_container function before.")

        # Extract only features for the IDs in X.index
        timeseries_container_X = restrict_input_to_index(self.timeseries_container, self.column_id, X.index)

        extracted_features = extract_features(timeseries_container_X,
```
Since the transforming function is really transforming on the 'time_series_container' selected only by X index, to generate proper output, I have to manually call set_time_series_container before I call transform. This cause me a headache when I put FeatureAugamenter into a pipeline or series of pipelines by FeatureUnion. At least seems to me, adding the time_series_container in the pipeline is unnecessary. 

```python
X = pd.merge(X, extracted_features, left_index=True, right_index=True, how="left")
```
The last line of the transforming function may cause users to lost rows and not realizing what is really causing the problem when X_index and time_series_container's index is incoherent. As I was said, I highly recommand the transforming function to directly transform on X instead of tiem_series_container.

### Another Suggestion.
 Since indexes are filtered, only X as Dataframe is supported. I highly suggest transforming function support numpy.array as well. This with make the pipeline more adaptable when chaining with other pipelines. 

Thanks

**Comment by MaxBenChrist** [comment]
> I have to manually call set_time_series_container before I call transform.

yes, for good reasons

The reason why we have the `time_series_container` is for situations where features `X` are already given by another source. Like the combinations of feature pipelines that you described. As far as I know, you can only pass one `X` object in a sklearn pipeline. That `X` is the feature matrix. That `X` should not be the time series container. Letting `X` be the time series container breaks the API of the sklearn pipeline. 

After we decided that we need a new object, the time series container, we have two options, either we add an argument to the transform function (like here https://stackoverflow.com/questions/35632634/how-to-pass-a-parameter-to-only-one-part-of-a-pipeline-object-in-scikit-learn) or we add a dedicated method to set the time series container. we went with the second option. 

Again if you have a better idea for this API, I happily review a pr on that topic.  

> The last line of the transforming function may cause users to lost rows and not realising what is really causing the problem when X_index and time_series_container's index is incoherent.

Agree, maybe we can add a big warning if rows are dropped.

>  I highly suggest transforming function support numpy.array as well. This with make the pipeline more adaptable when chaining with other pipelines.

Can you give me an example? I was never in a situation where I needed the ndarray support that badly.

**Comment by nils-braun** [comment]
Seems this issue is stalled. Closing now.
