### ISSUE TITLE
`settings.from_columns` cannot recover the correct data type for 'kind' values

### ISSUE THREAD

**Issue by Mithrillion** [blue-yonder/tsfresh#452]
OS: Ubuntu 18.04
Python version: 3.7
tsfresh version: 0.11.1

This is more of a limitation of the current code than a bug. The `settings.from_columns()` function is supposed to save the feature extraction / selection results so it can be reused later. It works by parsing the column names of the extracted dataframes. An unfortunate side effect of this is that when used with the 'long' format time series input, the typing information about  the 'kind' column is lost. For example, even if the 'kind' values are in int32, in the resulting settings dict, the type of the top level keys (representing different kind values) will be str, and when the dict is used as `kind_to_fc_parameters`, in the following lines in extraction.py:
``` python
if kind_to_fc_parameters and kind in kind_to_fc_parameters:
        fc_parameters = kind_to_fc_parameters[kind]
```
The code will fail to find any matching keys, and the extractor will use default settings instead. The following code illustrates this issue:
``` python
import numpy as np
import pandas as pd
from tsfresh import extract_features, select_features
from tsfresh.feature_extraction import settings

# note that 'kind' is int type
mock_ts = pd.DataFrame({'id': [1,1,1,1,2,2,2,2,3,3,3,3],
                        'time': [1,1,2,2,1,1,2,2,1,1,2,2],
                        'kind': [1,2,1,2,1,2,1,2,1,2,1,2],
                        'value': [1,2,3,4,2,3,4,5,3,4,5,6]})

features = extract_features(mock_ts, column_id='id', column_sort='time', 
                            column_kind='kind', column_value='value')
# select 50 features from each kind
selected_features = features.columns[list(range(50)) + list(range(794, 794 + 50))]
sample_settings = settings.from_columns(selected_features)
fixed_settings = {int(k): v for k, v in sample_settings.items()}

features_small = extract_features(mock_ts, column_id='id', column_sort='time', 
                                  column_kind='kind', column_value='value',
                                  kind_to_fc_parameters=sample_settings)
features_small_2 = extract_features(mock_ts, column_id='id', column_sort='time', 
                                  column_kind='kind', column_value='value',
                                  kind_to_fc_parameters=fixed_settings)
# pass
assert features_small_2.shape[1] == 100
# fail
assert features_small.shape[1] == 100
```

This problem can be circumvented by converting all 'kind' columns to str type beforehand or manually fixing the type of keys in the settings dict afterwards. However, since the same code is used for the RelevantFeatureAugmenter class, which does not have an exposed settings object, it can cause unexpected behaviours when used as a transformer, e.g. applying a trained model with feature selection on a test set. I think to fix this issue, some changes might have to be made on how extraction features are stored. Maybe internally, extraction settings should be stored as an object with intact typing instead of just as column names?

**Comment by MaxBenChrist** [comment]
Great bug report @Mithrillion. Thank you for it.

I have a half finished pr that I will finish this week that will fix this. I went with casting the kind column as a string. Then it is okay that the kind column in the kind_to_fc_parameters dictionary is parsed as string

**Comment by MaxBenChrist** [comment]
Alright, is fixed on current master, thanks again for reporting
