### ISSUE TITLE
Provide time series chunker

### ISSUE THREAD

**Issue by jeffneuen** [blue-yonder/tsfresh#453]
This falls under the "question" category, but I was asked to post this here instead of in the chat room.

I have a time series that is approximately 7M rows, with one observation (float or decimal) per timestamp. It looks like this:

2010-01-01 00:00:00 1000.10
2010-01-01 00:01:00 1500.10
2010-10-01 00:02:00 2000.10
... 

I am attempting to process it with the EfficientFCParameters parameter set. I am unfortunately running out of memory on a workstation with 128G. I ran the set one time in a cloud instance just to see how much RAM it would need to complete, and it took a little over 500G. This is too expensive to do on a regular basis, however. So, my idea was to split up the computation and paste the features back together manually. I made some efforts to do this with dask on my workstation, but wasn't successful, and I'm not sure if that is the proper way to attack this problem, although perhaps it is, based on this comment: (https://github.com/blue-yonder/tsfresh/issues/385#issuecomment-396032224)

Here is the code for my manual splitting, along with some of the output from each line for a smaller test data set. As you can see, when it is supposed to be chunking, it does almost the same number of iterations as the attempt to process the whole set in one shot. I think that perhaps I'm approaching the chunking wrong.

I'm running linux, with a recent pull of tsfresh from master.

``` python
from tsfresh import extract_features 
from tsfresh.feature_extraction.settings import MinimalFCParameters, EfficientFCParameters
from tsfresh.utilities.dataframe_functions import make_forecasting_frame

def chunkify(lst,n):
    return [ lst[i::n] for i in range(n) ]

np.shape(green_small)
(12961,)

df_shift_small, y_small = make_forecasting_frame(green_small, kind="price", max_timeshift=10, rolling_direction=1)

#attempt to process in chunks
for chunk in chunkify(df_shift_small, 10):
    print(str(len(chunk)))
    print(str(len(df_shift_small)))
    X = extract_features(chunk, column_id="id", column_sort="time", column_value="value", impute_function=impute,
                     show_warnings=False, disable_progressbar=False, n_jobs=40,chunksize = 1,default_fc_parameters=EfficientFCParameters())

12956
129555
Feature Extraction
100% 12956/12956 [00:37<00:00, 348.05it/s]
...
12955
129555
Feature Extraction
100% 12955/12955 [00:38<00:00, 336.04it/s]
... (10x repetitions total for the loop)

#attempt to process all in one pass
X = extract_features(df_shift_small, column_id="id", column_sort="time", column_value="value", impute_function=impute,
                     show_warnings=False, disable_progressbar=False, n_jobs=40,chunksize = 1,default_fc_parameters=EfficientFCParameters())
Feature Extraction
100% 12960/12960 [00:51<00:00, 251.14it/s]
```

Any thoughts on whether I'm approaching this in a reasonable way, or whether I should go back and spend more time on the dask approach (even though I only have a single workstation), would be appreciated.

Thanks.

**Comment by jeffneuen** [comment]
Is there anything else that I could provide to help make this question better? Would it help if I uploaded the green_small dataset to an s3 bucket or something?

**Comment by MaxBenChrist** [comment]
Sorry for the late response. You will have to chunk your dataframe outside of tsfresh and then run tsfresh on the chunks.

> Python
#attempt to process in chunks
for chunk in chunkify(df_shift_small, 10):
    print(str(len(chunk)))
    print(str(len(df_shift_small)))
    X = extract_features(chunk, column_id="id", column_sort="time", column_value="value", impute_function=impute,
                     show_warnings=False, disable_progressbar=False, n_jobs=40,chunksize = 1,default_fc_parameters=EfficientFCParameters())

**Comment by jeffneuen** [comment]
Thanks for your reply. I don't think I understand though. I only have one time series. I am just trying to split it into x number of chunks, outside of tsfresh, and then run tsfresh on each chunk. 

In theory my sample code should also be writing X to someplace else for later concatenation. Even with my sample code though, I don't understand why it would take 10x longer to process via chunks than in one shot. Are you saying that the chunkify function that I have defined isn't splitting up the single time series properly?

**Comment by MaxBenChrist** [comment]
> In theory my sample code should also be writing X to someplace else for later concatenation. Even with my sample code though, I don't understand why it would take 10x longer to process via chunks than in one shot. Are you saying that the chunkify function that I have defined isn't splitting up the single time series properly?

Yes. Please read my example carefully, you are not splitting by time series. You split by values which means that the time series get separated into chunks, thus you calculate the wrong features not on your original time series but parts of them

**Comment by jeffneuen** [comment]
I * think* I understand what. you mean now. I did some work on a new chunker, and still don't have it quite working, but if I'm understanding you correctly, the chunker would need to look something like the below code, which does run, but still outputs tuples instead of data frames.

```
def super_chunkify(df, n):
    tuple_of_tuples = []
    current_chunk = []
    i = 0
    for item in df.groupby(['id', 'kind']):
        current_chunk.append(item)
        i = i + 1
        if i > n-1:
            tuple_of_tuples.append(current_chunk)
            current_chunk = []
            i=0
    tuple_of_tuples.append(current_chunk)
    return tuple_of_tuples
```

Does this look like the right track to you? If so I'll see if I can get the tuple of tuples to convert to a list or tuple of dataframes, and that may provide a working if inelegant solution.

**Comment by mmann1123** [comment]
I have been trying to see if dask dataframes would work in this context. In particular using many csv files stored locally, for instance dd_df = dd.read_csv('./datachunk*.csv'). This would be the ideal solution, but so far no luck. Does anyone know if dask dataframes are supported?

**Comment by nils-braun** [comment]
I published a blog post on these problems: how to extract features with dask or spark and how to do it chunk by chunk. Things got a bit easier in the most recent tsfresh version (0.15.1). Please find it here: https://nils-braun.github.io/tsfresh-on-cluster-2/
That should hopefully solve your problems.
