### ISSUE TITLE
AssertionError with latest code

### ISSUE THREAD

**Issue by jheffez** [blue-yonder/tsfresh#454]
After running: pip install -U git+https://github.com/blue-yonder/tsfresh
I get the error below. If I uninstall and put the 'normal' version (pip install tsfresh) the error goes away. I have one label (0/1). 
Using windows10/python 3.6.6/pip.

``` python
AssertionError                            Traceback (most recent call last)
<timed exec> in <module>

c:\users\userx\py\36env\lib\site-packages\tsfresh\convenience\relevant_extraction.py in extract_relevant_features(timeseries_container, y, X, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, show_warnings, disable_progressbar, profile, profiling_filename, profiling_sorting, test_for_binary_target_binary_feature, test_for_binary_target_real_feature, test_for_real_target_binary_feature, test_for_real_target_real_feature, fdr_level, hypotheses_independent, n_jobs, chunksize, ml_task)
    135     """
    136 
--> 137     assert isinstance(y, pd.Series)
    138     assert len(set(y)) > 1, "Feature selection is only possible if more than 1 label/class is provided"
    139 

AssertionError:
```

**Comment by nils-braun** [comment]
Thanks for the info. Can you maybe provide an example how you apply tsfresh?

**Comment by MaxBenChrist** [comment]
Just to make sure, it fails during the installation or when you run a feature selection?

**Comment by jheffez** [comment]
Install goes fine. It's when I run feature selection. 
I can't recall now but I think it also failed on linux (centos).

**Comment by MaxBenChrist** [comment]
Ok. your target column only contains one class, there is no feature selection possible. Exactly as the error messages states

**Comment by jheffez** [comment]
I don't understand the reasoning.
Yes  it contains 1 column but with two classes: True and False.
In addition, the current version 11.1 works as expected without errors.
Can you please clarify?

**Comment by MaxBenChrist** [comment]
Sorry I overread that you installed from master, will have to look into that

**Comment by MaxBenChrist** [comment]
The error was thrown because you did not pass a pandas Series as your target vector, will improve the error message

**Comment by jheffez** [comment]
Thanks Max. Will give it a run.
