### ISSUE TITLE
extract_features getting stuck at 0%

### ISSUE THREAD

**Issue by ricardovvargas** [blue-yonder/tsfresh#456]
Hi, 

I'm facing a issue similar to described in #193, #400 and in #402 . The 'extract_features' always get stuck at 0% but I believe that none of what have been said in those issues apply in my case:

- The dataset is not big;
- I believe that all parameters are set ok;
- I using MinimalFCParameters;
- I using the current vers ion of tsfresh.

My environment is composed of:

- OS X El Capitan (10.11.6)
- Intel Core i5 2.8GHz 8GB
- Python 3.6.5
- Spyder 3.3.1
- tsfresh 0.11.1

To reproduce this issue, please use the attached file (data + code). Note that the 'extract_relevant_features' seems to be executed ok but 'sett' ends with a strange key named 'Unnamed: 0'. Is this key expected in any case?

Please, let me know if I can do anything else to help resolve this issue.

I'll appreciate for any help.

[issue_with_extract_features.zip](https://github.com/blue-yonder/tsfresh/files/2531721/issue_with_extract_features.zip)

**Comment by ricardovvargas** [comment]
One important thing to be mentioned is that if one uses the following code ('extract_features' with df_train) insted of 'extract_relevant_features' with df_train, the 'extract_features' with df_test works just fine (and very fast).

X_train_sel = extract_features(df_train, column_id='id', column_sort='timestamp', default_fc_parameters=MinimalFCParameters(), n_jobs=0)

So maybe the origin of this problem is inside the 'extract_relevant_features'.

**Comment by ricardovvargas** [comment]
I figured out the origin of the key named 'Unnamed: 0'. I've forgotten to set index_col parameter on the pd.read_csv command. But the second 'extract_features' still gets stucked at 0%. To reproduce this issue, please use the new version of the script.

[issue_with_extract_features_v2.py.zip](https://github.com/blue-yonder/tsfresh/files/2531968/issue_with_extract_features_v2.py.zip)

I'll appreciate for any help.

**Comment by delyanr** [comment]
Hi,

The problem could be due to multiprocessing. Not sure about OS X, but in Windows you definitely need to have your code encapsulated by the infamous `if __name__ == '__main__':` statement. Please do search around the issues - I'm sure it has been discussed before.

Also for more info: [multiprocessing docs](https://docs.python.org/3.6/library/multiprocessing.html?highlight=process#multiprocessing-programming)

Hope this helps!

**Comment by MaxBenChrist** [comment]
Can you run some of the examplary notebooks?

**Comment by MaxBenChrist** [comment]
> The problem could be due to multiprocessing. Not sure about OS X, but in Windows you definitely need to have your code encapsulated by the infamous if __name__ == '__main__': statement. Please do search around the issues - I'm sure it has been discussed before.

The name guard should only be necessary on window, OP is running mac os. However, I have also see the mac os multiprocessing library doing weird things sometimes.

Can you provide a datasample, @ricardovvargas. Your script looks fine

**Comment by ricardovvargas** [comment]
> The problem could be due to multiprocessing. Not sure about OS X, but in Windows you definitely need to have your code encapsulated by the infamous `if __name__ == '__main__':` statement. Please do search around the issues - I'm sure it has been discussed before.

@delyanr, I've heard around about what you've said but I am using OS X.

> Can you provide a datasample, @ricardovvargas. Your script looks fine

@MaxBenChrist, a dasample is already in [issue_with_extract_features.zip](https://github.com/blue-yonder/tsfresh/files/2531968/issue_with_extract_features_v2.py.zip). There is also a .py in this .zip but please use the [issue_with_extract_features_v2.py.zip](https://github.com/blue-yonder/tsfresh/files/2531968/issue_with_extract_features_v2.py.zip)

I'll appreciate for any help.

**Comment by delyanr** [comment]
Hi,

I finally got round to testing your code on my machine, and it wasn't working out of the box. I had to change:

`y_train = np.loadtxt('y_train.txt')`

to

`y_train = pd.Series(np.loadtxt('y_train.txt'), index=df_train.id.unique())`

Quite weird that you don't get an error. Could you try again with the above?

Also note that the `extract_relevant_features()` method will probably infer this as regression, and as far as I can see this should be a classification problem.

**Comment by ricardovvargas** [comment]
Hi. Thanks for your help @delyanr.

Yes, with this y_train the 'extract_relevant_features' infers it is a regression task. My falt. I have to use the 'ml_task' parameter. Thanks.

With 'y_train = np.loadtxt('y_train.txt')', y_train is a numpy.ndarray and the﻿'extract_relevant_features' works fine and fast (1 or 2 secs) without any error. I've checked the documentation and it is said that 'extract_relevant_features' expects y only as a pandas.Series. So I think that the documentation and the code are not compatible. In any case, I added the cast like you suggested. I think that I used a numpy.ndarray because the documentation says that 'select_features' accept y as pandas.Series or numpy.ndarray.

Below is the new code and something is still bad/weird.

- Execution of only the cells 1+3+4 works fine without any error or warning in just 2 ou 3 secs.
- Execution of only the cells 1+2+4 is very slow (hours). Cells 1 and 2 are executed fast. Why the execution of the cell 4 is so slow? Is the X_train_sel returned by extract_features different of the X_train_sel returned by ﻿extract_relevant_features?

[issue_with_extract_features_v3.txt](https://github.com/blue-yonder/tsfresh/files/2558686/issue_with_extract_features_v3.txt)

I'll appreciate for any help.

**Comment by delyanr** [comment]
Hi. You need to be careful when you use the `kind_to_fc_parameters` argument. It basically tells `extract_features()` method which features to extract for specific columns, but tells it nothing about the other columns. In fact, `extract_features()` still uses `default_fc_parameters `argument for those other columns. Therefore, you need to add `default_fc_parameters=None` in cell 4 to tell the method to ignore them.

**Comment by ricardovvargas** [comment]
Hi, @delyanr. Thanks for your advice. I'm been careful :)) I've check the documentation and I'm using the [perform-PCA-on-extracted-features.ipynb ](https://github.com/blue-yonder/tsfresh/blob/master/notebooks/perform-PCA-on-extracted-features.ipynb) as example. I'm still having problems :((

Maybe you didn't understand this issue right.

1. As the df_train and df_test have exacly the same columns and I am using the function ``from_columns``, there is no 'other columns' to be worried about;
1. My sett dict is always ok. If cell 3 is used (insted of cell 2), sett has 64 features and the cell 4 is computed fastly. If cell 2 is used (insted of cell 3), sett has 24 features (exacly a subset of the 64 features) and the cell 4 is computed VERY slowly. **That is the real issue here!!!**;
1. Using ``default_fc_parameters=None`` as parameter of ``extract_features()`` causes no effect because the default value of ``default_fc_parameters`` is already None. Am I right? By the way, this parameter is not set in the example.

Anyway, could you or anybody else please execute the code with the datasample to try find out what is wrong. It seems to be a weird bug.

I take this opportunity to raise another correlated issue. The documentation of the `from_columns` says that the 'columns' has to be a list of str. [Here](https://github.com/blue-yonder/tsfresh/blob/master/notebooks/perform-PCA-on-extracted-features.ipynb) it is used ``X_train_filtered.columns``, an Index and [here](https://tsfresh.readthedocs.io/en/latest/text/feature_extraction_settings.html?highlight=from_columns) it is used ``X_tsfresh_filtered``,  a Dataframe. I tryed to cast my `X_train_sel` with `list()` but this did not help. Maybe this is just a case of outdated documentation. What you guys think?

**Comment by delyanr** [comment]
Hi. Apologies - I see that I made a typo. What I meant to say is that you need to pass `default_fc_parameters={}`. This is because when you pass `None`, the `extract_features()` module defaults to the `ComprehensiveFCParameters()` settings. And in fact, there are "other columns" as per my previous post, as the `from_columns()` method only extracts features for 5 columns, leaving the other 5 columns to use the `ComprehensiveFCParameters()` settings (to check this simply type `sett.keys()` in your console). This is the reason execution is slow!

Regarding your correlated issue above, this is not a problem with the documentation per se. The Pythonic way of handling these things is to allow everything that behaves like "list of str" to be passed as argument (google "duck typing" and "goose typing" for more information). You can think about it as if Python automatically converts all objects that behave as "list of str" to "list of str". So the pd.Index object of the pandas.DataFrame is in fact one such object; more surprisingly in some circumstances so is the actual pandas.DataFrame object.

Hope this helps.

**Comment by ricardovvargas** [comment]
Hi @delyanr. Thanks a lot for your help!!! Now my script is working as expected.

I believe that now I understand IN THEORY the root cause of the slowness in execution of cell 4. As ``default_fc_parameters`` is not set, ``ComprehensiveFCParameters()`` that is more expensive is used. When ``default_fc_parameters={}`` is set, only the features in ``X_train_sel`` is used. Ok, but IN PRACTICE I still don't fully understand why the execution of cells 1+3+4 is fast while the execution of cells 1+2+4 is VERY slow. In both ``default_fc_parameters`` is not passed in cell 4. The slowness should be observed in both cases. 

In my opinion, the documentation is not clear about the needing to pass ``default_fc_parameters`` when ``kind_to_fc_parameters`` is used and ``ComprehensiveFCParameters()`` is not wanted. Actually [this](https://github.com/blue-yonder/tsfresh/blob/master/notebooks/perform-PCA-on-extracted-features.ipynb) example uses MinimalFCParameters(), don't set ``default_fc_parameters={}`` and `X_test_filtered` has 24 columns just like `X_train_filtered`. So it seems that ``ComprehensiveFCParameters()`` was not used. I am confused.

Thank you for your clarification about "list of str". In this situation I would expect something more generic like "array_like" but I am just a Python apprentice (including its taxonomy), so ... :-))

**Comment by HaithamHassanMahmoud** [comment]
I still have an error 

I am trying to use tsfresh feature extraction library in python 3.7.1 using efficient parameters with a test file (24 rows x 366 columns)

it never stops and keeps processing and i tried to run same library on a different laptop with installed python 2.17.16 but the tsfresh library did not work.

kindly help me of what should i do?


![image](https://user-images.githubusercontent.com/55799229/65610642-8c6e0b80-dfa9-11e9-93e4-91a8e02eebe7.png)

![image](https://user-images.githubusercontent.com/55799229/65610687-9859cd80-dfa9-11e9-81a4-30696478b546.png)
`from matplotlib import pyplot as plt
from matplotlib import style
import numpy as np
import pandas as pd

style.use('ggplot')


#from tsfresh import extract_features #as tsfreshobj
#from tsfresh import MinimalFeatureExtractionSettings
from tsfresh.feature_extraction import extract_features, EfficientFCParameters 
#X = extract_features(df, column_id='id', column_sort='time')
y=pd.read_csv ('1.csv')#, skiprows=1)

#y=np.loadtxt('T7_2.csv')#, 
             #unpack=True,
            # delimiter=',')
#y1=tsfreshobj.feature_extraction.extraction.generate_data_chunk_format(y)
#y2=tsfreshobj.feature_extraction.feature_calculators.absolute_sum_of_changes(y1)
#y1=extract_features(y, feature_extraction_settings=MinimalFeatureExtractionSettings)
print (y)

# from tsfresh.feature_extraction import MinimalFeatureExtractionSettings
y1=extract_features(y, column_id='time', default_fc_parameters=EfficientFCParameters())#, column_sort='time')
print (y)
print (y1)
plt.plot(y1)

print (y)
plt.title ('some numbers')
plt.ylabel('Y axis')
plt.xlabel ('X axis')


plt.show()     
`

**Comment by HARproject2020** [comment]
I have changed version of the tsfresh to 0.10 and it worked.

**Comment by e5k** [comment]
Just want to add my problem/fix. Took me some time to figure it out - just hope it can help:

### Problem
- Tried to install `tsfresh` in a Conda environment using `pip`
- Install worked but resulted in this error - i.e. feature extraction not starting
- `conda install -c Conda-forge tsfresh` returned some weird permission errors. `sudo` works, but it kept either retrieving wrong version or saying that package was already installed whereas it was not

### Fix
- Manually downloaded selected version from [Conda](https://anaconda.org/conda-forge/tsfresh/files)
- Installed using `conda install --offline path/to/file.bz2`
