### ISSUE TITLE
How to engineer features datetime ?

### ISSUE THREAD

**Issue by truongtamgio** [blue-yonder/tsfresh#464]
Hi,
How to engineer
Featuretools lib has Datetime Transform Primitives (    Second    Minute    Weekday    Weekend    Hour    Day    Week    Month    Year) which to engineer datetime feature. So, I wonder Tsfresh can do that ? If not, how to implement them to Tsfresh ? How to combine Tsfresh and featuretools ?

For example:

```
 index
 2014-05-05
```

engineer feature to : 

```
 Year            Month         Day
2014             05              05
```

Thank you !

**Comment by MaxBenChrist** [comment]
so far, we expect the input time series to contain numerical values (like floats, integers etc.). You want to pass timestamps into the feature extraction, which is a type of object that we do not support yet.

**Comment by MaxBenChrist** [comment]
Actually, we are working on index based feature calculators at the moment, see https://github.com/blue-yonder/tsfresh/pull/495

In what kind of features are you interested?

**Comment by nils-braun** [comment]
Seems this issue is stalled and there was no answer from OP. Closing now.
