### ISSUE TITLE
segmentation or windowing 

### ISSUE THREAD

**Issue by ghayth82** [blue-yonder/tsfresh#466]
I am working on raw accelerometer data and I am wondering what is the way to do segmentation or windowing of the raw data ( preprocessing data by segmentation or windowing )?
I am looking for something like this 

 https://dsp-nbsphinx.readthedocs.io/en/nbsphinx-experiment/spectral_analysis_deterministic_signals/window_functions.html

http://halim.readismed.com/2014/05/21/activity-identification-using-body-mounted-sensors-a-review-of-classification-techniques/

**Comment by MaxBenChrist** [comment]
tsfresh does not deal with preprocessing data., we map the time series into features.
