### ISSUE TITLE
roll_time_series problem

### ISSUE THREAD

**Issue by de-shui** [blue-yonder/tsfresh#467]
SOS.
The task I'm working on is hard drive failure detection.
For instance, I have 2 hard drives. One good, one broken. Let's say label 1 indicates failure while 0 indicates good.

If I call the time_series function separately according to the 2 drives, the time series I get will always be from a single certain drive and the label will always be 1 or 0. This is not OK, since when you tired to extract features more than one labels are needed.
However, when I tried to it together, there is a problem too.
![image](https://user-images.githubusercontent.com/40778840/49274765-56a8e500-f4b4-11e8-8d02-46459067d0a2.png)
As you can see above, the first time series contains 2 rows but has 2 label values because the 2 rows come from 2 different drives.This doesn't make sense because when you  extract features from the 2 rows ,they should come from one single drive.
Help. Thank you.
ps. My English is not very good so I'm sorry if I didn't explain it clearly.

**Comment by MaxBenChrist** [comment]
For every hard disk you should have multiple time series (one from each sensor) and I guess one label (either the hard drive is ok or not). 

Every harddrive will correspond to one row in the feature matrix. Does this help you?

**Comment by nils-braun** [comment]
Seems this issue is stalled and there was no answer from OP. Closing now.
