### ISSUE TITLE
Add to FAQ: Comparing tsfresh to other feature extraction and selection methods

### ISSUE THREAD

**Issue by ronikass** [blue-yonder/tsfresh#47]
Hi,

I reviewed the documentation. There are 2 main things in tsfresh:
1. Feature extraction (I saw you have a rather long list of features you create)
2. Feature filtering
 
I have some general questions:
1. What is unique about the feature filtering ? for example, let's say I want to use the features for classification. Can't I just take all the features to an information.gain software (like FSelector in R), it will tell me how good/bad each feature is, based on information gain, and by this way to use the feature ?
2. You have a long list of features, from your experience, how much is left after feature filtering ?  I know it is  a very general question, and it is very time series specific, but I wonder, from your experience, the typical filtering.
3. What is the "smart thing" about the tsfresh solution ? Is it new features, new filtering method, combo, please epxlain ?       
4. Any other insights you can provide on the algorithm Vs. other feature extraction and feature importance algorithms (RF,information.gain, …)

**Comment by MaxBenChrist** [comment]
Good questions:

> 1. What is unique about the feature filtering ? for example, let's say I want to use the features for classification. Can't I just take all the features to an information.gain software (like FSelector in R), it will tell me how good/bad each feature is, based on information gain, and by this way to use the feature ?

Its based on classical statistical hypothesis tests and a multiple test procedure. This means that the percentage of irrelevant among the extracted features will be asymptotically controlled by the filtering. 
Basically we take vintage statistical methods to solve a machine learning problem.

Most other feature selection algorithms such as the Boruta do not give you any insights in how many good or bad features they filter out. Often the algorithms "just work". With FRESH it is different. There are some more important points, just look in the paper for more details.

> 2. You have a long list of features, from your experience, how much is left after feature filtering ? I know it is a very general question, and it is very time series specific, but I wonder, from your experience, the typical filtering.

From our experience the selected features are often a mixture between basic features (mean, median) and very specialized features such as certain wavelet coefficient. The selection highly depends on the domain though. There is now "almighty feature"

> 3. What is the "smart thing" about the tsfresh solution ? Is it new features, new filtering method, combo, please epxlain ?

Are you referring to the package or the paper?

**Comment by MaxBenChrist** [comment]
Does this answers your questions?

**Comment by ronikass** [comment]
I want to know if this statement is accurate: "The features created are kind of standard typical time series features. The main innovation is the feature filtering process"

**Comment by ronikass** [comment]
Second question: I have a time series of length 1,000. Should/Can I create features for entire length and also features for half length, and also features for 0.25 length and then run filtering, or just to run on entire length ?

**Comment by MaxBenChrist** [comment]
Regarding your first question: the only oder Package i know of that automatically extracts time series features is the hctsa package by Ben fulcher (it is written in matlab) so the collection of feature extractions methods in Tsfresh is also unique!

**Comment by MaxBenChrist** [comment]
for the second question. Yes you can use Tsfresh with pandas resampling method for that

**Comment by ronikass** [comment]
Did anyone try and port tfresh to R or C#. I assume there are 2 main efforts, the feature extraction (tens of features, some are just 1 function in R, some maybe more problematic.) and feature filter algorithm.

I would like to try and port to R. Where can I see a very small time series, that shows the value for each feature (before feature filtering, so we can benchmark the port to R of filter extraction.

Then I need a few diffrent printouts, during the feature filter process

**Comment by MaxBenChrist** [comment]
It would be quite straightforward to port the feature filtering to R. 

However, it will not be trivial to port the feature calculation as some feature calculators depends on  libraries (numpy, scipy and so on) that use fortran / C code. Instead you could use the upcoming csv standalone script to extract the features and then just load them to R

**Comment by ronikass** [comment]
Maybe not trivial bit the way to go, as csv is very limited, especially in big data, but runs, multi process and so onSo I need a time series and output for each feature                                                                                                                                                                        Sent from my BlackBerry - the most secure mobile device                                                                                                                                        Original Message                                                                                                                                                                                                                                                            Show Details                                                                                                                                                                           From: notifications@github.comSent: November 9, 2016 11:06 AMTo: tsfresh@noreply.github.comReply-to: reply@reply.github.comCc: kassroni@gmail.com; author@noreply.github.comSubject: Re: [blue-yonder/tsfresh] Add to FAQ: Comparing tsfresh to other feature extraction and selection methods (#47)  It would be quite straightforward to port the feature filtering to R. 

However, it will not be trivial to port the feature calculation as some feature calculators depends on  libraries (numpy, scipy and so on) that use fortran / C code. Instead you could use the upcoming csv standalone script to extract the features and then just load them to R

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ronikass** [comment]
So, it is possible to get a list of all features with the output of each feature , with a sample time series ?
The time sries should be as SHORT as possible, for easy debug, could even be random numbers

**Comment by MaxBenChrist** [comment]
Just have a look at the documentation, all the features are documented there:

http://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html

**Comment by ronikass** [comment]
I am fully aware of this link, however, I am R user, not python (don't even have python), so this is why I need a time series (can be even 50 random numbers), which are ran against the features, and then the results should be sent as a text file, for benchmark, should take 5 seconds for you to make.

The I can take the time series, start developing each feature in R, and make sure I get same result as python benchmark, this is how professional robust  porting is done.

Once features are finished, then we do same process for feature filtering

**Comment by rahardikaku** [comment]
Does features filtering also work in one class data ? Assume i want to create One Class Classifier Model and there are only positive sample training data.

Regards

**Comment by MaxBenChrist** [comment]
> Does features filtering also work in one class data ? Assume i want to create One Class Classifier Model and there are only positive sample training data.

No, you need instances from two classes to properly decide about the discriminative power of individual features.
