### ISSUE TITLE
im trying to select a subset of features to calculate, am getting syntax error

### ISSUE THREAD

**Issue by knar974** [blue-yonder/tsfresh#475]
Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system
2. The version of *tsfresh* that you are using
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
4. A minimal code snippet which reproduces the problem/bug
5. Any reported errors or traceback

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by knar974** [comment]
1. rhel
2. 0.11.0
3. Anaconda 3.6
Am trying to select a subset of features to calculate and get the following error is there a fix?:

from tsfresh.feature_extraction import settings
from tsfresh import extract_features
from tsfresh.utilities.dataframe_functions import impute
selected_features = train_features.columns
sample_settings = settings.from_columns(selected_features[2:])

File "/opt/data/anaconda/Anaconda/envs/nkenv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-23-a069d48d6ecc>", line 5, in <module>
    sample_settings = settings.from_columns(selected_features[2:])

  File "/opt/data/anaconda/Anaconda/envs/nkenv/lib/python3.6/site-packages/tsfresh/feature_extraction/settings.py", line 69, in from_columns
    config = get_config_from_string(parts)

  File "/opt/data/anaconda/Anaconda/envs/nkenv/lib/python3.6/site-packages/tsfresh/utilities/string_manipulation.py", line 42, in get_config_from_string
    dict_if_configs[key] = ast.literal_eval(value)

  File "/opt/data/anaconda/Anaconda/envs/nkenv/lib/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')

  File "/opt/data/anaconda/Anaconda/envs/nkenv/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)

  File "<unknown>", line 1
    .mean.
    ^
SyntaxError: invalid syntax

#the features 
print(selected_features[2:].tolist())
['value__ar_coefficient__k_10__coeff_2', 'value__ar_coefficient__k_10__coeff_4', 'value__binned_entropy__max_bins_10', 'value__change_quantiles__f_agg_.mean.__isabs_True__qh_0.6__ql_0.0', 'value__change_quantiles__f_agg_.mean.__isabs_True__qh_0.6__ql_0.2', 'value__change_quantiles__f_agg_.mean.__isabs_True__qh_0.6__ql_0.4', 'value__change_quantiles__f_agg_.mean.__isabs_True__qh_0.8__ql_0.4', 'value__change_quantiles__f_agg_.var.__isabs_False__qh_0.6__ql_0.0', 'value__change_quantiles__f_agg_.var.__isabs_False__qh_0.6__ql_0.2', 'value__change_quantiles__f_agg_.var.__isabs_False__qh_0.6__ql_0.4', 'value__change_quantiles__f_agg_.var.__isabs_True__qh_0.6__ql_0.0', 'value__fft_coefficient__coeff_10__attr_.abs.', 'value__fft_coefficient__coeff_10__attr_.imag.', 'value__fft_coefficient__coeff_13__attr_.angle.', 'value__fft_coefficient__coeff_13__attr_.real.', 'value__fft_coefficient__coeff_16__attr_.real.', 'value__fft_coefficient__coeff_2__attr_.angle.', 'value__fft_coefficient__coeff_2__attr_.real.', 'value__fft_coefficient__coeff_3__attr_.real.', 'value__fft_coefficient__coeff_45__attr_.imag.', 'value__fft_coefficient__coeff_4__attr_.angle.', 'value__fft_coefficient__coeff_4__attr_.real.', 'value__fft_coefficient__coeff_53__attr_.angle.', 'value__fft_coefficient__coeff_53__attr_.imag.', 'value__fft_coefficient__coeff_5__attr_.angle.', 'value__fft_coefficient__coeff_5__attr_.real.', 'value__fft_coefficient__coeff_6__attr_.angle.', 'value__fft_coefficient__coeff_6__attr_.real.', 'value__fft_coefficient__coeff_77__attr_.real.', 'value__fft_coefficient__coeff_7__attr_.real.', 'value__fft_coefficient__coeff_9__attr_.abs.', 'value__fft_coefficient__coeff_9__attr_.imag.', 'value__fft_coefficient__coeff_9__attr_.real.', 'value__longest_strike_below_mean', 'value__partial_autocorrelation__lag_3', 'value__partial_autocorrelation__lag_4', 'value__partial_autocorrelation__lag_8', 'value__percentage_of_reoccurring_datapoints_to_all_datapoints', 'value__percentage_of_reoccurring_values_to_all_values', 'value__ratio_value_number_to_time_series_length', 'value__sample_entropy', 'value__sum_of_reoccurring_data_points', 'value__sum_of_reoccurring_values', 'value__value_count__value_0']

**Comment by MaxBenChrist** [comment]
I don't know why but your feature names are missformated!

'value__change_quantiles__f_agg_.mean.__isabs_True__qh_0.6__ql_0.0',__

feature has this `.mean.__` part that should not be there

**Comment by MaxBenChrist** [comment]
Where is train_features.columns coming from? It does not look like a bug on tsfresh side

**Comment by dbarbier** [comment]
This seems to be a user error, and no reply from OP, maybe this issue can be closed.

**Comment by nils-braun** [comment]
Thanks for checking the issues!
