### ISSUE TITLE
Incorrect param in documentation

### ISSUE THREAD

**Issue by dgodinez77** [blue-yonder/tsfresh#476]
Hello, I think there's a typo in the documentation. For the function 'agg_autocorrelation' the doc states to input the parameters with a dictionary containing "attr", but this doesn't work and I believe this is because the code looks for "f_agg" instead of "attr"

See: https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html#tsfresh.feature_extraction.feature_calculators.agg_autocorrelation

**Comment by MaxBenChrist** [comment]
Thx for reporting this, I fixed it
