### ISSUE TITLE
Issue with 'feature_extraction.settings.from_columns'

### ISSUE THREAD

**Issue by cdtennant** [blue-yonder/tsfresh#478]
OS: Windows 7 Enterprise
Python version: 3.6.5
tsfresh version: 0.11.0

I've been using tsfresh in a ML classification problem involving time-series data. For a single labeled event/example, I have 17 signals and when I apply tsfresh with ComprehensiveFCparameters it takes ~40 minutes to compute the nearly 800 features for each signal. Because it is so computationally expensive, I've only been able to get a feature matrix with 175 examples. This in turn leads to overfitting - since there are 13,000+ features. I've used several methods to determine only the most important features with the idea of passing those selected features (via feature_extraction.settings.from_columns) and thereby reducing the time required to feature engineer the remainder of my data (and also to avoid overfitting).

But here is where I find myself very confused by what tsfresh is doing. I first define a list of columns that were computed to be 5 most important:

![screen1](https://user-images.githubusercontent.com/44101401/50768819-e7ab7280-124f-11e9-97d5-792cadf1664f.png)

Next, I pass them via kind_to_fc_parameters and call extract_features:

![screen2](https://user-images.githubusercontent.com/44101401/50768842-feea6000-124f-11e9-9f35-739f30eb9bc7.png)

Several things are puzzling. First that it takes 3+ hours to compute the feature matrix for only 8 examples and the fact that apparently many other features were computed (which do not have finite values) which I did not ask for. If I look at the shape of the feature matrix I find:

![screen3](https://user-images.githubusercontent.com/44101401/50768853-07429b00-1250-11e9-9cbc-52aa88d3314e.png)

whereas I would expect (8, [5 features x 17 signals = 85]). Why are there over 10,000 features being computed? This is precisely what I was trying to avoid!

**Comment by cdtennant** [comment]
Here are some more details that hopefully illuminate the problem I have more clearly:

The tsfresh documentation states that tsfresh.feature_extraction.settings.from_columns is expecting a list of strings

![doc](https://user-images.githubusercontent.com/44101401/50908192-35161400-13f7-11e9-8821-e035b591e669.png)

I generate a subset of features (5 in this example) and create a list of strings with the specified column names

![pic1](https://user-images.githubusercontent.com/44101401/50908238-4f4ff200-13f7-11e9-89c7-02d1c016c7d2.png)

I then pass this to settings.from_columns() and while it is recognized as a 'dict', I wonder if the parsing is incorrect. No error or warning is raised, but I suspect there is something amiss and the program just reverts to the default extraction settings - which is why I'm getting thousands of features when I expect a few dozen.

![pic2](https://user-images.githubusercontent.com/44101401/50908473-ca190d00-13f7-11e9-8619-472f96d2bdf7.png)

However, I still don't understand where I went wrong in the above example. Suggestions or a workaround would be greatly appreciated!

**Comment by earthgecko** [comment]
Hi @cdtennant 

Just a suggestion that may be a workaround.  Have you tried also passing the ```columns_to_ignore``` parameter to ```settings.from_columns``` to exclude all the feature names columns that you do not want to include, that may be a workaround for the time being.

```python
settings.from_columns(feat[:5], feat[6:])
```

**Comment by cdtennant** [comment]
Thanks for the suggestion @earthgecko. In my actual implementation I used all the rows of 'feat'. I only selected 5 in the example above to keep things looking neat.

**Comment by MaxBenChrist** [comment]
Hi @cdtennant, can you send me a small data sample? I need 1-2 time series and the list of the 5 important features

**Comment by MaxBenChrist** [comment]
Bytheway, you are not using the latest tsfresh version v0.11.1, maybe you can update it and try it again?

**Comment by cdtennant** [comment]
@MaxBenChrist, I just sent you sample data. Thanks for taking a look!

P.S. I installed tsfresh via conda install from Anaconda Cloud. That is where I took the version number from. How would I install the newest version?

**Comment by MaxBenChrist** [comment]
sorry for the late response :-/

conda did not have the latest tsfresh version (0.11.1), only 0.11.0. I will cut a release somewhere this weekend that should be uploaded to conda. In the meantime, you can try the master by 

`pip install git+https://github.com/blue-yonder/tsfresh/`

And then retry the experiment. I will have a look over your data sample this weekend.

**Comment by MaxBenChrist** [comment]
I can confirm that this is a bug. As a quick fix, you can do: 

```Python
X = extract_features(X.astype("float64"), column_id="id", column_sort="Time", kind_to_fc_parameters=config, default_fc_parameters={})
```

**Comment by MaxBenChrist** [comment]
I made this default behaviour, thanks again for reporting and sorry for late answer
