### ISSUE TITLE
Passing pd.Series instead of np.ndarray

### ISSUE THREAD

**Issue by michetonu** [blue-yonder/tsfresh#483]
Hi,

Is there a reason why the data is passed to each function as a numpy array, instead of as a Series, and then converted to array only if needed?

This way, we could use the index of the values for extra manipulation (e.g. calculate the slope based on the timestamp, as mentioned in the #TODO comment in the linear_trend function). 

In addition, the docstrings of all functions in `feature_calculators` say that the type of `x` is `pd.Series`, while it is actually always `np.ndarray` (since it's converted in line 277 of `feature_extraction/extraction.py`: `data = data.values`, before being passed to the feature processor)

**Comment by MaxBenChrist** [comment]
In the beginning, tsfresh was passing `pd.Series` around. 

If I remember correctly, we switched from pd.Series to numpy arrays due to lower memory footprint and speed. 

thanks for the hint, we should adapt the docstrings

**Comment by michetonu** [comment]
It's really not that big of a problem in terms of memory/load - you convert from pd.Series to np.array only after the chunks have been made, before passing them to the functions. I've made a fork in which I added functions with a new "time" decorator, and in the loop in `_do_extraction`, if the function is a time function, it passes the pd.Series; otherwise, it passes the numpy array. Meaning that if you only want to use the current constructor functions, nothing changes. I can make a PR and show you, if you want.

I can guarantee that this will be definitely useful in a lot of applications where measurements are not taken at regular intervals (e.g. medicine).

**Comment by MaxBenChrist** [comment]
Sounds interesting, I happily to review the pr 👍 

You could use the set_property decorator to decide if to pass an numpy array or pandas series

```
 @set_property("input", "pd.Series")
def your_time_feature
```

**Comment by michetonu** [comment]
@MaxBenChrist so my approach was working until the latest version, but the change to this line

```
    data_in_chunks = [x + (y,) for x, y in df.set_index(column_id, drop=False).rename_axis(None).groupby([column_id, column_kind], as_index=True)[column_value]]
```

now means that it doesn't work anymore, because the index is reset to the 'id' column during the preparation. Before it used to be only a groupby. Is there a specific reason why you are doing this now?

**Comment by MaxBenChrist** [comment]
> Before it used to be only a groupby. Is there a specific reason why you are doing this now?

I was working through deprecation warnings and errors, I don't remember any specific reason why we shouldn't set it to the time columns. 

Do you want to do that on your pr?

**Comment by michetonu** [comment]
Yeah sure! Rather that set it explicitly to an index (as it is now) I would keep the index as the one set by the user before passing the data to the feature extraction (as it used to be).

I’ll try to change it back and see if nothing breaks ;)

**Comment by MaxBenChrist** [comment]
I just ran it and some stuff breaks, but nothing grave

> Yeah sure! Rather that set it explicitly to an index (as it is now) I would keep the index as the one set by the user before passing the data to the feature extraction (as it used to be).

I wouldn't do that. I would manually set it to the column_sort. (you have to deal with the case that the user does not specify a sort column, maybe replace it with range inside the groups for that case)

**Comment by dbarbier** [comment]
As far as I can tell, everything discussed here had been implemented, this issue can be closed.

**Comment by nils-braun** [comment]
Thanks for helping clean up the issues!
