### ISSUE TITLE
too many  features

### ISSUE THREAD

**Issue by dongfangyier** [blue-yonder/tsfresh#484]
Hello, when I had 40,000 + features, I couldn't get any features by select_features and fsr_level = 0.05. But when I extract 10,000 features each time, I can use select_features to get enough features.

 I wonder why this is and what is the result of extracting 10,000 features that makes sense?

I use linux（ubuntu） system to extract the characteristics of EEG signals. The tsfresh library is the latest version.

**Comment by MaxBenChrist** [comment]
Different feature selection algorithms will return different sets of relevant features. 

If you ran a feature selection algorithm on a subset of your data or in your case a subset of the features you will get different results ( result = set of relevant features).

The tsfresh procedure uses a multiple testing procedure. The lower the number of features, the more likely it is for any feature to be selected as relevant. Please have a look at our paper for details on the procedure.
