### ISSUE TITLE
Upgrade pyscaffold build dependency or remove it

### ISSUE THREAD

**Issue by rth** [blue-yonder/tsfresh#486]
Currently tsfresh requires pyscaffold < 2.6 that is not compatible with newer setuptools versions. 

As mentioned by @xhochy in https://github.com/conda-forge/tsfresh-feedstock/pull/2#issuecomment-459332997 this prevents from packaging v0.11.1 for conda forge,

> No, the problem is that these old pyscaffold versions don't work together with newer setuptools releases. But the newer setuptools are needed by other packages in the dependency chain. 

More generally this may be an issue for other installs as well, it's just that pip will not check global consistency of dependencies.

It would be nice to either upgrade pyscaffold build dependency or remove it.

TBH, I don't see the added value of pyscaffold in this case: tsfresh is a pure python package and so `setup.py` would be fairly straightforward with most configuration included in setup.cfg same as currently in any case. Not being compatible with latest setuptools is a larger concern IMO. Though I may be missing something.

**Comment by xhochy** [comment]
Have a look at https://github.com/xhochy/fletcher/blob/master/setup.py for a `setup.py` that was written with recent standards. @rth you might want to submit a PR to get rid of `pyscaffold`, then we can get this back on `conda-forge` again.

**Comment by rth** [comment]
Thanks for the feedback @xhochy , made a PR in #487

**Comment by MaxBenChrist** [comment]
Agree with kicking out pyscaffold. We set tsfresh up with it and then it just stayed in.

**Comment by xhochy** [comment]
@MaxBenChrist Can you cut a release so we get the version on `conda-forge` uptodate again?

**Comment by MaxBenChrist** [comment]
Sure sure, will do a release tomorrow. Experience tells me that you should never deploy/release on a Friday night...
