### ISSUE TITLE
wrong dependency for 0.11.2

### ISSUE THREAD

**Issue by ian-contiamo** [blue-yonder/tsfresh#492]
This commit appears to have broken feature selection:
https://github.com/blue-yonder/tsfresh/commit/68a64a0f8ebc27359177b10d9898a800502983a0

I get the following error:
```
from tsfresh import extract_features, select_features
features_filtered = select_features(train_features, train_target)

RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/opt/conda/lib/python3.6/site-packages/tsfresh/feature_selection/significance_tests.py", line 185, in target_real_feature_real_test
    tau, p_value = stats.kendalltau(x, y, method="asymptotic")
TypeError: kendalltau() got an unexpected keyword argument 'method'
"""
```

I believe the requirement for scipy is outdated:
https://github.com/blue-yonder/tsfresh/blob/master/requirements.txt#L4

Cheers!

**Comment by MaxBenChrist** [comment]
Oh, I added scipy to our travis pipeline to catch those kind of errors. Thanks for reporting it

**Comment by ian-contiamo** [comment]
Thank you!

**Comment by MaxBenChrist** [comment]
Will be fixed in 0.11.3

**Comment by zhangyouchang** [comment]
I meet this problem too ,plz tell me how to solve it .many thanks~

**Comment by cliffrunner** [comment]
I am having the same issue. Is there a workaround? Thanks.

**Comment by MaxBenChrist** [comment]
Hi @zhangyouchang and @cliffrunner , you will have to update scipy to 1.2.0.

**Comment by cliffrunner** [comment]
Hi @MaxBenChrist , my scipy version is 1.2 but the problem persists.

**Comment by Pavlov228** [comment]
@MaxBenChrist , For tsfresh 0.11.2 I updated scipy manually to version 1.3.0 - the error is still there.
