### ISSUE TITLE
Add runtime estimation before feature extraction

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#503]
It is frustrating for the user to wait long for the calculation of features.

Ideally, we would have an automatic check before running the feature extraction on all data that calculates the features on a subset of 1-2 time series and then extrapolates the runtime on all time series. That automatic check could also see if there is an imbalance between the runtime of the different features. From my experience, often a small group of features takes up the majority of the runtime ( I am looking at you, sample entropy )

We already have some code for the comparison of runtimes, maybe we can use that

https://github.com/blue-yonder/tsfresh/blob/master/notebooks/compare-runtimes-of-feature-calculators.ipynb

**Comment by nils-braun** [comment]
If users use the normal `tqdm` progress bar, they get this "for free".
