### ISSUE TITLE
Dependent versus independent features for the Benjamini Yekutieli procedure.

### ISSUE THREAD

**Issue by rhysimu** [blue-yonder/tsfresh#508]
I've been trying to get my head around the Benjamini Hochberg procedure used in tsfresh. As I interpret the paper, variable 'C' in feature_selection/benjamini_hochberg_test.py should be a scalar value the same for every index as the sum for i=(1 to m) of 1/i. However, the way it is implemented in the code is as a cumulative sum array, with its value different for every i. 

The paper which is referenced (Benjamini and Yekutieli, 2001) seems a bit confusing in this regard as the index i is used in formula (1) and in the definition of Theorem 3.1. However, when I look at Wikipedia (forgive me - https://en.wikipedia.org/wiki/False_discovery_rate), they use k for the index of the feature and i for the index of the sum, which suggests that the resultant C would be a scalar rather than an array.

Are you able to provide any insight on which of the two is correct, as I get a much greater number of relevant features with C as a cumulative sum array than I do with C as a scalar?

**Comment by MaxBenChrist** [comment]
There are two procedures, depending if the hypotheses (and with it the features) can be assumed to be statistically independent.

You use the cumulative sum if the features are dependent, which they are in most of the cases.

The feature selection in tsfresh will only kick out features that the procedures is sure are irrelevant.

> Are you able to provide any insight on which of the two is correct, as I get a much greater number of relevant features with C as a cumulative sum array than I do with C as a scalar?

You use C as a scaler if the features are thought to be independent. Otherwise use the cumulative sum.

**Comment by rhysimu** [comment]
If the features are independent then C is 1.

If the features are dependent, then, the way I read the procedure, C is solely dependent on m (the number of features) and doesn't apply differently along the array of features. 

For example, if there are 10 features, then the sum for i=1 to m of 1/i is ~2.93. I believe the array C should be [2.93, 2.93, ....., 2.93, 2.93] rather than [1, 1.5, ....., 2.83, 2.93] when determining the max p value for relevance.

Have I misread the paper? or misunderstood the implementation in tsfresh?

**Comment by MaxBenChrist** [comment]
Now I see what you are referring to. This looks like a bug.

Do you want to submit a pr for this?

> Are you able to provide any insight on which of the two is correct, as I get a much greater number of relevant features with C as a cumulative sum array than I do with C as a scalar?

I think you should get more relevant features with C as scalar than using the (wrong) cumulative sum. So, after the fix there should be more relevant features. 

Why? so, we only drop feature "k" if we reject "H_k"  

<img width="187" alt="Bildschirmfoto 2019-03-17 um 09 27 45" src="https://user-images.githubusercontent.com/13162426/54488221-4700b100-4897-11e9-9049-645542720b89.png">

So, the C as scalar is bigger for most k than the cumulative sum, hence the right side of that inequality is smaller for C as a scalar. Hence, for C scalar its harder to reject the null hypotheses and with it the features. Hence, we should get more features for C as scalar

**Comment by rhysimu** [comment]
If C is the correct scalar, then k/(m*c(m)))*alpha will be a smaller number as it's in the denominator. We only accept as relevant those features with p-values less than this value. Therefore, the number of features that are relevant will decrease.

I can do the PR sometime this week, but don't mind if someone else makes the change.

**Comment by MaxBenChrist** [comment]
Well, you are right again 👍 after the fix, the number of selected features will decrease.

> We only accept as relevant those features with p-values less than this value. 

Somehow, I got the hypothesis mixed up. I thought we test `H_0 = {feature is relevant}` but its actually `H_0 = {feature is irrelevant}`. 

> I can do the PR sometime this week, but don't mind if someone else makes the change.

ok, looking forward to your pr

**Comment by MaxBenChrist** [comment]
This is fixed in 0.12.0
