### ISSUE TITLE
Isolating specific set of functions from tsfresh

### ISSUE THREAD

**Issue by MelanieU** [blue-yonder/tsfresh#512]
I really like tsfresh and would like to incorporate it more efficiently into my current project. I'm interested in isolating features out of the 795 extracted ones that would give me information about seasonality / recurrent cyclic periods. Before going through all the features manually, are there certain feature groups that are more suitable for detecting seasonality (that you know of) or are there ways to isolate those quicker?

**Comment by MaxBenChrist** [comment]
Hard to answer that question without exactly knowing the statistical problem that you face. 

Can you tell us a little bit more about your data and what the exact task is?

**Comment by nils-braun** [comment]
It seems this issue is stalled and there was no answer from the OP. Closing it.
