### ISSUE TITLE
Unable to disable warnings in extract_features

### ISSUE THREAD

**Issue by jmrichardson** [blue-yonder/tsfresh#518]
I am unable to disable the warning messages.  I have tried all of the following:

```
import warnings
warnings.simplefilter("ignore")
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=RuntimeWarning)
numpy.warnings.filterwarnings('ignore')
```

I have also tried the switch:

```
X = extract_features(df_roll, column_id="id", column_sort="time", column_value="value",
                         impute_function=impute, disable_progressbar=True, show_warnings=False)
```

I have also tried suppressing stderr and stdout...

Is there any way to do it?  I have many columns to calculate and I get many RuntimeWarnings and RankWarning.  It floods my console and is redundant for each column.  Please advise.

1. Your operating system
Windows 10
2. The version of *tsfresh* that you are using
Latest
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
All time series
4. A minimal code snippet which reproduces the problem/bug
X = extract_features(df_roll, column_id="id", column_sort="time", column_value="value",
                         impute_function=impute, disable_progressbar=True, show_warnings=False)
5. Any reported errors or traceback

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by MaxBenChrist** [comment]
Which tsfresh version are you running? `0.11.2`?

**Comment by jmrichardson** [comment]
Yes, tsfresh 0.11.2

**Comment by MaxBenChrist** [comment]
can you upload some of those errors to a gist? https://gist.github.com/

**Comment by jmrichardson** [comment]
Here is the URL:

https://gist.github.com/jmrichardson/579aeec002c0d352d6c77b83b4151c07

**Comment by nils-braun** [comment]
Thanks for the issue (and sorry for the very late answer). This is actually a problem with the multiprocessing package (or in the way we use it). I have an idea to fix it and will do so soon.
