### ISSUE TITLE
Detect complex numbers as time series values

### ISSUE THREAD

**Issue by NoisySignal** [blue-yonder/tsfresh#519]
Question about the ability of TSFRESH to analyse complex-valued time series. This type of time series is often produced, for example, by software defines radios.

**Comment by NoisySignal** [comment]
Time series of complex numbers (IQ samples, x + iy data) are commonly produced by software defined radios.

Does TSFRESH correctly process these time series "out of the box" or will it crash because of data type issues?

**Comment by NoisySignal** [comment]
The short answer is no, TSFRESH will NOT work with complex time series (as shown below).

i.e. TypeError: 1st argument must be a real sequence 1

The pragmatic solution is to convert the complex time series to a real time series. This involves interpolation, filtering and doubling the sample rate.

---

Feature Extraction:   0%|          | 0/1 [00:00<?, ?it/s]
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/michaeljohnwilson/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/michaeljohnwilson/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/tsfresh/utilities/distribution.py", line 38, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "/Users/michaeljohnwilson/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/tsfresh/utilities/distribution.py", line 37, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "/Users/michaeljohnwilson/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/tsfresh/feature_extraction/extraction.py", line 358, in _do_extraction_on_chunk
    return list(_f())
  File "/Users/michaeljohnwilson/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/tsfresh/feature_extraction/extraction.py", line 345, in _f
    result = func(data, param=parameter_list)
  File "/Users/michaeljohnwilson/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/tsfresh/feature_extraction/feature_calculators.py", line 941, in fft_coefficient
    fft = np.fft.rfft(x)
  File "/Users/michaeljohnwilson/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/mkl_fft/_numpy_fft.py", line 331, in rfft
    output = mkl_fft.rfft_numpy(a, n=n, axis=axis)
  File "mkl_fft/_pydfti.pyx", line 609, in mkl_fft._pydfti.rfft_numpy
  File "mkl_fft/_pydfti.pyx", line 489, in mkl_fft._pydfti._rc_fft1d_impl
TypeError: 1st argument must be a real sequence 1
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-12-664e5901163f> in <module>
      8 X_tsfresh = extract_features(X, column_id="id", column_sort="time", 
      9                              column_kind="kind", column_value="value",
---> 10                             default_fc_parameters = settings)
     11 
     12 X_tsfresh.head()

~/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/tsfresh/feature_extraction/extraction.py in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor)
    157                                 default_fc_parameters=default_fc_parameters,
    158                                 kind_to_fc_parameters=kind_to_fc_parameters,
--> 159                                 distributor=distributor)
    160 
    161         # Impute the result if requested

~/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/tsfresh/feature_extraction/extraction.py in _do_extraction(df, column_id, column_value, column_kind, default_fc_parameters, kind_to_fc_parameters, n_jobs, chunk_size, disable_progressbar, distributor)
    294     kwargs = dict(default_fc_parameters=default_fc_parameters, kind_to_fc_parameters=kind_to_fc_parameters)
    295     result = distributor.map_reduce(_do_extraction_on_chunk, data=data_in_chunks, chunk_size=chunk_size,
--> 296                                     function_kwargs=kwargs)
    297     distributor.close()
    298 

~/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/tsfresh/utilities/distribution.py in map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    147             result = self.distribute(_function_with_partly_reduce, chunk_generator, map_kwargs),
    148 
--> 149         result = list(itertools.chain.from_iterable(result))
    150 
    151         return result

~/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/site-packages/tqdm/_tqdm.py in __iter__(self)
   1020                 """), fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1021 
-> 1022             for obj in iterable:
   1023                 yield obj
   1024                 # Update and possibly print the progressbar.

~/anaconda3/envs/tsfresh_python3_5_2/lib/python3.5/multiprocessing/pool.py in next(self, timeout)
    693         if success:
    694             return value
--> 695         raise value
    696 
    697     __next__ = next                    # XXX

TypeError: 1st argument must be a real sequence 1

**Comment by NoisySignal** [comment]
TSFRESH does NOT work with complex time series "out of the box".

**Comment by NoisySignal** [comment]
TSFRESH does NOT work with complex time series "out of the box".

**Comment by NoisySignal** [comment]
@MaxBenChrist - I did some work on this after my initial question.
I performed complex-to-real conversion before I processed the time series with TSFRESH.

This conversion appeared to be successful in that the EfficientFCParameters() features were calculated successfully.

**Comment by nils-braun** [comment]
I think the question was answered, so I am closing.
