### ISSUE TITLE
Can tsfresh be used to solve this problem

### ISSUE THREAD

**Issue by ronikass** [blue-yonder/tsfresh#52]
Hi,

I have 400,000 time series, each of length 1,000.
Each time series has a class 0 or 1 (binary classification problem). The dataset is balanced between 0 and 1

I have created my own features (min,max,sd,var,linear regression) on different time length of the time series (50,100,200,300,400,500,600,700,800,900,1000), which cam out to be 900 features.

I have ran the 900 features in grid search with CART (decision tree).
The best accuracy I got was 0.56 or so.

Can tsfresh be used (and hopefully get a much better job). If so, how ?

This is a real life problem, lets see how tsfresh handles it (vs other methods)

**Comment by MaxBenChrist** [comment]
Yes. Can you tell us more from which application this data belongs?

**Comment by ronikass** [comment]
Medical device

**Comment by ronikass** [comment]
Can you explain more how one would use tsfresh for this binary class problem

**Comment by MaxBenChrist** [comment]
Please have a look the paper, there we describe how we tackle binary classification problems with fresh

**Comment by MaxBenChrist** [comment]
Can you give more details about the medical device?

**Comment by ronikass** [comment]
It is a feasibility test of a prototype of some measurement device, where based on past samples, we want to understand if we can expect a irregular situation to happen (class 0 and class 1)

**Comment by MaxBenChrist** [comment]
So, maybe we can have another competition such as in [http://robjhyndman.com/hyndsight/ts-classification-contest/](http://robjhyndman.com/hyndsight/ts-classification-contest/) ?

This time with tsfresh 👍

**Comment by ronikass** [comment]
Where in the paper ? I cant find it in the online version

**Comment by MaxBenChrist** [comment]
Chapter 4 Introduction
Chapter 4.1 Accuracy

Pages 7 to 9

Am 10. November 2016 um 13:20 schrieb ronikass <notifications@github.com>:

Where in the paper ? I cant find it in the online version
