### ISSUE TITLE
[pip] tsfresh 0.11.2 Update dependency on scipy version

### ISSUE THREAD

**Issue by fabsen** [blue-yonder/tsfresh#520]
Hey,

my first issue post on github (exciting! :)), so please go easy on me if I'm missing something.

1. Your operating system - Ubuntu 16.x LTS Linux, python: 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
2. The version of *tsfresh* that you are using - fresh pip3 install tsfresh, i.e. Version 0.11.2
4. A minimal code snippet which reproduces the problem/bug - from the quickstart tutorial: 
https://tsfresh.readthedocs.io/en/latest/text/quick_start.html
everything worked until:
features_filtered = select_features(extracted_features, y)
5. Any reported errors or traceback
scipy.stats.kendalltau doesn't know the keyword "method".

Looks like scipy has to be a higher version than 1.1.0: https://github.com/scipy/scipy/blob/maintenance/1.1.x/scipy/stats/stats.py#L3427 
, whereas in 1.2.0 the 'method' keyword exists.

**Comment by MaxBenChrist** [comment]
Hi @fabsen 

Looks like you have an old version of scipy installed.

Can you post the output of `pip list` or `pip freeze` here?

**Comment by fabsen** [comment]
Thx for pointing that out :). I had scipy 1.1.0 installed and somehow pip didn't upgrade scipy to >= 1.2.0 (as defined in the requirements.txt). Manual scipy installation does the job. I guess upgrading dependencies is the desired behaviour of pip?
