### ISSUE TITLE
tsfresh formatting for column containing list of integers

### ISSUE THREAD

**Issue by sskulki** [blue-yonder/tsfresh#523]
Hi,

Need to understand more on tsfresh data processing. Please guid me through it.

1. Your operating system : Linux
2. The version of *tsfresh* that you are using : 

I have a dataframe containing 4 columns (id, date, col2, col3) and I want to extract the features from col2 and col3. But my col2 and col3 contains list of integers in each row. Can I extract the features using tsfresh? 
Could you please guide me how to proceed or any suggestions to preprocess the data before applying tsfresh?

**Comment by MaxBenChrist** [comment]
> I have a dataframe containing 4 columns (id, date, col2, col3) and I want to extract the features from col2 and col3. But my col2 and col3 contains list of integers in each row. Can I extract the features using tsfresh?

Yes, but you will have to flatten your dataframe before. I would not recommend to store lists/arrays inside DataFrame cells (you could use nested dictionaries for that instead).

**Comment by nils-braun** [comment]
Which features did you expect to work with your kind of data type? 
Just one example: What is the mean of a list of lists of integers? 
tsfresh is built for time series feature extraction (hence the name) and I would say your data format is not the typical time series :-) Why do you not have plain numbers per date?

So to be short: it will not give you the results you need.

**Comment by nils-braun** [comment]
I guess the issue has either been outdated or answered or is invalid. I will close it now. Feel free to reopen and answer the questions if we can help you :-)
