### ISSUE TITLE
chunksize in select_features()?

### ISSUE THREAD

**Issue by zygmuntz** [blue-yonder/tsfresh#525]
select_features() has a parameter chunksize. The docs say this:

> chunksize (None or int) – The size of one chunk that is submitted to the worker process for the parallelisation. Where one chunk is defined as a singular time series for one id and one kind. If you set the chunksize to 10, then it means that one task is to calculate all features for 10 time series. If it is set it to None, depending on distributor, heuristics are used to find the optimal chunksize. If you get out of memory exceptions, you can try it with the dask distributor and a smaller chunksize.

This looks like a description copied from feature extraction. In feature selection, there's no ids and no kinds. Also, as far as I understand, selection can go in parallel column-by-column (each col tested separately), but not row-by-row (we need a vector of size [rows, 1]).

**Comment by MaxBenChrist** [comment]
Good catch. Yes, that is a leftover indeed. I will fix the documentation. Thank you

**Comment by nils-braun** [comment]
@MaxBenChrist you are still up to do this?
