### ISSUE TITLE
Add check if integer time column / ZeroDivisionError in tqdm.py / pool.py

### ISSUE THREAD

**Issue by JPlanken** [blue-yonder/tsfresh#527]
Hi I'm encountering a problem with the following characteristics

Windows 10
tsfresh==0.11.2
Passing the following data:

```
time	flight_id	lat	long	velocity	heading	vertrate	baroaltitude
0	1510228979	1	52.5533	3.12302	224.176	55.471	2.276	10325.1
1	1510229159	1	52.7569	3.61336	224.157	55.945	0.325	10668
2	1510229339	1	52.9572	4.10536	227.719	56.238	0	10683.2
3	1510229519	1	53.1597	4.61277	224.298	56.602	0	10668
4	1510229699	1	53.3572	5.11777	223.883	57.004	0	10660.4
```
into this:

```
from tsfresh import extract_features
extracted_features = extract_features(df_10, column_id="flight_id", column_sort="time")
```
Gives a zero division error:

```
\AppData\Roaming\Python\Python36\site-packages\tqdm\_tqdm.py in __iter__(self)
   1020                 """), fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1021 
-> 1022             for obj in iterable:
   1023                 yield obj
   1024                 # Update and possibly print the progressbar.

~\AppData\Local\conda\conda\envs\opensky\lib\multiprocessing\pool.py in next(self, timeout)
    733         if success:
    734             return value
--> 735         raise value
    736 
    737     __next__ = next                    # XXX

ZeroDivisionError: float division by zero
```

While passing the example dataframe:

```
	id	time	F_x	F_y	F_z	T_x	T_y	T_z
0	1	0	-1	-1	63	-3	-1	0
1	1	1	0	0	62	-3	-1	0
2	1	2	-1	-1	61	-3	0	0
3	1	3	-1	-1	63	-2	-1	0
4	1	4	-1	-1	63	-3	-1	0
```

to this:

```
from tsfresh import extract_features
extracted_features = extract_features(timeseries, column_id="id", column_sort="time")
```
Works absolutely fine. 

Any ideas on why this may occur?

**Comment by JPlanken** [comment]
SOLVED: 
Casting the entire dataframe to a float seemed to resolve the problem. I think it is due to the fact that my 'time' column was a datatime_int64. 

`df_10 = df_10.astype(float)`

**Comment by MaxBenChrist** [comment]
Well, I will try to add a check for integer dtype in the time column. tsfresh should work with both.

**Comment by nils-braun** [comment]
Unfortunately I could not reproduce your issue (at least not with the newest version of tsfresh). I tried to use every kind of combination of datetime and strings and stuff, but it always worked :-)

Could you maybe try again with the newest version and if it still fails, reopen the issue and attach parts of your data somehow with the pandas types (just the first few rows should be fine).
