### ISSUE TITLE
tsfresh seems to be incompatible with latest versions of pandas

### ISSUE THREAD

**Issue by cchorn** [blue-yonder/tsfresh#528]
Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system
Ubuntu 18.04.2 LTS

2. The version of *tsfresh* that you are using
latest version
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
4. A minimal code snippet which reproduces the problem/bug
5. Any reported errors or traceback

error when trying to install:

tsfresh 0.11.2 has requirement pandas<=0.23.4,>=0.20.3, but you'll have pandas 0.24.2 which is incompatible.

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by AStupidBear** [comment]
Is there any specific reason for tsfresh not to use the latest stable pandas?

**Comment by jnj16180340** [comment]
```
pandas>=0.20.3,<=0.23.4 # pandas dropna is buggy in 0.24.0, see https://github.com/blue-yonder/tsfresh/issues/485 and https://github.com/pandas-dev/pandas/issues/25087
```

Looks like it's fixed in `0.25.0` https://github.com/pandas-dev/pandas/issues/25087#issuecomment-506855641

**Comment by lobpcg** [comment]
```
ERROR: tsfresh 0.12.0 has requirement pandas<=0.23.4,>=0.20.3, but you'll have pandas 0.25.0 which is incompatible.
```

**Comment by jpzhangvincent** [comment]
Same question! Can we merge this pull request? https://github.com/blue-yonder/tsfresh/pull/562

**Comment by dbarbier** [comment]
Hi, new conda packages are available, this issue can be closed.
