### ISSUE TITLE
Add example notebook on how to use tsfresh for unsupervised clustering

### ISSUE THREAD

**Issue by unidev10** [blue-yonder/tsfresh#531]
Hi! I've got a time series dataset on which I want to perform feature extraction and then cluster the features. I don't have any output column. I want to do it in an unsupervised manner. Can tsfresh be used for unsupervised algorithms?

**Comment by MaxBenChrist** [comment]
Sure, you can use tsfresh to extract features from your time series and then run a cluster algorithm on the feature matrix. 

The cluster algorithm will cluster the time series based on the feature values.

**Comment by Sukanya2191** [comment]
Can anyone help me which clustering algorithm can be used for the approach.
