### ISSUE TITLE
Suggestion Regarding Partial Autocorrelation Function (PACF) Calculator

### ISSUE THREAD

**Issue by nicholasg97** [blue-yonder/tsfresh#532]
Hey guys! Enjoying all the hard work you guys put into this project!

Just a small observation regarding the partial_autocorrelation function in the featue_calculators module. 

I'm working on a fairly large signal dataset where each 'id' has ~200,000 time_steps (only one feature though). I've been testing some of the functions in the feature_calculator module, for speed.

Without parallel processing, it takes my i7-6700 ~ 11 seconds to run the 
<pacf(x(150,000 time_steps), method="ld", nlags=2)> 
function alone on one sample. 

When using the exact same set-up, but specifying the method as 'yw' or 'Yule-Walker with bias correction in denominator for acovf'

It takes around ~.006 seconds or almost 2000x faster. This could be based on the way my enviormnent is setup, but I just wanted to let you guys know. Maybe you had a reason specifically for specifying Levinson-Durbin method! I don't know too much in-depth details about pacf. 

From the stats models documentation they also state, "Based on simulation evidence across a range of low-order ARMA models, the best methods based on root MSE are Yule-Walker (MLW), Levinson-Durbin (MLE) and Burg, respectively. The estimators with the lowest bias included these three in addition to OLS and OLS-unbiased."

So it doesn't look like for Yule-Walker is terribly worse (they even state better) than Levinson-Durbin, but maybe it's different for feature engineering. 

Thanks again for all the great work.

**Comment by MaxBenChrist** [comment]
I am not an expert on the different ways of estimating the Partial Autocorrelation Function. 

Did you compare the results? Were they comparable?

If you want you could submit a pr with a switch. We could internally switch the estimator, depending on how many points the time series has.

**Comment by nils-braun** [comment]
It seems this issue is stalled and/or there was no answer from the OP. If you still want to discuss something, please feel free to reopen!
