### ISSUE TITLE
cross_val_score works with FeatureAugmenter, but not with RelevantFeatureAugmenter

### ISSUE THREAD

**Issue by thanhd10** [blue-yonder/tsfresh#537]
Hi, I'm new to tsfresh and wanted to implement the RelevantFeatureAugmenter in a sklearn.pipeline to cross-validate, but encountered the problem, that it doesn't work with RelevantFeatureAugmenter, but with FeatureAugmenter. I reconstructed the problem with the robot_failure dataset:

~~~~ python
from tsfresh.examples import load_robot_execution_failures
from tsfresh.transformers import RelevantFeatureAugmenter, FeatureAugmenter, PerColumnImputer, FeatureSelector
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
import pandas as pd

x, y = load_robot_execution_failures()
pipe = make_pipeline(RelevantFeatureAugmenter(column_id='id', column_sort='time'),
                     SVC())
pipe.set_params(featureaugmenter__timeseries_container=x)

xfit = pd.DataFrame(index=y.index)
score = cross_val_score(pipe, xfit, y, cv=4)
~~~~
When I run the program, I get the following error message:
~~~~ python
File "/anaconda3/lib/python3.7/site-packages/tsfresh/transformers/relevant_feature_augmenter.py", line 260, in fit
    X_augmented = self.feature_extractor.transform(X_tmp)
  File "/anaconda3/lib/python3.7/site-packages/tsfresh/transformers/feature_augmenter.py", line 185, in transform
    timeseries_container_X = restrict_input_to_index(self.timeseries_container, self.column_id, X.index)
  File "/anaconda3/lib/python3.7/site-packages/tsfresh/utilities/dataframe_functions.py", line 203, in restrict_input_to_index
    df_or_dict_restricted = df_or_dict[df_or_dict[column_id].isin(index)]
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/anaconda3/lib/python3.7/site-packages/pandas/core/internals.py", line 4124, in get
    raise ValueError("cannot label index with a null key")
ValueError: cannot label index with a null key
~~~~
If I run the program with FeatureAugmenter + PerColumnImputer + FeatureSelector, it works perfectly fine. Is that a bug, or did I do something wrong with the RelevantFeatureAugmenter?

1. Your operating system: macOS High Sierra
2. The version of *tsfresh* that you are using: 0.11.2

**Comment by pnb** [comment]
I ran into the same issue, did a little debugging, and found that `column_id` is null by the time it gets to `restrict_input_to_index()`. Setting `column_id` in the pipeline params instead fixes that problem, but raises what I think the real underlying issue is: the `RelevantFeatureAugmenter` cannot be cloned because the constructor has side effects (i.e., it creates a `FeatureAugmenter` and a `FeatureSelector`). It also does not save all the constructor params.

I think this can probably be fixed by refactoring all the side effects into `fit()` and saving the constructor params. If I have time in the near future I will try it and submit a pull request if it works out.

**Comment by MaxBenChrist** [comment]
This is contained in 0.12.0
