### ISSUE TITLE
Parallellization optimisation for feature extraction

### ISSUE THREAD

**Issue by jonimatix** [blue-yonder/tsfresh#541]
Hi,

Is it required to enclose the code in if __name__ == "__main__" in order to achieve better CPU utilization, in conjunction with n_jobs parameter? Is this included in the current release?

Thanks
Jon

**Comment by MaxBenChrist** [comment]
see https://github.com/blue-yonder/tsfresh/issues/185

has nothing to do with performance, is only necessary on windows
