### ISSUE TITLE
Almost useless feature called mean_change

### ISSUE THREAD

**Issue by thautwarm** [blue-yonder/tsfresh#542]
https://github.com/blue-yonder/tsfresh/blob/00884fb2a7ed3a364ebe27f140be8bf425fcde86/tsfresh/feature_extraction/feature_calculators.py#L528

The result is equivalent to (`x_last - x_first) / (n - 1)`.

If you do want this as a feature, `(x[-1] - x[0])/(len(x) - 1)` instead.

**Comment by nils-braun** [comment]
The optimized function is included, thanks to @blu3r4y 
It might still be a useless feature, but you never know and that is why we have a feature selection ;-)
