### ISSUE TITLE
Feature extraction on eeg signals with MultiprocessingDistributor on local machine

### ISSUE THREAD

**Issue by akatav** [blue-yonder/tsfresh#543]
Hi
Thanks for the library. 
So, i have about 20 eeg files from 19 channels, each with varying time series lengths. An average file is matrix of dimension (19,30000). 
I am on an ubuntu 16.04, 8 core. 
The code i am running is like:

```
from tsfresh.feature_extraction import extract_features
from tsfresh.utilities.distribution import MultiprocessingDistributor
import numpy as np

x = [n.strip() for n in columns] # columns is the array of all channel names
x.append("id")

Distributor = MultiprocessingDistributor(n_workers=8,                                        disable_progressbar=False,progressbar_title="Feature Extraction")

for subj in allfiles:#allfiles is a list of EEGRaw objects from mne
    subj=subj.get_data()#matrix shaped (n_channels, n_times)
    subj=subj.T
    ids = np.ones(subj.shape[0])
    output = np.column_stack((subj, ids))
    df=pd.DataFrame(data=output[0:,0:], columns=x)
    X = extract_features(timeseries_container=df,column_id='id',distributor=Distributor)`
```

Obviously, i have reshaped the matrix and added "id" column to make it suitable for extract_features function in tsfresh (although, i'd really like to know if there's a way to do just feed the actual matrix)
Perhaps, it is because all 1000+ features are computed for all the 20 files which i really dont need. Is there a way to select just a few features (<5) in the extract_features() function. 
But, even with just 1 file, this takes a really long time and actually breaks my system. What is wrong with the code?
Thank you

**Comment by MaxBenChrist** [comment]
please read this https://tsfresh.readthedocs.io/en/latest/text/feature_extraction_settings.html
