### ISSUE TITLE
Bug computing friedrich_coefficients with kind_to_fc_parameters

### ISSUE THREAD

**Issue by cdtennant** [blue-yonder/tsfresh#544]
OS: Windows 7 Enterprise
Python version: 3.6.4
tsfresh version: 0.11.2

I am aware that a similar (closed) issue has already been raised on this topic (#501), though I don't know if it is exactly the same.

I am specifying a set of features to compute using `kind_to_fc_parameters`. When I read in 5 examples (i.e. 5 different instances of a signal) I get the following output:

![5samples](https://user-images.githubusercontent.com/44101401/59212996-d4dff580-8b81-11e9-9115-a2b9f3de60eb.png)

All is well and the output feature matrix contains my 5 examples (rows) and the 5 features I specified (columns). However, when I remove the last two examples and read in only 3 instances of the signal, I get the following:

![3samples](https://user-images.githubusercontent.com/44101401/59213085-0953b180-8b82-11e9-8879-efa20413ae2d.png)

Now *none* of the features are calculated, despite the fact that all I did was to remove 2 of the 5 signals. Why should this have an impact? This is causing all sorts of problems with a trained ML application I have - where extracting features of a training set consisting of lots of examples is fine, but then trying to extract features for a single instance, things fall apart.

I see there was some recent work regarding the `friedrich_coefficients` so I don't know if that will address my issue or not. How does one get an unreleased version of `tsfresh`?

![unreleaed](https://user-images.githubusercontent.com/44101401/59213251-6d767580-8b82-11e9-9aab-8e2335bc8b68.png)

**Comment by cdtennant** [comment]
I failed to notice that in my example, it wasn't just the `friedrich_coefficients` that have an issue, but the `max_langevin_fixed_point` is also not being computed when going from 5 to 3 samples.

**Comment by MaxBenChrist** [comment]
I think you have a bug in your notebook somewhere, I couldn't reproduce the bug with the data that you provided. 

To help you, I need an ipython notebook that contains the whole workflow:

* loading packages
* loading data
* splitting data into the 3 and 5 sample dataframe
* extract features

After I have that, I can debug this.

**Comment by cdtennant** [comment]
Hi Max,

Sure thing! Please find attached an ipython notebook (forMax.ipynb) and the data file (X_test_data.csv). After running the notebook you should see that the features I've defined are computed when 5 time signals are used, but when two signals are removed from the data set, none of the features are computed.
Let me know if you have any questions or if anything is unclear.Thanks,chris
    On Sunday, July 7, 2019, 03:36:11 AM EDT, Maximilian Christ <notifications@github.com> wrote:  
 
 
I think you have a bug in your notebook somewhere, I couldn't reproduce the bug with the data that you provided.

To help you, I need an ipython notebook that contains the whole workflow:
   
   - loading packages
   - loading data
   - splitting data into the 3 and 5 sample dataframe
   - extract features

After I have that, I can debug this.

**Comment by cdtennant** [comment]
@MaxBenChrist, I sent you an e-mail with the ipython notebook and data file attached. Thanks.

**Comment by MaxBenChrist** [comment]
There is no bug in the feature extraction. 

The features for the first 4 samples will return NaNs. When you extract only the first 3 samples, those NaNs are get set to 0.

If you extract 5 Samples, the values of the features for the last sample are used to impute the first 4 sample. This is the reason why in the case with 5 samples you get different values

Just remove the impute from the extract_features and you are good to go.
