### ISSUE TITLE
sklearn transformers docs example fails

### ISSUE THREAD

**Issue by Whamp** [blue-yonder/tsfresh#546]
Hi I tried to run the tsfresh example located here:

https://tsfresh.readthedocs.io/en/latest/text/sklearn_transformers.html

and I got two errors, one I fixed and one that I'm raising here. 

I'm running:
tsfresh-0.11.2
pandas-0.24.2
system is Ubuntu 18.04

The first error was the example requires the following code to be run before you can run the actual code shown in the example:

```python
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures
download_robot_execution_failures()
```

This seems like a simple fix to the docs to me. 

However after downloading the data and running the exact code shown in the example as shown here:

```python
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from tsfresh.examples import load_robot_execution_failures
from tsfresh.transformers import RelevantFeatureAugmenter

pipeline = Pipeline([('augmenter', RelevantFeatureAugmenter(column_id='id', column_sort='time')),
            ('classifier', RandomForestClassifier())])

df_ts, y = load_robot_execution_failures()
X = pd.DataFrame(index=y.index)

pipeline.set_params(augmenter__timeseries_container=df_ts)
pipeline.fit(X, y)
```
I get the following error:
![screencapture-localhost-8888-notebooks-Dalton-USA-USA-Feature-Creation-and-Modeling-Stacker-ipynb-2019-06-12-16_27_46](https://user-images.githubusercontent.com/1115485/59393199-6f316c00-8d2f-11e9-9e5b-a04aae1a16c1.png)

**Comment by nils-braun** [comment]
Thanks for the issue and sorry for the super-late answer. Running the example now it works with the current tsfresh version. I will fix the issues with the imports.

Sorry again for the delay!
