### ISSUE TITLE
Multiprocessing stops working when random seed is set

### ISSUE THREAD

**Issue by thepycoder** [blue-yonder/tsfresh#554]
When working in a Jupyterlab environment, when setting python's random seed to anything causes the Multiprocessing functionality of tsfresh to stop working. The progress bar appears but does not leave 0%. Htop also suggests no calculations are taking place at all.

1. Your operating system
The Jupyterlab environment runs on a Google Cloud AI Platform VM, which runs Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
using python 3.5.3

2. The version of *tsfresh* that you are using
0.11.2

3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
Any data that I tried

4. A minimal code snippet which reproduces the problem/bug
```
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, \
    load_robot_execution_failures
download_robot_execution_failures()
timeseries, y = load_robot_execution_failures()

import random

random.seed = 42

from tsfresh import extract_features
extracted_features = extract_features(timeseries, column_id="id", column_sort="time")
```

This won't progress. But when either:

- Commenting out the random.seed
- Setting n_jobs=0

It will work perfectly. When applying any of these changes, restart kernel to get effect (and reset the seed).

5. Any reported errors or traceback
When interrupting the frozen process I get the following error stack (always the same). The rest of the error is just the keyboard interrupt, but the empty deque is an interesting one.
![image](https://user-images.githubusercontent.com/11781950/60876345-078e1400-a23c-11e9-85e0-e56338f1e21e.png)

**Comment by MaxBenChrist** [comment]
This looks like an issue inside the multiprocessing library (See also https://stackoverflow.com/questions/44488981/why-this-small-snippet-hangs-using-multiprocessing-with-maxtasksperchild-numpy?rq=1)

Can you try if it also hangs with python 3.6 or 3.7?

**Comment by thepycoder** [comment]
I tried locally to verify:
Python 3.5.7 and Python 3.6.8 show the issue


Python 3.7.4 is fine though, that works. Any idea?

**Comment by nils-braun** [comment]
Hi @thepycoder 

thanks for the issue. Actually, as @MaxBenChrist mentioned, this is an upstream issue with the `multiprocessing` package. You can verify with this code:

```python3
def run_function(argument):
    return argument


import random
import multiprocessing

random.seed = 42
pool = multiprocessing.Pool(processes=multiprocessing.cpu_count() // 2)

for i in pool.imap_unordered(run_function, list(range(100))):
    print(i)
```
which also hangs (and does not use tsfresh at all). I guess the reason it works with 3.7 is that they changed the way the random state is handled (using this https://github.com/python/cpython/commit/346cbd351ee0dd3ab9cb9f0e4cb625556707877e).

If you really need the random state setting, you can also use a 
```
import multiprocessing
multiprocessing.set_start_method('spawn', True)
```
(but then you need to put everything into a `__main__` function).
