### ISSUE TITLE
Not able to import tsfresh in jupyter

### ISSUE THREAD

**Issue by vule-de** [blue-yonder/tsfresh#556]
Hi guys, I'm facing a problem importing tsfresh in jupyter notebook with python 2. Although the  python command line works fine with tsfresh, I can't import tsfresh in jupyter. 
1. Your operating system
RHEL 7.5
2. The version of *tsfresh* that you are using
0.11.0
3. When I import in Jupyter, I get the following error.
```
ImportErrorTraceback (most recent call last)
<ipython-input-1-5710679c9656> in <module>()
----> 1 import tsfresh

/apps/anaconda2/lib/python2.7/site-packages/tsfresh/__init__.py in <module>()
      2 
      3 """
----> 4 At the top level we export the three most important submodules of tsfresh, which are:
      5 
      6     * :mod:`~tsfresh.extract_features`

ImportError: No module named settings
```
I found file settings.py in folder ...site-packages/tsfresh/feature_extraction. After doing a hack to sys.path, the problem still exists but with different import.
```
sys.path.append("/apps/anaconda2/lib/python2.7/site-packages/tsfresh/feature_extraction")
import tsfresh
```

```
ImportErrorTraceback (most recent call last)
<ipython-input-5-0a3489d32393> in <module>()
      1 sys.path.append("/apps/anaconda2/lib/python2.7/site-packages/tsfresh/feature_extraction")
----> 2 import tsfresh

/apps/anaconda2/lib/python2.7/site-packages/tsfresh/__init__.py in <module>()
      2 
      3 """
----> 4 At the top level we export the three most important submodules of tsfresh, which are:
      5 
      6     * :mod:`~tsfresh.extract_features`

/apps/anaconda2/lib/python2.7/site-packages/tsfresh/feature_extraction/settings.py in <module>()
     17 from itertools import product
     18 
---> 19 from tsfresh.feature_extraction import feature_calculators
     20 from tsfresh.utilities.string_manipulation import get_config_from_string
     21 

ImportError: No module named feature_extraction
```
I'm not sure the problem is with tsfresh or jupyter. Any help is appreciated, thanks

**Comment by MaxBenChrist** [comment]
Please update tsfresh to 0.12.0

Von meinem iPhone gesendet

**Comment by vule-de** [comment]
Is it a known problem for tsfresh 0.11.0. Because tsfresh 0.12.0 requires to upgrade a lot of library in our current Anaconda setup, including major libs like numpy, scipy ..., which may lead to a lot of incompatibility issue. That's why I choose to install version 0.11.0. Can I have a work around or something?
