### ISSUE TITLE
Imputing  nan and inf values 

### ISSUE THREAD

**Issue by senjed** [blue-yonder/tsfresh#558]
Hi, 
My data does not contain any nan values. However, after extracting features with tsfresh,  I get a data frame that has many nan and non-finate values. Do you have any insight on what imputation method works the best for filling the nan values? There are so many types of features and I guess they have to be dealt with in a different manner based on the feature type(I do not mean categorical or numerical by type).

**Comment by MaxBenChrist** [comment]
We do not have a feature dependent imputing method. 

First I am not sure if such a method would provide that much of value to a classifier/regressor that is trained on the feautures. Maybe it will but I think for most applications, the imputing strategies that are implemented, e.g. in scikit learn are sufficient. 

If you are interested in a dedicated imputer, you would have to go over all the feature calculators and define specific strategies. However, I just did this quickly and checked a few cases where we raise NaNs. E.g. in the `ar_coefficient` feature calculator we raise a NaN if the fitting of the ar model raised an error. I am not sure how you would impute that in a dedicated fashion?

**Comment by senjed** [comment]
Thanks for your answer. So I think for the example that you provided it's better to just drop nan values and not try to impute them.

**Comment by nils-braun** [comment]
I am closing as I think the question has been answered. Please feel free to reopen.
