### ISSUE TITLE
Problems with  FeatureSignificanceTestsSettings

### ISSUE THREAD

**Issue by etkaminski** [blue-yonder/tsfresh#560]
Hello Max,
Thanku so much for tsfresh and making my master thesis possible. I am having a problem when I try to change the fdr_level for my relevant features extraction. The issue is that I become an error while importing FeatureSignificanceTestsSettings. 
My current version is 0.12.0 while i already tried with the 2 versions before and that didnt solve the problem. I am operating on windows. 

O also tried with from tsfresh.feature_selection.settings import FeatureSignificanceTestsSettings as i saw in the documentation and also didnt work 

``` python
import pandas as pd
import numpy as np
from tsfresh import defaults
from tsfresh.utilities.dataframe_functions import check_for_nans_in_columns
from tsfresh.feature_selection.relevance import calculate_relevance_table
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, load_robot_execution_failures
from tsfresh import extract_features, extract_relevant_features, select_features, feature_selection  
from tsfresh.utilities.dataframe_functions import impute
from tsfresh.feature_extraction import ComprehensiveFCParameters


from tsfresh.feature_selection import FeatureSignificanceTestsSettings
sett = FeatureSignificanceTestsSettings()
sett.fdr_level = 0.99 # increases the risk of unimportant features being extracted
sett.write_selection_report = True # will create a report with more information
ImportError: cannot import name 'FeatureSignificanceTestsSettings'
```

It would be awesome if you knew how to solve this. I wish you a nice day:
Erik

**Comment by MaxBenChrist** [comment]
Hi Eric, 

I don't understand where you have that snippet with the `FeatureSignificanceTestsSettings`. 

The fdr level is a argument of the select_features method, no need to initiate any settings

**Comment by Marble90** [comment]
Hi,
there is this Document: https://tsfresh.readthedocs.io/_/downloads/en/v0.7.0/pdf/
which uses:
>>> from tsfresh.feature_selection import FeatureSignificanceTestsSettings
>>> settings = FeatureSignificanceTestsSettings()
>>> settings.fdr_level = 0.1
>>> from tsfresh.feature_selection import select_features
>>> select_features(X, y, feature_selection_settings=settings)

**Comment by nils-braun** [comment]
Just to note: that document uses version 0.7.0 of tsfresh (from 2018). I don't think it is wrong in the current version, or?
