### ISSUE TITLE
Extracting features for single time series

### ISSUE THREAD

**Issue by ivan94fi** [blue-yonder/tsfresh#564]
Hi I would like to know if there is a standard way of extracting features from a single time series instead of a set of time series, for the purpose of outlier/anomaly detection on the single time series.

For single time series I mean an univariate time series, with a single observed value, e.g:

timestamp | value
-------------- | -------
12-11-2009 | 23
13-11-2009 | 28
14-11-2009 | 27
15-11-2009 | 10 
16-11-2009 | 25
17-11-2009 | 24

My intention would be to extract features for each data point, in order to train an unsupervised model for anomaly detection (e.g. Isolation forest or One-Class SVM) with a classical n datapoints x m features dataset:

timestamp  | value | feature_1 | feature_2 | ... | feature_m |
--------------- | ------- | ------------- | -------------| -- | -------------- |
12-11-2009 |   23   |     0.350    |    0.501   | ... |     0.922    |
13-11-2009 |   28   |     0.099    |    0.321   | ... |     0.778    |
14-11-2009 |   27   |     0.383    |    0.285   | ... |     0.125    |
15-11-2009 |   10   |     0.597    |    0.618   | ... |     0.771    |
16-11-2009 |   25   |     0.945    |    0.173   | ... |     0.054    |
17-11-2009 |   24   |     0.019    |    0.957   | ... |     0.089    |

Is this something possible in `tsfresh`?

Thank you for your support and for this amazing package!

**Comment by nils-braun** [comment]
I am not sure I understand your issue correctly.

`tsfresh` extracts features of time series - this means some data that vary over time. In your example you want to extract features from one single value independently at every time step?

If you want to have features which are calculated on a rolling time series, we have that covered: https://tsfresh.readthedocs.io/en/latest/text/forecasting.html

Please reopen in case I misunderstood.

**Comment by ivan94fi** [comment]
Yes thank you. I did end up using the rolling mechanism in the end.
