### ISSUE TITLE
[Building issue - arm64]

### ISSUE THREAD

**Issue by 3sztof** [blue-yonder/tsfresh#565]
### Dear Devs,

I am not sure if this actually concerns you, but I have no idea who else would care... I think that something is terribly wrong with the automated build process of tsfresh (or rather its dependencies) on ARM64 (where pip can't pull wheels for numpy, pandas statsmodels, it tries to build them).

What I have been doing is trying to build a snap using the python plugin (with python-package tsfresh as a dependency for my part). When compiling natively on ARM64, the build fails with corss-dependency errors (for instance pandas depends on numpy, which could not be found).

This is rather not an issue with Snapcraft, but with the build process using pip (the dependencies are built in wrong order, perhaps?)

What I have tried:
- Building natively on Raspberry PI Ubuntu Core 18 (with snapcraft cleanbuild)
- Building natively in 'docker in docker' with qemu arm64 emulation
- Building with launchpad
- Installing tsfresh on Raspberry PI using pip3 (the deps still need to be built - it seems that the issue persists there - mostly module numpy not found).

Or maybe the question should be: is ARM64 architecture supported at all? :(

All the best,
Krzysztof

**Comment by nils-braun** [comment]
Hi @3sztof !
Nice you try that out - looks like a super cool project.
To be honest, at least I have never tried that. I think we could first try to fix the very last bullet point (installing it native on the RP) before going into more "complicated" things (like snap).

So If numpy is really the problem, have you tried installing it with apt?

`apt-get install python3-numpy`

I think RP should automatically use piwheels (https://www.raspberrypi.org/blog/piwheels/) but should fall back to PyPi if something is wrong. Maybe this is not working properly?

Sorry for not giving you a good answer already...

**Comment by 3sztof** [comment]
Hello @nils-braun,

Thanks! It is indeed a cool project, a part of my master thesis to be precise (more details will be released in the upcoming months). The feature extraction is supposed to run on ARM64 based PLC controller. Hopefully it will work! 😄 

I just want to mark: if you somehow fix pip3 building issue, snapcraft issues should be fixed too... in principle.

About piwheels, I am not sure if they are supported on Ubuntu for PI (which should be used to build snaps) Perhaps I should try building on Raspbian (which is not reccomended by Canonical, but thats my problem 😢).

I have tried using apt python3-numpy, python3-pandas and python3-scipy packages as preinstalled depencencies before. The problem with those is that apt usually doesn't host the newest versions. For instance, scipy version required by statsmodels (which is pulled by tsfresh) is 0.18.0, while apt install python3-scipy provides 0.17.0...
Uninstalling python3-scipy and trying to build it results in:
``` numpy.distutils.system_info.NotFoundError: No lapack/blas resources found. ```
Looks like a gcc / g++ issue to me... That's why I don't know who should I ask for a solution... its the dependencies that are failing here...

I will try to build using piwheels on Raspbian now. The problem is that it doesn'y really solve the issue for other ARM64 machines which would build and run tsfresh in the future and are not PIs 😢).

**Comment by 3sztof** [comment]
## Temporary solution below

I have managed to prepare the aarch64/arm64 wheels for tsfresh and all of its dependencies. If you need to run it on arm64 and encounter dependency (mostly numpy/scipy/statsmodels in my case) compilation problems (or just want to save A LOT of time building those), just follow the instructions in the repo linked below:

[https://github.com/3sztof/master-thesis-wheelhouse](https://github.com/3sztof/master-thesis-wheelhouse)

Note that this prebuilt wheelhouse is just for tsfresh 0.12.0.
Hopefully it will help some poor soul in the future! 😄 

All the best,
[Krzysztof](https://linkedin.com/in/3sztof)
