### ISSUE TITLE
multivariate time series regression

### ISSUE THREAD

**Issue by quancore** [blue-yonder/tsfresh#566]
I have a **z** different time series with different lengths. For each time series, there are a different number of time points with timestamps and for each time point, there is an **m** different features and observed float outcome for this time point. My aim is modeling a regressor (given m features what is the outcome). I have trained a regressor by omitting the temporal dimension of a dataset (train on all data points using m features and predict the outcome), but it resulted in a poor result. 

My aim is to add temporal dimension for each time point (for each time point, mean of past values of features, std of past feature values etc). As far as I understand, I can use rolling of features, however, the function creates new time series for rolling, which does not make sense to me. My aim is to add rolling features of an original feature like a column for each time point rather than a new time series. How can I resolve it? (I have checked examples but all of them focusing on univariate time series prediction after observing several data point).

**Comment by nils-braun** [comment]
Sorry for the late answer! Your question just slipped through...
Yes, you are right. That is the exact use case of rolling.
We need to create "new" time series - however out of the already present time series. Actually what you want to do is "forecasting", which is described in our docu: https://tsfresh.readthedocs.io/en/latest/text/forecasting.html
It does not matter if you have one dimension or multiple - the rolling and feature extraction works the same. However, please note that `tsfresh` only does feature extraction on one dimension at a time.

Let me give you an example why we need "new" time series. The input to `tsfresh` is always a bunch of timeseries (uni- or multidimensional) separated by `id` and it will output the features for all of the `id`s separately. If you now want to extract the features for all values until timestep `t_1`, then for all values until timestep `t_2`,... you need to have an input timeseries with all values starting from 0 to `t_1` (and give it an `id`), then one for all values from 0 to `t_2` (give it another `id` etc.)
That is why we need to do rolling.

**Comment by PhilipMachineLearning** [comment]
The multivariate forecasting does't work for me:

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by nils-braun** [comment]
Could you share your code and data? Because it is very hard to help you without that.
You can also open a new issue if you want

**Comment by PhilipMachineLearning** [comment]
No worries thanks @nikhase solved now I'm using TSFEL now worked in 10 seconds. 

The architecture design for rolling TS could be redesigned and simplified to make it easier to use - check out the source code for TSFEL.

**Comment by nils-braun** [comment]
Thanks for the feedback - we are aware of the TSFEL library (it is a great tool). I would love to understand what makes the TSFEL API easier - so as to improve tsfresh. As far as I see, TSFEL has the option to roll directly in the feature extraction function whereas tsfresh has split up the two in two separate functions. Is this the difference? Sorry for my naive question, maybe you can still share your (maybe now TSFEL) code so that we can understand where we can improve!
