### ISSUE TITLE
Does tsfresh need new maintainer(s)?

### ISSUE THREAD

**Issue by Froskekongen** [blue-yonder/tsfresh#579]
The maintainer seems to be inactive for the moment. Is this due to this news (https://now.jda.com/blueyonder)? In any case, it would be sad for tsfresh to grow stale. It would be nice with some information on this matter (:

**Comment by rpanai** [comment]
@Froskekongen the acquisition was completed on August 2018 [see](https://www.cloudpro.co.uk/operations/7613/jda-completes-acquisition-of-blue-yonder-to-boost-ai-tech).
But then you are right to rise the hand as you have several open PR.

**Comment by MaxBenChrist** [comment]
I am the only maintainer at the moment. Unfortunately, I only have limited amount of time to spend on tsfresh. This is unrelated to the acquisition of blue-yonder by JDA, personally, I left blue-yonder in 2017. I will try to go over the open pull requests in the next days

**Comment by nils-braun** [comment]
I will try to again work more on tsfresh in the near future - so there should be two maintainers around. Sorry for the long pause!
I started by looking into some of the PRs. I am also in the process of triaging some issues and closing them. Hope we get down to a manageable number of issues soon :-)

(For example closing this one ;-))

**Comment by dbarbier** [comment]
At the moment, the most annoying issue IMHO is conda package depending on pandas <= 0.23.4, any chance to have that fixed soon?  Thanks.

**Comment by nils-braun** [comment]
I see. I will try to have a look into the corresponding PRs. Still need to catch up a little ;-)

**Comment by nils-braun** [comment]
I have now cleaned up the issues a bit so we can at least have a better overview again :-) 
Next thing is the python 2.7 support drop and then comes the pandas version problems.
Thank you so much for being patient and helping us out! :tada: :coffee:
