### ISSUE TITLE
Missing terms on C3 linearity check inplementation

### ISSUE THREAD

**Issue by eduardojlbatista** [blue-yonder/tsfresh#585]
Good day sir. I've been testing your library for feature selection and have been excited with the ideas presented. However, while scanning through the docummentation of the C3 feature calculator I noticed an error on the algorythm. While you present it as a mean of the lag operator in the form of "E[L^2(X)^2*L(X)*X]", while coding there's a missing square on the formulation. I attached some examples I tried to check if I wasn't mistake. Hope it helps! Thank you very much for your hard work!

1. Windows
2. Tsfresh version 0.12.0
3. x = pd.Series([1, 1, 6, 9, 5, 4, 1, 2])
4. 
lag = 2
np.mean((_roll(x, 2 * -lag) * _roll(x, -lag) * x)[0:(n - 2 * lag)])
np.mean((x**2) * x.shift(periods=lag) * x.shift(periods = 2*lag))

5. From the formulation I was expecting that, for a simple example like the series t, the resulting value would be 117 but, instead got 42. I compared it with my own implementation of the formula, which I thought was somewhat clearer. Hope you can check it and, if it's wrong, fix it. 

Thank you very much!

**Comment by dbarbier** [comment]
My understanding is that code is right but there are 2 errors in docstring, i should start from 1 and square exponentiation must be removed, ie:

     C3 = \mathbb{E}[L^2(X) \cdot L(X) \cdot X] = \frac{1}{n-2lag} \sum_{i=1}^{n-2lag} x_{i + 2 \cdot lag} \cdot x_{i + lag} \cdot x_{i}

<a href="https://www.codecogs.com/eqnedit.php?latex=\mathbb{E}[L^2(X)&space;\cdot&space;L(X)&space;\cdot&space;X]&space;=&space;\frac{1}{n-2lag}&space;\sum_{i=1}^{n-2lag}&space;x_{i&space;&plus;&space;2&space;\cdot&space;lag}&space;\cdot&space;x_{i&space;&plus;&space;lag}&space;\cdot&space;x_{i}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\mathbb{E}[L^2(X)&space;\cdot&space;L(X)&space;\cdot&space;X]&space;=&space;\frac{1}{n-2lag}&space;\sum_{i=1}^{n-2lag}&space;x_{i&space;&plus;&space;2&space;\cdot&space;lag}&space;\cdot&space;x_{i&space;&plus;&space;lag}&space;\cdot&space;x_{i}" title="\mathbb{E}[L^2(X) \cdot L(X) \cdot X] = \frac{1}{n-2lag} \sum_{i=1}^{n-2lag} x_{i + 2 \cdot lag} \cdot x_{i + lag} \cdot x_{i}" /></a>

**Comment by nils-braun** [comment]
@dbarbier or @eduardojlbatista Do you want to supply a PR to fix this docstring issue? Thanks!
