### ISSUE TITLE
Add feature class: Count/Percentage same value

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#59]
I had an idea for a class of features. 

1.  percentage of data points that occur at least second time 
2. sum of data points that occur at least second time 
3. percentage of observed values that occur at lest second time 
...

**Comment by nils-braun** [comment]
@MaxBenChrist if this issue is not already assigned to someone else, I would take care of this.

**Comment by MaxBenChrist** [comment]
Go for it!
