### ISSUE TITLE
tsfresh never passes 0% when there are around 67+ rows per ID. 

### ISSUE THREAD

**Issue by CampbellPryor** [blue-yonder/tsfresh#596]
1. Your operating system
Ubuntu 16.04.6
2. The version of *tsfresh* that you are using
0.12.0
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)

Dataframe with 3 columns (id, datetime, value)
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 4 columns):
index       87 non-null int64
id          87 non-null int64
datetime    87 non-null datetime64[ns]
value       87 non-null float32
dtypes: datetime64[ns](1), float32(1), int64(2)
memory usage: 2.5 KB
```

4. A minimal code snippet which reproduces the problem/bug
```
import numpy as np
from tsfresh import extract_features
from tsfresh.feature_extraction import EfficientFCParameters

a = pd.DataFrame({'id': np.repeat(1,100), 'datetime': pd.to_datetime(np.arange(100)*10e13), 'value': np.random.rand(100)})
a = a.head(67)
b = extract_features(a, column_id='id', column_sort='datetime', default_fc_parameters=EfficientFCParameters())
```

The feature extraction successfully completes in <5 seconds, if I instead only have 65 rows:
```
a = a.head(65)
b = extract_features(a, column_id='id', column_sort='datetime', default_fc_parameters=EfficientFCParameters())
```

The feature extraction also successfully completes when I have multiple IDs with 65 rows per group:
```
a = pd.DataFrame({'id': np.repeat([1,2],100), 'datetime': pd.to_datetime(np.arange(200)*10e13), 'value': np.random.rand(200)})
a = a.groupby('id').head(65)
b = extract_features(a, column_id='id', column_sort='datetime', default_fc_parameters=EfficientFCParameters())
```

5. Any reported errors or traceback
No. The code simply stalls with `Feature Extraction:   0%|          | 0/2 [00:00<?, ?it/s]` indefinitely.

**Comment by dbarbier** [comment]
@CampbellPryor  I cannot reproduce your problem.  Your example does not import pandas, so it cannot work, and maybe there are other things in your working environment which cause some trouble.  If you write your snippet into a file and run python on it directly, does it work?

**Comment by CampbellPryor** [comment]
@dbarbier Thanks for the reply. You are correct that it was some other code run earlier that seems to be triggering the issue. I am running this on Azure and it is after I convert a dataframe from spark to pandas that the issue then occurs. This is not reproducible code but just noting it for reference:

```
from pyspark.sql.functions import *
from pyspark.sql import *
import pandas as pd
import numpy as np
from tsfresh import extract_features, select_features
from tsfresh.feature_extraction import EfficientFCParameters

spark_df = function_to_read_in_spark_df()
df = spark_df.toPandas() # It is only if I run this line that the issue occurs.

a = pd.DataFrame({'id': np.repeat([1,2],100), 'datetime': pd.to_datetime(np.arange(200)*10e13), 'value': np.random.rand(200)})
a = a.groupby('id').head(67)
b = extract_features(a, column_id='id', column_sort='datetime', default_fc_parameters=EfficientFCParameters())
```

It is not a memory issue given I am well below capacity and creating a much larger, irrelevant dataframe doesn't cause any issue. E.g.:
```
import pandas as pd
import numpy as np
from tsfresh import extract_features, select_features
from tsfresh.feature_extraction import EfficientFCParameters

irrelevant_df = pd.DataFrame({'id': np.random.rand(80000000).astype(str), 'datetime': pd.to_datetime(np.random.rand(80000000)), 'value': np.random.rand(80000000)})
import sys
print(sys.getsizeof(irrelevant_df)/1e6)
# Try out on made up data. Works with 65 rows. Not with 67 rows.
a = pd.DataFrame({'id': np.repeat([1,2],100), 'datetime': pd.to_datetime(np.arange(200)*10e13), 'value': np.random.rand(200)})
a = a.groupby('id').head(67)
b = extract_features(a, column_id='id', column_sort='datetime', default_fc_parameters=EfficientFCParameters())
```

**Comment by nils-braun** [comment]
Hm - interesting.
Have you tried to turn off multi-processing by setting the jobs to 0?

**Comment by CampbellPryor** [comment]
@nils-braun Setting n_jobs=0 fixes the issue! I'm not on top of tsfresh's extract_features process or the processing restrictions of my current Azure cluster enough to easily identify why this worked. Nevertheless, I am happy for this issue to be closed unless anyone else is wanting to look into this further.

**Comment by nils-braun** [comment]
It seems we do have some strange multiprocessing issues going on. 
Glad it helped, I will need to have a look sometimes in the future...
