### ISSUE TITLE
On DASK, extract_features raises ValueError: You have NaN values in your id column.

### ISSUE THREAD

**Issue by LutzFassl** [blue-yonder/tsfresh#597]
Dear all!

I got a strange error when using DASK:
`ValueError: You have NaN values in your id column.`

OS: Windows 10, 64bit
tsfresh0.12.0

**data:** 
- dask dataframe consisting of 13 flat pandas dataframes in parquet format
- Columns: Index(['DateTime', 'GunVoltage', 'Run'], dtype='object')
Dtypes:
- DateTime      datetime64[ns]
- GunVoltage           float64
- Run                   object

Data content
- Run column has just strings like "19B0365"
- GunVoltage has floats between 0-60
- Datetime is a date+time in ms notation (that was cut down from us notation when saved to parquet)

**Code:**
```
import dask.dataframe as dd
df = dd.read_parquet("dask_df/*.parquet", engine='pyarrow')


from tsfresh.feature_extraction import extract_features
from tsfresh.utilities.distribution import LocalDaskDistributor
Distributor = LocalDaskDistributor(n_workers=2)
X = extract_features(timeseries_container=df,
                     column_id="Run",
                     column_sort="DateTime",
                     column_value="GunVoltage",
                     distributor=Distributor)
```

The error raises in
```
dataframe_functions.py in _normalize_input_to_internal_representation
if timeseries_container[column_id].isnull().any():
```

But that's a bit strange, because when I try to validate this I get a different result:
`df["Run"].isnull().any().compute()`
results in **False**

I confirmed the same is running fine when using one pandas df instead of the DASK df.
Also the dask df seems fine, I can run computations on it like df["GunVoltage"].mean().compute()
The ddf is very small at the moment for testing (no problem with size), only 3200 rows.
Can anyone reproduce the error or please help me with this problem?
Is it possible that the code handles the df like it's a pandas df and not a dask df, which might explain why it sees no values?

Here is the full error log:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-44-aa2dcf87f2e2> in <module>
     10                      column_sort="DateTime",
     11                      column_value="GunVoltage",
---> 12                      distributor=Distributor)

C:\ProgramData\Anaconda3\envs\p36NN\lib\site-packages\tsfresh\feature_extraction\extraction.py in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor)
    152             column_id=column_id, column_kind=column_kind,
    153             column_sort=column_sort,
--> 154             column_value=column_value)
    155     # Use the standard setting if the user did not supply ones himself.
    156     if default_fc_parameters is None and kind_to_fc_parameters is None:

C:\ProgramData\Anaconda3\envs\p36NN\lib\site-packages\tsfresh\utilities\dataframe_functions.py in _normalize_input_to_internal_representation(timeseries_container, column_id, column_sort, column_kind, column_value)
    293 
    294     if timeseries_container[column_id].isnull().any():
--> 295         raise ValueError("You have NaN values in your id column.")
    296 
    297     # Check sort column

ValueError: You have NaN values in your id column.
```

**Comment by nils-braun** [comment]
Hi @LutzFassl 
so did I understand it correctly that you are passing in a `dask` DataFrame and not a `pandas` DataFrame?
Even when you are using the dask distributor, `tsfresh` still expects a pandas dataframe.

Some technical details:
The line where it breaks (`if timeseries_container[column_id].isnull().any()`) is only valid for pandas dataframes.
For dask dataframes, it would need to call the `.compute()` as you did it in your example. If you remove the `.compute()` it just gives you the dask computation object which happens to be `True` when casted to a boolean.

**Comment by LutzFassl** [comment]
Hi @nils-braun 
Yes, that's correct. When I read about dask support, I immediately assumed dask dataframe support. Now the behavior is clear, thanks.

Maybe I can ask you a question:
I wanted to use a dask dataframe because I have 150Mio rows to analyze by tsfresh (currently in 13 parquet files). If I put them in one pandas dataframe, even with the EfficientParameters, my machine (16GB ram, quadcore i7) will not produce any results / will crash after hours. (I used n_jobs=6 or 8, maybe I should avoid using n_jobs because the error in the end is related to multiprocessing).
May I ask what would be the correct behavior in this case: Downsample/Slice the data if possible or splitting up the data in multiple pandas dataframes, each with only one ID, and use the extract_features routine on each of them individually?

**Comment by nils-braun** [comment]
I would probably go with the last possibility, so plit it up into the IDs and run it on each ID separately (or only on a few IDs). Also makes it easier to maybe store the results.
You could even use things as luigi/airflow etc. to control it (I wanted to write some help on this, but if you figure it out we are happy for a PR ;-))

If you have access to a compute cluster you could of course use some distributed dask process... ;-)

**Comment by nils-braun** [comment]
Closing. Feel free to reopen if you have another question.
