### ISSUE TITLE
Fix pypi package overview and documentation

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#6]
Currently, travis is starting "setup.py upload" which uploads tsfresh to pypi. This setup py also uses the README.MD as the package description on pypi. [However, the documentation looks bad because pypi does not support the github markdown highlighting](https://pypi.python.org/pypi/tsfresh/0.1.0) We should have a separate readme for pypi. 

Also, pypi or travis seem to uploaded not only to rtd but also to [http://pythonhosted.org/tsfresh/](http://pythonhosted.org/tsfresh/). This seems like a waste of resources, we should only hoste it on rtd (I prefer rtd because you can directly edit the documentation in your browser)

**Comment by MaxBenChrist** [comment]
Further, there seem to be an issue with the autodoc importer on read the docs

http://tsfresh.readthedocs.io/en/latest/api/tsfresh.convenience.html

**Comment by MaxBenChrist** [comment]
the read the docs problem with autodoc was solved by activating the installation of the project package in the read the docs advantage settings

**Comment by jneuff** [comment]
https://github.com/blue-yonder/tsfresh/commit/9862ee965de2299b92b00ce3ce2b919683e0cf20

**Comment by MaxBenChrist** [comment]
the documentation is still uploaded to python hosted as the option 

`with-docs=0`

in setup.cfg is ignored. We can tackle this manually by uploading the pypi_index.zip manually to pypi after each release deployment.
