### ISSUE TITLE
How do extracted features and regression make predictions?

### ISSUE THREAD

**Issue by rhagan09** [blue-yonder/tsfresh#600]
Hi, 

I was wondering if someone could explain exactly how the extracted features from a time series are used with regression models (i.e. AdaBoost Regressor) to make predictions of the time series?

I have read the documentation and can't seem to find an exact answer on how the predictions are actually made. 

Many thanks, 
Rachael.

**Comment by nils-braun** [comment]
Hi,
tsfresh is a feature extraction (and selection) library. The idea is not to do any kind of machine learning/training etc. but use other packages for that (e.g. the adaboost you mentioned). So if you want to understand how a regression works I guess the best place is to start with those packages and/or some online documentation on machine learning in general (there is really a lot out there, I guess you will find something).

If you have a specific tsfresh question/issue I am happy to answer that. Just reopen this issue :-)
