### ISSUE TITLE
Explain the FeatureExtractionSettings object in documentation

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#61]
Especially how to control which features are calculated with `setting.name_to_param` dictionary.

**Comment by MaxBenChrist** [comment]
Further we should explain how to prevent unnecessary features being calculated with the from columns method

**Comment by MaxBenChrist** [comment]
@nils-braun Keen to write some documentation? :)

**Comment by nils-braun** [comment]
Will be fixed with #133 - so in the next version.

**Comment by MaxBenChrist** [comment]
is obsolete like the extraction settings object :D

**Comment by nils-braun** [comment]
:+1: I like solving issues by deleting the code they are referring to :-D
