### ISSUE TITLE
number_crossing_m implementation

### ISSUE THREAD

**Issue by Armannas** [blue-yonder/tsfresh#615]
tsfresh version: 0.13.0
OS: Ubuntu 18.04.3 LTS

Would it be faster/more elegant to use np.sum() to count m-crossings?
np.where() returns where the crossings occured, followed by the amount through the size property.
It seems faster to just count the number of crossings directly by summing without inspecting where it occured.

```
x = np.array([array([1, 5, 1, 7, 7, 1])
positive = x > 2
```
```

print(np.where(np.diff(positive))[0].size)
4
```
Same solution:
```
print(np.sum(np.diff(positive)))
4
```

**Comment by nils-braun** [comment]
I am with you with the "more elegant", but I am not with you with the "faster" ;-)

```python3
from timeit import timeit
timeit("np.where(np.diff(positive))[0].size", "import numpy as np; positive = np.array([1, 2, 1, 1, 0, -3, -4, 7, 8, 9, 10, -2, 1, -3, 5, 6, 7, -10])", number=1000000)
3.9557633709628135
timeit("np.sum(np.diff(positive))", "import numpy as np; positive = np.array([1, 2, 1, 1, 0, -3, -4, 7, 8, 9, 10, -2, 1, -3, 5, 6, 7, -10])", number=1000000)7.3964086779160425
```

I guess the reason is that `where` is really optimized for boolean, whereas `sum` seems to have some problems with it.

**Comment by nils-braun** [comment]
But I am happy to hear more ideas!
Faster is always better, so please do not stop to open these issues! Thanks for that
