### ISSUE TITLE
fft_aggregated__aggtype_"skew" produces different results on Windows and Linux

### ISSUE THREAD

**Issue by apcarp** [blue-yonder/tsfresh#616]
# Problem Summary
tsfresh generates different values for fft_aggregated__aggtype_"skew" on Windows and Linux given the same data.  I have attached a zip file containing a test script and CSV files of different lengths.  They are the same data, just truncated at various lengths.  I only see the differences appear for the 4096 and 8192 length files in my limited testing.

Please note that I have also tested this on the same Linux system using Python 3.6.8 and seen similar behavior.

## 1) OS Info
**LINUX**
```bash
 uname -a
Linux <hostname> 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 7.7 (Maipo)
```

```bash
python3 --version
 Python 3.6.9
```

```bash
pip3 freeze
attrs==19.3.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
dask==2.8.1
distributed==2.8.1
future==0.18.2
HeapDict==1.0.1
idna==2.8
importlib-metadata==1.1.0
jsonschema==3.2.0
more-itertools==8.0.0
msgpack==0.6.2
numpy==1.16.2
pandas==0.23.4
patsy==0.5.1
psutil==5.6.7
pyrsistent==0.15.6
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.1.2
requests==2.22.0
scikit-learn==0.20.3
scipy==1.3.3
six==1.13.0
sortedcontainers==2.1.0
statsmodels==0.10.2
tblib==1.5.0
toolz==0.10.0
tornado==6.0.3
tqdm==4.40.0
tsfresh==0.12.0
urllib3==1.25.7
zict==1.0.0
zipp==0.6.0
```

**WINDOWS**
 OS Name Microsoft Windows 10 Enterprise
Version 10.0.17763 Build 17763
System Manufacturer Dell Inc.
System Model Precision 7530
System Type x64-based PC
System SKU 0831
Processor Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz, 2904 Mhz, 6 Core(s), 12 Logical Processor(s)
BIOS Version/Date Dell Inc. 1.8.2, 4/26/2019
SMBIOS Version 3.1

```powershell
python --version
Python 3.6.8
```

```powershell
pip3 freeze
attrs==19.3.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
dask==2.8.1
distributed==2.8.1
future==0.18.2
HeapDict==1.0.1
idna==2.8
importlib-metadata==1.1.0
jsonschema==3.2.0
more-itertools==8.0.0
msgpack==0.6.2
numpy==1.16.2
pandas==0.23.4
patsy==0.5.1
psutil==5.6.7
pyrsistent==0.15.6
python-dateutil==2.8.1
pytz==2019.3
PyYAML==5.1.2
requests==2.22.0
scikit-learn==0.20.3
scipy==1.3.3
six==1.13.0
sortedcontainers==2.1.0
statsmodels==0.10.2
tblib==1.5.0
toolz==0.10.0
tornado==6.0.3
tqdm==4.40.0
tsfresh==0.12.0
urllib3==1.25.7
zict==1.0.0
zipp==0.6.0
```

## 2) tsfresh versions:
0.12.0 (most testing)
0.13.0 (also demonstrated behavior)

## 3) data
Please see attached zip file for examples. These are a single time series ranging in length from 32 to 8192 points.  Only see differences for the 4196 and 8192 files.

[tsfresh-test.zip](https://github.com/blue-yonder/tsfresh/files/3918045/tsfresh-test.zip)

## 4) code
Please see attached zip file for code.  Basic snippet is this.
```python
df = pd.read_csv(file)
ext_settings = tsfresh.feature_extraction.settings.from_columns(['GMES__fft_aggregated__aggtype_"skew"'])
features = tsfresh.extract_features(df.astype("float64"),
                                            column_id="id",
                                            column_sort="Time",
                                            impute_function=tsfresh.utilities.dataframe_functions.impute,
                                            disable_progressbar=True,
                                            default_fc_parameters={},
                                            kind_to_fc_parameters=ext_settings)
print(features)
```

[tsfresh-test.zip](https://github.com/blue-yonder/tsfresh/files/3918045/tsfresh-test.zip)

## 5) errors or tracebacks
**On Windows I get this data:**
```
...
tsfresh_4096.csv 4096
variable  GMES__fft_aggregated__aggtype_"skew"
id
1.0                                   1.779761
tsfresh_8192.csv 8192
variable  GMES__fft_aggregated__aggtype_"skew"
id
1.0                                  -1.217886
```

**On Linux I get this data:**
```
...
variable  GMES__fft_aggregated__aggtype_"skew"
id                                            
1.0                                  21.501061
tsfresh_8192.csv 8192
variable  GMES__fft_aggregated__aggtype_"skew"
id                                            
1.0                                   3.042428
```

**Comment by apcarp** [comment]
Please note, this issue is time sensitive for my application.  Thank you for your help!

**Comment by nils-braun** [comment]
Hi @apcarp - unfortunately I do not have access to any Windows machine (at least not quickly).

I tested in my linux `4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux` ubuntu 18.04.3
with both python 3.6.9 and python 3.6.8. I got the same result (the 21.501061 and 3.042428).

I tried tsfresh 0.12.0 and the newest one - both the same.

Did I understand you correctly that you were also seeing a difference between 3.6.8 and 3.6.9 on the same linux?

**Comment by nils-braun** [comment]
(let me add that I want to thank you for this very well-written issue!)

**Comment by nils-braun** [comment]
Something for you to try out to get some more ideas. This is a very much stripped down version of the calculation you are running:
```python3
from tsfresh.feature_extraction.feature_calculators import fft_aggregated
import pandas as pd
import numpy as np

x = pd.read_csv("tsfresh_8192.csv")["GMES"]


def get_moment(y, moment):
    return y.dot(np.arange(len(y), dtype=float)**moment) / y.sum()

def get_centroid(y):
    return get_moment(y, 1)

def get_variance(y):
    return get_moment(y, 2) - get_centroid(y) ** 2

def get_skew(y):
    variance = get_variance(y)
    if variance < 0.5:
        return np.nan
    else:
        return (
            get_moment(y, 3) - 3*get_centroid(y)*variance - get_centroid(y)**3
        ) / get_variance(y)**(1.5)

fft_abs = np.abs(np.fft.rfft(x))

res = get_skew(fft_abs)
print(res)
```

Maybe you could run this on the two systems and add some debugging/print statements. Then we can find out when exactly it has a problem?

**Comment by apcarp** [comment]
Thank you for the quick response!  Python 3.6.8 and 3.6.9 both returned the same results (which were different than Windows).  Sorry that was not clear, but I'm happy the rest of bug report was good.  :-)

I'll try your code and report back.

**Comment by apcarp** [comment]
I ran a slightly modified version of your code which printed out every intermediate result and found that there were no differences between linux and windows.  Not what I was expecting.  Here's the code that I ran.

```python
from tsfresh.feature_extraction.feature_calculators import fft_aggregated
import pandas as pd
import numpy as np
import sys

np.set_printoptions(threshold=sys.maxsize)
x = pd.read_csv("tsfresh_8192.csv")["GMES"]

def get_moment(y, moment):
    return y.dot(np.arange(len(y), dtype=float)**moment) / y.sum()

def get_centroid(y):
    return get_moment(y, 1)

def get_variance(y):
    return get_moment(y, 2) - get_centroid(y) ** 2

def get_skew(y):
    variance = get_variance(y)
    if variance < 0.5:
        return np.nan
    else:
        print("get_moment(y,3):", get_moment(y, 3))
        print("3 * get_centroid(y) * variance:", 3 * get_centroid(y) * variance)
        print("get_centroid(y)**3:", get_centroid(y)**3)
        print("get_variance(y)**(1.5)", get_variance(y)**(1.5))
        return (get_moment(y, 3) - 3*get_centroid(y)*variance - get_centroid(y)**3) / get_variance(y)**(1.5)

fft_abs = np.abs(np.fft.rfft(x))

print("fft_abs:", fft_abs)

res = get_skew(fft_abs)
print("res:", res)
```

**Comment by apcarp** [comment]
Here's one of the things I'm puzzling over.  If I run the script I gave you which calls tsfresh directly, my results don't match what your script generates.  I've looked at the tsfresh source and I would have thought they should produce the same results.  I'm using my IDE here, but I've gotten the same results calling directly from powershell.

I made a couple more updates to the scripts to print out centroid and variance.  Strangely, those match your script's number, but the skew is different.

My script
```python
import tsfresh
import pandas as pd

if __name__ == "__main__":

    print("tsfresh:", tsfresh.__version__)
    print("pd:", pd.__version__)

    file_list = ["tsfresh_8192.csv"]

    for file in file_list:
        df = pd.read_csv(file)
        ext_settings = tsfresh.feature_extraction.settings.from_columns([
            'GMES__fft_aggregated__aggtype_"skew"',
            'GMES__fft_aggregated__aggtype_"centroid"',
            'GMES__fft_aggregated__aggtype_"variance"',
        ])
        features = tsfresh.extract_features(df.astype("float64"),
                                            column_id="id",
                                            column_sort="Time",
                                            impute_function=tsfresh.utilities.dataframe_functions.impute,
                                            disable_progressbar=True,
                                            default_fc_parameters={},
                                            kind_to_fc_parameters=ext_settings)

        print(file, len(df))
        for i in features:
            print(features[i])
```

My output
```
tsfresh: 0.12.0
pd: 0.23.4
tsfresh_8192.csv 8192
id
1.0    312.686397
Name: GMES__fft_aggregated__aggtype_"centroid", dtype: float64
id
1.0   -1.217886
Name: GMES__fft_aggregated__aggtype_"skew", dtype: float64
id
1.0    589169.74619
Name: GMES__fft_aggregated__aggtype_"variance", dtype: float64
```

Your modified script output (minus the fft_abs):
```
get_moment(y,3): 1959129640.0396354
3 * get_centroid(y) * variance: 552676095.811638
get_centroid(y)**3: 30572219.256244536
get_variance(y)**(1.5) 452231340.6568481
get_moment(y,1) == get_centroid: 312.6863971920205

get_centroid(y): 312.6863971920205
get_variance(y): 589169.7461895451
get_skew(fft_abs) (res): 3.0424280700522432
```

**Comment by nils-braun** [comment]
Could you try this with the newest tsfresh version? Because there were some changes due to numerical instabilities.

**Comment by nils-braun** [comment]
Apart from that I am as puzzled as you are and do not have another clue right now :-/

**Comment by apcarp** [comment]
Ahh ... If I run my code with tsfresh 0.13.0 on Windows I get number that match the stripped down test and Linux.  What actually changed with regards to numerical stability?  All I see is the addition of dtype=float here.
```python
    def get_moment(y, moment):
        r"""
        Returns the (non centered) moment of the distribution y:
        E[y**moment] = \\sum_i[index(y_i)^moment * y_i] / \\sum_i[y_i]

        :param y: the discrete distribution from which one wants to calculate the moment
        :type y: pandas.Series or np.array
        :param moment: the moment one wants to calcalate (choose 1,2,3, ... )
        :type moment: int
        :return: the moment requested
        :return type: float
        """
        return y.dot(np.arange(len(y), dtype=float)**moment) / y.sum()
```

If I remove that line from your stripped down version, I get results that match my script on 0.12.0 on Windows (i.e., -1.217...).  What is that doing exactly?  Why did it only affect Windows and not Linux?  I'm happy I'm getting consistent numbers, but I'm a little freaked out by all of this behind-the-scenes numerical wizardry.

Upgrading to the latest version was the first thing I tried, but I tried it only on Linux.  I guess Windows was the wrong one, but I didn't suspect it because I was basing my test suite on a colleagues results.  Of course those were also on an older version of tsfresh running on Windows.

We were using the older tsfresh results to train some ML models.  Looks like we will need to retrain them since the old skew numbers were unstable.  Unless you have some other thoughts.

Thanks for your help.  I especially appreciate the responsiveness!

**Comment by dbarbier** [comment]
This had been discussed in #529, but I totally forgot about that :-/

**Comment by nils-braun** [comment]
So yes, to repeat what was written there (https://github.com/blue-yonder/tsfresh/pull/584):
> According to #529, np.arange(4096)**3 overflows on Windows 10 because dtype is set to int32. Specify dtype=float to avoid overflows.

Its not "behind-the-scenes numerical wizardry" (:-D) but just a good old overflow... (https://www.bbc.com/future/article/20150505-the-numbers-that-lead-to-disaster)

Sorry for not remembering it! Hope you can still go on using tsfresh in your project :-)

**Comment by apcarp** [comment]
Thanks for the update and giving the fix.  It seems like an odd choice on the part of numpy to use different default dtypes on different operating systems (both 64-bit), but there is probably a reason.  Has any filed an issue with them?

Sorry for my delayed response.  I've been hustling to redo the work with the new tsfresh version.

**Comment by dbarbier** [comment]
In Python 2.x, `int` is equivalent to C `long` type, which is int64 on Linux and int32 and Windows.
In Python 3, `int` has unlimited precision, but Numpy needs fixed precision for efficiency reasons, thus it seems logical for `np.int` to stick with the same definition.
