### ISSUE TITLE
Can the feature list obtained with 'from_columns()' be directly used in extract_features()?

### ISSUE THREAD

**Issue by YiDuan1221** [blue-yonder/tsfresh#619]
Here is my code:

from tsfresh import extract_features
from tsfresh import select_features
from tsfresh.utilities.dataframe_functions import impute
from tsfresh.feature_extraction.settings import from_columns

# extract features on labeled data
extracted_features = extract_features(df, column_id="# id")

# select relevant features for new data prediction
y = np.array(y)
impute(extracted_features)
features_filtered = select_features(extracted_features, y)

# get the list of the filtered feature names
fc_settings = from_columns(features_filtered)

# read the new data
new_df = pd.read_csv('new_data')

# extract filtered features on new data
pred_extracted_features = extract_features(new_df , column_id="# id", default_fc_parameters=fc_settings)

Error:
AttributeError: module 'tsfresh.feature_extraction.feature_calculators' has no attribute 'ch6'

**Comment by dbarbier** [comment]
@YiDuan1221 You must pass it to `kind_to_fc_parameters` argument, not `default_fc_parameters`.

**Comment by YiDuan1221** [comment]
@dbarbier Thanks mate. That solves my problem.

**Comment by Sahil028** [comment]
@dbarbier I was facing the same problem, Thanks brother!!

**Comment by nils-braun** [comment]
Thanks you @dbarbier for the very quick answer!
