### ISSUE TITLE
Update the Quick Start

### ISSUE THREAD

**Issue by AnnaVM** [blue-yonder/tsfresh#62]
In order to follow along on the Quick Start page, in the Dive in section, I believe the method used to load the data should be updated, as the code would not run as is.

```
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, load_robot_execution_failures

download_robot_execution_failures()
timeseries, y = load_robot_execution_failures()
```

**Comment by earthgecko** [comment]
@AnnaVM I found the same thing yesterday, added a pull request with the updated the Dive In section in, thanks.

**Comment by earthgecko** [comment]
That said @AnnaVM I think you should do this pull request :)

 I just copied the file across ;)  I think you really fixed this error in the .rst code :)

```
RuntimeError: The example data could not be found. You need to download the Robot Execution Failures LP1 Data Set from the UCI Machine Learning Repository. To do so, you can call the function tsfresh.examples.robot_execution_failures.download_robot_execution_failures
```

**Comment by MaxBenChrist** [comment]
4e3d1f4 fixed this
