### ISSUE TITLE
Import of tsfresh.extract_features breaks logger configuration

### ISSUE THREAD

**Issue by shakhat** [blue-yonder/tsfresh#620]
**Version:** 
``tsfresh==0.13.0``

**OS:** 
```
$ uname -a
Linux desktop 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Issue:** 
Import of tsfresh.extract_features configures root Python logger, as result it affects logging in the whole application. Ideally the library should not change logging configuration - it is responsibility of the application entry point (main thread). Probably the following code could be safely removed: https://github.com/blue-yonder/tsfresh/blob/v0.13.0/tsfresh/feature_extraction/extraction.py#L21-L27

**Steps to reproduce:**
_The code without import works as expected:_
```
import sys
import logging

LOG = logging.getLogger(__name__)

if __name__ == '__main__':
    logging.basicConfig(stream=sys.stdout,
                        level='INFO',
                        format='%(asctime)s %(process)d %(levelname)s %(name)s %(message)s')
    LOG.info('Log info')
    LOG.error('Log error')
```
_Output:_
```
2020-01-14 11:43:29,277 29072 INFO __main__ Log info
2020-01-14 11:43:29,277 29072 ERROR __main__ Log error
```
_The code with import produces wrong output:_
```
import sys
import logging

from tsfresh import extract_features

LOG = logging.getLogger(__name__)

if __name__ == '__main__':
    logging.basicConfig(stream=sys.stdout,
                        level='INFO',
                        format='%(asctime)s %(process)d %(levelname)s %(name)s %(message)s')
    LOG.info('Log info')
    LOG.error('Log error')
```
_Output:_
```
ERROR:__main__:Log error
```
Note that configuration is not applied here since `logging.basicConfig` does not update root logger if it is already set. One of possible workarounds is to manually update root logger which is a bit hackish.

**Comment by nils-braun** [comment]
Thanks for the issue!
Yes, you are correct - and it seems Max already thought about that when including the comment :-)
I will create a PR hopefully this evening.

**Comment by nils-braun** [comment]
Sorry, took a bit longer...

**Comment by shakhat** [comment]
@nils-braun Thanks a lot for the fix! It works for me (checked on py36).
