### ISSUE TITLE
How to use roll_time_series on sample robotic data set to extract features at each timestamp

### ISSUE THREAD

**Issue by flowersw** [blue-yonder/tsfresh#622]
Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system
MacOSX
2. The version of *tsfresh* that you are using
0.13.0
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
Very similar to the robot data set described on the Quick Start page of documentation
4. A minimal code snippet which reproduces the problem/bug
5. Any reported errors or traceback
Does the tsfresh.utilities.dataframe_functions.roll_time_series() function expect each "time" element to be different? In the example provided at https://tsfresh.readthedocs.io/en/latest/text/forecasting.html, this is true. And it also would seem true, since the new ID's that are created are are based off of the timestamp. 

How would you use tsfresh.utilities.dataframe_functions.roll_time_series() to create a set of features at each time stamp, using the robot dataset in quick start?

Maybe I am missing something.

Thanks,
Will

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by nils-braun** [comment]
I think I did not fully understand your question - sorry :-/ 

If you do not have distinct time elements - but you want to have some - you could just build a new column out of e.g. the index (or alike). 
What do you mean "to create a set of features at each time step"? We still do time series feature extraction - we use the time series until a specific point to extract features.

Sorry if I totally misunderstood your point :-(

**Comment by flowersw** [comment]
Hi @nils-braun  - thanks for responding. Just for clarification - how would you go about using the roll_time_series() function on the robotic dataset, and extracting features from the resulting dataset?

By "creating a set of features at each time step", I mean, in the case of the robotic data set, for each time step, using roll_time_series of something similar to extract features up to that time step (perhaps all of the steps up to that point, or a rolling window). So, the resulting data set would look very similar to the original data set, except each row would represent an (rolling) aggregation, instead a single point in time.

I just wondered if there was built-in functionality for this. Does this question make sense?

As a way of illustration, this is what I'm looking for in the resulting dataset:

<img width="1082" alt="Screen Shot 2020-02-03 at 1 20 32 PM" src="https://user-images.githubusercontent.com/12040615/73679271-0fa21b00-4688-11ea-8df2-3814ee34f802.png">

**Comment by nils-braun** [comment]
Ah I see, sure!

The key to this question is, that you have two index columns you are later interested in:
* one is the "id" from the original dataframe (lets call it robot_id)
* and one is the id of the time series after rolling (lets call it time_id)

Example: you use the time series for one robot (same robot_id), which has length 10. You produce 10 rolled time windows out of it (first one only t1, second one t1 and t2, etc). To name each of those new time series, you give each of them a number, the time_id.
Later we just need to group by the combination of both in extract_features.

Ok, lets do this!

```python3
from tsfresh.examples.robot_execution_failures import download_robot_execution_failures, load_robot_execution_failures
from tsfresh import extract_features, extract_relevant_features, select_features
from tsfresh.utilities.dataframe_functions import roll_time_series
from tsfresh.feature_extraction.settings import MinimalFCParameters

download_robot_execution_failures()
df, y = load_robot_execution_failures()

# rolling and id magic:
# Make sure to store the old id (which is the robot id)
df["robot_id"] = df["id"]
# Now roll it. The new "id" is the time_id.
df_rolled = roll_time_series(df, column_id="id", column_sort="time", rolling_direction=1, column_kind=None)
# Create a combined column of both, so that tsfresh feature extraction can work on one id only
df_rolled["my_combined_id"] = df_rolled.apply(lambda x: f"{x['robot_id']}_{x['id']}", axis=1)
# we do not need the other ones now
df_rolled = df_rolled.drop(columns=["robot_id", "id"])

# feature extraction using the new combined id column
extract_features(df_rolled, column_id="my_combined_id", column_sort="time", default_fc_parameters=MinimalFCParameters())
```

Its not pretty, but it works. Maybe we should have this as an option in the rolling function!

**Comment by flowersw** [comment]
Yes - I think this is exactly what I'm looking for and can work with 😃 . I'm working on a time series classification problem, and this is how I have my dataset / target set - up. Looking forward to seeing the results. Thanks again for getting back to me - and for this very cool project! Looking forward to seeing where it goes. I'm interested to dig into the code base further too.
Closing this ticket now...
