### ISSUE TITLE
Not compatible with pandas 1.0

### ISSUE THREAD

**Issue by rodrigorivera** [blue-yonder/tsfresh#623]
Dear tsfresh team,

the latest version of tsfresh is not compatible with pandas 1.0. In the release notes here:
https://pandas.pydata.org/pandas-docs/version/1.0/whatsnew/v1.0.0.html#backwards-incompatible-api-changes
One can find "Removed Index.contains, use key in index instead (GH30103)"

In feature_extraction/extraction.py in the line 318, you have
if result.columns.contains("value"):

At the moment, ts-fresh is only compatible until pandas 0.25

**Comment by dbarbier** [comment]
Already fixed in master, but a new release is needed.

**Comment by igorpereirabr1** [comment]
Any idea when we'll  have a new release?

**Comment by nils-braun** [comment]
Yes, good point - I will do one today.

**Comment by nils-braun** [comment]
Sorry, I would like to wait for another PR to enter which will happen tomorrow. Hope you can wait until then :-/

**Comment by igorpereirabr1** [comment]
yes @nils-braun , we can!

**Comment by nils-braun** [comment]
New release under way!
