### ISSUE TITLE
How to perform forecasting not prediction using tsfresh?

### ISSUE THREAD

**Issue by emangy** [blue-yonder/tsfresh#628]
Hi .. Thank you so much for this very useful tutorial. However, this is a prediction model not forecasting the future, since the x_test provided is already extracting feature for the y_test that has to be there for the test beforehand. How can we tweak this to perform a future forecasting where we don't know the y_test ? and we only have the time stamp. 

Thanks a lot.

**Comment by kempa-liehr** [comment]
In general, you would always use the last known (historic) time series values (up to the respective time stamp) in order to forecast future values. 

For a general introduction to time series forecasting, please have a look at https://otexts.com/fpp3/ or http://shop.oreilly.com/product/0636920187714.do.

**Comment by emangy** [comment]
The thing is that the features extracted from tsfresh for training the model is actually coming from the known Y value, which is not available in the case of the forecasting. For example, the X fed to the model to be predicted is actually coming from the y value to be predicted which is x["high"] in this example. 
Can you please clarify how to do forecasting for the future in this case ? 
```
df_shift, y = make_forecasting_frame(x["high"], kind="price", max_timeshift=20, rolling_direction=1)

%%capture
X = extract_features(df_shift, column_id="id", column_sort="time", column_value="value", impute_function=impute, show_warnings=False)

ada = AdaBoostRegressor(n_estimators=10)
y_pred = [np.NaN] * len(y)

isp = 100   # index of where to start the predictions
assert isp > 0

for i in tqdm(range(isp, len(y))): 
    ada.fit(X.iloc[:i], y[:i])
    y_pred[i] = ada.predict(X.iloc[i, :].values.reshape((1, -1)))[0]

```
