### ISSUE TITLE
Typo Documentation

### ISSUE THREAD

**Issue by rpanai** [blue-yonder/tsfresh#631]
Hi, I believe there is a typo in `MinimalFCParameters` in this [tsfresh/feature_extraction/settings.py](https://github.com/blue-yonder/tsfresh/blob/master/tsfresh/feature_extraction/settings.py). At line 160 donate should be denoted.  Do you want me to do a PR for this?

**Comment by kempa-liehr** [comment]
Hi rpanai, 
thanks for reporting the typo. It has been corrected.
Cheers, Andreas
