### ISSUE TITLE
Generate sub-series from timeseries, to extract all possible features 

### ISSUE THREAD

**Issue by raedbsili1991** [blue-yonder/tsfresh#633]
Using tsfresh ( for example the roll function): 
Is it possible to generate features as a matrix X, containing in each row, all the possible features of every sub-series of the time-series data ? 

![image](https://user-images.githubusercontent.com/31764213/74353604-74612200-4dba-11ea-9885-05360aa9ee5e.png)

**Comment by nils-braun** [comment]
You can do this without any rolling: you could just give each cycle (the orange and the blue part in your picture) a distinct ID and use this for grouping in the select features call.

For example, assuming you have three time series (call them A, B and C) and each of them has five cycles (1, 2, 3, 4, 5) you could create a new index by concatenating them (A1, A2, ...) and add it as new column to each row. Then you would use this new column in `column_id` (and delete the other id columns).

**Comment by raedbsili1991** [comment]
Thanks for the feedback. I am already doing this "manually" (iterating and stacking every cycle with a different ID), as you described. ( I created a function that convert a timeseries to a TSFRESH dataframe ). 
I was just wondering if TSFRESH  has already such a function that is capable of doing this.

**Comment by uzi0espil** [comment]
This is the very same case that I am dealing with as well, I also wrote a function to convert a timeseries to tsfresh data format. I think that it would be useful to add the function to `tsfresh.utilities.dataframe_functions` as well.

**Comment by nils-braun** [comment]
Would anyone of you be happy to provide a PR for this?

**Comment by raedbsili1991** [comment]
I share my function, let anyone here to add it to _tsfresh.utilities.dataframe_functions_ 
J is a 1d-array (the time-series signal), delta is an int ( in my case it was 84). 

```python
def convert_to_tsfresh_df2(J,delta): 
  
   mat = []
   K = 0 
   N = 1
   while(True): 
       mat.append(J[K:N*delta])
       K = N*delta 
       N += 1 
       if ( K > np.size(J) ) : break
   
   d = pd.DataFrame(mat).stack()
   d.index.rename(['id','time'], inplace = True)
   d = d.reset_index()
    
   return pd.DataFrame(d.values, columns=['id','index','J'])

tsfresh_df = convert_to_tsfresh_df2(J = np.random.randn(10000), delta = 84)
```
