### ISSUE TITLE
Do all features that tsfresh generate based on previous price values? 

### ISSUE THREAD

**Issue by ivan-bulka** [blue-yonder/tsfresh#634]
Hi, guys, 
I'm new in tsfresh and have some general questions.
tsfresh generates lots of features and it's great. 
Do all features that tsfresh generate based on previous price values? 
For example, I have prices for timestamps: t-n, t-n-1, ... t-1, t. 
Am I right if we generate features for timestamp t, we use only data from timestamps t-n, t-n-1, ... t-1. We do not use future data or data for existing timestamp (for example for timestamps t, t+1 and t+2) 

Thank you

**Comment by nils-braun** [comment]
Hi! That depends on how you use tsfresh :-) The software itself has no concept of "time". It will only generate the features of the time series you give it. You might want to have a look into our rolling or forecasting documentation.
Would you mind sharing your code?

**Comment by ivan-bulka** [comment]
Hi! Sure. I use tsfresh for time series prediction. 
- Generate features based on train dataset
- Train the model 
- Generate features based on the test dataset 
- predictions for the test dataset

Look the example, please: 

```
# Get some data from dataframe
df_train = data[:100000]
df_test = data[100000:120000]

# Apply tsfresh
data_shift_train, y_train = make_forecasting_frame(df_train['p'], kind = 'price', max_timeshift=10, rolling_direction=10)
data_shift_test, y_test = make_forecasting_frame(df_test['p'], kind = 'price', max_timeshift=10, rolling_direction=10)
X_train = extract_relevant_features(data_shift_train, y_train, column_id="id", column_sort="time", column_value="value", 
                     show_warnings=False)
X_test = extract_relevant_features(data_shift_test, y_test, column_id="id", column_sort="time", column_value="value", 
                     show_warnings=False)

# Define the function for columns intersection. We should use the same features for train and test 
def Intersection(lst1, lst2): 
    return set(lst1).intersection(lst2) 
col = Intersection(X_test, X_train)

# Apply column intersection function
X_train = pd.DataFrame(X_train,columns = col)
X_test = pd.DataFrame(X_test,columns = col)

# Generate the target value
_, y_1_train = get_target(df_train, predict_step = 5, trades = 10)
_, y_1_test = get_target(df_test, predict_step = 5, trades = 10)

# I try to predict 5 steps in the future based on the previous 10 values in get_target function. 
X_fin_train = X_train[15:-10]
X_fin_test = X_test[15:-10]
y_1_train_c = y_1_train[5:]
X_fin_train_c = X_fin_train[:-5]
y_1_test_c = y_1_test[5:]
X_fin_test_c = X_fin_test[:-5]

# Apply normalization to data 
mm_scaler = preprocessing.MinMaxScaler()
X_train_minmax = mm_scaler.fit_transform(X_fin_train_c)
X_test_minmax = mm_scaler.transform(X_fin_test_c)
clf = LGBMClassifier()
clf.fit(X_train_minmax, y_1_train_c)
clf.predict(X_test_minmax)
```

I want to understand if this approach is right? If all features that tsfresh generate based on previous values, it means that my logic is correct. For example, if I generate features for timestamp t, I can only use data from timestamps t-1 and earlier. 

Thank you for the help

**Comment by nils-braun** [comment]
I am not sure :-) 
Two things I am a bit puzzled (without knowing exactly how your data and your problem looks like):
* you have a `y_train/test` which you use for extracting the relevant features (so tsfresh will use this target for defining, what is relevant and what not) but later for training your classifier you use a different target. Why is that so?
* if you want to be sure on which data tsfresh extracts its features you can juts have a look into the `data_shift_test` dataframe, or? Maybe I am not understanding your concrete problem :-)

**Comment by nils-braun** [comment]
Sorry, I created a PR to solve another issue and accidentely connected with this one...

**Comment by nils-braun** [comment]
@ivan-bulka I am closing this issue now. If you still have the problem, please reopen this issue and try to answer my questions so I can help you :-)
