### ISSUE TITLE
Overivew on extracted features table needs word wrapping.

### ISSUE THREAD

**Issue by mjcourte** [blue-yonder/tsfresh#636]
My issue is with the readthedocs page for list of features [here](https://tsfresh.readthedocs.io/en/latest/text/list_of_features.html). 

It is quite hard to read this table because the window of readable characters is narrow and fixed, and the scrollbar is way down at the foot of a (relatively) long table. One would need to scroll up and down and back and forth to read each line.

Consider adding word wrap to the descriptions column of the table.

I'm on Windows 10, Google Chrome if it matters.

Thanks y'all.

**Comment by nils-braun** [comment]
That is definitely a valid point. 
I will try out the suggestion from https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html and hope that this will help!

**Comment by nils-braun** [comment]
Sorry that took so long for merging! I just forgot about it...
