### ISSUE TITLE
tsfresh.utilities.dataframe_functions.make_forecasting_frame, add option to remove ids with lesser lags

### ISSUE THREAD

**Issue by jontis** [blue-yonder/tsfresh#638]
tsfresh.utilities.dataframe_functions.make_forecasting_frame conveniently builds a dataframe with lags from a time series and takes the parameter max_timeshift for number of lags to include. A few of the id's in the end will get less than max_timeshift lags. Running feature extraction on those will thus give very different results than if they had max_timeshift lags. I propose to include an option to filter out those ids that did not get max_timeshift lags.

**Comment by nils-braun** [comment]
Yes, very good proposal!

**Comment by nils-braun** [comment]
Would you like to do a PR for this?

**Comment by nils-braun** [comment]
A function for that was introduced in #668. You can now specify the `min_timeshift` to do exactly this.
