### ISSUE TITLE
[Question] Feature importance to speed up training?

### ISSUE THREAD

**Issue by jarlva** [blue-yonder/tsfresh#640]
Hello,

My observation training dataset has many columns ( > 400). It's reasonable to assume that not all of them are important and some are more important than others. Finding which ones will greatly reduce training and optimization cycles.
For example: say I train using all columns a simplified problem. Then, analyzing tensorboard and/or saved model data (or another way) to find which features were actually used most by TF to train and further optimize.
Anyone idea how to find out?

**Comment by nils-braun** [comment]
So in principle (I guess) you are describing 100% the use case of tsfresh, or am I wrong?
tsfresh is a feature extraction and *selection* library.
Please have a look into our documentation, e.g. https://tsfresh.readthedocs.io/en/latest/text/feature_filtering.html

**Comment by jarlva** [comment]
@nils-braun, to clarify: my features are tsfresh features (all >400) of them. I also used the extract_relevant_features and got around 90 features.
