### ISSUE TITLE
Extracting features from a big dataset

### ISSUE THREAD

**Issue by minhduc0711** [blue-yonder/tsfresh#642]
I have around 1.7M time series, each with a length of 72. 
Is there a way to extract features from this much data without getting my memory filled up? Thanks.

**Comment by nils-braun** [comment]
As tsfresh works on each of the time series independently the easiest solution would probably to read them and extract feature one after the other and write our the features into csv/parquet/what ever you need. There is no convenience function for that, but I guess with a simple for loop you might already achieve this

**Comment by minhduc0711** [comment]
@nils-braun thanks for the reply
But I guess I was talking about feature selection as well, does the selection process also work on each time series independently?

**Comment by nils-braun** [comment]
Ah I see. Well no, you are right. All data is used for this. But with that much time series it should probably also be possible to select the features only on a subset. 
I would extract the features for some time series, store the results maybe somewhere and then select the features.

One additional comment: length of 72 is not that long. Maybe not all of the features actually make that much sense for your use case. You can also limit the features created already before doing the extraction by using the settings. Please check our our docu on this.

**Comment by minhduc0711** [comment]
Oh okay I understand, thank you so much for the support!
