### ISSUE TITLE
Add multiprocessing capability to rolling

### ISSUE THREAD

**Issue by demontamer** [blue-yonder/tsfresh#646]
Oh no, you encountered a problem while using *tsfesh*.
I notice the above functions do not take njobs or distributor as args. They are quite slow for even moderately large datasets of size 5000?

**Comment by nils-braun** [comment]
Yes, `roll_time_series` is not implemented in a multiprocessing ready way. Probably it is possible, but we have never thought about it. If you have any good idea on how to do it, we are happy to hear it (or even a pull request :-))
The `extract_relevant_features` function has a parameter for `njobs`, but not for the distributor, that is correct. I will fix this. Until that, you can also just use the normal `extract_features` function with the `select_features` function, which is basically the same.

**Comment by nils-braun** [comment]
I added the parameter in #648

**Comment by nils-braun** [comment]
Now also `roll_time_series` has multiprocessing capabilities.
