### ISSUE TITLE
Multivariate Feature Extraction

### ISSUE THREAD

**Issue by firmai** [blue-yonder/tsfresh#655]
Hi, is it possible to take in two feature to calculate the final (one) signal? Has this been done, can this be done? Thanks.

**Comment by kempa-liehr** [comment]
Hi, 
This would be a classical time series regression problem. 
Let's assume you'd have a target time series y with y(t_0),..., y(t_1000) and some other time series x_1(t_0)...x_1(t_1000) and x_2(t_0), ... x_2(t_1000). 
You could train a model for predicting y(t_100),...,(y_1000) by extract time series features from rolling windows of 100 time series samples.  So, time-series features from  time-series x_1(t_0), ..., x_1(t_99) and x_2(t_0),...,x_2(t_99) would form a row of your feature matrix and would map to target y(t_100).
Time-series features from  time-series x_1(t_1), ..., x_1(t_100) and x_2(t_1),...,x_2(t_100) would form a row of feature matrix and would map to target y(t_101) and so on.
However, remember that you need to evaluate your model using temporal cross-validation (https://robjhyndman.com/hyndsight/tscv/).

**Comment by firmai** [comment]
Thanks, do you know if we have the ability to do this with TSFRESH, should I include one feature as a parameter? Has this already been done in the package?

**Comment by kempa-liehr** [comment]
Have a look at the following notebook, which discusses a forecasting problem. You can use function make_forecasting_frame in a similar way.
https://github.com/blue-yonder/tsfresh/blob/master/notebooks/timeseries_forecasting_basic_example.ipynb

**Comment by firmai** [comment]
1) So can I create a function that takes in two time series?
2) Can I dynamically load the new feature into tsfresh or do I have to recreate the package? - I have read your documentation, this is not yet clear to me. 

I see you are in Auckland, that is exciting!

**Comment by kempa-liehr** [comment]
😀  You you graduated from UoA 👍

You would apply make_forecasting_frame and extract_features both for for x_1 and x_2 independently, join the resulting DataFrames to feature matrix X, which could use for feature selection and training together with target y.
