### ISSUE TITLE
Roll_time_series

### ISSUE THREAD

**Issue by OJL96** [blue-yonder/tsfresh#659]
Hello,

thank for for the tsfresh package, it has been most useful.

So im trying to extract features from my dataset, before doing so i would like to using a rolling method to increase my data entries by getting the mean of  (im guessing thats the purpose of it).

so my dataset looks like this:
TIME            VALUE  CLASS  uniqueID
 0.150050 | 0.368338   |   0    |     0
 0.150100 | 0.364448   |   0    |     1
 0.150150 | 0.360232   |   0    |     2
 0.150200 |0.355811    |   0    |     3
 0.150250 |0.351306    |   0    |     4
         ...       ...    ...       ...
 0.299799 | 1.917936   |   6  |  539455
 0.299849 | 1.916304   |   6  |  539456
 0.299900 | 1.914653   |   6  |  539457
 0.299950 | 1.913025   |   6  |  539458
 0.300000 | 1.911464   |   6  |  539459

and after executing:
data["uniqueID"] = len(data)
y = data.CLASS
rolledData = roll_time_series(data, 
                              column_id="CLASS",
                              column_sort="TIME",
                              column_kind=None,
                              rolling_direction=100)

i get the following user warning: UserWarning: Your time stamps are not uniformly sampled, which makes rolling nonsensical in some domains. 

it never finishes the function and displays the new data 

any help is much appreciated.

**Comment by nils-braun** [comment]
Hi, thanks for the issue.

So maybe to start from the beginning: I think I did not really understand your data.
* why do you want to roll? Rolling produces a prediction dataset out of a normal time series. You can find some information here: https://tsfresh.readthedocs.io/en/latest/text/forecasting.html From your "y = data.CLASS" I understand however, you have a classification problem? Or what is the purpose you want to achieve? 
* what do you mean by "getting the mean"?
* you are using `data.CLASS` both as `y` as well as an the `column_id`. Are you sure that makes sense? Check out the nomenclature here: https://tsfresh.readthedocs.io/en/latest/text/data_formats.html
* what do you mean it never ends? Is it just too slow? The warning is not a reason why it should not end (but it is a warning, which is for your information). Check out about warnings: https://docs.python.org/3/library/warnings.html which are normally not a reason why it should not finish. Could you try with less data? You have quite a large data sample.

**Comment by nils-braun** [comment]
I guess #668 and the additional parameter for the number of jobs will help you. If not, please reopen the issue!
