### ISSUE TITLE
Reference for "the prediction of the quality of steel billets during a continuous casting process"

### ISSUE THREAD

**Issue by ayanray089** [blue-yonder/tsfresh#660]
Hi,

Can you provide me any reference to the below use case mentioned in Introduction section of tsfresh.
"the prediction of the quality of steel billets during a continuous casting process".

Thanks!

**Comment by kempa-liehr** [comment]
Hi,
the use case is discussed in 

Christ, M., Kempa-Liehr, A.W. and Feindt, M. (2017).
Distributed and parallel time series feature extraction for industrial big data applications.
ArXiv e-print 1610.07717, https://arxiv.org/abs/1610.07717.

All the best,
Andreas
