### ISSUE TITLE
Readthedocs "latest" version of documentation is outdated

### ISSUE THREAD

**Issue by rwedge** [blue-yonder/tsfresh#667]
It looks like the "latest" version of the documentation is out of date,  given that the last [changelog](https://tsfresh.readthedocs.io/en/latest/changes.html) entry references the 0.12.0 release.

Both "stable" and "master" versions of the docs reference the 0.15.1 release

**Comment by nils-braun** [comment]
Nice catch! Seems something was wrong in the readthedocs build.
I fixed it - thanks for this!
