### ISSUE TITLE
No Selected Features

### ISSUE THREAD

**Issue by javierorozco** [blue-yonder/tsfresh#67]
Using a collection of 147 time series with 20 time stamps each, the method `extract_features returns` 211 features. Some of the features are constant across all 147 IDs but others are not constant.

![image](https://cloud.githubusercontent.com/assets/5426388/20428582/d242cb3a-ad81-11e6-9732-7758926c4bc9.png)

When the method `select_features` is applied to the (147,211) DataFrame `X`, the outcome is and empty DF.

![image](https://cloud.githubusercontent.com/assets/5426388/20428917/9da6b60a-ad83-11e6-98aa-390b0710944d.png)

However, there are features whose STD is not zero, `X.iloc[:, X.std().values!=0].shape`, `(147, 165)`
This is an example of the correlation between these 165 non-constant features and target

![image](https://cloud.githubusercontent.com/assets/5426388/20429182/071a438a-ad85-11e6-95f2-0a933f32e53a.png)

Other attempts were made such as:

1. renaming the columns to match the demo notebooks. Resulted in different features but the same empty DF of selected features.
2. Use `extract_relevant_features` directly. Resulted in different features but the same empty DF of selected features.
3. Use other series type. Resulted in different features but the same empty DF of selected features.
4. Use more than one series type, i.e. DF of shape (147, 12), where 2 of the columns are id and time, the remaining columns are series types. Resulted in different features but the same empty DF of selected features.
5. Use longer time series, e.g. 200 time stamps. Resulted in different features but the same empty DF of selected features.
6. Use different values for `extraction_settings.fdr_level = 0.1`. Resulted in different features but the same empty DF of selected features. Extracted features were still 211.

**Questions**

1. Why only 211, even when extending the series to 200 tim stamps?
2. Why no selected features from any series type when the initial pool of features is 211?
3. are there any parameters missing to be set?
4. Is there any problem with the type of inputs?

**Comment by MaxBenChrist** [comment]
Can you provide an examplary notebook with data? Otherwise we can not investigate properly.

Also, can you provide a selection report? You get it by setting the `write_selection_report`flag of the FeatureSelectionObject to True

**Comment by javierorozco** [comment]
This ZIP contains demo data and Jupiter Notebook
[javier_demo.zip](https://github.com/blue-yonder/tsfresh/files/600657/javier_demo.zip)

**Comment by MaxBenChrist** [comment]
You have too many unimportant features.

``` python

from tsfresh.feature_selection import FeatureSignificanceTestsSettings
sett = FeatureSignificanceTestsSettings()
sett.fdr_level = 0.5 # increases the risk of unimportant features being extracted
sett.write_selection_report = True # will create a report with more information

# i only inspect first columns to 50th feature to reduce number of irrelevant features 
X_filtered3 = select_features(X.iloc[:,0:50], y, feature_selection_settings=sett)
X_filtered3.head()
```
This will extract a__time_reversal_asymmetry_statistic__lag_2,	a__mean_change and a__number_peaks__n_1

However, the handling of constant features is internally not done in the best fashion. TSFRESH could extract more features, I am working on that.

**Comment by MaxBenChrist** [comment]
I looked into that in detail javier. I found some bugs but your problem stays the same. Your samples does not contain enough evidence to make a feature "relevant".

Either increase the FDR level or use another feature selection method

**Comment by javierorozco** [comment]
Thanks Max for the update, have you pushed the bugs fixing to master?

**Comment by MaxBenChrist** [comment]
Yes it is commit 7a21b5e05fff2917aad8d7bcd753eff976b1c6df

you can install master of tsfresh by `pip install git+https://github.com/blue-yonder/tsfresh`
