### ISSUE TITLE
Rolling time not using last values

### ISSUE THREAD

**Issue by ramdhan1989** [blue-yonder/tsfresh#672]
For multistep prediction x steps ahead, I am thinking to use rolling window start from t-x data. Let say use 3 windows t-30, t-31, t-32 for 30 steps ahead prediction from t? Is it possible using tsfresh?

**Comment by nils-braun** [comment]
Sure. Three steps are needed:
1. extract all the length-3 windows from your data, which can be done using the `roll_time_series` function (see documentation https://tsfresh.readthedocs.io/en/latest/text/forecasting.html). One of that will for example be the time series with times 41, 42, 43. It is called "43" (the nomenclature is to give it the name of the last time included in the sample, but it is just a name)
2. using these extracted time series (each of length 3), extract the features for each of them. So we will get e.g. the features for our time series with name "43"
3. Train the ML algorithm (or whatever you want to use) with the input feature dataset (which also includes a row with our features for "43"). As the target vector, use the values 30 steps ahead, so for our row "43" the target should be the value for "t=73".
