### ISSUE TITLE
time series input values contain category or binary data

### ISSUE THREAD

**Issue by ramdhan1989** [blue-yonder/tsfresh#674]
does this package and the feature calculator consider the possibility of using time series input data that contain multi class / binary values?

**Comment by nils-braun** [comment]
That is a good question.
We certainly have some feature calculators, which also make sense for binary/categorial values (e.g. `has_duplicate`), but others clearly make no sense (like the linear trend). As far as I know, we do not have a list of feature calculators which is viable for categorial values (we only have the full list https://tsfresh.readthedocs.io/en/latest/text/list_of_features.html). Maybe @MaxBenChrist  or @kempa-liehr have some experience with that?
Is there any specific feature you are after?

**Comment by ramdhan1989** [comment]
@nils-braun thanks for your information. I will take a look more detail to each feature calculators

**Comment by nils-braun** [comment]
@ramdhan1989 - I am closing this issue (for a bit of house keeping). If you have an additional question, feel free to reopen!
