### ISSUE TITLE
what is the impact of rolling_direction in roll_time_series?

### ISSUE THREAD

**Issue by ramdhan1989** [blue-yonder/tsfresh#675]
Hi,
this is really good package for feature selection. I would like to clarify after doing some trial.
I am still confused with rolling_direction parameter. what is the impact of this value ? It works for the direction (moving forward or backward) but the magnitude doesn't affect anything. So, the resulted dataframe with rolling_direction = 1, 2, 3 or 4 has same dataframe size. an then the value zero has same effect with None , isn't it ?

**Comment by nils-braun** [comment]
Yes, as written in the documentation (https://tsfresh.readthedocs.io/en/latest/api/tsfresh.utilities.html#tsfresh.utilities.dataframe_functions.roll_time_series) only the sign is relevant. So 1, 2, 3 and 4 will give the same result.
A `rolling_direction` if 0 (or `None`) is not allowed.
