### ISSUE TITLE
TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

### ISSUE THREAD

**Issue by TheSilentNoise** [blue-yonder/tsfresh#677]
Hi,

Below are details:

1. Operating System: Ubuntu
2. tsfresh version: Latest
3. Sample data from dataframe
df.head(2)
**signal_name        observation_time       value**
0  MaxHyst_US 2020-04-01 00:43:50.999    1.181103
1      Max_US 2020-04-01 00:43:50.999   31.496080

**Data types:**
signal_name                 object
observation_time    datetime64[ns]
value                      float64

**Code snippet:**
df_extracted_features = extract_features(df, column_id='signal_name',column_sort='observation_time')

It is a flat dataframe.
The above code runs fine for first 1000 rows. But it starts throwing the below error when ran on the entire dataframe.
TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

Since, the code is running fine for first few rows and generating data in desired format it makes me think that this is caused by some bad data. What shall I look for and How can I solve this?

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by nils-braun** [comment]
Would it be possible to share your dataset somehow?
If not, are you sure all of your "value" entries are actually floats? Is the `Data Types` you printed for the full data sample or just the first 1000 rows? 
`<U32` is a string and we do not use any string calculations within `tsftesh` so the only reason I can see why strings would enter the calculation is coming from your input data.

**Comment by nils-braun** [comment]
Sorry,  closing was not intended :-/

**Comment by nils-braun** [comment]
@TheSilentNoise Was this issue solved (e.g. because you actually had strings in your data)? If not, could you share some example data that trigger this issue?

**Comment by nils-braun** [comment]
Feel free to re-open at any time!
