### ISSUE TITLE
Difference between sum_of_reoccurring_data_points and sum_of_reoccurring_values?

### ISSUE THREAD

**Issue by coolcodecding** [blue-yonder/tsfresh#679]
I was wondering what is the diffrence between the two features:

`sum_of_reoccurring_data_points`
`sum_of_reoccurring_values`

I have read the docu, but it didn't make clear what is the difference between a datapoint and a value.
For my understanding, i don't give any datapoints into tsfresh, whereas I hand over values.

Do I misunderstand something?

**Comment by nils-braun** [comment]
If you want, you can see it by looking into the code (that is one of the nice things about open source!):

´´´python
def sum_of_reoccurring_values(x):
    unique, counts = np.unique(x, return_counts=True)
    counts[counts < 2] = 0
    counts[counts > 1] = 1
    return np.sum(counts * unique)
```

and

```python
def sum_of_reoccurring_data_points(x):
    unique, counts = np.unique(x, return_counts=True)
    counts[counts < 2] = 0
    return np.sum(counts * unique)
```

As you see, the `sum_of_reoccurring_data_points` is really the sum of every data point (= time series value), which is reoccuring. So for example

```python
>>> from tsfresh.feature_extraction.feature_calculators import sum_of_reoccurring_data_points
>>> sum_of_reoccurring_data_points([2, 2, 2, 2, 1])
8
```
because 2 is reoccuring (1 is not) all values of 2 get summed, so 4*2 = 8.

On the other side, `sum_of_reoccurring_values` only sums up the values of the re-occurring time series data points, so 

```python
>>> from tsfresh.feature_extraction.feature_calculators import sum_of_reoccurring_values
>>> sum_of_reoccurring_values([2, 2, 2, 2, 1])
2
```

because 2 is a reoccuring value, it gets summed up with all other reoccuring values (there is no other), so the result is 2.

I will add those examples to the documentation.
