### ISSUE TITLE
Empty selected feature set returned despite plenty of data supplied

### ISSUE THREAD

**Issue by techtide** [blue-yonder/tsfresh#682]
1. Your operating system
Windows 10
2. The version of *tsfresh* that you are using
v0.15.1
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
This is what the data looks like. It sits in multiple files, but I concatenate it using ``pd.concat()`` into one big DataFrame, and group it back into filenames using the ``extract_features()`` by setting the parameter ``column_id="filename"``.
```
Time,Xpos,Ypos,Xrot,Yrot,Zrot,FdX,FdY,FdZ,Gd
2,246.073320287097,-0.255677,0.15425250000000001,0.4624518,22.03174,17.75638,3.6650139999999998,0.28270029999999996,-0.3751202,0.8828166999999999,0.415707422286338
3,246.13618043064602,-0.2561713,0.1543418,0.4620944,21.926579999999998,17.39712,3.576257,0.27736459999999996,-0.37341820000000003,0.8852276,0.380018571695365
4,246.199040574194,-0.25648160000000003,0.15489,0.4619201,21.59542,17.30583,3.424439,0.2765913,-0.3680502,0.8877141,0.451515041318906
```
The ``extract__features()`` step is successful, albeit with many zeros and infinitesimal values (i.e., -1E98).
4. A minimal code snippet which reproduces the problem/bug
```python
def fresh(dfs, stage="original", debug=False):
    df = pd.concat(dfs)
    xdf = df.drop(["name", "sequence"], axis=1)
    y = []
    for row in xdf["filename"].unique():
        name = cli.extract_filedata(stage, row)["name"]
        y.append(name)
    y = np.asarray(y)
    extracted_features = extract_features(xdf, column_id="filename", column_sort="Time")
    impute(extracted_features)
    extracted_features.to_csv(os.path.join(cli.get_data("features"), "pre-selection.csv"))
    selected_features = select_features(extracted_features, y)
    selected_features.to_csv(os.path.join(cli.get_data("features"), "features.csv"))
```

5. Any reported errors or traceback
I don't get an error from _tsfresh_, but I do have a problem with the results. I output the step after feature selection to a CSV. However, the CSV only contains an "id" column with the filenames, and no selected features, even with an FDR of 0.99. I have seen one issue like this, but it was discarded due to a possible lack of data. I think I am misusing the library in some way (though I have followed the documentation), but I do not think it is because of a lack of data. The dataframe contains thousands of entries, which I understand should be relatively okay for _tsfresh_ to run feature extraction and selection for. I'd greatly appreciate any advice on what I'm doing wrong and how to correct it.

Thanks in advance, and thank you for providing the community with such a great library.

**Comment by nils-braun** [comment]
Hi @techtide!
Thanks for the issue. You are correct, "thousands" of entries seems to be enough. 
Before digging deeper, one question: is you `y` (the target vector) numeric or is it really a "name" (= a string)?

**Comment by techtide** [comment]
Hey @nils-braun. Thanks for your reply! ``y`` is a vector of strings and is not numeric. Have I overlooked something in the documentation and I have to supply a numeric vector? I was wondering if I should binarise the data into positive/negative classes or supply a mapping for number to name. Is one better than the other?

**Comment by nils-braun** [comment]
I see, So yes, we assume (and expect) all targets to be numerical.
If you have a binary classification problem (or you can boil down your problem to one), it would be best to use a binary target.
If you fill in a non-binary numerical target, we will assume you have a regression problem (which might not make sense in your use case...).
I would see three possibilities:
* you somehow manage to do formulate a binary classification problem out of your original problem
* you turn your multi-classification problem into multiple 1-vs-rest (binary classification) problems and select the features for each case and then take the union of all features
* you do not use the feature selection algorithm of tsfresh at all, but rely on some ML algorithm in your data pipeline further down to do the feature selection

Maybe @MaxBenChrist or @kempa-liehr have some idea on how to handle this better?

**Comment by techtide** [comment]
Thanks so much for your response.
I will first try to frame the problem as Binary Classification. I think it actually makes more sense to do this in my particular scenario versus the multiple 1-vs-rest approach (which is very interesting, by the way!) because in reality the model will only need to predict 1 class against another.
What are examples of further algorithms in the data pipeline I could use? Like shapelet methods, inception time, etc? I was planning on trying the feature based classification models and then comparing their efficacy to other such models

**Comment by nils-braun** [comment]
Just to mention: we have an example on multiclass selection [here](https://github.com/blue-yonder/tsfresh/blob/master/notebooks/examples/04%20Multiclass%20Selection%20Example.ipynb).

Concerning your question, I am not really an expert in this field. Maybe @kempa-liehr or @MaxBenChrist can support?

**Comment by techtide** [comment]
@nils-braun I'm actually not even doing multi-class selection anymore. I can extract features of 157 rows x 7,560 columns, and have a Numpy array of binary values of (0,1) where 1 corresponds to the positive class and 0 corresponds to the negative class.  Nevertheless, even with an fdr level of 0.99, I get a completely empty feature selection dataframe, with the error when running select_features(): 
`relevance.py:206: RuntimeWarning: No feature was found relevant for classification for fdr level = 0.99 (which corresponds to the maximal percentage of irrelevant features, consider using an higher fdr level or add other features.`

**Comment by nils-braun** [comment]
Just to be sure: are you still using the older tsfresh version 0.15?
And is your target vector a numpy array as written in your example above? Are you sure it matches the IDs of the extracted feature df as you expect?

**Comment by techtide** [comment]
I assume the extracted feature dataframe maintains the order of IDs. If so, then I am sure it matches with the IDs of the extracted feature df.
I am using 0.15.1.

**Comment by techtide** [comment]
Note that I have just updated to 0.16, ran the same code, and still have an empty dataframe.

Any suggestions on how to proceed? @nils-braun

**Comment by nils-braun** [comment]
Yes, in principle we keep the order. However I would definitely check this. I would maybe even go one step further and not create a numpy array for y but a pandas series where the index is the Id.

You could do a short "self-Check" if your pipeline is working at all: after feature extraction you also add the target as another column. As the target should be highly relevant for predicting the target (obviously), at least that feature should be kept.

Afterwards, have a look into the produced features and actually think about if they have actually the power to predict your target.
What will be your final use case of the features? Can you also live with the full table of features? 

I just had another look into the example code, and I am not sure if I understand it correctly. Is your y as long as the data you give into the feature extraction? It should be the same size as the number of ids. How long are the time series for each id?

**Comment by techtide** [comment]
Hi Nils. I tried converting from a numpy array with no success on the
tsfresh feature selection end. My y is the same length as the extracted
features array. It won't really make sense to use all the extracted
features given the curse of dimensionality - unless there is an alternative
way to select features which you might suggest? I'll try adding the target
column to X for tsfresh and let you know how it goes. I doubt that this
many columns would be irrelevant.

**Comment by nils-braun** [comment]
@techtide Did you test it with the target vector?

**Comment by techtide** [comment]
@nils-braun I did test it with the target vector. I ended up just going for a custom-built solution to select the features. Tsfresh was still undoubtedly useful in helping generate a dictionary of features, and I thank you for your work on the project.
