### ISSUE TITLE
extracted an empty selected feature set

### ISSUE THREAD

**Issue by nicewenhui** [blue-yonder/tsfresh#698]
1. Your operating system: macOS
2. The version of *tsfresh*: 0.16.0 

My input data has 96 samples, time: 60s, and 12 features.
For function "extract_features", I got feature set of size (96,9156), but when I use the 
function "select_features", I got a feature set(96,0), only index ,no features!
so what should I do? Thank you so much!
[data_and_script.zip](https://github.com/blue-yonder/tsfresh/files/4650618/data_and_script.zip)

**Comment by nils-braun** [comment]
Thanks for sharing code and data!
The technical details are fine, you are using `tsfresh` correctly.

It seems you just have no relevant feature.

However, 96 samples is not a large number. You might want to try out with more data.

**Comment by nicewenhui** [comment]
Hi @nils-braun Thanks for your reply! It helps me a lot!  I tried all 1728 samples,  got a size of (1728, 9156) extracted features, and got (1728, 1029) filtered features finally.

One more question: why the data example of tsfresh only have 88 samples, but it can extract a selected feature?  Thank you so much!

**Comment by nils-braun** [comment]
For distinguishing relevant from irrelevant features, tsfresh uses statistical hypothesis tests. As we need to test many hypothesis (in your case each feature separately, so 9156 different hypothesis effects), we then apply the Benjamini-Yekutieli correction. You can find a lot more details in our paper (https://www.researchgate.net/publication/324948288_Time_Series_FeatuRe_Extraction_on_basis_of_Scalable_Hypothesis_tests_tsfresh_-_A_Python_package).

It is hard so say in your case (you probably know your data better), but it could be for example:
* the statistical difference between relevant and not is very small and you had a down-fluctuation in the first data samples (= you were just unlucky)
* there is really no relevant feature in the first ~90 datasamples, but the other 1700 samples have  relevant features

In our example dataset, the target can actually be reasonably described by the time series and therefore there exist features with a strong relevance - so the algorithm can also "see" them with a small amount of data.
