### ISSUE TITLE
I always got same error 'Index' object has no attribute 'contains', even when i tried to run simple example

### ISSUE THREAD

**Issue by hattajr** [blue-yonder/tsfresh#714]
Hi,

I am new in tsfresh and nowadays I am trying to run some simple example in Jupyter notebook.
But, every time I run the code I always got some issue which is " 'Index'object has no attribute 'contains' ". You can find the problem attached.

OS : Win 10
tsfresh version : 0.16.0

I will appreciate any help!
![image](https://user-images.githubusercontent.com/53370870/84726263-72f17180-afc7-11ea-84f7-6fa6dd0675e5.png)
![image](https://user-images.githubusercontent.com/53370870/84726294-83a1e780-afc7-11ea-8cb6-34e4201a24c9.png)

**Comment by nils-braun** [comment]
Hi @hattajr!
Thank you very much for your report and welcome!

I wrote a small python script to reproduce your error
```python
import numpy as np
import pandas as pd

from tsfresh import extract_features
from tsfresh.feature_extraction.settings import MinimalFCParameters

np.random.seed(42)

df = pd.DataFrame(np.concatenate([np.repeat(range(500), 40)[:, np.newaxis],
                                  np.tile(range(40), 500)[:, np.newaxis],
                                  np.random.randn(20000, 1)], axis=1), columns=["id", "time", "x"])

print(df.head())
```

Unfortunately, however, I do not see the same exception (for me, it runs through).

I am also a bit puzzled because the arrow in the stack trace in your screenshot point to code cells, which are either empty or contain comments - so the exception can definitely not be raised there.

Could it be that you need to reload your jupyter notebook because you have some different versions of tsfresh or other libraries recently installed? 

Could you run a `pip freeze` in the notebook and copy the output here? Thanks!

**Comment by hattajr** [comment]
Hi, thanks for your response!
You are right, I try to ran the script in conda and it works fine.
But when I ran the script in the server (using docker), the same error appeared.

So, I think the problem is my python version which is in conda i have ver 3.7.7  and  in docker is ver 3.6.8.

Is there any suggestion from you so that this script could run in my server (docker) jupyter notebook? because I found that it's quite complicated to update using docker

![image](https://user-images.githubusercontent.com/53370870/84840610-033cbe80-b07b-11ea-926e-d908ef73442c.png)
![image](https://user-images.githubusercontent.com/53370870/84840630-151e6180-b07b-11ea-8905-ab1b601ecd2c.png)
![image](https://user-images.githubusercontent.com/53370870/84840647-236c7d80-b07b-11ea-9472-d3c0a7db2ebf.png)
![image](https://user-images.githubusercontent.com/53370870/84840670-33845d00-b07b-11ea-9c58-ce26e6d3eb33.png)
![image](https://user-images.githubusercontent.com/53370870/84840684-3da65b80-b07b-11ea-94bc-1dc321dedfe4.png)

**Comment by hattajr** [comment]
Hi @nils-braun , it's done.
it was because my pandas package is not up-to-date.

Thanks for your time, I appreciate it!

**Comment by JRodDynamite** [comment]
@hattajr - Which version of pandas did you use? I'm using 1.2.1 and still facing the same issue.

**Comment by nils-braun** [comment]
Hi @JRodDynamite - can you share your code example that causes the issue?
