### ISSUE TITLE
What data does tsFresh apply to

### ISSUE THREAD

**Issue by mengmengPython** [blue-yonder/tsfresh#718]
Right now I have trajectory data for multiple targets, including longitude, latitude and altitude.
The flight trajectory of different targets is different, so I want to classify a large number of trajectory data I have, whether it is possible to extract features with TSFresh (since it does not involve the size of data, but the difference of different targets caused by different data changes), and whether TsFresh can manually extract features I need
In addition, whether tsfresh can be applied to the live data and streamed data

**Comment by MaxBenChrist** [comment]
Maybe you have a look at our documentation? https://tsfresh.readthedocs.io/en/latest/text/introduction.html

**Comment by nils-braun** [comment]
Feel free to reopen, but I think Max already answered with a link to our documentation.
