### ISSUE TITLE
Description not matching function name

### ISSUE THREAD

**Issue by emanuelef** [blue-yonder/tsfresh#724]
Hi,
just noticed a possible mismatch in the documentation, is it possible that the descriptions for 
percentage_of_reoccurring_datapoints_to_all_datapoints  and
percentage_of_reoccurring_values_to_all_values
have been swapped ?

https://github.com/blue-yonder/tsfresh/blob/f8a952e4ea9d80189e2a6d6c43b119727047c4c4/tsfresh/feature_extraction/feature_calculators.py#L866

https://github.com/blue-yonder/tsfresh/blob/f8a952e4ea9d80189e2a6d6c43b119727047c4c4/tsfresh/feature_extraction/feature_calculators.py#L894

**Comment by nils-braun** [comment]
Hi @emanuelef !
Thanks for the issue :-) You are right, there is something unclear there.
In my opinion, I think the descriptions match the code:

```
   ...
        len(different values occurring more than once) / len(different values)
    This means the percentage is normalized to the number of unique values,
    ...
np.sum(counts > 1) / float(counts.shape[0])
```

and

```
    ...
        # of data points occurring more than once / # of all data points
    This means the ratio is normalized to the number of data points in the time series
    ...
reoccuring_values / x.size
```

However, one could argue that the function names themselves are swapped! 
Would you like to do a pull request to change that?

**Comment by emanuelef** [comment]
Sure, I guess also tests needs to be fixed then:
https://github.com/blue-yonder/tsfresh/blob/f8a952e4ea9d80189e2a6d6c43b119727047c4c4/tests/units/feature_extraction/test_feature_calculations.py#L518

I also wanted to ask why one has two decorators:
@set_property("fctype", "simple")
@set_property("input", "pd.Series")
but the other one misses "input"

Thanks

**Comment by emanuelef** [comment]
Another question is about the name of the test for percentage_of_reoccurring_values_to_all_values
which is currently test_ratio_of_doubled_values

**Comment by emanuelef** [comment]
Last question is about creating the PR, I cannot create a branch here, ok to create the PR from a fork ?

**Comment by nils-braun** [comment]
Let me try to answer:
* Yes, forking is the usual way (not only for tsfresh, but basically for every project on GitHub)
* Feel free to change every naming that makes sense to you! We can discuss the details on the pull request :-)
* The input parameter controls the type conversation. I need to look up the details, but it looks like it is not needed. You can leave it as it is for now

**Comment by nils-braun** [comment]
Sorry quick update: the input parameter is fine. The second function uses the "value_counts" method of the pandas series whereas the first one uses numpy functionality.

**Comment by nils-braun** [comment]
Fixed in referencing PR
