### ISSUE TITLE
example 05 time series forecasting - rolling time series produce string id not tuple

### ISSUE THREAD

**Issue by cpop-fr** [blue-yonder/tsfresh#726]
I am trying to follow the example _05 Timeseries Forecasting.ipynb_ provided in the master repository.

When I tried to filter the id by a tuple I didn't get any match:
df_rolled[df_rolled["id"] == ("AAPL", pd.to_datetime("2015-07-15"))]

I realize the id column return by the **roll_time_series** is not a tuple but a string.
I managed to filter the id by doing this:

to_find = 'id={},timeshift={}'.format("AAPL", pd.to_datetime("2015-07-07"))
df_rolled[df_rolled["id"] == to_find]

Did the implementation change or did I do something wrong ?

The test are done using:
- Mac OS 
- tsfresh==0.16.0

**Comment by nils-braun** [comment]
Hi @cpop-fr !
Very good catch, thanks for that.
The implementation did actually change and is currently changing. In the next release, it will be a tuple.
I do now know why the change in the notebook did already make it into v0.16.0... It is inconsistent now. Sorry for that! 
I will try to make sure that it is consistent in the next release.
Are you fine with waiting for the next release or should we patch v0.16.0 to fix this?

**Comment by cpop-fr** [comment]
hi, 
yes I could live with that don't worry :) 
Thanks for your quick reply

**Comment by nils-braun** [comment]
The new version 0.17.0 should now fix this inconsistency (it is both a tuple now). I just tested the notebook and it is fine again! thanks for raising the issue.
