### ISSUE TITLE
example 05 time series forecasting - final shift for predict value

### ISSUE THREAD

**Issue by cpop-fr** [blue-yonder/tsfresh#727]
Hi again,

While digging deeper into the example 05 time series forecasting, I am not sure about the last shift for the prediction values.

To compare the next day price (y) with the prediction (y_pred) you shift the prediction vector.

y.plot(ax=plt.gca())
y_pred.shift(-1).plot(ax=plt.gca(), legend=None, marker=".")

But by doing this there is no more value for the last date. So what's is the prediction for this one ?
I don't see the point to shift the values if you compare with the vector of the next day price which y_pred should be, right ?

**Comment by nils-braun** [comment]
Hi @cpop-fr!
Yes - good catch. I recently changed the logic of this notebook, and it seems that had gone wrong. The shift is already done for the definition of `y` itself - no need to do it twice.

**Comment by MaxBenChrist** [comment]
@nils-braun, this can be closed right?
