### ISSUE TITLE
ZeroDivisionError: division by zero / neat-python

### ISSUE THREAD

**Issue by vinny95922** [blue-yonder/tsfresh#739]
can someone point out to me why i get the division by zero error in the neat-python module when i set the default config file's "pop_size" to 1, the exact error is given for the the neat/mathutil.py file, line 9 in mean, return sum(map(float, values)) / len(values), ZeroDivisionError: division by zero.

if i set pop_size to anything above 1, theres no error but i do occasionally get a muddle up in my results as ive written my code to only run 1 genome at a time which is what i need.

in advance thank you very much for your time, im looking forward with your replies.

**Comment by nils-braun** [comment]
Hello @vinny95922 !

Thank you very much for your issue. However, I am not sure I understand it correctly. Are you using tsfresh or any library in top of it? We do not have any settings of pop_size I am aware of and we are also not working with genomes directly.
Could you please share some code and the data?

**Comment by nils-braun** [comment]
I am going to close this issue due to inactive. Feel free to reopen if the problem reoccurs
