### ISSUE TITLE
Classifying the feature calculators.

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#74]
We can use our `@set_property(` decorator to give the feature calculators objects properties. 

This can be for example used to classify `fast` calculators such as `@set_property("minimal", True)`. We could use such properties to classify our feature calculators even further. For example we could denote calculators that are *"time independent"* or that are *"medium costly"* or highly *"highly costly"*. 

This issue should be a starting point for a discussion.

**Comment by nils-braun** [comment]
Some hints on how to find those functions (and already many fixes) are in #186

**Comment by nils-braun** [comment]
We have a "high_comp_cost" setting which does exactly this.
