### ISSUE TITLE
function calculator is an estimate for a time series complexity (cid_ce)

### ISSUE THREAD

**Issue by ghayth82** [blue-yonder/tsfresh#742]
the equation you are using to calculate  cid_ce is different from the original paper as the upper limit of sum is (n-1) in the paper while you put (n-2lag) in the documentation 
<img width="349" alt="1" src="https://user-images.githubusercontent.com/43137393/89958796-81fd4480-dc43-11ea-8736-bcc60cafbfeb.PNG">
<img width="153" alt="2" src="https://user-images.githubusercontent.com/43137393/89958800-832e7180-dc43-11ea-8fb3-68730c71dd47.PNG">

**Comment by nils-braun** [comment]
@MaxBenChrist @kempa-liehr Could you help out here?

**Comment by kempa-liehr** [comment]
Hi @ghayth82, thanks for pointing this out. Cheers, Andreas
