### ISSUE TITLE
what is the easiest way to write a simple custom feature

### ISSUE THREAD

**Issue by HaveF** [blue-yonder/tsfresh#745]
I read the doc - [How to add a custom feature — tsfresh 0.16.1.dev64+g33910f5 documentation](https://tsfresh.readthedocs.io/en/latest/text/how_to_add_custom_feature.html)

And also searched the issues.

I just want to add a simple feature like `(feature1_last_item - feature1_first_item)/feature1_first_item`.

Does adding the simple calculation to the tsfresh code is the only option?

In tsfresh issues, some posts say I can moving these calculations to pre/post-processing step, but I also want to use rolling features in tsfresh, so it seems to do the calculations in tsfresh is a reasonable choice.

Thanks in advance

**Comment by dbarbier** [comment]
Hello, there is an example at https://github.com/blue-yonder/tsfresh/issues/482#issuecomment-667203955

**Comment by HaveF** [comment]
@dbarbier Thanks your idea. I will try it later.
btw, if I use `kind_to_fc_parameters`, so I just add the functions to `tsfresh.feature_extraction.EfficientFCParameters`, it also works, right?
