### ISSUE TITLE
tsfresh-0.16.0: TYPE_ERROR 

### ISSUE THREAD

**Issue by lonet** [blue-yonder/tsfresh#747]
Hi

tsfresh is a great repo of various useful methods.. Thanks for this bunch of methods. 

I am using Debian GNU/Linux 9 (stretch) 64-bit tsfresh-0.16.0:

I am encountering an error stating that:

TypeError: sequence item 0: expected str instance, int found

164         if not str(table_const.empty):
    165             warnings.warn("[test_feature_significance] Constant features: {}"
--> 166                           .format(", ".join(map(str,table_const.feature))), RuntimeWarning)
    167 
    168         if len(table_const) == len(relevance_table):

in the file lib/python3.5/site-packages/tsfresh/feature_selection/relevance.py

I used the following method in tsfresh to find the relevance of the features:

tsfresh.feature_selection.relevance.calculate_relevance_table(df,YTrain, ml_task='classification', n_jobs=1, show_warnings=False, chunksize=None, test_for_binary_target_binary_feature='fisher', test_for_binary_target_real_feature='mann', test_for_real_target_binary_feature='mann', test_for_real_target_real_feature='kendall', fdr_level=0.05, hypotheses_independent=False) >

The df is the data frame which has the dimension 390 rows × 17 columns and YTrain is the target which has the dimension (390,)

A  smple of df 
 	0 	1 	2 	3 	4 	5 	6 	7 	8 	9 	10 	11 	12 	13 	14 	15 	16
0 	1 	43 	0 	43 	1 	0 	2 	42 	0 	43 	1 	0 	3 	44 	2 	44 	3
1 	1 	43 	0 	43 	1 	0 	1 	43 	0 	43 	1 	0 	2 	44 	2 	44 	3
----
----
389 -------------
A smple of YTrain

0      22
1      28
2      21
3      15
4       2
  
---
389  --     ..

Could you help me to find the root cause and solution to this error?

**Comment by nils-braun** [comment]
Hi @lonet!
Thank you very much for the bug report! (just a small hint: you can use the "code" format in your post, that will make it easier to read).

Guessing from your stacktrace, you have already tried to fix it with a `map(str, table_const.feature)` and that is very correct! Would you like to file a PR (we always love to have more contributors!)  or should I fix it?

**Comment by lonet** [comment]
@nils-braun: Thanks for your appreciation. I am not familiar with pulling request steps. I tried for it with some demo files and ended up in some key issues when I use git commit. Any steps that I should follow to contribute from my side.?

**Comment by lonet** [comment]
@nils-braun  I think I can make the sufficient changes and file a PR. Shall I proceed with forking and fixing it.?

**Comment by nils-braun** [comment]
Yes, that would be awesome! If you need help with git in general or with GitHub, just tell me! 
Thank you for your contribution!

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by lonet** [comment]
@nils-braun I have raised a pull request after fixing the issue. Is that sufficient for this issue..

**Comment by nils-braun** [comment]
Hi @lonet - where did you create your pull request? I can not find one on the `tsfresh` repo: https://github.com/blue-yonder/tsfresh/pulls

**Comment by lonet** [comment]
Hi @ nils-braun - Thanks for your short sufficient intro into PR and committing logic..Great..

**Comment by lonet** [comment]
Hi @ nils-braun - Thanks for your short sufficient intro into PR and committing logic..Great..

**Comment by lonet** [comment]
Hi @nils-braun - Thanks for your short sufficient intro into PR and committing logic..Great..
