### ISSUE TITLE
extractfeatures: Error in coloum id

### ISSUE THREAD

**Issue by lonet** [blue-yonder/tsfresh#751]
Hi

I am using the extract features function from tsfresh and getting this error regarding the columids. ...
My dataframes are like the attachment given with this error message
![dframe](https://user-images.githubusercontent.com/5396836/91838823-b6c15200-ec6b-11ea-9489-0955ee344b4a.png)

AttributeError                            Traceback (most recent call last)
<ipython-input-111-bda3c1f76209> in <module>
      1 newT = pd.concat(frame1)
      2 from tsfresh import extract_features, select_features
----> 3 X_extracted = extract_features(newD, newD.column_id, newD.sort_values)
      4 X_selected = select_features(X_extracted, newT)

~/anaconda3/envs/trend/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5128             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5129                 return self[name]
-> 5130             return object.__getattribute__(self, name)
   5131 
   5132     def __setattr__(self, name: str, value) -> None:

AttributeError: 'DataFrame' object has no attribute 'column_id'
``

Even after changing to the extract features normal parameter format I am getting this error as

![erro2](https://user-images.githubusercontent.com/5396836/91840021-a27e5480-ec6d-11ea-9232-6d14d9829999.png)
Anyone could figure out this error will be much appreciated..

**Comment by nils-braun** [comment]
Thank you for your message!

tsfresh is referring to the columns by name. This means your pandas data frame actually needs to have named columns. From the screenshot you shared it seems, your columns are names 1, 2, 3 etc. 
Which if them is the id column? And do you have a time column? If you give the columns some better, telling names you can refer to them in the extract features function

**Comment by lonet** [comment]
@nils-braun Thanks for your valuable input... I will work on it..

**Comment by nils-braun** [comment]
@lonet Any updates on this? I will close the issue now because from my perspective, the solution is written down but if you need more information, please feel free to reopen it!
