### ISSUE TITLE
error running the quickstart example code

### ISSUE THREAD

**Issue by AsiehH** [blue-yonder/tsfresh#752]
Hi, 
I'm running the example code in the quick start and I receive an error running **extract_features**. Please find the information request below. 

1. Your operating system: **windows 10**
2. The version of *tsfresh* that you are using: **0.16.0**
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one): **load_robot_execution_failures()**
4. A minimal code snippet which reproduces the problem/bug: 
`from tsfresh import extract_features
extracted_features = extract_features(timeseries, column_id="id", column_sort="time")`

5. Any reported errors or traceback

> RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\HARAAS\Miniconda3\envs\myclone\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\HARAAS\Miniconda3\envs\myclone\lib\site-packages\tsfresh\utilities\distribution.py", line 39, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "C:\Users\HARAAS\Miniconda3\envs\myclone\lib\site-packages\tsfresh\utilities\distribution.py", line 38, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "C:\Users\HARAAS\Miniconda3\envs\myclone\lib\site-packages\tsfresh\feature_extraction\extraction.py", line 390, in _do_extraction_on_chunk
    return list(_f())
  File "C:\Users\HARAAS\Miniconda3\envs\myclone\lib\site-packages\tsfresh\feature_extraction\extraction.py", line 376, in _f
    result = func(x, param=parameter_list)
  File "C:\Users\HARAAS\Miniconda3\envs\myclone\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py", line 418, in partial_autocorrelation
    pacf_coeffs = list(pacf(x, method="ld", nlags=max_lag))
  File "C:\Users\HARAAS\Miniconda3\envs\myclone\lib\site-packages\statsmodels\tsa\stattools.py", line 1026, in pacf
    "Can only compute partial correlations for lags up to 50% of the "
ValueError: Can only compute partial correlations for lags up to 50% of the sample size. The requested nlags 9 must be < 7.

> 

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-45-51bb4f99bf3d> in <module>
      1 from tsfresh import extract_features
----> 2 extracted_features = extract_features(timeseries, column_id="id", column_sort="time")

~\Miniconda3\envs\myclone\lib\site-packages\tsfresh\feature_extraction\extraction.py in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor)
    158                                 default_fc_parameters=default_fc_parameters,
    159                                 kind_to_fc_parameters=kind_to_fc_parameters,
--> 160                                 distributor=distributor)
    161 
    162         # Impute the result if requested

~\Miniconda3\envs\myclone\lib\site-packages\tsfresh\feature_extraction\extraction.py in _do_extraction(df, column_id, column_value, column_kind, default_fc_parameters, kind_to_fc_parameters, n_jobs, chunk_size, disable_progressbar, show_warnings, distributor)
    309     result = distributor.map_reduce(_do_extraction_on_chunk, data=data_in_chunks,
    310                                     chunk_size=chunk_size,
--> 311                                     function_kwargs=kwargs)
    312     distributor.close()
    313 

~\Miniconda3\envs\myclone\lib\site-packages\tsfresh\utilities\distribution.py in map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    165             result = self.distribute(_function_with_partly_reduce, chunk_generator, map_kwargs),
    166 
--> 167         result = list(itertools.chain.from_iterable(result))
    168 
    169         return result

~\Miniconda3\envs\myclone\lib\site-packages\tqdm\std.py in __iter__(self)
   1128 
   1129         try:
-> 1130             for obj in iterable:
   1131                 yield obj
   1132                 # Update and possibly print the progressbar.

~\Miniconda3\envs\myclone\lib\multiprocessing\pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

ValueError: Can only compute partial correlations for lags up to 50% of the sample size. The requested nlags 9 must be < 7.

>

**Comment by nils-braun** [comment]
Thank you very much for your issue!

This problem has already been solved on #748. The next release will include these changes. Maybe I can do a new release today in the evening (europe time).

If you want to fix it right now, you can also downgrade the statsmodels package to a version below 0.12.

**Comment by AsiehH** [comment]
thank you @nils-braun!

**Comment by nils-braun** [comment]
@AsiehH I just uploaded a new version (tsfresh 0.17.0). Would you mind testing it with the new version?

**Comment by world4jason** [comment]
> @AsiehH I just uploaded a new version (tsfresh 0.17.0). Would you mind testing it with the new version?
upgrade from 0.16.0 to 0.17.0 and the issue is solved
