### ISSUE TITLE
Improve documentation on "impute_function"

### ISSUE THREAD

**Issue by AsiehH** [blue-yonder/tsfresh#754]
I receive an error when passing a dataframe with nan in some columns in the following code where df_rolled is the output of `roll_time_series`:

`from tsfresh.feature_extraction import extract_features, EfficientFCParameters`
`from tsfresh.utilities.dataframe_functions import impute`

`extraction_setting = EfficientFCParameters()`
`X = extract_features(df_rolled, 
                     column_id="id", column_sort="month", 
                     default_fc_parameters=extraction_setting,
                     impute_function=impute, 
                     show_warnings=False)`

`ValueError: Column must not contain NaN values: ratio_last_sum_PPDOS`

There is an old issue #18 but it appears that `tsfresh.feature_extraction. FeatureExtractionSettings` doesn't exist anymore.

**Comment by AsiehH** [comment]
Ok, so I figured out that the `impute_function` parameter in `extract_features` does not impute missing values in the input but the output! 
It would be great to clarify this in the documentation [here](https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html?highlight=extract_features#tsfresh.feature_extraction.extraction.extract_features)

Currently the definition is as follows

> impute_function

 >(None or callable) – None, if no imputing should happen or the function to call for imputing>

**Comment by nils-braun** [comment]
Thanks for getting back to the issue and looking for the solution by yourself. If you have a a good suggestion, we would love to see a PR :-)
Otherwise we can also try to fix it
