### ISSUE TITLE
ValueError: The following ids are in the time series container but are missing in y:

### ISSUE THREAD

**Issue by grig101** [blue-yonder/tsfresh#755]
Hello, I'm using tsfresh to extract features from univariate energy time series. On the newer versions >0.15 the same code that was working fine some months ago outputs the error above and a huge list of ids (input data is a year of 15-min sampled energy readings).

x=pd.Series(data=dfs[0].values.flatten(),index=dfs[0].index)
df_shift, y = make_forecasting_frame(x, kind="price", max_timeshift=10, rolling_direction=1)
X = extract_relevant_features(df_shift,y, column_id="id", column_sort="time", column_value="value", 
                     show_warnings=False)

If I downgrade to 0.12 for example it works fine. Could you please tell me what changed between versions with regard to the rolling mechanism or with the column ids for the feature extraction step? Thank you!

**Comment by nils-braun** [comment]
Thank you very much for your issue, @grig101!

That actually looks like a but - thanks for finding it! 
I will create a PR to fix it. In the meantime, you can probably just include the line

```python
y.index = map(lambda x: ("id", x), y.index)
```

before the feature extraction to fix this.

As you were interested in the changes: both 0.16.0 and 0.17.0 changed the way that we output the rolled indices. Unfortunately it seems, we have not changed the output of the `y` accordingly in this function.

**Comment by igorkf** [comment]
Seems that the `y` needs to get an index from `X` data. Is this right? I was having problems, but when I did:
```
y.index = data['id'].tolist()
```
Now seems that I can use `extract_relevant_features()` well.

**Comment by nils-braun** [comment]
Yes, that is correct. `y` needs to have an index, which contains the identifiers of X.
Does this mean it is still not working even with the fix?
