### ISSUE TITLE
'MaybeEncodingError' in extracting feature

### ISSUE THREAD

**Issue by ramdhan1989** [blue-yonder/tsfresh#764]
Hi, this is very great repo. I got the problem when doing extract_feature. the error is shown below. and my data type is 
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1270829 entries, 128949 to 16922388
Data columns (total 5 columns):
    Column            Non-Null Count    Dtype         
---  ------            --------------    -----         
 0   time              1270829 non-null  datetime64[ns]
 1   PREV_JOB_NUMBER   1270829 non-null  object        
 2   AVG_VOLT_TOTAL_x  1270829 non-null  float64       
 3   AVG_AMP_TOTAL_x   1270829 non-null  float64        
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 58.2+ MB

I try to extract from two time series  AVG_VOLT_TOTAL_x ,  AVG_AMP_TOTAL_x 

`---------------------------------------------------------------------------
MaybeEncodingError                        Traceback (most recent call last)
<ipython-input-75-a74a403c457d> in <module>
      4                      default_fc_parameters=extraction_settings,
      5                      # we impute = remove all NaN features automatically
----> 6                      impute_function=None)

~\AppData\Local\Continuum\anaconda3\envs\segmentation\lib\site-packages\tsfresh\feature_extraction\extraction.py in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor, pivot)
    159                                 kind_to_fc_parameters=kind_to_fc_parameters,
    160                                 distributor=distributor,
--> 161                                 pivot=pivot)
    162 
    163         # Impute the result if requested

~\AppData\Local\Continuum\anaconda3\envs\segmentation\lib\site-packages\tsfresh\feature_extraction\extraction.py in _do_extraction(df, column_id, column_value, column_kind, column_sort, default_fc_parameters, kind_to_fc_parameters, n_jobs, chunk_size, disable_progressbar, show_warnings, distributor, pivot)
    253     result = distributor.map_reduce(_do_extraction_on_chunk, data=data,
    254                                     chunk_size=chunk_size,
--> 255                                     function_kwargs=kwargs)
    256 
    257     if not pivot:

~\AppData\Local\Continuum\anaconda3\envs\segmentation\lib\site-packages\tsfresh\utilities\distribution.py in map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    211             result = self.distribute(_function_with_partly_reduce, chunk_generator, map_kwargs),
    212 
--> 213         result = list(itertools.chain.from_iterable(result))
    214 
    215         self.close()

~\AppData\Local\Continuum\anaconda3\envs\segmentation\lib\site-packages\tqdm\std.py in __iter__(self)
   1079             """), fp_write=getattr(self.fp, 'write', sys.stderr.write))
   1080 
-> 1081         for obj in iterable:
   1082             yield obj
   1083             # Update and possibly print the progressbar.

~\AppData\Local\Continuum\anaconda3\envs\segmentation\lib\multiprocessing\pool.py in next(self, timeout)
    733         if success:
    734             return value
--> 735         raise value
    736 
    737     __next__ = next                    # XXX

MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x000001D0590DC208>'. Reason: 'PicklingError("Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError",)'`

please advise,

thank you

**Comment by nils-braun** [comment]
Thank you very much for your issue and I am very sorry it took so long to answer it!

The exception comes from the fact, that the multiprocessing library we use is not able to pickle the Memory error which is thrown on one of your processes. So the solution is actually not to fix this encoding error, but to resolve your memory exception.

There are multiple ways you can try out. Some of them are described in our [documentation](https://tsfresh.readthedocs.io/en/latest/text/large_data.html) or one of my [blog entries](https://nils-braun.github.io/tsfresh-on-cluster-1/) 

Is all your data just from a single id? Or how many identifiers do you have? How large is a single time series?

**Comment by ramdhan1989** [comment]
the data is coming from multiple id ~ 300 id. each id has different amount of time/row with same data freq. So, single time series would be different for each id. certain id could have 1500 rows.

**Comment by nils-braun** [comment]
Then I would suggest to either reduce the number of concurrent jobs in multiprocessing (will take longer, but will also need less memory) or do it step by step with something like luigi (as described in the second part of the blog post). 
If you are already familiar with dask or spark, you could of course also use that but I would not start with it.

**Comment by ramdhan1989** [comment]
Thanks for your information. It works by making same number of step for each ID. So, I need to change the way of problem framing  which still ok from expertise point of view.
