### ISSUE TITLE
Rolling Time series arbitrary slice step.

### ISSUE THREAD

**Issue by madpower2000** [blue-yonder/tsfresh#765]
As I understand, roll_time_series() shifts data one timestep only and there is no possibility to have shifts it arbitrary.
For some kind of huge time series data, I think will be useful using slice step greater than one, so I suggest consider adding the appropriate argument to the function roll_time_series().

For example my time series data has 300 000 samples and I am using a rolling window=100, so the resulting rolled dataset will be an enormous size with default rolling steps equal to one. Besides I think it’s also a waste of computational resources hence my data changes slowly.

**Comment by nils-braun** [comment]
That sounds to me like a very reasonable feature request!
How about using the already present "rolling_direction" parameter and using the abs value for it?
That would look something like this:
```python
from tsfresh.examples import load_robot_execution_failures
from tsfresh.utilities.dataframe_functions import roll_time_series

df, _ = load_robot_execution_failures()
print(roll_time_series(df, column_id="id", column_sort="time", rolling_direction=-2, max_timeshift=5).head(20))

          id  time  F_x  F_y  F_z  T_x  T_y  T_z
528   (1, 0)     0   -1   -1   63   -3   -1    0
529   (1, 0)     1    0    0   62   -3   -1    0
530   (1, 0)     2   -1   -1   61   -3    0    0
531   (1, 0)     3   -1   -1   63   -2   -1    0
532   (1, 0)     4   -1   -1   63   -3   -1    0
533   (1, 0)     5   -1   -1   63   -3   -1    0
0     (1, 2)     2   -1   -1   61   -3    0    0
1     (1, 2)     3   -1   -1   63   -2   -1    0
2     (1, 2)     4   -1   -1   63   -3   -1    0
3     (1, 2)     5   -1   -1   63   -3   -1    0
4     (1, 2)     6   -1   -1   63   -3    0    0
5     (1, 2)     7   -1   -1   63   -3   -1    0
1056  (1, 4)     4   -1   -1   63   -3   -1    0
1057  (1, 4)     5   -1   -1   63   -3   -1    0
1058  (1, 4)     6   -1   -1   63   -3    0    0
1059  (1, 4)     7   -1   -1   63   -3   -1    0
1060  (1, 4)     8   -1   -1   63   -3   -1    0
1061  (1, 4)     9   -1   -1   61   -3    0    0
1584  (1, 6)     6   -1   -1   63   -3    0    0
1585  (1, 6)     7   -1   -1   63   -3   -1    0
```

**Comment by madpower2000** [comment]
Incredible responsiveness to feature requests. Taking off my hat!

**Comment by nils-braun** [comment]
:-D unfortunately we can not solve every issue with this speed but I try ;-)

**Comment by arashtavakoli** [comment]
When I change the rolling_direction parameter nothing actually happens. It provides the same time series as keeping rolling_direction to pretty much any positive number

**Comment by nils-braun** [comment]
@arashtavakoli, let's handle this issue on #794, so we do not have duplicated conversations :-)
