### ISSUE TITLE
Error parsing using list of str in settings.from_column

### ISSUE THREAD

**Issue by ramdhan1989** [blue-yonder/tsfresh#768]
I am using tsfresh 0.17.0 and get error when doing settings.from_columns(configure). where configure is a list as shown below : 
`['amp__abs_energy',
 'amp__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"max"',
 'amp__autocorrelation__lag_5',
 'amp__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"var"',
 'amp__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"',
 'volt__fft_aggregated__aggtype_"kurtosis"',
 'volt__abs_energy',
 'volt__permutation_entropy__dimension_7__tau_1',
 'amp__quantile__q_0.9',
 'volt__c3__lag_2',
 'amp__sum_of_reoccurring_values',
 'volt__cid_ce__normalize_True',
 'amp__fft_coefficient__attr_"abs"__coeff_9',
 'amp__fft_coefficient__attr_"abs"__coeff_0',
 'amp__count_below_mean',
 'amp__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"mean"',
 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.6__ql_0.2',
 'amp__lempel_ziv_complexity__bins_100',
 'amp__partial_autocorrelation__lag_9',
 'amp__ar_coefficient__coeff_3__k_10',
 'volt__longest_strike_below_mean',
 'amp__c3__lag_2',
 'volt__change_quantiles__f_agg_"var"__isabs_False__qh_0.8__ql_0.2',
 'volt__quantile__q_0.3',
 'amp__change_quantiles__f_agg_"mean"__isabs_True__qh_0.6__ql_0.0',
 'volt__ar_coefficient__coeff_9__k_10',
 'volt__variance',
 'volt__longest_strike_above_mean',
 'amp__autocorrelation__lag_2',
 'volt__quantile__q_0.7',
 'volt__linear_trend__attr_"stderr"',
 'amp__ar_coefficient__coeff_2__k_10',
 'volt__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"mean"',
 'amp__linear_trend__attr_"intercept"',
 'volt__ar_coefficient__coeff_2__k_10',
 'volt__benford_correlation',
 'volt__change_quantiles__f_agg_"mean"__isabs_True__qh_0.6__ql_0.4',
 'amp__number_crossing_m__m_0',
 'amp__maximum',
 'amp__cwt_coefficients__coeff_4__w_10__widths_(2,_5,_10,_20)',
 'amp__percentage_of_reoccurring_values_to_all_values',
 'amp__number_crossing_m__m_-1',
 'amp__quantile__q_0.7',
 'volt__quantile__q_0.1',
 'volt__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"max"',
 'volt__permutation_entropy__dimension_5__tau_1',
 'volt__fft_coefficient__attr_"abs"__coeff_0',
 'amp__fft_coefficient__attr_"abs"__coeff_13',
 'amp__energy_ratio_by_chunks__num_segments_10__segment_focus_0',
 'volt__number_crossing_m__m_1',
 'amp__ratio_value_number_to_time_series_length',
 'amp__first_location_of_minimum',
 'amp__number_crossing_m__m_1',
 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.6',
 'amp__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.6',
 'amp__fft_aggregated__aggtype_"centroid"',
 'amp__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.4',
 'volt__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"max"',
 'volt__autocorrelation__lag_4',
 'volt__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"min"',
 'volt__maximum',
 'volt__median',
 'volt__fft_coefficient__attr_"abs"__coeff_47',
 'amp__ar_coefficient__coeff_6__k_10',
 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.4',
 'volt__cwt_coefficients__coeff_3__w_20__widths_(2,_5,_10,_20)',
 'amp__quantile__q_0.1',
 'amp__longest_strike_below_mean',
 'amp__ratio_beyond_r_sigma__r_2',
 'amp__fft_coefficient__attr_"abs"__coeff_8',
 'amp__mean_abs_change',
 'volt__spkt_welch_density__coeff_2',
 'volt__autocorrelation__lag_1',
 'amp__fft_coefficient__attr_"abs"__coeff_52',
 'volt__ar_coefficient__coeff_3__k_10',
 'volt__lempel_ziv_complexity__bins_10',
 'amp__ar_coefficient__coeff_8__k_10',
 'volt__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"',
 'amp__cwt_coefficients__coeff_0__w_10__widths_(2,_5,_10,_20)',
 'amp__cid_ce__normalize_True',
 'amp__cwt_coefficients__coeff_13__w_20__widths_(2,_5,_10,_20)',
 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.6__ql_0.4',
 'volt__mean_abs_change',
 'amp__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"var"',
 'volt__lempel_ziv_complexity__bins_100',
 'volt__quantile__q_0.9',
 'amp__count_above__t_0',
 'volt__quantile__q_0.6',
 'amp__longest_strike_above_mean',
 'amp__energy_ratio_by_chunks__num_segments_10__segment_focus_9',
 'amp__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.6',
 'volt__partial_autocorrelation__lag_1',
 'amp__binned_entropy__max_bins_10',
 'volt__minimum',
 'amp__quantile__q_0.2',
 'amp__skewness',
 'volt__fft_coefficient__attr_"abs"__coeff_28',
 'amp__fft_coefficient__attr_"abs"__coeff_1',
 'volt__percentage_of_reoccurring_values_to_all_values',
 'volt__partial_autocorrelation__lag_4',
 'volt__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.0',
 'volt__cwt_coefficients__coeff_8__w_20__widths_(2,_5,_10,_20)',
 'volt__partial_autocorrelation__lag_7',
 'volt__cwt_coefficients__coeff_7__w_10__widths_(2,_5,_10,_20)',
 'amp__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.8',
 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.4__ql_0.0',
 'volt__fft_coefficient__attr_"abs"__coeff_37',
 'amp__percentage_of_reoccurring_datapoints_to_all_datapoints',
 'volt__fft_coefficient__attr_"abs"__coeff_39',
 'amp__ratio_beyond_r_sigma__r_1.5',
 'amp__fft_aggregated__aggtype_"skew"',
 'volt__quantile__q_0.2',
 'volt__fft_coefficient__attr_"abs"__coeff_58',
 'amp__change_quantiles__f_agg_"mean"__isabs_False__qh_0.8__ql_0.4',
 'volt__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.2',
 'amp__ar_coefficient__coeff_4__k_10',
 'amp__fft_coefficient__attr_"abs"__coeff_59',
 'volt__partial_autocorrelation__lag_2',
 'volt__count_below__t_0',
 'volt__fft_coefficient__attr_"abs"__coeff_48',
 'volt__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"max"',
 'volt__change_quantiles__f_agg_"mean"__isabs_True__qh_0.8__ql_0.0',
 'amp__fft_coefficient__attr_"abs"__coeff_33',
 'amp__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"var"',
 'amp__quantile__q_0.4',
 'amp__minimum',
 'volt__permutation_entropy__dimension_6__tau_1',
 'amp__change_quantiles__f_agg_"mean"__isabs_False__qh_0.6__ql_0.0',
 'volt__variation_coefficient',
 'volt__standard_deviation',
 'amp__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.4',
 'amp__quantile__q_0.8',
 'volt__fft_coefficient__attr_"abs"__coeff_36',
 'volt__time_reversal_asymmetry_statistic__lag_1',
 'amp__spkt_welch_density__coeff_5',
 'amp__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.2',
 'amp__lempel_ziv_complexity__bins_2',
 'volt__autocorrelation__lag_2',
 'amp__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"min"',
 'volt__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.4',
 'volt__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.2',
 'volt__autocorrelation__lag_5',
 'volt__range_count__max_1__min_-1',
 'amp__linear_trend__attr_"rvalue"']`

the error message is shown below : 
`Traceback (most recent call last):
  File "C:\Users\...\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-63-6d16b73651ec>", line 1, in <module>
    settings.from_columns(configure)
  File "C:\Users\...\site-packages\tsfresh\feature_extraction\settings.py", line 68, in from_columns
    config = get_config_from_string(parts)
  File "C:\Users\...\site-packages\tsfresh\utilities\string_manipulation.py", line 41, in get_config_from_string
    dict_if_configs[key] = ast.literal_eval(value)
  File "C:\Users\...\lib\ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "C:\Users\...\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    20)
      ^
SyntaxError: unexpected EOF while parsing`

I checked the error comes from item with extension values "widths_(2,_5,_10,_20)". anyone can help to fix it ?

pleas eadvise,

thank you

**Comment by nils-braun** [comment]
Hi @ramdhan1989 !
Thanks for the issue. May I ask how you created this list of columns? Was it by hand or did you use any of the functions we ship?

Because the string `widths_(2,_5,_10,_20)` is actually wrong - it should be ` "widths_(2, 5, 10, 20)"` (without the underscore).
If I use this in your list I can also successfully extract the settings.
```python
l = ['amp__abs_energy', 'amp__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"max"', 'amp__autocorrelation__lag_5', 'amp__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"var"', 'amp__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"mean"', 'volt__fft_aggregated__aggtype_"kurtosis"', 'volt__abs_energy', 'volt__permutation_entropy__dimension_7__tau_1', 'amp__quantile__q_0.9', 'volt__c3__lag_2', 'amp__sum_of_reoccurring_values', 'volt__cid_ce__normalize_True', 'amp__fft_coefficient__attr_"abs"__coeff_9', 'amp__fft_coefficient__attr_"abs"__coeff_0', 'amp__count_below_mean', 'amp__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"mean"', 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.6__ql_0.2', 'amp__lempel_ziv_complexity__bins_100', 'amp__partial_autocorrelation__lag_9', 'amp__ar_coefficient__coeff_3__k_10', 'volt__longest_strike_below_mean', 'amp__c3__lag_2', 'volt__change_quantiles__f_agg_"var"__isabs_False__qh_0.8__ql_0.2', 'volt__quantile__q_0.3', 'amp__change_quantiles__f_agg_"mean"__isabs_True__qh_0.6__ql_0.0', 'volt__ar_coefficient__coeff_9__k_10', 'volt__variance', 'volt__longest_strike_above_mean', 'amp__autocorrelation__lag_2', 'volt__quantile__q_0.7', 'volt__linear_trend__attr_"stderr"', 'amp__ar_coefficient__coeff_2__k_10', 'volt__agg_linear_trend__attr_"stderr"__chunk_len_10__f_agg_"mean"', 'amp__linear_trend__attr_"intercept"', 'volt__ar_coefficient__coeff_2__k_10', 'volt__benford_correlation', 'volt__change_quantiles__f_agg_"mean"__isabs_True__qh_0.6__ql_0.4', 'amp__number_crossing_m__m_0', 'amp__maximum', 'amp__cwt_coefficients__coeff_4__w_10__widths_(2, 5, 10, 20)', 'amp__percentage_of_reoccurring_values_to_all_values', 'amp__number_crossing_m__m_-1', 'amp__quantile__q_0.7', 'volt__quantile__q_0.1', 'volt__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"max"', 'volt__permutation_entropy__dimension_5__tau_1', 'volt__fft_coefficient__attr_"abs"__coeff_0', 'amp__fft_coefficient__attr_"abs"__coeff_13', 'amp__energy_ratio_by_chunks__num_segments_10__segment_focus_0', 'volt__number_crossing_m__m_1', 'amp__ratio_value_number_to_time_series_length', 'amp__first_location_of_minimum', 'amp__number_crossing_m__m_1', 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.6', 'amp__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.6', 'amp__fft_aggregated__aggtype_"centroid"', 'amp__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.4', 'volt__agg_linear_trend__attr_"slope"__chunk_len_50__f_agg_"max"', 'volt__autocorrelation__lag_4', 'volt__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"min"', 'volt__maximum', 'volt__median', 'volt__fft_coefficient__attr_"abs"__coeff_47', 'amp__ar_coefficient__coeff_6__k_10', 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.8__ql_0.4', 'volt__cwt_coefficients__coeff_3__w_20__widths_(2, 5, 10, 20)', 'amp__quantile__q_0.1', 'amp__longest_strike_below_mean', 'amp__ratio_beyond_r_sigma__r_2', 'amp__fft_coefficient__attr_"abs"__coeff_8', 'amp__mean_abs_change', 'volt__spkt_welch_density__coeff_2', 'volt__autocorrelation__lag_1', 'amp__fft_coefficient__attr_"abs"__coeff_52', 'volt__ar_coefficient__coeff_3__k_10', 'volt__lempel_ziv_complexity__bins_10', 'amp__ar_coefficient__coeff_8__k_10', 'volt__agg_linear_trend__attr_"intercept"__chunk_len_10__f_agg_"min"', 'amp__cwt_coefficients__coeff_0__w_10__widths_(2, 5, 10, 20)', 'amp__cid_ce__normalize_True', 'amp__cwt_coefficients__coeff_13__w_20__widths_(2, 5, 10, 20)', 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.6__ql_0.4', 'volt__mean_abs_change', 'amp__agg_linear_trend__attr_"rvalue"__chunk_len_10__f_agg_"var"', 'volt__lempel_ziv_complexity__bins_100', 'volt__quantile__q_0.9', 'amp__count_above__t_0', 'volt__quantile__q_0.6', 'amp__longest_strike_above_mean', 'amp__energy_ratio_by_chunks__num_segments_10__segment_focus_9', 'amp__change_quantiles__f_agg_"mean"__isabs_True__qh_1.0__ql_0.6', 'volt__partial_autocorrelation__lag_1', 'amp__binned_entropy__max_bins_10', 'volt__minimum', 'amp__quantile__q_0.2', 'amp__skewness', 'volt__fft_coefficient__attr_"abs"__coeff_28', 'amp__fft_coefficient__attr_"abs"__coeff_1', 'volt__percentage_of_reoccurring_values_to_all_values', 'volt__partial_autocorrelation__lag_4', 'volt__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.0', 'volt__cwt_coefficients__coeff_8__w_20__widths_(2, 5, 10, 20)', 'volt__partial_autocorrelation__lag_7', 'volt__cwt_coefficients__coeff_7__w_10__widths_(2, 5, 10, 20)', 'amp__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.8', 'volt__change_quantiles__f_agg_"var"__isabs_True__qh_0.4__ql_0.0', 'volt__fft_coefficient__attr_"abs"__coeff_37', 'amp__percentage_of_reoccurring_datapoints_to_all_datapoints', 'volt__fft_coefficient__attr_"abs"__coeff_39', 'amp__ratio_beyond_r_sigma__r_1.5', 'amp__fft_aggregated__aggtype_"skew"', 'volt__quantile__q_0.2', 'volt__fft_coefficient__attr_"abs"__coeff_58', 'amp__change_quantiles__f_agg_"mean"__isabs_False__qh_0.8__ql_0.4', 'volt__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.2', 'amp__ar_coefficient__coeff_4__k_10', 'amp__fft_coefficient__attr_"abs"__coeff_59', 'volt__partial_autocorrelation__lag_2', 'volt__count_below__t_0', 'volt__fft_coefficient__attr_"abs"__coeff_48', 'volt__agg_linear_trend__attr_"intercept"__chunk_len_5__f_agg_"max"', 'volt__change_quantiles__f_agg_"mean"__isabs_True__qh_0.8__ql_0.0', 'amp__fft_coefficient__attr_"abs"__coeff_33', 'amp__agg_linear_trend__attr_"stderr"__chunk_len_5__f_agg_"var"', 'amp__quantile__q_0.4', 'amp__minimum', 'volt__permutation_entropy__dimension_6__tau_1', 'amp__change_quantiles__f_agg_"mean"__isabs_False__qh_0.6__ql_0.0', 'volt__variation_coefficient', 'volt__standard_deviation', 'amp__change_quantiles__f_agg_"var"__isabs_False__qh_0.6__ql_0.4', 'amp__quantile__q_0.8', 'volt__fft_coefficient__attr_"abs"__coeff_36', 'volt__time_reversal_asymmetry_statistic__lag_1', 'amp__spkt_welch_density__coeff_5', 'amp__change_quantiles__f_agg_"var"__isabs_True__qh_1.0__ql_0.2', 'amp__lempel_ziv_complexity__bins_2', 'volt__autocorrelation__lag_2', 'amp__agg_linear_trend__attr_"slope"__chunk_len_10__f_agg_"min"', 'volt__change_quantiles__f_agg_"mean"__isabs_False__qh_1.0__ql_0.4', 'volt__change_quantiles__f_agg_"var"__isabs_False__qh_1.0__ql_0.2', 'volt__autocorrelation__lag_5', 'volt__range_count__max_1__min_-1', 'amp__linear_trend__attr_"rvalue"']
```

**Comment by ramdhan1989** [comment]
Ok I got it. I used lgbm feature importance to get name of feature using extracted feature from tsfresh. It changed the string with underscore. it is fixed thank you so much.
