### ISSUE TITLE
tsfresh.select_features.  Is it used for regression tasks? How should I set y?

### ISSUE THREAD

**Issue by yaosting** [blue-yonder/tsfresh#772]
Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system
2. The version of *tsfresh* that you are using
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
4. A minimal code snippet which reproduces the problem/bug
5. Any reported errors or traceback

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by yaosting** [comment]
If the ID of my data set belongs to a different type of product, but I don't know beforehand. If you put all data'y into select_features, you tend to get no features, because the interrelationships between the different types of features with y are themselves different, and if you put them together, it's hard to pass the hypothesis test

**Comment by yaosting** [comment]
Just like the demo data, it uses the robot monitoring data. This is a classification problem, and all the data is of the same kind. If there are different types of robots in the same data set, what should I do?  how to select features

**Comment by nils-braun** [comment]
Sorry it took a bit longer with the answer.

Why can't you just divide your dataset according to the different classes you have and then select the features on each of them separately?

Maybe I misunderstood your problem. Could you provide some example data?

**Comment by yaosting** [comment]
When I was preparing to reply to you, I think I was wrong in my previous thinking, or my understanding of TsFresh was wrong.
Previously, I planned to feed different types of sample data into TSFresh, and then obtain important features through .select_features()

Obviously, when multiple classes are mixed together, it will affect the result returned.

I think the design of TeFESH itself enters the same class by default.
so in the case of multiple classes, you are right, first extract the important features of each class, and then artificially select the common important features from the important features of each class.
