### ISSUE TITLE
How to extract a fixed list of features using tsfresh?

### ISSUE THREAD

**Issue by QitianHu46** [blue-yonder/tsfresh#773]
I would like to extract the following features:
`['qrate__sum_values', 'qrate__abs_energy', 'qrate__mean_change', 'qrate__median', 'qrate__mean', 'qrate__skewness', 'qrate__longest_strike_below_mean', 'qrate__count_below_mean', 'qrate__sample_entropy', 'qrate__minimum', 'qrate__time_reversal_asymmetry_statistic__lag_1', 'qrate__time_reversal_asymmetry_statistic__lag_2', 'qrate__time_reversal_asymmetry_statistic__lag_3', 'qrate__c3__lag_1', 'qrate__c3__lag_2']`

These are the column names of my tsfresh.select_features(). Where 'qrate' is my column name. My raw dataframe has the following columns: time, qrate, series_name. I found that I can edit tsfresh.ComprehensiveFCParameters() and make it a parameter of tsfresh.select_features(). However, if I select hundreds of features, it would be extremely inconvenient. I wonder if there's a way to just fit in those column names above and extract the corresponding features?

Thank you!

**Comment by nils-braun** [comment]
Hi! 
Yes, there is a possibility. Have you looked into https://tsfresh.readthedocs.io/en/latest/text/feature_extraction_settings.html#a-handy-trick-do-i-really-have-to-create-the-dictionary-by-hand?

Maybe this helps

**Comment by QitianHu46** [comment]
> Hi!
> Yes, there is a possibility. Have you looked into https://tsfresh.readthedocs.io/en/latest/text/feature_extraction_settings.html#a-handy-trick-do-i-really-have-to-create-the-dictionary-by-hand?
> 
> Maybe this helps

Thank you so so much! This helps a lot!

**Comment by nils-braun** [comment]
Very good! Glad that helps. If you have another question, feel free to comment again or re-open.
