### ISSUE TITLE
When faced with discrete time series data, how to use TSFresh to calculate the characteristics within a certain period of time?

### ISSUE THREAD

**Issue by yaosting** [blue-yonder/tsfresh#774]
-- The extract_feature is the feature under the calculation window, in which the data are sorted according to column_sort,
The result is a 'sequential feature' rather than a true temporal feature. The window size is all the incoming data.
So tsFresh cannot directly calculate the characteristics for a certain period of time accurately, even if column_sort passes in a real time value.

The following two methods can be used to calculate the characteristics over a certain period of time
1. When the extract_feature data is passed in, the data has been divided according to the time period, and then the divided data is passed in batch to obtain the results, and then merged.
--2. Use tsfresh.roll_time_series(feasible in some cases)
When max_timeshift = min_timeshift, ROLL_time_series returns a window data at column_sort with rows equal to min_timeshift,
If the data for column_sort at this point correspond to real time data, and are complete, it could return an equivalent of 1. Window data.
Then pass it to the extract_feature.
The core is to correlate the column_sort used by TsFresh one to one with actual time.

Is there any other way?

**Comment by nils-braun** [comment]
Yes, you are correct. tsfresh is "unopinionated" when it comes to data frequency and up or downsampling. That was a design decision, as there are too many ways such a resampling might happen to provide reasonable parameters.
We usually recommend to resample the data before to a fixed frequency of this is needed for your use case (e.g. with the pandas own functions).

Maybe you can combine the two methods: first start with a rolling to produce small time slices and then prune them if they contain inhomogeneous time frequencies.
But apart from that I think you are in the right track with your options.

**Comment by yaosting** [comment]
I think you're right, tsfresh should be 'unpinionated'.

1. When using TsFresh, users should ensure that the feed data is the same granularity in terms of time_index, although it may be discontinuous.
Because TsFresh does not aggregate itself, there is often complex logic behind aggregation. For example, when TIME_index is day level, two pieces of data should not appear in the data on the same day.

2. However, I think the roll_time_series calculation should be associated with time_index, for example
time_index, x1
0, 1
1, 5
2, 3
3, 6
6, 4
7, 4

When we want to get a window of length 3, we should get time_index[0,1,2],time_index[1,2,3], instead of four Windows, which are mandatory contiguously.

However, when the user has such a requirement, he can first return two DataFrame in the outer layer according to the continuity of time_index,
0, 1
1, 5
2, 3
3, 6
and
6, 4
7, 4

Then use roll_time_series with two DataFrame.

**Comment by nils-braun** [comment]
That is correct!
You can also produce all 4 time windows and the just filter out the wrong ones afterwards
