### ISSUE TITLE
ValueError: Could not guess the value column! Please hand it to the function as an argument

### ISSUE THREAD

**Issue by ynjacobs** [blue-yonder/tsfresh#792]
Hi, firstly thanks so much for this wonderful library!

I'm using ubuntu and tsfresh v:0.17.0

I'm trying to extract features on my data but I keep getting an error:
```
ValueError: Could not guess the value column! Please hand it to the function as an argument.
```
In the [source code for tsfresh feature extraction](https://tsfresh.readthedocs.io/en/latest/_modules/tsfresh/feature_extraction/data.) I see:

```
def _get_value_columns(df, *other_columns):
    value_columns = [col for col in df.columns if col not in other_columns]

    if len(value_columns) == 0:
        raise ValueError("Could not guess the value column! Please hand it to the function as an argument.")

    return value_columns
```
Which seems to indicate that my column length is 0 but when I print the length of my column, I see it is 64.
```
print(len(df.temperature))
```
```
[64 rows x 1 columns]
64
```

Here is the code I am working with:
```
from tsfresh import extract_features, extract_relevant_features, select_features
from tsfresh.utilities.dataframe_functions import impute

df = pandas.DataFrame(data=tempArray)
          
df.columns = ['temperature']
print(len(df.temperature))
extracted_features= extract_features(df, column_id='temperature')
impute(extracted_features)
```
Thanks so much!

**Comment by nils-braun** [comment]
I see you have closed the issue @ynjacobs - did you solve it? The problem was probably, that you only had a single column and no identifiers.

**Comment by ynjacobs** [comment]
Hi @nils-braun, yes thanks so much that was exactly my problem, I added an index column and it worked

**Comment by nils-braun** [comment]
Glad you solved it!

**Comment by ynjacobs** [comment]
Thanks so much!
