### ISSUE TITLE
Rolling_direction

### ISSUE THREAD

**Issue by arashtavakoli** [blue-yonder/tsfresh#794]
Hi,

I am trying to use rolling direction, but it seems that whatever number I put there it does not do anything. Basically, I change the rolling direction and it still provides the same dataframe no matter what. Here is my code. Is there any restrictions on the rolling_direction? my data has equal size timestamps. 

import tsfresh as ts
from tsfresh import extract_relevant_features
from tsfresh.utilities.dataframe_functions import roll_time_series

features = ['event_inside_labeled']
df_rolled = roll_time_series(lab_act_temp, column_id="source",column_sort="sort",min_timeshift=10,max_timeshift=15,rolling_direction=5)
print(df_rolled.shape)
for feature in features:
    extracted_features = ts.extract_features(df_rolled, column_id="id",column_value=feature)
    print(lab_act_temp.shape)
    print(extracted_features.shape)

**Comment by arashtavakoli** [comment]
Just to update here I am using a simple csv file and whenever I change the rolling direction it basically does nothing. 


sort | name | arash
-- | -- | --
1 | 4 | z
2 | 5 | z
3 | 6 | z
4 | 7 | z
5 | 8 | z
6 | 9 | z
7 | 10 | z
8 | 11 | z



and here is the simple code
import pandas as pd
import tsfresh as ts
from tsfresh import extract_relevant_features
from tsfresh.utilities.dataframe_functions import roll_time_series

if __name__ == '__main__':
	lab_act_temp = pd.read_csv("D:/Google Drive/UVA_PhD/Projects/Wearable Projects/Codes/Wearable_Event_detection/Activity classification/hjk.csv")
	df_rolled = roll_time_series(lab_act_temp, column_id="arash",min_timeshift=4,max_timeshift=4,rolling_direction=2)
	print(df_rolled.shape)

**Comment by nils-braun** [comment]
Hi @arashtavakoli!
Thanks for the issue. I am not 100% sure what you mean with "does not change". For example if I run:

```python
import pandas as pd
import tsfresh as ts
from tsfresh import extract_relevant_features
from tsfresh.utilities.dataframe_functions import roll_time_series

df = pd.DataFrame({"sort": [1, 2, 3, 4, 5, 6, 7, 8],
                   "name": [4, 5, 6, 7, 8, 9, 10, 11],
                   "arash": ["z"]*8
                  })


for rolling_direction in [-2, -1, 1, 2]:
    df_rolled = roll_time_series(df, column_id="arash", min_timeshift=4, max_timeshift=4, 
                                 rolling_direction=rolling_direction, disable_progressbar=True)
    print(f"rolling_direction = {rolling_direction}")
    print(df_rolled)
```
on the newest tsfresh head version I get:

```
rolling_direction = -2
   sort  name arash      id
5     0     4     z  (z, 0)
6     1     5     z  (z, 0)
7     2     6     z  (z, 0)
8     3     7     z  (z, 0)
9     4     8     z  (z, 0)
0     2     6     z  (z, 2)
1     3     7     z  (z, 2)
2     4     8     z  (z, 2)
3     5     9     z  (z, 2)
4     6    10     z  (z, 2)
rolling_direction = -1
    sort  name arash      id
5      0     4     z  (z, 0)
6      1     5     z  (z, 0)
7      2     6     z  (z, 0)
8      3     7     z  (z, 0)
9      4     8     z  (z, 0)
0      1     5     z  (z, 1)
1      2     6     z  (z, 1)
2      3     7     z  (z, 1)
3      4     8     z  (z, 1)
4      5     9     z  (z, 1)
10     2     6     z  (z, 2)
11     3     7     z  (z, 2)
12     4     8     z  (z, 2)
13     5     9     z  (z, 2)
14     6    10     z  (z, 2)
15     3     7     z  (z, 3)
16     4     8     z  (z, 3)
17     5     9     z  (z, 3)
18     6    10     z  (z, 3)
19     7    11     z  (z, 3)
rolling_direction = 1
    sort  name arash      id
0      0     4     z  (z, 4)
1      1     5     z  (z, 4)
2      2     6     z  (z, 4)
3      3     7     z  (z, 4)
4      4     8     z  (z, 4)
5      1     5     z  (z, 5)
6      2     6     z  (z, 5)
7      3     7     z  (z, 5)
8      4     8     z  (z, 5)
9      5     9     z  (z, 5)
10     2     6     z  (z, 6)
11     3     7     z  (z, 6)
12     4     8     z  (z, 6)
13     5     9     z  (z, 6)
14     6    10     z  (z, 6)
15     3     7     z  (z, 7)
16     4     8     z  (z, 7)
17     5     9     z  (z, 7)
18     6    10     z  (z, 7)
19     7    11     z  (z, 7)
rolling_direction = 2
   sort  name arash      id
0     1     5     z  (z, 5)
1     2     6     z  (z, 5)
2     3     7     z  (z, 5)
3     4     8     z  (z, 5)
4     5     9     z  (z, 5)
5     3     7     z  (z, 7)
6     4     8     z  (z, 7)
7     5     9     z  (z, 7)
8     6    10     z  (z, 7)
9     7    11     z  (z, 7)
```

Please note, that the feature you referring to is not already in any version, but can so far only be used with the development version so far.

**Comment by arashtavakoli** [comment]
Hi, thanks for your response. I finally figured out and install dit from github directly. The documentation says this is a feature so I naturally assumed this feature is added if it is on the documentation. Sorry, my bad, and thanks.

**Comment by nils-braun** [comment]
Ah, ok I understand. The documentation shows the current version on GitHub. If you would like to show documentation for a released version, you can change the shown version on the bottom left.
