### ISSUE TITLE
adding new features

### ISSUE THREAD

**Issue by arashtavakoli** [blue-yonder/tsfresh#795]
Hi again :D,

Based on the documentation I understand that for adding a new feature I only have to add it to the feature_extractor.py file. So I found that file and I added this feature as follows which basically tells me what is the maximum occurring element in the series (this can be used for labels in a time series with numerical labels), however, no new feature is being added after saving the feature extractor file. Also even if I comment out everything on the feature_extractor file it still calculates the features. It makes me wonder whether it is reading features from somewhere else? here is the feature I am trying to add:

@set_property("fctype", "simple")
def counting_labels(x):
    """
    The description of your feature

    :param x: the time series to calculate the feature of
    :type x: pandas.Series
    :return: the value of this feature
    :return type: bool, int or float
    """
    # Calculation of feature as float, int or bool
    f = x.value_counts().idxmax()
    return f

**Comment by nils-braun** [comment]
Hi ;-)
Two things that come to my mind. 
1. Did you also add your new feature to the feature settings, as described [here](https://tsfresh.readthedocs.io/en/latest/text/how_to_add_custom_feature.html#step-3-add-custom-settings-for-your-feature)
2. Make sure you are actually installing tsfresh in development mode. That is not tsfresh related, but a general python thing: how did you setup and download tsfresh? The correct way would be: git clone and then `pip install -e .` (without the `-e`, changes to the files will not be picked up)

**Comment by arashtavakoli** [comment]
thank you so much
