### ISSUE TITLE
get selected features from sklearn pipeline

### ISSUE THREAD

**Issue by nikoltchovskaa** [blue-yonder/tsfresh#796]
Hi. I am using your scikit-learn transformer (the `RelevantFeatureAugmenter`) to do some feature extraction on time series. I am interested in the features that tsfresh selects. So when I call the `extract_features` and `select_features` functions, tsfresh returns a dataframe with the extracted/selected features. So I am looking for a similar functionality with the transformer. In sklearn the pipelines have a `get_params` function but I couldn't find out if there is a parameter which gives me the selected features names. Is there a way to do this?

**Comment by nils-braun** [comment]
Good question!
Yes, it is possible. We have described it in our [pipeline notebook](https://github.com/blue-yonder/tsfresh/blob/main/notebooks/examples/02%20sklearn%20Pipeline.ipynb). You can call
```python
ppl.named_steps["augmenter"].feature_selector.relevant_features
```
(if `ppl` is your pipeline).

**Comment by nikoltchovskaa** [comment]
Thank you so much! This is exactly what I was looking for.
