### ISSUE TITLE
extract_features cannot get below 2.5 seconds

### ISSUE THREAD

**Issue by Thibaud-Barreau-ILB** [blue-yonder/tsfresh#803]
Hi,

1. OS : Windows 10  16 cores (but same issue on Linux 16 cores)
2. version : 0.17.0
3. A Time Series of length 10
4. The dataframe: 
![Capture_tsfresh](https://user-images.githubusercontent.com/75303264/105979849-70dead80-6094-11eb-8bcc-4cda3f1953bb.PNG)

The code:
![Capture_tsfresh2](https://user-images.githubusercontent.com/75303264/105980161-cfa42700-6094-11eb-9bac-d33c039f469c.PNG)

When I run the feature extraction using this code, it always takes at least 2.5 seconds, which seems a lot given that I'm working on 10 points with the MinimalFCParameters(). 
I would like to know if this is normal, if there is some kind of initialization time of some sort. 
I could not find any clear answer about this, the closest clue I could find is that it might be linked to the "pivot" operation, before the extraction, which is said to be slow. 
Do you have any other explanation ? Has this issue already been raised ? 

The issue is that I was planning on using tsfresh for an online application, to extract features to feed a pre-trained Machine Learning algorithm. But the execution time is currently arround 3 seconds, which is a bit much for this kind of operation. 
Is there a way to speed up the extraction execution, other than coding it myself ?  
Thanks ! :)

**Comment by nils-braun** [comment]
Cool issue :-)
Unfortunately, I can not reproduce :-( for me, the following code prints around 0.009 s.
Can you test with n_jobs = 0? Because just starting jobs (which are then not used) will take some time.

```python
import numpy as np
from time import time

import pandas as pd
from tsfresh import extract_features
from tsfresh.feature_extraction.settings import MinimalFCParameters

df = pd.DataFrame({"x": 2000*np.random.rand(20), "time": pd.date_range("2018-01-01", periods=20, freq="D"), "id": [0.0]*20})
df = df.set_index("time", drop=False)
df.index = df.index.set_names("")

print(df)

start = time()
X = extract_features(df, column_id="id", column_sort="time", default_fc_parameters=MinimalFCParameters(), n_jobs=0)
end = time()
print(end - start)
```

**Comment by Thibaud-Barreau-ILB** [comment]
It worked ! 
I roughly get around 0.01 s too.
Thanks a lot !
