### ISSUE TITLE
Dickey Fuller feature - return test statistic or boolean?

### ISSUE THREAD

**Issue by mynameisvinn** [blue-yonder/tsfresh#81]
as it currently stands, the feature returned by augmented_dickey_fuller is the test statistic. should (1) we return the test statistic feature or (2) a boolean, regarding reject/fail-to-reject hypothesis test?

in conventional analysis, this value is compared with corresponding values at 1%, 5%, 10% significance to test for stationarity (eg if DA statistic > 5% value, then fail to reject hypothesis of non-stationarity).

**Comment by MaxBenChrist** [comment]
we can have three different feature calculator: 1) value of test statistic 2) p-value 3) rejection of null hypothesis for level (alpha)

but the call to the augmented_dickey_fuller method should be cached by a decorator

**Comment by mynameisvinn** [comment]
sounds good. wrt #3 ill create the predicate function

**Comment by MaxBenChrist** [comment]
So, pr #227 will add the p-value. It is not that easy to also add the boolean flag because we are only calculating the features once. For the boolean flag you would need:

1.) calculate p-value => 2.) decide to reject hypothesis

I would leave 2.) to the user for the time being.

**Comment by nils-braun** [comment]
#227 was merged and no user complained :-)
