### ISSUE TITLE
Multiprocessing Not Working on Apple M1

### ISSUE THREAD

**Issue by befowler** [blue-yonder/tsfresh#812]
When using extract_features with n_jobs=-1 code doesn’t process. Changing n_jobs=0 code processes as it should. I’m running on Big Sur Apple Mac Mini M1 with 16gb of ram. I’m performing this operation on 10 columns and about 80,000 rows of stock ticker data from Tingo API. Of those 80,000 rows, I’m passing in about 4,500 rows at each call to extract_features. I also am unable to run multiprocessing jobs on the Mac as code doesn’t error but never completes. So, this may not be an issue that is resolvable until multiprocessing gets M1 support.

**Comment by nils-braun** [comment]
Did you add your code in a `__main__` guard, e.g. as described [here](https://stackoverflow.com/questions/65859890/python-multiprocessing-with-m1-mac)? That might be unrelated to Apple's M1 - or is it well-known fact multiprocessing does not run on the M1?

**Comment by befowler** [comment]
Thank you. I didn’t use main guard but will check it in the future.
