### ISSUE TITLE
select_features() does not work for binary target in time series forecasting

### ISSUE THREAD

**Issue by mendel5** [blue-yonder/tsfresh#814]
### Explanation
Hi @nils-braun, I would like to predict a binary target based on multiple real features.

What I'm trying to do is very similar to [https://github.com/blue-yonder/tsfresh/blob/main/notebooks/examples/05%20Timeseries%20Forecasting.ipynb](https://github.com/blue-yonder/tsfresh/blob/main/notebooks/examples/05%20Timeseries%20Forecasting.ipynb), except that I am trying to predict a binary target value instead of a real target value.

It works until here:
```
X_train_selected = select_features(X_train, y_train)
```

The data frame ```X_train_selected``` has all the rows but zero columns.

I read the docs at [https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_selection.html#module-tsfresh.feature_selection.selection](https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_selection.html#module-tsfresh.feature_selection.selection) but unfortunately that didn't help me.

### Standard template

Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system
This issue occurs both on Linux Mint 20 and Windows 7 (tsfresh installed through `pip`)

2. The version of *tsfresh* that you are using
Version is `0.17.0`

3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
Here it is:

|   | Date       | feature_Open | feature_High | feature_Volume | symbol_ID | target_Open_Higher_Tomorrow |
|---|------------|--------------|--------------|----------------|-----------|-----------------------------|
| 0 | 2021-02-12 | 134.35       | 135.530      | 60145130       | AAPL      | 1                           |
| 1 | 2021-02-16 | 135.49       | 136.010      | 80576316       | AAPL      | 0                           |
| 2 | 2021-02-17 | 131.25       | 132.220      | 98085249       | AAPL      | 0                           |
| 3 | 2021-02-18 | 129.20       | 129.995      | 96856748       | AAPL      | 1                           |
| 4 | 2021-02-19 | 130.24       | 130.710      | 87668834       | AAPL      | 0                           |
| 5 | 2021-02-22 | 128.01       | 129.720      | 103916419      | AAPL      | 0                           |
| 6 | 2021-02-23 | 123.76       | 126.710      | 158273022      | AAPL      | 0                           |

4. A minimal code snippet which reproduces the problem/bug
```
X_train_selected = select_features(X_train, y_train)
X_train_selected
```
`X_train_selected` has 0 columns. I would expect `X_train_selected` to have a reduced number of columns compared to `X_train`, but still >0 columns.

5. Any reported errors or traceback
no errors and no traceback

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

Related:
- https://tsfresh.readthedocs.io/en/latest/text/list_of_features.html
- https://tsfresh.readthedocs.io/en/latest/text/feature_extraction_settings.html
- https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html#module-tsfresh.feature_extraction.extraction
- https://tsfresh.readthedocs.io/en/latest/_modules/tsfresh/feature_extraction/extraction.html

**Comment by mendel5** [comment]
Hi @nils-braun, I'm still stuck at the `select_features(X_train, y_train)` method which returns 0 columns but I need more than 0 columns.

Unfortunately I cannot upload a sample of my actual data set because of copyright/ privacy issues with my university. My actual data set is about psychological statistics and I received it from my university.

To better illustrate my issue, I have created a dummy notebook and uploaded it at https://github.com/mendel5/tsfresh-issues/blob/main/01_time-series-forecast-binary/05%20Timeseries%20Forecasting_Classification.ipynb .
Strangely this time the `select_features(X_train, y_train)` method works.

My main problem with the actual psychology data set is that the `select_features()` method returns 0 columns and I don't know if that's because:
- (a) I made a mistake somewhere and the `select_features()` method cannot do the selection process properly, e.g. there are NaN or infinity values, wrong data type (float64 instead of int32, etc.). However there are no error messages which would indicate an error, or
- (b) the selection process works properly but there are no relevant features in my data set, hence 0 columns are returned.

The data type of the binary values I try to predict were numpy.float64. My guess was that maybe the `select_features()` method doesn't recognize the values as binary values. Therefore I've tried casting the values to different types, e.g. converting from numpy.float64 to numpy.int32. Unfortunately that didn't solve my issue.

What I am trying to do now is to figure out why the `select_features()` method in the dummy notebook linked above works but does not work in my actual notebook (with the psychology data).
My data frame has 1300 rows and 92000 columns after using the `extract_features()` method from the rolled data frame. Is that too much? Do you have any idea what might cause this issue?

Thanks!

**Comment by nils-braun** [comment]
Hi @mendel5! 
I think that (b) might be the actual cause, but you can do maybe some simple tests to see if you pipeline is actually working:
Before feature selection, add the target as another feature. The target should definitely be relevant for predicting the target, so it should survive any feature selection. If that does not work, you can go ahead and try to debug your pipeline. Maybe there is some indexing error? 
You can also try the other way round and use a target, which is very easy to predict and see if more features survive.

> Is that too much?

No, I highly doubt that. At this stage the data size has no impact. 

> My guess was that maybe the select_features() method doesn't recognize the values as binary values. 

A binary value for us is any column which only has two possible values, so that should actually work.

Maybe you can check with [this](https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_selection.html#tsfresh.feature_selection.relevance.calculate_relevance_table) method if your calculated p-values look reasonable?

**Comment by mendel5** [comment]
Thank you for your detailed answer!

>  You can also try the other way round and use a target, which is very easy to predict and see if more features survive.

As far as I know that's not possible with my data set because I don't know if my target is predictable at all.
The task I am trying to accomplish is an assessment of a specific data set of whether it qualifies as a predictor of a binary target variable. Right now it seems that the data cannot be used for prediction. My difficulty lies in engineering the data set in such a way that maybe I still succeed in predicting the target variable.

> Maybe you can check with this method if your calculated p-values look reasonable?
> calculate_relevance_table()

I tried using the `calculate_relevance_table()` function with multiple `fdr_level`s and set `show_warnings=True`. Here is my code:

```
p_table = calculate_relevance_table(X,
                                    y,
                                    n_jobs=7,
                                    ml_task='classification',
                                    fdr_level=0.01,
                                    show_warnings=True)

.../lib/python3.8/site-packages/tsfresh/feature_selection/relevance.py:210: RuntimeWarning:
No feature was found relevant for classification for fdr level = 0.01
(which corresponds to the maximal percentage of irrelevant features,
consider using an higher fdr level or add other features.
```

```
p_table = calculate_relevance_table(X,
                                    y,
                                    n_jobs=7,
                                    ml_task='classification',
                                    fdr_level=0.50,
                                    show_warnings=True)

.../lib/python3.8/site-packages/tsfresh/feature_selection/relevance.py:210: RuntimeWarning:
No feature was found relevant for classification for fdr level = 0.5
(which corresponds to the maximal percentage of irrelevant features,
consider using an higher fdr level or add other features.
```

```
p_table = calculate_relevance_table(X,
                                    y,
                                    n_jobs=7,
                                    ml_task='classification',
                                    fdr_level=0.95,
                                    show_warnings=True)

.../lib/python3.8/site-packages/tsfresh/feature_selection/relevance.py:210: RuntimeWarning:
No feature was found relevant for classification for fdr level = 0.95
(which corresponds to the maximal percentage of irrelevant features,
consider using an higher fdr level or add other features.
```

In all of the three outputs there are a lot of warnings like this one:
```
.../lib/python3.8/site-packages/tsfresh/feature_selection/significance_tests.py:249: RuntimeWarning:
A binary feature should have only values 1 and 0 (incl. True and False).
Instead found {0.0, 0.047619047619047616} in feature ''MY_FEATURE_sem__ratio_beyond_r_sigma__r_3''.
  warnings.warn("A binary feature should have only "
```


> Before feature selection, add the target as another feature. The target should definitely be relevant for predicting the target, so it should survive any feature selection.

I will do that in the next step.

**Comment by mendel5** [comment]
### Add target variable to features

I added the target as another feature. I removed the `fdr_level` parameter in the function so it was set at its default value with `fdr_level=0.05`.

```
p_table = calculate_relevance_table(X,
                                    y,
                                    n_jobs=7,
                                    ml_task='classification',
                                    show_warnings=True)
```

Code for table output:
```
p_table.head(5)
```

| feature                                                             | type    | p_value   | relevant |
|---------------------------------------------------------------------|---------|-----------|----------|
| TARGET_VARIABLE                                              | binary  | 0.000000  | True     |
| SOME_FEATURE_01__fft_coefficient__attr_"abs"__coeff_3  | real    | 0.000037  | False    |
| SOME_FEATURE_02__fft_coefficient__attr_"real"__coeff_9          | real    | 0.000092  | False    |
| SOME_FEATURE_03__fft_coefficient__attr_"abs"__coeff_3  | real    | 0.000107  | False    |
| SOME_FEATURE_04__variance                              | real    | 0.000108  | False    |

To me it seems like the data set is not a good predictor of the target variable. Or what do you think, @nils-braun ?

**Comment by nils-braun** [comment]
Yes, indeed - that seems to be the case... I do not see any "technical" reason why it is not working. 
Unfortunately, there is not much that I can help you with from now on. 

What you might want to keep in mind, is that `tsfresh` can only ever do a statistical test. That means if you are training a ML method afterwards it might be able to extract meaningful information also from features, which `tsfresh` has classified as not significant. 

If there is more that I can help from the library-side, please feel free to re-open the issue.

**Comment by mendel5** [comment]
> Yes, indeed - that seems to be the case... I do not see any "technical" reason why it is not working.

Thanks for you feedback. I tried multiple things to get my model to work but my target values just seem to be non-predictable.
