### ISSUE TITLE
Feature request: analysis of frequency spectrum

### ISSUE THREAD

**Issue by jontis** [blue-yonder/tsfresh#816]
Hi, 
I'm looking to use frequency spectra as features for machine learning tasks.
I'm very interested in using automated feature extraction for this.
I think TSFRESH is the best candidate I've found, and the frequency spectra I have are quite similar to time series.
Also, TSFRESH already contain some functionality to process FFT and it's a natural extension to time series.

Could you be interested to in extending the functions to process frequency spectra?
I'll upload some small examples.

**Comment by jontis** [comment]
frequency,channel_0,channel_1,channel_2,channel_3
0.0015876893014167073,0.9628995697638191,0.9082852072712135,0.9280095694189681,0.9096159002987848
0.033341475329750854,0.9813142324593477,0.9726140972145105,0.9650211239365142,0.9745299432650425
0.065095261358085,0.9993689421015522,0.9292947742637866,1.0097214528814615,1.0256669126379436
0.09684904738641914,0.9946244018034116,0.9808207240327839,0.9728384240587673,0.9990389760634567
0.1286028334147533,0.9920414565040165,1.0009822118040692,1.0036820711415735,1.0047869560712983
0.16035661944308743,0.9887557146860807,1.0235484802967227,0.9340550997068071,0.9956665999131082
0.19211040547142158,0.9815311528330746,0.980629166463147,0.9146965876621099,0.9358551362610283
0.22386419149975573,0.9796683217181144,0.8774530231349644,0.989575790360206,0.9697290807960623
0.2556179775280899,0.9785954554971976,1.0042933044359195,1.0921832106684584,0.9908787738371814

**Comment by nils-braun** [comment]
Hi @jontis!

tsfresh technically does not care if the time series is on real time values or on anything else - as long as you give it anything that is a list of numbers. So you might already be able to start with tsfresh as it is (some of the feature calculators might not have the original meaning anymore, but might still be relevant features). 

Which functionality would you still like to see in tsfresh to help you with your frequency spectras? Is there any additional feature calculator that comes to your mind?

**Comment by jontis** [comment]
That's interesting. Thank you so much for that suggestions. Um, my physics and wave theory is a bit rusty. Is there a significant difference between loading a time series and extracting fourier coefficients, to loading the FFT first?
Could TSFRESH be fed the FFT as well as a time series? Figuring they are semi interchangeable?

**Comment by nils-braun** [comment]
Sorry, maybe I was not clear:
If you feed tsfresh an FFT, it will *treat* it as a time series. This means it will calculate its features without "knowing" that it is not in the time dimension, but in the frequency domain.
For example, the "mean" feature will then not be the mean of the time series but the mean of the FFT, the number of peaks will be the number of frequency peaks etc. If you only care about extracting useful features for ML, this might be all you need. If you try to understand what is going on by looking at the feature values, this might make things a bit more complicated.

If you give tsfresh both an FFT and a time series, it will treat them separately and extract features on both. That might give you additional interesting features for your ML method - but it will not figure out that they are interchangeable.
