### ISSUE TITLE
When can I use feature selection for multiclass?

### ISSUE THREAD

**Issue by Bennett-Yang** [blue-yonder/tsfresh#821]
Hi. I am new to tsfresh and appreciate the amazing package. I followed the docs and tried to use feature selection for my multiclass classification problem. However, I found out that the support for multiclass has not been released yet. Is there any way I can use it?

**Comment by nils-braun** [comment]
Glad you like it!
You are totally correct - I missed creating a new release for quite some time. 
Let me schedule a new release to end of this week. After that (and if all CI pipelines have suceeded) you should be able to pip-install the newest version.

If you want to use it already know, you can always install tsfresh [from source](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/).

**Comment by Bennett-Yang** [comment]
Thank you!
