### ISSUE TITLE
What is the naming rule of the column name of the returned dataframe of extract_ features ()?

### ISSUE THREAD

**Issue by G1401010** [blue-yonder/tsfresh#823]
I want to know the naming rule of the column name of the returned dataframe of extract_ features () , for example, what does 7_ fft_ coefficient_ attr_ "abs"_ coeff_47  stand for?

I use extract_ features () to extract the features of CHB-MIT EEG signal, and tens of thousands of features are obtained. I use xgboost to analyze the importance of these features, and find that the above feature is the most important, but I don't know what this feature is.

**Comment by G1401010** [comment]
![download](https://user-images.githubusercontent.com/79445478/110199351-fbd07600-7e92-11eb-881a-383ab026a0a2.png)

**Comment by nils-braun** [comment]
Hi @G1401010 
We have documentation on this available here: https://tsfresh.readthedocs.io/en/latest/text/feature_calculation.html

**Comment by G1401010** [comment]
Thank you!

**Comment by G1401010** [comment]
Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "blue-yonder/tsfresh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月6日(星期六) 下午5:29
收件人:&nbsp;"blue-yonder/tsfresh"<tsfresh@noreply.github.com&gt;;
抄送:&nbsp;"小兔子"<1159927587@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [blue-yonder/tsfresh] What is the naming rule of the column name of the returned dataframe of extract_ features ()? (#823)





 
Hi @G1401010
 We have documentation on this available here: https://tsfresh.readthedocs.io/en/latest/text/feature_calculation.html
