### ISSUE TITLE
What is the difference between time series data and streaming data? Thanks♪(･ω･)ﾉ

### ISSUE THREAD

**Issue by lupupu** [blue-yonder/tsfresh#829]
I see the [doc](https://tsfresh.readthedocs.io/en/latest/text/introduction.html#what-not-to-do-with-tsfresh) refer to "streaming data".
```
Currently, tsfresh is not suitable
for usage with streaming data
to train models on the features (we do not want to reinvent the wheel, check out the python package scikit-learn for example)
```

**Comment by nils-braun** [comment]
Streaming data comes in events. This means you never have the full data available, but all you ever have is the current event. Additionally, streaming data is only useful if processed directly - and not after some data is collected. Think of alert data. 

The way tsfresh is built, we process the data in batches. We require to have the full data available and classification only makes sense if you have access to multiple time series. This is he use case for tsfresh.

**Comment by lupupu** [comment]
> Streaming data comes in events. This means you never have the full data available, but all you ever have is the current event. Additionally, streaming data is only useful if processed directly - and not after some data is collected. Think of alert data.
> 
> The way tsfresh is built, we process the data in batches. We require to have the full data available and classification only makes sense if you have access to multiple time series. This is he use case for tsfresh.

offline → time series data
online → streaming data
？

**Comment by nils-braun** [comment]
Yes, at least this is how tsfresh defines it (not sure if this is the "general definition").
By the way, if you think this should be clearer in the documentation, would you like to do a PR? I would be very happy!

**Comment by lupupu** [comment]
> Yes, at least this is how tsfresh defines it (not sure if this is the "general definition").
> By the way, if you think this should be clearer in the documentation, would you like to do a PR? I would be very happy!

I will try to do a PR, even though my network is in poor condition.
