### ISSUE TITLE
extract_features gives error: TypeError: unsupported operand type(s) for /: 'str' and 'int'

### ISSUE THREAD

**Issue by simpsus** [blue-yonder/tsfresh#830]
OS: Win10, python 3.7.10, packaged by conda-forge
tsfresh.__version__ '0.18.0'
data: One ticker downloaded from yahoo finance with package yfinance, see attached issue.zip
[issue.zip](https://github.com/blue-yonder/tsfresh/files/6212126/issue.zip)

code producing the error
`ef = extract_features(df, column_id='price')`

Thank you very much. Any help appreciated

stacktrace

`Feature Extraction:   0%|                                                                       | 0/29 [00:07<?, ?it/s]
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\basti\Anaconda3\envs\signals\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\basti\Anaconda3\envs\signals\lib\site-packages\tsfresh\utilities\distribution.py", line 43, in _function_with_partly_reduce
    results = list(itertools.chain.from_iterable(results))
  File "C:\Users\basti\Anaconda3\envs\signals\lib\site-packages\tsfresh\utilities\distribution.py", line 42, in <genexpr>
    results = (map_function(chunk, **kwargs) for chunk in chunk_list)
  File "C:\Users\basti\Anaconda3\envs\signals\lib\site-packages\tsfresh\feature_extraction\extraction.py", line 337, in _do_extraction_on_chunk
    return list(_f())
  File "C:\Users\basti\Anaconda3\envs\signals\lib\site-packages\tsfresh\feature_extraction\extraction.py", line 323, in _f
    result = [("", func(x))]
  File "C:\Users\basti\Anaconda3\envs\signals\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py", line 231, in variance_larger_than_standard_deviation
    y = np.var(x)
  File "<__array_function__ internals>", line 6, in var
  File "C:\Users\basti\Anaconda3\envs\signals\lib\site-packages\numpy\core\fromnumeric.py", line 3703, in var
    **kwargs)
  File "C:\Users\basti\Anaconda3\envs\signals\lib\site-packages\numpy\core\_methods.py", line 222, in _var
    subok=False)
TypeError: unsupported operand type(s) for /: 'str' and 'int'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-7-fda67ee3748c> in <module>
----> 1 ef = extract_features(df, column_id='price')

~\Anaconda3\envs\signals\lib\site-packages\tsfresh\feature_extraction\extraction.py in extract_features(timeseries_container, default_fc_parameters, kind_to_fc_parameters, column_id, column_sort, column_kind, column_value, chunksize, n_jobs, show_warnings, disable_progressbar, impute_function, profile, profiling_filename, profiling_sorting, distributor, pivot)
    160                                 kind_to_fc_parameters=kind_to_fc_parameters,
    161                                 distributor=distributor,
--> 162                                 pivot=pivot)
    163 
    164         # Impute the result if requested

~\Anaconda3\envs\signals\lib\site-packages\tsfresh\feature_extraction\extraction.py in _do_extraction(df, column_id, column_value, column_kind, column_sort, default_fc_parameters, kind_to_fc_parameters, n_jobs, chunk_size, disable_progressbar, show_warnings, distributor, pivot)
    255     result = distributor.map_reduce(_do_extraction_on_chunk, data=data,
    256                                     chunk_size=chunk_size,
--> 257                                     function_kwargs=kwargs)
    258 
    259     if not pivot:

~\Anaconda3\envs\signals\lib\site-packages\tsfresh\utilities\distribution.py in map_reduce(self, map_function, data, function_kwargs, chunk_size, data_length)
    211             result = self.distribute(_function_with_partly_reduce, chunk_generator, map_kwargs),
    212 
--> 213         result = list(itertools.chain.from_iterable(result))
    214 
    215         self.close()

~\Anaconda3\envs\signals\lib\site-packages\tqdm\std.py in __iter__(self)
   1176 
   1177         try:
-> 1178             for obj in iterable:
   1179                 yield obj
   1180                 # Update and possibly print the progressbar.

~\Anaconda3\envs\signals\lib\multiprocessing\pool.py in next(self, timeout)
    746         if success:
    747             return value
--> 748         raise value
    749 
    750     __next__ = next                    # XXX

~\Anaconda3\envs\signals\lib\multiprocessing\pool.py in worker()
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

~\Anaconda3\envs\signals\lib\site-packages\tsfresh\utilities\distribution.py in _function_with_partly_reduce()
     41     kwargs = kwargs or {}
     42     results = (map_function(chunk, **kwargs) for chunk in chunk_list)
---> 43     results = list(itertools.chain.from_iterable(results))
     44     return results
     45 

~\Anaconda3\envs\signals\lib\site-packages\tsfresh\utilities\distribution.py in <genexpr>()
     40     """
     41     kwargs = kwargs or {}
---> 42     results = (map_function(chunk, **kwargs) for chunk in chunk_list)
     43     results = list(itertools.chain.from_iterable(results))
     44     return results

~\Anaconda3\envs\signals\lib\site-packages\tsfresh\feature_extraction\extraction.py in _do_extraction_on_chunk()
    335             warnings.simplefilter("default")
    336 
--> 337         return list(_f())

~\Anaconda3\envs\signals\lib\site-packages\tsfresh\feature_extraction\extraction.py in _f()
    321                               parameter_list)
    322                 else:
--> 323                     result = [("", func(x))]
    324 
    325             for key, item in result:

~\Anaconda3\envs\signals\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py in variance_larger_than_standard_deviation()
    229     :return type: bool
    230     """
--> 231     y = np.var(x)
    232     return y > np.sqrt(y)
    233 

<__array_function__ internals> in var()

~\Anaconda3\envs\signals\lib\site-packages\numpy\core\fromnumeric.py in var()
   3701 
   3702     return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
-> 3703                          **kwargs)
   3704 
   3705 

~\Anaconda3\envs\signals\lib\site-packages\numpy\core\_methods.py in _var()
    220     if isinstance(arrmean, mu.ndarray):
    221         arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
--> 222                                  subok=False)
    223     else:
    224         arrmean = arrmean.dtype.type(arrmean / rcount)

TypeError: unsupported operand type(s) for /: 'str' and 'int'`

**Comment by MaxBenChrist** [comment]
because you use the price as an id it tells me that you did not read the documentation nor understand the input parameters, please have a look at https://tsfresh.readthedocs.io/en/latest/text/data_formats.html

**Comment by simpsus** [comment]
Thank you for replying to me question.
