### ISSUE TITLE
[DOCS] Missing description in docs section list_of_features

### ISSUE THREAD

**Issue by OliEfr** [blue-yonder/tsfresh#832]
https://tsfresh.readthedocs.io/en/latest/text/list_of_features.html

In the following lines the full description of the features is missing:

`c3(x, lag) | This function calculates the value of`

`mean_abs_change(x) | Returns the mean over the absolute differences between subsequent time series values which is`

`mean_change(x) | Returns the mean over the differences between subsequent time series values which is`

`time_reversal_asymmetry_statistic(x, lag) | This function calculates the value of`

`agg_autocorrelation(x, param) | Calculates the value of an aggregation function  (e.g.`

**Comment by MaxBenChrist** [comment]
I think the problem is that toctree parses only the first line of each docstring. We need to adapt the docstring of each feature calculator function to contain a short description in the first line of the docstring (which sounds like a good idea anyway)

**Comment by OliEfr** [comment]
Unfortunately, I dont think I will be able to fix this anytime soon.

**Comment by MaxBenChrist** [comment]
opened a pr
