### ISSUE TITLE
Using feature extraction function with Dataframe.rolling.apply

### ISSUE THREAD

**Issue by xiaoxiaoyaozi** [blue-yonder/tsfresh#835]
Suppose I have a dataframe `df[['close']]` which contain one stock price. I want to calculate some feature of rolling data, for example `tsfresh.feature_extraction.feature_calculators.agg_autocorrelation` and `rolling window = 10`. Here is my code:
```
param = [{'f_agg': 'mean', 'maxlag': 3}]
df['NewFeature] = df['close'].rolling(10).apply(tsfresh.feature_extraction.feature_calculators.agg_autocorrelation, args=(param))
```
But it get error:`TypeError: string indices must be integers`. So can the `feature extraction function` in conjunction with `Dataframe.rolling.apply`?

**Comment by nils-braun** [comment]
The feature extractors of tsfresh (like the agg_autocorrelation) are not to be used standalone, but are typically used from tsfresh's extract_features function.
In principle, you can probably also make it work with `Dataframe.rolling.apply`, but please note that tsfresh comes with its own rolling mechanism (https://tsfresh.readthedocs.io/en/latest/text/forecasting.html), which will definitely work (as it is tested).

Feel free to reopen the issue if you have any more questions.
