### ISSUE TITLE
Add testing for install_requirements.sh

### ISSUE THREAD

**Issue by OliEfr** [blue-yonder/tsfresh#836]
Add testing for install_requirements.sh

I think the easiest test for this script would be to just call it in our build pipeline (a.k.a in our .github workflows) :-)
I do not think that it would make sense to write a unittest for the content of this file (IMHO).

_Originally posted by @nils-braun in https://github.com/blue-yonder/tsfresh/pull/833#discussion_r605213244_

**Comment by OliEfr** [comment]
you can assign me

**Comment by nils-braun** [comment]
Fixes, as there is no installation script anymore :)
