### ISSUE TITLE
binary classification with time series component

### ISSUE THREAD

**Issue by jboverio** [blue-yonder/tsfresh#838]
Oh no, you encountered a problem while using *tsfesh*.

We, the maintainers, are happy to help you. When opening an issue, please provide the following information to us:

1. Your operating system
2. The version of *tsfresh* that you are using
3. The data on which the problem occurred (please do not upload 1000s of time series but try to boil the problem down to a small group or even a singular one)
4. A minimal code snippet which reproduces the problem/bug
5. Any reported errors or traceback

For questions, you can also use our [gitter chatroom](https://gitter.im/tsfresh/)

**Comment by nils-braun** [comment]
Hi @jboverio 
Your issue report only contains the questions, but not the answers. I can unfortunately not help you without information :-)

**Comment by jboverio** [comment]
Hi ! I am getting a graph like this:

![image](https://user-images.githubusercontent.com/15717698/115161199-a3d08600-a072-11eb-8fa4-7256a5004ced.png)

It is a binary classification (X axis makes no sense and I see only y_test , no blue colors). What's wrong?

**Comment by nils-braun** [comment]
Hi @jboverio
I do not see any tsfresh code involved in your shown screenshot, but I can try to help you anyways:
Better than checking the plot, it might be easier to show the data itself.
Maybe the blue dots are just overlayed by the orange ones?

**Comment by nils-braun** [comment]
@jboverio  - I am closing this issue as I did not get any response from your side and I currently do not see how it is related to tsfresh. I am happy to help if you have any further questions. Please re-open the issue in this case or just ping me.
Thanks!
