### ISSUE TITLE
Confusion about extract_relevant_features

### ISSUE THREAD

**Issue by t2396156** [blue-yonder/tsfresh#84]
I have two time serises with different length and value, and they belong to two different labels, and i transform them into pandas.Dateframe like this
![image](https://cloud.githubusercontent.com/assets/12410347/20738055/7ee813fa-b6eb-11e6-9cab-d2fc3bbb3872.png)
when i use the method extract_relevant_features, and it return an empty list like this
![image](https://cloud.githubusercontent.com/assets/12410347/20738075/9e940204-b6eb-11e6-963c-f9fe26fdd5b4.png)
i dont understand the result, does it mean the two serise have no relevant features?

and here i post my code, pitch（picth2）is a list like 
![image](https://cloud.githubusercontent.com/assets/12410347/20738083/bb69704e-b6eb-11e6-8128-0a38cb031b9b.png)

my code：
y = [0, 1]
y = np.array(y)
pitch = pitch_analyse.pitch_profile("new001.wav")
pitch2 = pitch_analyse.pitch_profile(r"D:\emotion_new\angry\angry_1_009.wav")
time1 = range(len(pitch))
time2 = range(len(pitch2))
time1.extend(time2)
id_dic = [0]*len(pitch)+[1]*len(pitch2)
pitch.extend(pitch2)
series = {'id': id_dic, 'time': time1,'value': pitch}
series = pd.DataFrame(series)
features_filtered_direct = extract_relevant_features(series, y, column_id='id', column_sort='time')
print features_filtered_direct

**Comment by MaxBenChrist** [comment]
can you provide a notebook? with the data? so we can debug it.

from a first glimpse:

- y does not have an index
- you only have two samples, so your dataset contains not enough statistic. the filtering mechanism will reject all features. make sure you have at least 30+ samples

**Comment by MaxBenChrist** [comment]
You can just extract all features with `extract_relevant_features(series, column_id='id', column_sort='time')` and then use another filtering mechanism from sklearn (lasso, boruta etc)

**Comment by t2396156** [comment]
I'v tried your comment, this time i use 100 samples and turn y into pd.Series. But tsfresh raises a error
![image](https://cloud.githubusercontent.com/assets/12410347/20779222/fe466be8-b7ad-11e6-82ea-06aaf81b376b.png)
For your convenience, i post my code and data:
I used angry1 and fear1 in my last try
[fear1.txt](https://github.com/blue-yonder/tsfresh/files/623547/fear1.txt)
[angry1.txt](https://github.com/blue-yonder/tsfresh/files/623548/angry1.txt)

and i post all my data, i have six different categories data, my ultimate purpose is to extract effective feature so i can accomplish my classification task.
[angry.txt](https://github.com/blue-yonder/tsfresh/files/623558/angry.txt)
[fear.txt](https://github.com/blue-yonder/tsfresh/files/623559/fear.txt)
[happy.txt](https://github.com/blue-yonder/tsfresh/files/623562/happy.txt)
[normal.txt](https://github.com/blue-yonder/tsfresh/files/623564/normal.txt)
[surprise.txt](https://github.com/blue-yonder/tsfresh/files/623566/surprise.txt)


my code:


import numpy as np
import pandas as pd
from tsfresh import extract_features
from tsfresh import extract_relevant_features

def creat_series(pitchs, label):
    pitch_list = []
    time_list = []
    id_list = []
    for pitch in pitchs:
        pitch_list.extend(pitch)
        time_list.extend(range(len(pitch)))
        id_list.extend([label]*len(pitch))
        label += 1
    return (pitch_list, time_list, id_list, label)


if __name__ == "__main__":
    pitch_list = []
    time_list = []
    id_list = []
    y = []

    angry_pitch = []
    label = 0
    id_l = 0
    for line in open("pitch_data/angry1.em"):
        line = line.strip()
        if not line:
            continue
        line = np.array(line.split(), dtype=np.float32)
        angry_pitch.append(line)
        y.append(id_l)
    ll = creat_series(angry_pitch, label)
    pitch_list.extend(ll[0])
    time_list.extend(ll[1])
    id_list.extend(ll[2])

    fear_pitch = []
    label = ll[3]+1
    id_l = 1
    for line in open("pitch_data/fear1.em"):
        line = line.strip()
        if not line:
            continue
        line = np.array(line.split(), dtype=np.float32)
        fear_pitch.append(line)
        y.append(id_l)
    ll = creat_series(fear_pitch, label)
    pitch_list.extend(ll[0])
    time_list.extend(ll[1])
    id_list.extend(ll[2])

    series = {'id': id_list, 'time': time_list,'value': pitch_list}
    series = pd.DataFrame(series)
    print series
    y = pd.Series(y)
    print y
    features_filtered_direct = extract_relevant_features(series, y, column_id='id', column_sort='time')

**Comment by t2396156** [comment]
i'm sorry ,there is a bug in my code post before.
i will reply later after i try tsfresh im my whole data.

**Comment by MaxBenChrist** [comment]
so you fixed everything? If yes, close this issue please

**Comment by wintermayr** [comment]
Can you tell me your solution to this? I encounter the same problem as the return is empty list.

**Comment by MaxBenChrist** [comment]
@wintermayr 

did you try just to extract features? without the selection/filtering
