### ISSUE TITLE
Feature combinations for different time series combination

### ISSUE THREAD

**Issue by MaxBenChrist** [blue-yonder/tsfresh#85]
At the moment the calculated features are always based on one type of time series.

It would be nice to have features that are based on multiple time series.

We could use something in the line of http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html to get feature combinatins.

**Comment by MaxBenChrist** [comment]
I do not see how this is related to speed milestone

**Comment by nils-braun** [comment]
Very very long time ago we decided that this is not a feature we will support soon, as it needs some rather large refactoring.
So I think we can abandon it here.

**Comment by EyescannerJE** [comment]
> Very very long time ago we decided that this is not a feature we will support soon, as it needs some rather large refactoring. So I think we can abandon it here.

Hi, is this still the case? I don't think my features make much sense in isolation since timings and delays between signals are important. How can i capture that?
