### ISSUE TITLE
Extracting Relevant Features

### ISSUE THREAD

**Issue by leonanto** [blue-yonder/tsfresh#862]
**The problem**:

Trying to do some feature extraction on dataset and select the relevant features based on my label dataset, when I tried using the extract_relevant_features function I got 'Target contains NaN values'.  So I attempted to get rid of the NaNs then select the relevant features but whenever I run this (or just the default impute function): 

X = impute_dataframe_zero(features)
filtered_features = select_features(X, y)

I still get Target contains NaN values  

**Anything else we need to know?**:

**Environment**:

- Python version: 3.8
- Operating System: Windows 10
- tsfresh version: 0.18
- Install method (conda, pip, source): conda

**Comment by nils-braun** [comment]
Hi!
As the error message says, your target (the `y` in your example) contains NaNs. Inputing the feature vector/matrix does not help here :-) 
On most use cases, inputing the target vector does not make any sense, so I would remove any NaN rows (make sure to also remove them in the feature matrix or only pass in the data without a NaN target in the feature extraction).

**Comment by leonanto** [comment]
Thanks. It just dawned on me, the panda series I'm using is where the issues is. The predictions keep getting transformed to NaNs though the index is fine.
