### ISSUE TITLE
Error: ufunc 'isnan' not supported for the input types

### ISSUE THREAD

**Issue by hdk0102** [blue-yonder/tsfresh#869]
Hello everyone,

Like below, my time series data has 3 ids, and each id has 2048 time observations. Hence, shape is (3*2048 = 6144, 7).

![image](https://user-images.githubusercontent.com/61997423/123964169-23bd8980-d9ee-11eb-83a7-bedad44c2b8e.png)

But when I do extract_features(timeseries, column_id="id", column_sort="time"), I am keep encountering this particular error:

_ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''_

Does anyone know why? I don't see how my data is different from the [toy](https://tsfresh.readthedocs.io/en/latest/text/quick_start.html) example given in the tsfresh website. My data doesn't have any np.nans. Can someone please help..?? 

Thank you for the great tool though! Very much looking forward to using it in my working paper.

**Comment by nils-braun** [comment]
Hi @hdk0102 ! Thanks for your question.
This particular error ja typically a sign that you have non-numeric coon types. From the screenshot you share it does but look like it, but some of the columns might be actually strings. Can you do a `df.dtypes` to check? 
If they are strings, you need to convert them to integer/floats before using the data in tsfresh.

**Comment by hdk0102** [comment]
Dear @nils-braun , Following your advice I could solve the problem! Thank you. I could never imagine the numbers I see on screen is 'strings'...! Really appreciate your input :) I hope my work can meet its fruitful end! Will cite tsfresh if it does. 

Btw, it extracts a lot of features from my time series. Do you have a recommendation of where I might better understand what each feature is about? It would be interesting to know a bit more what those features actually mean :)

Thanks Nils!

**Comment by nils-braun** [comment]
Hi @hdk0102!
Glad it helped. 

Of you want to learn about the features, I would start with our documentation (there is a lost with a short description). If you want to learn even more, have a look into the code documentation, where we typically cite papers or more references. 
Feel free to get back to me if you can not find it.
