### ISSUE TITLE
scipy error

### ISSUE THREAD

**Issue by vladimircape** [blue-yonder/tsfresh#880]
`from tsfresh import extract_features, extract_relevant_features, select_features`

cannot import name 'float_factorial' from 'scipy._lib._util'

**Comment by nils-braun** [comment]
Hi @vladimircape!
Which version of tsfresh and related packages (in this case especially `scipy`) are you using? Did you install it via conda or pip? Which OS are you using? 
We normally provide a template for bug reports where we ask all those questions. Without these answers, its very hard to guess what is happening and to reproduce.

**Comment by vladimircape** [comment]
1)install via pip install tsfresh
2)Ubuntu
3)scipy 1.7.1 only downgrade to 1.2.* helps

**Comment by nils-braun** [comment]
I have just tried to reproduce on my Ubuntu machine with python 3.9.6 and did not see the same issue.
Can you do a "normal" import scipy without tsfresh?

**Comment by kempa-liehr** [comment]
I'm closing this issue for now. Please feel free to reopen, if this is still relevant.
