### ISSUE TITLE
'Index' object has no attribute 'contains'

### ISSUE THREAD

**Issue by jonimatix** [blue-yonder/tsfresh#886]
Hi,

Trying to run a very simple command, but at the end of the execution I get:

'Index' object has no attribute 'contains'

Any help?

Running on version: '0.11.2'

Code

```
X = extract_features(s,
                     column_id="row", column_sort="interval"
                     )
```

```
Traceback (most recent call last):

  File "<ipython-input-22-20569e0fbcd2>", line 3, in <module>
    column_id="row", column_sort="interval"

  File "C:\Users\xx\Anaconda3\lib\site-packages\tsfresh\feature_extraction\extraction.py", line 159, in extract_features
    distributor=distributor)

  File "C:\Users\xx\Anaconda3\lib\site-packages\tsfresh\feature_extraction\extraction.py", line 301, in _do_extraction
    if result.columns.contains("value"):
```

s is a dataframe with numeric data type fields.

Regards.

**Comment by nils-braun** [comment]
Hi @jonimatix!
Version 0.11.2 is actually quite old :-) (more than 2 years). I would assume it is just not compatible with the newest pandas version.
Is there a particular reason you are using such an old version of tsfresh or can you try to update?

**Comment by jonimatix** [comment]
Thanks @nils-braun !

Yes totally that was in fact the issue... I just updated tsfresh and now all good.

Cheers
