### ISSUE TITLE
Provide example for a workflow in case of a multiclass target

### ISSUE THREAD

**Issue by jneuff** [blue-yonder/tsfresh#9]
When selecting features we assume the classification case only when the target is binary:

``` python
target_is_binary = len(set(y)) == 2
```

Otherwise we assume the regression case.

So for a multiclass target the user has to perform a binary one versus rest classification. We should provide an example how to efficiently do that using tsfresh, i.e.:
1. Calculate all features once
2. Select the features separately for each one versus rest case

**Comment by MaxBenChrist** [comment]
We have an example now

**Comment by MaxBenChrist** [comment]
contained in 

https://github.com/blue-yonder/tsfresh/blob/master/notebooks/human_activity_recognition_multi_class_example.ipynb
