### ISSUE TITLE
complexity-invariant distance (CID) calculation is wrong

### ISSUE THREAD

**Issue by ghayth82** [blue-yonder/tsfresh#909]
**The problem**:
According to your documentation, you are calculating the CID, but the code and the equation you are using it calculate the Euclidean distance. See the paper and you will find that you are missing the correction factor which is the idea of CID

I was not able to write equations here, but see https://link.springer.com/article/10.1007/s10618-013-0312-3#Sec10 for more details

**Anything else we need to know?**:

**Environment**:

- Python version:
- Operating System:
- tsfresh version:
- Install method (conda, pip, source):

**Comment by kempa-liehr** [comment]
@ghayth82, thanks for reporting this issue. I will have a look into the paper and the implementation.

**Comment by kempa-liehr** [comment]
Related to #742

**Comment by kempa-liehr** [comment]
The correction factor [(Batista et al. (2014), p.642)](https://doi.doi.org/10.1007/s10618-013-0312-3), which you are referring to , is calculated for the CID of two different sequences.

However, the `cid_ce` feature computes only the complexity estimate (CE) of the input sequence as documented in Eq. (1) of  [Batista et al. (2014)](https://doi.doi.org/10.1007/s10618-013-0312-3).
