### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by ClimbsRocks** [blue-yonder/tsfresh#91]
I noticed quite a few divide by zero warnings, like below:
`/home/preston/.local/lib/python2.7/site-packages/scipy/signal/_peak_finding.py:412: RuntimeWarning: divide by zero encountered in double_scalars`

But then, at one point after running for a while, the entire `extract_features()` process errored out. 

```
Traceback (most recent call last):
  File "df_dev_script.py", line 590, in <module>
    features = extract_features(combined_df, column_id='store_id', column_sort='created_at_in_local_time')
  File "/home/preston/.local/lib/python2.7/site-packages/tsfresh/feature_extraction/extraction.py", line 93, in extract_features
    extracted_features = pool.map(partial_extract_features_for_one_time_series, kind_to_df_map.items())
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ZeroDivisionError: float division by zero
```
Should be pretty easy to do safe division that doesn't error.

**Comment by nils-braun** [comment]
Thanks for reporting this. The warning is now gone (thanks for your other issue), but the exception is still there. The code is in the scipy package, so we can probably not change the division there.

Can you maybe send a notebook with the data, so I can play around a bit?

**Comment by ClimbsRocks** [comment]
Thanks for your quick action on all this! I was trying this out on our production data, so unfortunately I can't share that publicly. 

Do you have any recommended workarounds? Is there somewhere in the codebase I can wrap a line in a try/except block, and have it return 0 if it catches this exception? Or should I just add a constant 0.5 to everything so we don't have any 0 values?

**Comment by MaxBenChrist** [comment]
@ClimbsRocks do you know which feature calculator caused this error? 

We have similar problems when fitting the ARIMA models where we catch LinAlg Errors.

**Comment by ClimbsRocks** [comment]
I don't know off-hand. I'll update the module and try re-running again. Other than just copying the whole terminal output here, is there anything in particular I should be looking for, or any settings I can set that'll provide more detailed/useful debugging info?

**Comment by MaxBenChrist** [comment]
@nils-braun you got an idea what caused this? 

@ClimbsRocks maybe you have a full stack trace? 

If we know which feature calculator caused this, we can catch it like in the `augmented_dickey_fuller` calculator.

**Comment by MaxBenChrist** [comment]
@ClimbsRocks you could just calculate feature individually to see which one caused it.

**Comment by nils-braun** [comment]
Well, you can use a debugger (e.g. pdb), but this is probably quite some amount of work....
Or you can hope that it is an apply function, so you can include a print statement in line 192 of extraction.py.

**Comment by MaxBenChrist** [comment]
@ClimbsRocks just to get a better feeling for your data:

- is it categorical = some values occur more than once?
- can the time series sample contain a lot of 0s?
- is there at least one time series sample that only contains 0s?
- is there a constant time series sample = all data points are equal

**Comment by MaxBenChrist** [comment]
I got a possible reason for this, in `mean_autocorrelation` we divide by `/sum(x)`. autsch! :/

**Comment by nils-braun** [comment]
Where do we do this? In `mean_autocorrelation` only numpy values are used, which do not have this problem.

**Comment by MaxBenChrist** [comment]
Ah, wrong copy paste, it is in `index_mass_quantile`

**Comment by nils-braun** [comment]
@ClimbsRocks if this is really the problem, can you check if #100 helps?

**Comment by MaxBenChrist** [comment]
@nils-braun have a look at my pr. we should not allow negative mass in `index_mass_quantile`

**Comment by MaxBenChrist** [comment]
I think we can close this one. @ClimbsRocks if this error still recurs with version 0.3.1 up please reopen this issue.
