### ISSUE TITLE
Reverse of the feature extraction 

### ISSUE THREAD

**Issue by Timbimjim** [blue-yonder/tsfresh#928]
Hey, is there a way to reverse a time series from already extracted features?

Let's say I have the extracted coefficients of a time series, is there a way to recover the underlying time series data. Not 100% accurate ofc.

Thx for information

**Comment by kempa-liehr** [comment]
Hi, 
actually that would be an inverse problem, and I am not aware of any black-box implementation for this type of problem. I'm sorry. 
Cheers,
Andreas
