### ISSUE TITLE
Can i extract the specific features using tsfresh？

### ISSUE THREAD

**Issue by t2396156** [blue-yonder/tsfresh#93]
I'v extracted some features through the method extract-relevant-features with my training data.
Now i have a new audio file, can i extract the same feature only with one new wav?

**Comment by MaxBenChrist** [comment]
yes, you can for example use our sklearn transformers: http://tsfresh.readthedocs.io/en/latest/text/sklearn_transformers.html

**Comment by MaxBenChrist** [comment]
you can fit that augmentor and then later apply it to your new wave to extract the same features

**Comment by trivedip** [comment]
@MaxBenChrist  Is there a way I can store the extracted features, in the given jupyter notebook, when I print X-train it only has single column!
So the question is which variable has the extracted features ? and why are we training it with just single column ?
