### ISSUE TITLE
Add test support for linux aarch64 

### ISSUE THREAD

**Issue by odidev** [blue-yonder/tsfresh#932]
Hi Team, 

I tried testing **tsfresh** package on Arm64 architectures but it is generating `24 errors with 10 passed and 11 skipped` for the **tox test command** with the below error on **GHA**: 

```
E   ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it). 

```
**GHA log at Arm64:**  https://github.com/odidev/tsfresh/runs/5511909365?check_suite_focus=true

And for x86_64 on GHA, getting` 13 failed, 302 passed, 11 skipped` with error: 

```
E TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type  

/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:1461: TypeError 

```
**GHA log at x86_64:** https://github.com/odidev/tsfresh/runs/5511909672?check_suite_focus=true

Also, checked arm64 locally and getting same result as above. 

Also found an [issue](https://github.com/blue-yonder/tsfresh/issues/565) where the author has asked for help and then himself suggested a link of [master-thesis-wheelhouse](https://github.com/3sztof/master-thesis-wheelhouse) which gives temporary support for Arm64, and closed it. 

@kempa-liehr Could you please share your feedback regarding this and suggest what can be done to test it over ARM64 server? 

Thanks in advance.

**Comment by odidev** [comment]
@kempa-liehr Could you please share your feedback regarding this?

**Comment by ilkersigirci** [comment]
I am also experiencing the same issue. I think it is a problem with dependancy package called `matrixprofile`

**Comment by kempa-liehr** [comment]
Fixed in https://github.com/blue-yonder/tsfresh/tree/v0.20.0.
Many thanks for your patience and perseverance.

Merry Christmas and a Happy New Year!
