### ISSUE TITLE
Import Error - python 3.10.0

### ISSUE THREAD

**Issue by Luke12062** [blue-yonder/tsfresh#937]
Hi, I seem to be getting an import error when trying to use tsfresh after pip installing to python 3.10.0.
I have attached a screenshot of the issue.
![image](https://user-images.githubusercontent.com/79952181/161903374-a9f157d4-09d1-44a5-b29a-58e3fb172f43.png)
tsfresh version is 0.19.0
numpy version is 1.21.5

**Comment by 0liu** [comment]
When trying to upgrade from Python 3.9 to 3.10, the following error happens:

> Looking for: ['python=3.10']
> 
> conda-forge/linux-64                                        Using cache
> conda-forge/noarch                                          Using cache
> Encountered problems while solving:
>   - package matrixprofile-1.1.10-py39hce1f21e_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed

`tsfresh` depends on [`matrixprofile`](https://github.com/matrix-profile-foundation/matrixprofile), which is developed by academic researchers. It's not been updated for 10 months. It would be better for `tsfresh` to decouple with this project, or somebody has to contribute to it.

**Comment by vanbenschoten** [comment]
Co-author of matrixprofile here.

Unfortunately @OliEfr is correct - we haven't been able to update matrixprofile for quite some time. Though we hope to do so in the next 1-2 months, there's no guarantee we'll be able to get to it. So, @nils-braun if this dependency is causing tsfresh to run into substantial issues, I'd recommend swapping it out with the STUMPY library (@seanlaw is the author and can help here). STUMPY is already a tsfresh dependency so it'd be pretty straightforward.

**Comment by CyrilLeMat** [comment]
+1 This is a real problem for me.

**Comment by kempa-liehr** [comment]
Fixed in https://github.com/blue-yonder/tsfresh/tree/v0.20.0.
Many thanks for your patience and perseverance.

Merry Christmas and a Happy New Year!
