### ISSUE TITLE
ModuleNotFoundError: No module named tsfresh 

### ISSUE THREAD

**Issue by maxdembovsky** [blue-yonder/tsfresh#943]
CODE (using pyspark)
<img width="750" alt="image" src="https://user-images.githubusercontent.com/57484973/169086117-7f4d412f-b3ef-48a6-a20d-ae468ee0569a.png">

ERROR
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/57484973/169085409-0da07714-6d19-43cc-8b09-e023d4811790.png">

pip freeze
<img width="411" alt="image" src="https://user-images.githubusercontent.com/57484973/169085843-ed8f1527-70ed-46e1-8fc0-1463e8d74f79.png">

**Environment**:

- Python version: 3.6
- Operating System: windows 10
- tsfresh version: 0.18.0
- Install method (conda, pip, source): pip

**Comment by maxAgostini** [comment]
did you ever find a solution?

**Comment by nils-braun** [comment]
Hi @maxdembovsky - sorry for the massive delay in answering. It looks like tsfresh is not installed in the worker environment - but I am also not an expert in spark. Where did you run the `pip freeze`? I assume on the driver?

As this does not look like a tsfresh issue to me (please correct me if I am wrong!) but rather a spark issue (where I unfortunately can not help you that much), I am closing it here. Feel free to ping us in case we can help
