### ISSUE TITLE
If I have a series data for only one id and I don't want extract feature and compress to one row?

### ISSUE THREAD

**Issue by b-y-f** [blue-yonder/tsfresh#969]
**The problem**:

If I have a series data for only one id and I don't want extract feature and compress to one row?  I just want to generate more column like lagged f1 lagged f2, f1 or f2 relation to the previous or past time?
```
ts     f1    f2  label
1       a     b    True
2      c     d    True
3      e     f    False
4      c     g    True
5      y     r    True
......
```
I want:

```
ts    f1    f2    added_feature 1  label
1      a      b    A True
2     c      d    B  True
3     e      f    C  False
4     c     g    D    True
5     y      r     E  True
......
```

**Anything else we need to know?**:

**Environment**:

- Python version:
- Operating System:
- tsfresh version:
- Install method (conda, pip, source):

**Comment by kempa-liehr** [comment]
Hi @b-y-f, the solution is to create rolling windows and extract features for each of the windows.

**Comment by nils-braun** [comment]
We have documentation available on this topic here: https://tsfresh.readthedocs.io/en/latest/text/forecasting.html
