### ISSUE TITLE
calculated_cwt encounter out of bounds

### ISSUE THREAD

**Issue by netivs** [blue-yonder/tsfresh#97]
As my data to abstracting features is a little too big (more than 8G),  I abstracting the relevant features on a sampled much more small data (1% ) using  `extract_relevant_features` and create a extractingsetting using `FeatureExtractionSettings.from_columns` and then to abstracting only the relevant features on the full data. Relative code is shown as followng:
```
df_filter_features = extract_relevant_features(x_filter_train,y_filter_train['label'], column_id="rank_id", column_sort="day_index")
feature_setting = FeatureExtractionSettings.from_columns(df_filter_features.columns)
df_features = extract_features(ts_ec, column_id="rank_id", column_sort="day_index",feature_extraction_settings=feature_setting)
```
The `extract_relevant_features` run all fine but after hours waiting, the `extract_features` on the full data encounter an error:
`
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\ouyang\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\ouyang\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\ouyang\Anaconda3\lib\site-packages\tsfresh\feature_extraction\extraction.py", line 189, in _extract_features_for_one_time_series
    current_result = dataframe.groupby(column_id)[column_value].apply(apply_function, **kwargs).unstack()
  File "D:\ouyang\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 694, in apply
    return self._python_apply_general(f)
  File "D:\ouyang\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 698, in _python_apply_general
    self.axis)
  File "D:\ouyang\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 1601, in apply
    res = f(group)
  File "D:\ouyang\Anaconda3\lib\site-packages\pandas\core\groupby.py", line 685, in f
    return func(g, *args, **kwargs)
  File "D:\ouyang\Anaconda3\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py", line 77, in func_on_nonNumberObject
    return func(x, *arg, **args)
  File "D:\ouyang\Anaconda3\lib\site-packages\tsfresh\feature_extraction\feature_calculators.py", line 832, in cwt_coefficients
    res_tmp = calculated_cwt[i, coeff]
IndexError: index 14 is out of bounds for axis 1 with size 2
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/ouyang/sgcc/sgcc_python/monthly_ec_basic_feature_basic_model.py", line 154, in <module>
    run_user_probe_xgb_basic_model(df_ec,1,per_feature_set)
  File "D:/ouyang/sgcc/sgcc_python/monthly_ec_basic_feature_basic_model.py", line 46, in run_user_probe_xgb_basic_model
    df_tsfresh = feature_abstractor['tsfresh'](df_ec)
  File "D:\ouyang\sgcc\sgcc_python\feature_abstractor.py", line 304, in get_tsfresh_feature
    df_features = extract_features(ts_ec, column_id="rank_id", column_sort="day_index",feature_extraction_settings=feature_setting)
  File "D:\ouyang\Anaconda3\lib\site-packages\tsfresh\feature_extraction\extraction.py", line 91, in extract_features
    extracted_features = pool.map(partial_extract_features_for_one_time_series, kind_to_df_map.items())
  File "D:\ouyang\Anaconda3\lib\multiprocessing\pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\ouyang\Anaconda3\lib\multiprocessing\pool.py", line 608, in get
    raise self._value
IndexError: index 14 is out of bounds for axis 1 with size 2

Process finished with exit code 1
`
It seems the error is occoured by the function `calculated_cwt` and I spent hours to try to find the problem but result nothing. Please give me some help or sugguestion. Thanks!

**Comment by MaxBenChrist** [comment]
I know where the error occurs. To fix it, I need the  `feature_setting .kind_to_calculation_settings_mapping` parameter after you call 

```
feature_setting = FeatureExtractionSettings.from_columns(df_filter_features.columns)
```

**Comment by MaxBenChrist** [comment]
You are using version 0.3.0?

**Comment by netivs** [comment]
Yes. I have install the tsfresh using pip install tsfresh, and the version shown is 0.3.0. I have checked the version use pip list and it is 0.3.0.

**Comment by netivs** [comment]
Yes. I have install the tsfresh using pip install tsfresh, and the version shown is 0.3.0. I have checked the version use pip list and it is 0.3.0.

**Comment by netivs** [comment]
The following is the `` ,please give me some help. Thanks!

**Comment by MaxBenChrist** [comment]
how long is the smallest time series sample in your data?

can you provide a minimal code example as a notebook with data?

**Comment by netivs** [comment]
The data is to big to upload as a notebook. I debug the code and found it was broken at the line number of  91 of extraction.py, whose code is shown as the following:
`
pool = Pool(feature_extraction_settings.n_processes)
partial_extract_features_for_one_time_series = partial(_extract_features_for_one_time_series, column_id=column_id,column_value=column_value, settings=feature_extraction_settings)
extracted_features = pool.map(partial_extract_features_for_one_time_series, kind_to_df_map.items()) # the broken code
`
The last line of code is broken and shown 'index 12 is out of bounds for axis 1 with size 2'
Is there anyway to just temporary shutdown the pool and using just one precessor? I'm using tsfresh to finish a competition and the deadline is coming soon.

**Comment by MaxBenChrist** [comment]
I don't think that the pool.map is the problem. Instead I think this error is caused by the cwt feature calculator

If you want you can send me a subset of your data and the notebook, then I can debug it. If you don't want your code to be leaked you can send it to me in private.

**Comment by netivs** [comment]
I removed all the cwt calculations by remove all features that has the keyword 'cwt' before `from_columns` is called, then the problem fixed. So, you are right, the problem is the cwt feature calculator. Because the data is too big, I'll try how to repeat this problem with a more small data and send you the code with neccesary data. Thanks for your help.

**Comment by MaxBenChrist** [comment]
No problem, I am looking forward to the sample so I can debug this asap :) .

**Comment by netivs** [comment]
I have repeat the problem with a very small dataset and have sent it to your e-maill address at me.com. Thanks.

**Comment by MaxBenChrist** [comment]
Thanks, I received your mail.

**Comment by MaxBenChrist** [comment]
I fixed it, see the pr.

**Comment by MaxBenChrist** [comment]
Thanks for the minimal example @netivs
