### ISSUE TITLE
Error shows when I copy paste same code from doc

### ISSUE THREAD

**Issue by b-y-f** [blue-yonder/tsfresh#970]
**The problem**:

Followed [this](https://tsfresh.readthedocs.io/en/latest/text/forecasting.html) doc's code.
my code:

```python3
import pandas as pd
from tsfresh import extract_features
from tsfresh.utilities.dataframe_functions import roll_time_series
df = pd.DataFrame({
   "id": [1, 1, 1, 1, 2, 2],
   "time": [1, 2, 3, 4, 8, 9],
   "x": [1, 2, 3, 4, 10, 11],
   "y": [5, 6, 7, 8, 12, 13],
})
df_rolled = roll_time_series(df, column_id="id", column_sort="time")
df_features = extract_features(df_rolled, column_id="id", column_sort='time')
```

The error after run above code
```
cannot do a non-empty take from an empty axes.
```

**Anything else we need to know?**:

**Environment**:

- Python version: py3.9
- Operating System: mac
- tsfresh version: 0.19.0
- Install method (conda, pip, source):conda

**Comment by kempa-liehr** [comment]
The example works fine with python 3.8.12 and pandas 1.3.5. Which pandas version are you using, @b-y-f ?

**Comment by kempa-liehr** [comment]
The error is reproducible with pandas 1.5.1.

**Comment by b-y-f** [comment]
NotImplementedError: AR has been removed from statsmodels and replaced with statsmodels.tsa.ar_model.AutoReg.
