### ISSUE TITLE
Dependece upon `matrixprofile`

### ISSUE THREAD

**Issue by erezinman** [blue-yonder/tsfresh#972]
Hi, 
It seems that the package `matrixprofile` is no longer maintained. The package forces a specific and deprecated version of `protobuf`, and hence is incompatible with many packages (tensorflow, pytorch, etc.). Please remove the dependence upon `matrixprofile`, or, at least, make this package's installation optional (maybe using `extras_require` in the `setup.py`?).

**Comment by arturdaraujo** [comment]
I fully agree. When creating an environment with pyarrow on python 3.7+ I had the same compatibility problem. Pyarrow is used for importing parquet and feather files which makes this incompatibility quite annoying. 
```

(base) C:\Users\artur>conda create -n env_tsfresh36 python=3.9 spyder tsfresh=0.19 pyarrow
...
Collect all metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package tsfresh-0.19.0-pyhd8ed1ab_0 requires matrixprofile >=1.1.10,<2.0.0, but none of the providers can be instald

```

**Comment by aiwalter** [comment]
Hi together, we are having same issue and would appreciate a solution here with a new `tsfresh` release!

**Comment by PJPRoche** [comment]
Hello, I am having the same issues with matrixprofile too. I raised an issue in their GitHub repo (https://github.com/matrix-profile-foundation/matrixprofile/issues/102) with a suggestion to fix the issue, but there has not been any activity for a long time.
Would be great of the dependency can be removed here

**Comment by williamgilpin** [comment]
Hello, thank you very much for this incredible package. We are also having this issue, and have not yet been able to find a workaround. 

How many of the features depend on `matrixprofile`? Would it be possible to drop those features for now (and thus the dependency) until an alternative like `stumpy` is implemented?

**Comment by arturdaraujo** [comment]
Any news on this issue @kempa-liehr ? This update would be incredibly helpful!

**Comment by enrique-wesper** [comment]
It would be amazing to be able to install tsfresh. I am using a mac M2 and I have also not been able to find a workaround

**Comment by kempa-liehr** [comment]
Fixed in https://github.com/blue-yonder/tsfresh/tree/v0.20.0.
Many thanks for your patience and perseverance.

Merry Christmas and a Happy New Year!
