### ISSUE TITLE
Append New Data

### ISSUE THREAD

**Issue by ericvoots** [blue-yonder/tsfresh#979]
Hi,

When running the data on training or initial data sets that works great.  So lets say the initial dataset size is 5000, then I get 1000 new rows.  Do I always need to completely refit based on the 6000 observations?  or is there a way to have the initial tsfresh instance use the new 1000 rows and generate the 1000 new rows without refitting on the 6000 total observations?

**Comment by kempa-liehr** [comment]
Good practise is to separate feature extraction and feature selection. 

You could extract features for each of the time-series batches separately, concatenate the feature matrices, and only refit the FeatureSelector() transformer.
