### ISSUE TITLE
To improve the usability of the package, remove matrix_profile.

### ISSUE THREAD

**Issue by arturdaraujo** [blue-yonder/tsfresh#984]
**The problem**:

The package matrix_profile is causing a lot of compatibility problem in pypi and conda. It is best to REMOVE this feature due to compatibility problems caused in python 3.9, 3.10, 3.11. As it is, tsfresh=0.19 can only be used in python 3.8.

**Comment by SirJohnFranklin** [comment]
Maybe it's possible to replace it with this version: https://github.com/matrix-profile-foundation/matrixprofile

**Comment by arturdaraujo** [comment]
Matrixprofile is no longer maintained. The most similar package to replace is stumpy https://github.com/TDAmeritrade/stumpy
