### ISSUE TITLE
unmaintained dependency `matrixprofile` makes `tsfresh` uninstallable on python 3.10

### ISSUE THREAD

**Issue by mmp3** [blue-yonder/tsfresh#991]
**The problem**:

`tsfresh` cannot be installed on `python 3.10` because it has `matrixprofile` as a dependency, yet `matrixprofile` cannot be installed on `python 3.10` and is no longer maintained. 

**Anything else we need to know?**:

`matrixprofile` is superseded by `stumpy`.

**Environment**:

- Python version: 3.10

**Comment by arturdaraujo** [comment]
This package is stuck on Python 3.8 until this bug is not fixed, we are all waiting for this fix. This issue was posted before on https://github.com/blue-yonder/tsfresh/issues/972 and https://github.com/blue-yonder/tsfresh/issues/984

**Comment by arturdaraujo** [comment]
@kempa-liehr

**Comment by arturdaraujo** [comment]
This is the setup.py file now:

```
import sys

from setuptools import find_packages, setup

with open("README.md") as f:
    long_description = f.read()

with open("requirements.txt") as f:
    requirements = [line for line in f if not line.startswith("#")]

needs_sphinx = {"build_sphinx", "upload_docs"}.intersection(sys.argv)
sphinx = ["sphinx", "sphinx_rtd_theme"] if needs_sphinx else []

setup(
    use_scm_version=True,
    long_description=long_description,
    long_description_content_type="text/markdown",
    setup_requires=["setuptools_scm"] + sphinx,
    packages=find_packages(exclude=["tests.*", "tests"]),
    install_requires=requirements,
)
```
For making matrixprofile optional, the setup.py solution is like this:

```
import sys

from setuptools import find_packages, setup

with open("README.md") as f:
    long_description = f.read()

with open("requirements.txt") as f:
    requirements = [line for line in f if not line.startswith("#")]

needs_sphinx = {"build_sphinx", "upload_docs"}.intersection(sys.argv)
sphinx = ["sphinx", "sphinx_rtd_theme"] if needs_sphinx else []

simple_requirements = [r for r in requirements if r != "matrixprofile>=1.1.10,<2.0.0"]
advanced_requirements = [r for r in requirements if r == "matrixprofile>=1.1.10,<2.0.0"]

setup(
    use_scm_version=True,
    long_description=long_description,
    long_description_content_type="text/markdown",
    setup_requires=["setuptools_scm"] + sphinx,
    packages=find_packages(exclude=["tests.*", "tests"]),
    extras_require={
        "advanced": advanced_requirements,  # Advanced features
        "simple": simple_requirements,  # Basic features
    }
)
```
However, the function "matrix_profile" will still try to import it. The solution for this is to check if matrixprofile package is installed before importing it. Make this changes on  feature_extraction/feature_calculators.py

1st:
```

import importlib.util

package = "matrixprofile"
is_present = importlib.util.find_spec(package)

if is_present is not None:
    import matrixprofile as mp
```

2nd:
```

if is_matrix_profile_present is not None:
    @set_property("fctype", "combiner")
    def matrix_profile(x, param):
        """
        Calculates the 1-D Matrix Profile[1] and returns Tukey's Five Number Set plus the mean of that Matrix Profile.
        .. rubric:: References
        |  [1] Yeh et.al (2016), IEEE ICDM
        :param x: the time series to calculate the feature of
        :type x: numpy.ndarray
        :param param: contains dictionaries
                      {"sample_pct": x, "threshold": y, "feature": z}
                      with sample_pct and threshold being parameters of the matrixprofile
                      package https://matrixprofile.docs.matrixprofile.org/api.html#matrixprofile-compute
                      and feature being one of "min", "max", "mean", "median", "25", "75"
                      and decides which feature of the matrix profile to extract
        :type param: list
        :return: the different feature values
        :return type: pandas.Series
        """
    
        x = np.asarray(x)
    
        [...]
    
        return [(key, value) for key, value in res.items()]
```

**Comment by erezinman** [comment]
@arturdaraujo Just separate the 'matrixprofile' requirement from the rest. I'll try creating a PR if I'll get to it later. Otherwise, good job!

**Comment by arturdaraujo** [comment]
I think `try: ... except ImportError: ... ` is a much better solution also now that you mentioned it, no need for using importlib.

Thanks for the reply

**Comment by arturdaraujo** [comment]
I just realized that there is a PR https://github.com/blue-yonder/tsfresh/pull/985 
Can you guys also check if that's adequate? It seems pretty good to me

**Comment by nils-braun** [comment]
PR has been merged and a new version 0.20.0 released :) 
(if you still see issues, please let us know by!)
Thank you for your time and effort!

**Comment by nils-braun** [comment]
Thanks @aiwalter ! I have added py 3.10 as a classifier. I have not added an upper bound to the `python_requires` as the ´tsfresh´ package itself has no limitation on it (some dependencies might have though).
Also, I have not added a 3.11 classifier as currently the dependencies will not allow tsfresh to be installed on py 3.11.

**Comment by ElreboCM** [comment]
@nils-braun I still cannot use tsfresh with python 3.10.9. I am getting the following error:
`ModuleNotFoundError: TSFreshFeatureExtractor requires python version to be <3.10, but system python version is 3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)].`

I am using the main branch.

**Comment by nils-braun** [comment]
Hi @ElreboCM - it looks like you are not using tsfresh directly, but maybe via the aeon toolkit by @aiwalter? Because `TSFreshFeatureExtractor` sounds like it. So maybe there is another layer which prevents you from using it? The version constraint in tsfresh is removed though.

**Comment by ElreboCM** [comment]
Indeed I was importing from sktime

`from sktime.transformations.panel.tsfresh import TSFreshFeatureExtractor`
